app/packages/core/src/components/Actions/ActionsRow.tsx, app/packages/state/src/hooks/useSetView.ts, app/packages/state/src/recoil/selectors.ts
Current when pinnning/saving filters with selected samples in a group view, the following server error is encountered
It seems this error also exist in `0.18.0`
=> Select slice when pinning

fiftyone/core/dataset.py
Previously the media size computation in `Dataset.stats()` only accounted for the current slice of a grouped dataset. Now it includes all slices, as expected.
```py
stats1 = dataset.stats(include_media=True)
stats2 = dataset.select_group_slices(_allow_mixed=True).stats(include_media=True)
assert stats1["total_bytes"] == stats2["total_bytes"]
```
=> Include all group slices in media size stat

app/packages/core/src/components/Sidebar/Sidebar.module.css, app/packages/core/src/components/Sidebar/Sidebar.tsx
PR adds hover/active state to the sidebar resize rule (bolder blue border) and adds an ability to resize sidebar to default width when resize rule is double-clicked:
Preview:
Tested interactive in-app for both modal and non-modal sidebar
-   [ ] Other
=> sidebar re-size enhancements

app/packages/core/src/components/Actions/Similar.tsx, fiftyone/core/session/events.py, fiftyone/core/state.py
Currently, Python client's cannot connect properly because the initializer payload is malformed.
```py
view = dataset.limit(10)
```
=> Fix Python client session initialization

app/packages/core/src/components/Actions/ActionsRow.tsx
When no sample is selected, saveFilter is not working properly. For instance, sort by similarity, and then save filters fail. 
This PR fixes this issue. 
-   [ ] Other
=> SaveFilters bug 

app/packages/looker/src/elements/common/actions.ts
Associate shortcut to all event keys when `eventkeys` is an array. 
@benjaminpkane PR undoes [this change ](https://github.com/voxel51/fiftyone/pull/2093/files#diff-b731314c70a8bd373561bb299112b8ac883762eafe407026fe915a8ad12b9d91R24). Do you expect this change to re-introduce issue the change in  PR #2093 fixed?
Interactively in app with a video player to ensure all items in array of event keys are associated to its respective action
-   [ ] Build: Build and test infrastructure …
=> Associate shortcut to all event keys

app/packages/core/src/components/ViewBar/ViewStage/viewStageParameterMachine.ts
problem
Trying to matchTags with spaces is impossible
Reason
The parser is removing all spaces when entered in MatchTags expression
Solution
Allow single spaces in parser for list of strings
- Replace all spaces with single space
- Replace ", " with single comma
- Remove trailing spaces
https://user-images.githubusercontent.com/109545780/218838504-bfbe49c4-2936-4a6c-977b-a57457276740.mov
Manually - see video
@benjaminpkane can this cause regression elsewhere as far as you know?  …
=> Allows space in list of strings in viewbar stages

app/packages/spaces/src/components/AddPanelItem.tsx
PR adds the ability to open a panel directly in split mode:
- Selecting a new panel to add while holding `Option` (`Alt` in linux/windows) key will open a new panel in side-by-side panel split mode
- Selecting a new panel to add while holding `Shift` key will open a new panel in top-and-bottom panel split mode
Interactively within the app
- Selecting a new panel to add while holding `Option` (`Alt` in linux/windows) key will open a new panel in side-by-side panel split mode
- Selecting a new panel to add while holding `Shift` key will open a new panel in top-and-bottom panel split mode
-   [ ] …
=> add ability to open a panel directly in split mode

fiftyone/core/dataset.py
@lanzhenw recently noticed that saving views fails (intermittently) raising `raise ValueError("Cannot save view into a different dataset")`
Digging into it, It fails every other time or so after trying to save a view (whatever the view be). For some reason (ideas are welcomed) the `view._root_dataset is not self:` condition started passing/failing depending on how many times you try to save a view. 
Fix: making the condition check based on slug is more efficient and seems to fix the issue.
https://user-images.githubusercontent.com/109545780/219476413-f7375aab-221d-4149-b69f-2678b10b961c.mov
(Details)
notes for …
=> Check slug instead of the entire dataset before saving views

fiftyone/core/session/session.py, fiftyone/zoo/models/manifest-tf.json
- current version of the tutorial: https://docs.voxel51.com/tutorials/open_images.html
- rerun notebook, fix functions, and cleanup outputs 
- change model requirements to `tensorflow|tensorflow-macos`
(Details)
-   [ ] Other
=> Fix open_images tutorial

app/packages/core/src/components/Sidebar/Sidebar.module.css, app/packages/core/src/components/Sidebar/Sidebar.tsx
PR fixes sidebar resize active blue border flashing on clicking
Interactively in-app for both modal and non-modal sidebar
-   [ ] Other
=> fix sidebar resize border flash on click

fiftyone/core/view.py, tests/unittests/view_tests.py
- Currently, select_group_slices is being called when it's not supposed to be in make_optimized_select_view, leading to the select group slice stage getting appended to the list of view stages always, leading to errors when creating a saved view
(Details)
-   [ ] Other
=> Fix make_optimized_select_view for group datasets

fiftyone/server/aggregations.py, fiftyone/server/dataloader.py, fiftyone/server/paginator.py, fiftyone/server/query.py, fiftyone/server/samples.py, fiftyone/server/utils.py
Adds a `from_dict` wrapper for `dacite` in server utils for ensuring a common configuration and removes all direct usage of dacite's `from_dict`
* Resolves #2672
=> from_dict wrapper for server dataclasses

fiftyone/core/dataset.py
Update `export_dir` to `dataset_dir` in the `fo.Dataset.from_dir()` docstring.
=> Fix docstring for Dataset.from_dir()

app/packages/plugins/src/index.ts
Allow for plugins to load components and utilities from runtime instead of compiling their own, with its own state at runtime. This fixes issues where the fetch function will point to the wrong URL and cuts down on build times for plugins that use components.
=> externalize plugin deps

fiftyone/core/fields.py
Previous versions of FiftyOne technically allowed negative integer mask targets (although the docs recommend only using non-negative integers), but [this update](https://github.com/voxel51/fiftyone/commit/171071da26e432b6ea2d831b589d09f6fe79b7e1) changed the implementation in such a way that existing datasets that *do* happen to contain mask targets with negative integers would no longer be loadable.
=> Add support for negative integer mask targets

fiftyone/server/samples.py
- Fixes https://github.com/voxel51/fiftyone/issues/2681
https://user-images.githubusercontent.com/30936736/221044147-e8eec4b4-8cd6-48d3-904b-29db4ded8bc7.mov
To create the demo views:
```
dataset = foz.load_zoo_dataset('quickstart-video', dataset_name = 'video')
v1=dataset.limit(1).filter_labels("frames.detections", F("label") == "road sign")
dataset.save_view('limit1 road sign',v1)
v1=dataset.limit(1).filter_labels("frames.detections", F("index") == 9)
dataset.save_view('limit1 index 9',v1)
v1 = dataset.skip(3).limit(1).match_frames(F("detections.detections.label").contains('vehicle'))
dataset.save_view('skip3 limit1 vehicle',v1)
v1 = …
```
=> Fix samples request

docs/source/user_guide/using_datasets.rst, fiftyone/__public__.py, fiftyone/core/odm/mixins.py, tests/unittests/dataset_tests.py
Documents a previously-possible-but-undocumented pattern for creating custom embedded documents:
- declare an empty `DynamicEmbeddedDocument` field
- add dynamic attributes to it as desired
```py
dataset.add_sample_field(
"camera_info",
fo.EmbeddedDocumentField,
embedded_doc_type=fo.DynamicEmbeddedDocument,
)
dataset.add_sample_field("camera_info.camera_id", fo.StringField)
assert "camera_info.camera_id" in dataset.get_field_schema(flat=True)
sample1 = fo.Sample(
filepath="/path/to/image1.jpg",
camera_info=fo.DynamicEmbeddedDocument(
camera_id="123456789",
quality=51.0,
),
)
sample2 = fo.Sample(
filepath="/path/to/image2.jpg",
camera_info=fo.DynamicEmbeddedDocument(camera_id="123456789"),
)
dataset.add_samples([sample1, sample2], dynamic=True) …
```
=> Documenting on-the-fly custom embedded document creation

.github/workflows/test.yml
Adds an upload token to the codecov action to better ensure successful reports and correct coverage deltas in PRs
=> Add CODECOV_TOKEN to coverage upload

app/packages/core/src/components/Actions/utils.tsx, app/packages/state/src/recoil/aggregations.ts
Resolves #2692 
Fixes tagging selection data by adding the new `selected` flag for the aggregations selector family which can be subscribed to downstream by the label tag and sample tag count selectors for the Tagger component
=> Fix tagging selection

app/packages/embeddings/src/useViewChangeEffect.tsx
Currently throws an error: 
Proposal:
Handle fetch failure:
(Details)
-   [ ] Other
=> Present error message for embeddings plot if no results

app/packages/looker/src/lookers/video.ts, docs/source/recipes/custom_exporter.ipynb
- ensure frames exist before checking length, otherwise filtering may throw errors in the app
- remove `f` so that calls of `getSample()` complete as expected
(Details)
-   [ ] Other
=> Fix bug in looker video

fiftyone/server/routes/values.py
Currently we use regex matching for string fields (like `id`, `filepath`, etc.). It breaks the app when the user enters invalid regex, example: `*`. This PR includes a fix such that we use wildcard matching instead of regex matching.
Tested locally. No automated tests.
-   [ ] Other
=> bugfix: use wildcard pattern matching in app

app/packages/core/src/components/Sidebar/Entries/PathValueEntry.tsx
`format` method creates a link with the url and should not be rendered as a string
(Details)
-   [ ] Other
=> Bugfix: url is rendered in wrong type in sidebar

fiftyone/core/session/events.py, fiftyone/core/state.py, fiftyone/server/routes/event.py, fiftyone/server/routes/events.py
Resolves #2700 
Resolves session updates by reloading the dataset singleton on the server when building a view that raises an exception
=> Fix session usage for schema changes

fiftyone/server/mutation.py, fiftyone/server/view.py
Resolves https://github.com/voxel51/fiftyone/issues/2710.
Applies extended stages (panel selections, similarity sorts) before sidebar filters when constructing the extended view.
In general, since view stages are applied serially in a pipeline, we may have to update the extended view logic to remember the order in which the user's operations were performed in order to produce exactly the view they are looking at.
HOWEVER, the only extended view stages that we currently use operate solely based on _selecting_ sample/label IDs, so, for now, it's true that putting them first and then applying filters will always match what the user is looking at in the grid.
=> Apply extended stages before filters in extended view

app/packages/core/src/Root/Root.tsx, app/packages/core/src/components/Dataset.tsx, app/packages/core/src/components/EmptySamples.tsx, app/packages/core/src/components/ImageContainerHeader.tsx, app/packages/core/src/components/index.ts, app/packages/core/src/plugins/samples.tsx
Shows an Empty component for when there are no samples in a dataset or there are no samples in the given view.
(Details)
-   [ ] Other
=> Empty samples page with reset button

app/packages/core/src/components/Modal/Looker.tsx, app/packages/looker/src/elements/common/actions.ts, app/packages/looker/src/elements/common/looker.ts
Fixes #2472  by fixing existing support for this feature - only handle events when the looker has mouse over.
=> fixes #2472

fiftyone/core/collections.py, fiftyone/core/dataset.py, fiftyone/core/frame.py, fiftyone/core/odm/document.py, fiftyone/core/odm/mixins.py, fiftyone/core/runs.py, fiftyone/core/sample.py, fiftyone/server/mutation.py, fiftyone/utils/data/importers.py, tests/unittests/dataset_tests.py, tests/unittests/group_tests.py, tests/unittests/utils3d_tests.py, tests/unittests/video_tests.py
- Frame collections are now lazily created only when necessary. Previously an empty frames collection would always be created when a dataset is created, even if the dataset doesn't contain videos
- Added an `add_group_slice()` method to declare new slices on grouped datasetes
- Updated the `_save()` implementation to only use `upsert=True` when explicitly requested by the caller
- Updated the codebase to use `Dataset.save()` rather than `DatasetDocument.save()`, for consistency and so that the last valid dataset doc is automatically reloaded from the database if a bad save occurs. Previously, the user must manually correct any bad data on their `_doc` or manually reload the dataset in order to continue using the `Dataset` object if an error occurred due to invalid data during a `save()`
- …
=> No unnecessary upserts or frames collections

app/packages/core/src/components/Actions/Checker.tsx, docs/source/recipes/custom_exporter.ipynb
Throws error when tapping enter a second time in add label tag popover
(Details)
-   [ ] Other
=> [Bugfix] Error when pressing enter twice

app/packages/core/src/components/Group/Group.tsx, app/packages/core/src/components/GroupSliceSelector.tsx, app/packages/core/src/components/Modal/Group.tsx, app/packages/core/src/components/Modal/Looker.tsx, app/packages/core/src/components/Sidebar/Sidebar.tsx, app/packages/state/src/hooks/useCreateLooker.ts, app/packages/state/src/recoil/atoms.ts, app/packages/state/src/recoil/groups.ts, app/packages/state/src/recoil/modal.ts, fiftyone/utils/utils3d.py
- Show pointcloud slice selector in group datasets (also resolves #2722)
- Address a number of bugs in grouped datasets
- Pinned slice persists in the looker when switching samples, but not in the sidebar. Not a regression.
- It didn't use to persist in the looker as well, but that has been fixed.
- Orthographic projection metadata, if calculated, is only available in the pointcloud slice. However, the sidebar shows this field for all slices. This can create a confusing experience. Not a regression.
- Projected bounding boxes are painted off the center once in a blue moon-ly. I haven't been able to reproduce this but I'll dive deeper in next iteration. Not a regression.
- Nit: Group dataset primitives and state management need some rethinking and refactoring. Atoms and selectors are …
=> Group modal  and orthographic projection improvements

app/packages/components/src/components/Tooltip/Tooltip.tsx, app/packages/core/src/components/Modal/Bars.tsx, app/packages/core/src/components/Modal/Group.tsx, app/packages/core/src/components/Modal/Looker.tsx, app/packages/core/src/components/Modal/Modal.tsx, app/packages/core/src/components/Modal/Sample.tsx
Currently the tooltip doesn't show for 3D labels if looker2D is not in context. This PR fixes that. Also closes #2723.
Note to the reviewer: `lookerRefCallback` is a callback prop that, when invoked, sets the ref. More on it: https://github.com/voxel51/fiftyone/pull/2766/files#diff-59872f6c92cd7fab33aaf4419234215cac6c621914dc9a321c36980e87a62917R253
Locally. No automated tests.
-   [ ] Other
=> move tooltip from looker2D to modal

fiftyone/core/odm/mixins.py, fiftyone/core/odm/utils.py, tests/unittests/dataset_tests.py
Fixes a bug with `dynamic=True` expansion for list fields that contain embedded documents.
=> Fixing an issue with dynamic embedded list schemas

app/packages/core/src/components/Modal/Group.tsx, app/packages/core/src/components/Modal/Modal.tsx, app/packages/core/src/components/Sidebar/Entries/PathValueEntry.tsx, app/packages/looker-3d/src/state.ts, app/packages/state/src/recoil/groups.ts, app/packages/state/src/recoil/sidebar.ts
Ensure the integrity of group metadata in the sidebar as you navigate between different samples with different pinned slices.
Additional small changes not directly related to this PR:
1. Update point size default to 2 in looker 3d.
2. Don't "prevent default" when `c` is pressed.
3. Fix minor bugs introduced in #2766
Locally. 
1. Load quickstart dataset. Open a sample. Make sure everything looks normal in the sidebar. Navigate next/previous.
4. Load quickstart-groups dataset. For each slice, load a sample on the modal and see if filename + metadata + group metadata are correct. Group metadata is in the bottom of the modal sidebar.
5. Additionally, for each sample modal, alter between different slices from within the modal and make sure filename + metadata + group metadata are correct. …
=> Fix sidebar metadata inconsistency in group modal 

fiftyone/core/collections.py, tests/unittests/view_tests.py
The `set_values()` method previously did not validate the provided values against the type of existing fields. This PR fixes that.
=> Adding validation to set_values()

fiftyone/server/view.py
Changes in fiftyone/server/view.py --> As the previous code looks only for numeric classes so when the user is filtering wrt. labels the app was crashing. Made the changes in func "_make_keypoint_list_filter" now code will able to handle those cases.
its thoroughly tested on thousands of images.
Keypoints filter bug fix to avoid app crashing while filtering categorical variables.
yes
-   [x ] No. You can skip the rest of this section.
Fixes app crashing while filtering keypoints labels. This change is specific to keypoints function only. The changes are made only on …
=> fixes app crashing while filtering keypoints labels (view.py)

app/packages/state/src/hooks/useCreateLooker.ts, fiftyone/server/metadata.py
Use dedicated media field for orthographic projection filepath
Locally, with quickstart-groups dataset, both with and without projections computed.
-   [ ] Other
=> Use dedicated media field for orthographic projection filepath

app/packages/core/src/components/EmptySamples.tsx, app/packages/core/src/components/Grid/Grid.tsx, app/packages/core/src/plugins/samples.tsx
Empty state was reloading and returning null even while loading. This caused several issues. 
- empty state would not update/display when filters caused 0 results
- when selecting samples in embeddings empty state would re-render in the loading state and cause issues with spaces (closing the embeddings tab)
=> Fix empty state loading

app/packages/core/src/components/Actions/ActionsRow.tsx, app/packages/core/src/components/Actions/similar/utils.ts
As a user, I can select a bounding box in the sample modal and then execute a similarity search against any brain_key that corresponds to a similarity run with that matches that label's patches_field.
https://user-images.githubusercontent.com/17770824/225401265-b37123ca-da46-4d29-a043-bbf6172fcd4d.mov
-   [ ] Other
=> fix toPatches modal view regression for similarity search

app/packages/components/src/components/Selection/Selection.tsx
Scrollbar is visible for some users unnecessarily which @imanjra correctly found the root issue and fix! 🎉  
(Details)
-   [ ] Other
=> Selection scrollbar is now overflow auto instead of scroll

app/packages/core/src/components/Actions/similar/utils.ts, fiftyone/server/routes/sort.py
reset selected labels after submitting similarity sort
(Details)
https://user-images.githubusercontent.com/17770824/225454688-6537e730-4b0b-49e0-8a75-fe5b78f0b42e.mov
-   [ ] Other
=> reset selectedLabels after sort submission

fiftyone/server/mutation.py
deleting saved views crashes since the property does not exist in state
https://voxel51.atlassian.net/browse/TEAMS-1029
(Details)
-   [ ] Other
=> fix delete saved view crash

app/packages/looker-3d/src/state.ts, fiftyone/server/metadata.py
- fix aspect ratio error for orthographic projections
- fix bug where orthographic projection metadata was not being computed on cache miss
- fix browserstorage effect bug for grid lines
- fix `media_fields` mutating bug in media url creation causing an explosion of `urls`
Locally.
-   [ ] Other
=> looker3d pass / bugfix

app/packages/looker-3d/src/action-bar/PointSize.tsx, app/packages/looker-3d/src/action-bar/style.module.css
- Set color of point cloud size textbox to theme text primary color
- Override MUI's font for point cloud size label
Locally
-   [ ] Other
=> more explicit font declaration for point cloud size input

README.md
Updates the blog link in the readme to point to blog.voxel51.com rather than medium
=> Update blog link in README.md

fiftyone/core/collections.py, tests/unittests/view_tests.py
Closes https://github.com/voxel51/fiftyone/issues/2836 where `SampleCollection.stats()` was being reported as the full document size total even if a SelectField stage was present.
This bug was due to a change in behavior of $bsonSize within a $group stage after MongoDB ~ 5.2. It's believed because of the usage of the Slot Based Execution query engine for $group stage in 5.2.
A [MongoDB bug ticket has been filed](https://jira.mongodb.org/browse/SERVER-75267) but that's about all we can do since there appears to be no way to turn off the SDE engine selectively.
The workaround is to grab document sizes first then sum them, in 2 stages instead of 1. This may be slightly more inefficient but likely not by much.
Added unit test exposing bug in MongoDB >= 5.2. Passes now.
```python
import …
```
=> workaround mongodb bug in _get_samples_bytes()

fiftyone/core/collections.py, fiftyone/server/view.py, tests/unittests/server_tests.py
When "Showing samples with ..." in the sidebar, `new_field` changes are not included. Also fixes a clash of hidden `__` field processing between `MatchLabels` and `fiftyone.server.view.get_view`
=> Hidden results and server MatchLabels fix 

fiftyone/core/dataset.py
- Check that `load_dataset` was called with a non-empty name before returning a `Dataset` since all valid datasets should have names
(Details)
-   [ ] Other
=> Prevent loading a dataset without a name in the sdk

app/packages/core/src/components/FieldLabelAndInfo/index.tsx, fiftyone/core/session/client.py, fiftyone/core/state.py
- update json dump to be able to save a date object in field
- display datetime and float type in field.info table in the tooltip
To test this change, you can run the following SDK code: 
```
In [1]: import fiftyone as fo
...: import fiftyone.zoo as foz
...: from datetime import datetime
...:
...: dataset = foz.load_zoo_dataset("quickstart")
...:
...: field = dataset.get_field("ground_truth")
...: field.info = {"created_at": datetime.utcnow(), "sample": float(InF)}
...: field.save()
...: dataset.save()
...: session = fo.launch_app(dataset)
```
(Details)
if …
=> Bugfix: a user can save a float/datetime object in field.info and see that in the tootlip

fiftyone/utils/labelbox.py, requirements/common.txt
relies on: https://github.com/voxel51/eta/pull/590
removed ndjson & patool, removed ndjson from this repo as well and pointed the one call to ndjson directly to the eta lib functionality. 
Also added the missing parameter to the labelbox `create_project` call which may have been caused by a breaking change in a recent update. This was necessary to get the labelbox tests working so I could test the ndjson -> jsonlines changes via the `tests/intensive/labelbox_tests`, not a robust fix for the [existing labelbox issue](https://voxel51.atlassian.net/browse/TEAMS-1065).  
manually tested & ran through existing labelbox tests (which covered the ndjson -> jsonlines changes in eta, PR [here](https://github.com/voxel51/eta/pull/590/files))
-   [ ] …
=> Replace ndjson and patool packages with non-GPL code

app/package.json, app/packages/looker/src/worker/index.ts, app/yarn.lock
Only png images were supported for `mask_path` / `map_path` for on-disk segmentations / heatmaps, this PR adds support for jpg as well.
Locally
-   [ ] Other
=> add support for jpg segmentations / heatmaps

fiftyone/core/session/client.py
Post data in `fiftyone.core.session.client.Client.run` initialization  the same way `post_event` does to fix `datetime` serialization when initializing a`Session` with a non-`None` dataset value
```py
field = dataset.get_field("ground_truth")
field.info = {"created_at": datetime.utcnow(), "sample": float("inf")}
field.save()
session = fo.launch_app(dataset) # previously would fail
```
=> Fix client serialization initialization

tests/unittests/view_tests.py
The `test_set_values_validation` test was doing something it shouldn't: declaring that an existing (previously undeclared) embedded field that contains strings should now have type `IntField`.
=> Don't add field that conflicts with existing field values

fiftyone/core/dataset.py
If a `merge_samples()` operation fails, some indexes must be cleaned up which may not exist. Previously, in the case of a failed merge, another "index does not exist" error message could be raised, which may distract the user from the *initial* error that caused the failed merge, which likely requires them to change something about their `merge_samples()` syntax.
Now only the initial error will be raised.
=> Avoid errors during failed merge cleanup

fiftyone/server/routes/embeddings.py
The embeddings panel backend previously did not correctly handle the case of pulling color-by data for a sample embeddings plot when the current view is a patches view.
I tested all four combinations of sample/patches views/embeddings on the dataset below and now colors work in all cases:
```py
fob.compute_visualization(
dataset,
model="clip-vit-base32-torch",
brain_key="img_viz",
)
fob.compute_visualization(
dataset,
patches_field="ground_truth",
model="clip-vit-base32-torch",
brain_key="gt_viz",
)
```
=> Pulling correct data when viewing patches with a sample embeddings plot

fiftyone/core/aggregations.py, fiftyone/core/collections.py, fiftyone/core/dataset.py, fiftyone/core/fields.py, fiftyone/core/labels.py, fiftyone/core/odm/mixins.py, tests/unittests/dataset_tests.py
The `get_dynamic_field_schema()` and `add_dynamic_sample_fields()` methods did not previously handle either of these cases:
- fields that contain lists of embedded documents 
- dynamic embedded documents (eg `Label` fields)
Now it does!
```py
filepath="/Users/Brian/Desktop/test.png",
tasks=[
fo.DynamicEmbeddedDocument(
annotator="eric",
labels=fo.Classifications(
classifications=[
fo.Classification(label="cat", mood="surly"),
fo.Classification(label="dog"),
]
),
),
fo.DynamicEmbeddedDocument(
annotator="mani",
labels=fo.Classifications(
classifications=[
fo.Classification(label="rabbit"),
fo.Classification(label="squirrel", age=51),
]
),
),
]
)
fo.pprint(dataset.get_field_schema(flat=True)) …
```
=> Adding support for dynamically inferring fields on embedded lists and documents

app/packages/looker/src/worker/index.ts
Fixes field mask targets for RGB segmentations:
```py
import fiftyone.utils.labels as foul
"coco-2017",
label_types="segmentations",
classes=["chair", "couch"],
max_samples=3,
)
labels = dataset.distinct("ground_truth.detections.label")
color_pool = [
"#ee0000", "#ee6600", "#993300", "#996633", "#999900", "#009900",
"#003300", "#009999", "#000099", "#0066ff", "#6600ff", "#cc33cc", "#777799"
]
cmap2d = {idx: lbl for idx, lbl in enumerate(labels)}
print(cmap2d)
cmap3d = {color_pool[idx]: lbl for idx, lbl in enumerate(labels)}
print(cmap3d)
foul.objects_to_segmentations(dataset, "ground_truth", "seg2d_binary")
foul.objects_to_segmentations(
dataset,
"ground_truth",
"seg2d", …
```
=> Fix field mask targets for RGB

app/packages/looker/src/overlays/heatmap.ts, app/packages/looker/src/overlays/util.ts, app/packages/looker/src/worker/index.ts, app/packages/looker/src/worker/painter.ts, app/packages/state/src/recoil/selectors.ts
Fixes bug in RGB heatmaps. 
Locally.
```py
import os
def random_kernel(metadata):
h = metadata.height // 2
w = metadata.width // 2
sign = np.sign(np.random.randn())
x, y = np.meshgrid(np.linspace(-1, 1, w), np.linspace(-1, 1, h))
x0, y0 = np.random.random(2) - 0.5
kernel = sign * np.exp(-np.sqrt((x - x0) ** 2 + (y - y0) ** 2))
return fo.Heatmap(map=kernel, range=[-1, 1])
dataset = foz.load_zoo_dataset("quickstart").select_fields().clone()
heatmap = random_kernel(sample.metadata)
map_path = os.path.join("/tmp/heatmaps", os.path.basename(sample.filepath))
heatmap.export_map(map_path, update=True)
sample["heatmap"] = heatmap
sample.save()
``` …
=> on-disk heatmap bug part 2

docs/source/user_guide/using_aggregations.rst, docs/source/user_guide/using_datasets.rst, fiftyone/__public__.py, fiftyone/core/aggregations.py, fiftyone/core/collections.py, fiftyone/core/dataset.py, fiftyone/core/odm/mixins.py, tests/unittests/aggregation_tests.py, tests/unittests/dataset_tests.py
The `get_dynamic_field_schema()` and `add_dynamic_sample_fields()` methods now support nested list fields.
In order to implement this, we needed a method to inspect the value type(s) of list fields across a collection, which is now exposed publicly as a new `list_schema()` aggregation.
```py
sample1 = fo.Sample(
filepath="image1.png",
ground_truth=fo.Classification(
label="cat",
info=[
fo.DynamicEmbeddedDocument(
task="initial_annotation",
author="Alice",
timestamp=datetime(1970, 1, 1),
notes=["foo", "bar"],
),
fo.DynamicEmbeddedDocument(
task="editing_pass",
author="Bob",
timestamp=datetime.utcnow(),
),
],
),
)
sample2 = fo.Sample(
filepath="image2.png",
ground_truth=fo.Classification(
label="dog",
info=[ …
```
=> Adding support for list fields to dynamic schema methods

app/packages/dataset/src/Dataset.tsx, app/packages/state/src/recoil/atoms.ts
pass canEditCustomColors for permission in teams usage
(Details)
-   [ ] Other
=> permission for custom color settings

app/packages/state/src/recoil/sidebar.ts
After some backend PRs to enable expanding nested lists into top level ones, we can show these in the sidebar now - filterability for free.
No way one line change enables this haha 
The videos show the results in UI sidebar after following commands. New fields can be visualized and filtered just like any other fields
image dataset
https://user-images.githubusercontent.com/109545780/230228235-2163216e-15d1-4372-bcb3-ecd070d9044b.mp4
video dataset
https://user-images.githubusercontent.com/109545780/230228466-62e7b7b6-d4f8-4804-8e6d-7161f1a2666e.mov
**Case 1** Simple dynamic embedded document 
```
sm[“custom_document”] = fo.DynamicEmbeddedDocument(
a=1,
b="a_string",
c=1.1,
d=False,
e=["custom_tag_1", "custom_tag_11"]
)
fo.pprint(ds.get_field_schema(flat=True))
{
…
'tasks.labels.logits': …
```
=> Show embedded documents and list of documents in sidebar as filterable fields

fiftyone/utils/eval/segmentation.py, tests/intensive/evaluation_tests.py
Dice score computation in `evaluate_segmentations`
Existing unit-test parametrized to `compute_dice=True/False`.
NOTE: I had to disable `pylint` for both `test_classification_results` tests as it was not kept up-to-date with the recent `ClassificationResults` changes. I can help with the fix as well if required. 
Dice score can be computed per sample when evaluating semantic segmentations.
Specify `evaluate_segmentation(..., compute_dice=True)` in order to add a sample field
with `{eval_key}_dice` to each sample or run calculation on a segmentation results object: `results.dice_score()` .
-   [ ] …
=> add optional dice score computation for evaluate_segmentations

fiftyone/server/extensions.py
Adds back `stack` to GraphQL exceptions ensuring error boundaries work. Unfortunately, this regression was introduced by the unexpected upgrade then downgrade of strawberry caused by #2750
=> Add stack to GraphQL error extensions

fiftyone/core/clips.py, fiftyone/core/patches.py, fiftyone/core/video.py, fiftyone/core/view.py, tests/unittests/similarity_tests.py, tests/unittests/view_tests.py
Calling `reload()` now causes view stages to be re-validated, which allows for views to take into account any changes to the underlying dataset that occurred after the view is created.
In general, one can always reconstruct views from scratch, but `reload()` is now more a more viable option in cases where it is desired to continue using an existing `DatasetView` instance while a dataset may be changing underneath.
Example use case:
```py
view = dataset.select_fields("uniqueness")
dataset.delete_sample_field("uniqueness")
view.reload()
```
=> Revalidate stages upon view reload

fiftyone/core/patches.py, fiftyone/utils/eval/detection.py, fiftyone/utils/iou.py
Extended keypoints support and metrics for evaluation.
Tested on thousands of images.
Extended support for keypoints
-   [x] Yes
This will extend support for keypoints and its evaluation .The code changes are done only on keypoints function. This change is not interfering with other applications.
-   [ ] Other
=> Adding support for evaluating keypoints

setup.py
Relaxes the `starlette` dependency per a use request. All minor versions were verified to work
=> Relax starlette dependency

app/packages/looker/src/worker/benchmarking/benchmark-indexed-png-decoder.ts, app/packages/looker/src/worker/index.ts, app/packages/looker/src/worker/indexed-png-decoder.ts, app/packages/looker/src/worker/tests/indexed-png-decoder.test.ts
fixes #2920, essentially adding support for color type 3 PNGs (https://www.w3.org/TR/PNG-Chunks.html)
Locally.
-   [ ] Other
=> add support for indexed encoding in pngs

fiftyone/core/stages.py
Changelog
- Moves the `meta_filter` logic from `get_selected_fields()` and `get_excluded_fields()` to `_get_selected_fields()` and `_get_excluded_fields()`, respectively. This is necessary so that the relevant fields will be included when `to_mongo()` is called
- Ensures that `meta_filter` is also applied when processing frame-level fields (ie, when `frames=True` is passed to the above methods)
On a loosely related note, I also decided to always return `False` in `_needs_frames()`. I can explain offline if desired.
=> Meta filter updates

docs/source/user_guide/evaluation.rst, docs/source/user_guide/using_datasets.rst, fiftyone/core/collections.py, fiftyone/core/patches.py, fiftyone/core/stages.py, fiftyone/utils/eval/coco.py, fiftyone/utils/eval/detection.py, fiftyone/utils/eval/openimages.py, fiftyone/utils/iou.py
Finishes the work started in https://github.com/voxel51/fiftyone/pull/2776 to add keypoint evaluation to FO.
Matching is done via [object keypoint similarity](https://cocodataset.org/#keypoints-eval).
```py
"coco-2017",
label_types="detections",
classes=["person"],
max_samples=5,
)
model = foz.load_zoo_model("keypoint-rcnn-resnet50-fpn-coco-torch")
dataset.default_skeleton = model.skeleton
dataset.apply_model(model, label_field="gt")
dataset.clone_sample_field("gt_keypoints", "pred_keypoints")
for sample in dataset.iter_samples(autosave=True):
for keypoint in sample.pred_keypoints.keypoints:
points = …
```
=> Adding keypoint evaluation

app/packages/looker/src/worker/painter.ts
Correct inverted alpha value calculation in heatmap.
Locally.
-   [ ] Other
=> fix heatmap alpha bug

app/packages/core/src/components/Schema/SchemaSearch.tsx
noticed that all spaces should **not** be removed so we can support multi-word search ex: "description:bad annotations"
solution is to trim() instead
(Details)
-   [ ] Other
=> fix a bug with search and space replacement

app/packages/state/src/recoil/groups.ts
Account for dynamic groups edge case and return null if neither modal slice or default slice are defined
Locally
-   [ ] Other
=> fix null error

docs/source/cli/index.rst, fiftyone/core/cli.py, fiftyone/utils/image.py, fiftyone/utils/video.py
Resolves https://github.com/voxel51/fiftyone/issues/2909.
Two changes were made when updating images/videos in-place:
- Docstrings are updated to clarify that existing files will be moved to `-original` when `delete_originals=False`
- If an error occurs while transforming, the original file is moved back into place
Additionally, users can now opt *not* to update their dataset's filepaths by passing `update_filepaths=False`.
```py
import fiftyone.utils.image as foui
images_dir1 = "/tmp/images1"
images_dir2 = "/tmp/images2"
foz.load_zoo_dataset("quickstart").export(
export_dir=images_dir1,
dataset_type=fo.types.ImageDirectory,
)
dataset = fo.Dataset.from_images_dir(images_dir1)
foui.transform_images(dataset, size=(32, -1), …
```
=> Reencode updates

docs/source/user_guide/config.rst, fiftyone/core/config.py, fiftyone/operators/decorators.py, fiftyone/operators/executor.py, fiftyone/operators/server.py
=> add timeout to operator execution

fiftyone/core/dataset.py, tests/unittests/dataset_tests.py
`delete_labels()` did not previously handle the case where a sample with `None`-valued field was involved.
```py
dataset = foz.load_zoo_dataset("quickstart", max_samples=25)
dataset.take(10, seed=51).set_field("ground_truth", None).save()
label_id = dataset.exists("ground_truth").first().ground_truth.detections[0].id
view = dataset.select_labels(ids=label_id, fields="ground_truth")
assert len(view) == 1
dataset.delete_labels(ids=label_id, fields="ground_truth")
assert len(view) == 0
```
=> Handling missing label fields when deleting labels

fiftyone/utils/cvat.py
CVAT integration: support CVAT server v2.4 
tests/intensive/cvat.py; quick manual smoketest
CVAT integration: support CVAT server v2.4 
-   [ ] Other
=> CVAT v2.4 support

app/packages/core/src/components/Modal/Group/GroupContextProvider.tsx
Add missing app support for nested fields in dynamic groups (#2475).
Locally.
-   [ ] Other
=> add missing app support for nested fields in dynamic groups

app/packages/core/src/components/Schema/SchemaSearch.tsx, app/packages/core/src/components/Schema/SchemaSettings.tsx, app/packages/core/src/components/Sidebar/Entries/FilterEntry.tsx, app/packages/relay/src/mutations/__generated__/searchSelectFieldsMutation.graphql.ts, app/packages/relay/src/mutations/searchSelectFields.ts, app/packages/state/src/hooks/useSchemaSettings.ts, app/schema.graphql, fiftyone/server/mutation.py, fiftyone/server/query.py
- Fixes teams where dataset is null
- adds datasetName to seearchFields mutation
- Cleans up unused code
- merge frame fields and sample fields schemas to make better selection decision
(Details)
-   [ ] Other
=> Teams search fields mutation fix and cleanup for video dataset

app/packages/core/src/plugins/OperatorIO/utils/index.ts, fiftyone/operators/types.py
Adds a kwarg to specificy custom component to render for an operator input or output
(Details)
-   [ ] Other
=> add component property to view

app/packages/core/src/components/ImageContainerHeader.tsx, app/packages/core/src/components/Modal/Group/DynamicGroup/carousel/DynamicGroupsFlashlightWrapper.tsx, app/packages/core/src/components/Modal/Group/GroupView.tsx, app/packages/flashlight/src/index.ts, app/packages/state/src/recoil/groups.ts
Address comments from #2934
Locally
-   [ ] Other
=> Address dynamic groups PR comments

fiftyone/core/annotation.py, fiftyone/core/brain.py, fiftyone/core/dataset.py, fiftyone/core/evaluation.py, fiftyone/core/odm/dataset.py, fiftyone/core/runs.py, fiftyone/server/mutation.py, fiftyone/server/query.py, fiftyone/utils/data/exporters.py
If broken saved view/run references are encountered, log warnings that describe how to run the utils introduced in https://github.com/voxel51/fiftyone/pull/2970 to patch the issue *and* omit the broken references from all operations that would raise an error when encountering broken refs.
Example usage:
```py
from bson import ObjectId, DBRef
db = foo.get_db_conn()
dataset = foz.load_zoo_dataset("quickstart", max_samples=10, dataset_name="zzz")
dataset.evaluate_detections("predictions", gt_field="ground_truth", eval_key="eval")
dataset.save_view("test", dataset.limit(10))
dataset_dict = db.datasets.find_one({"name": dataset.name})
dataset_dict["saved_views"] = [ObjectId()]
dataset_dict["evaluations"] = …
```
=> Log warnings that hint how to patch broken saved views and runs

.github/workflows/build-db.yml, docs/source/getting_started/troubleshooting.rst, install.bash, package/db/setup.py
Partially addresses https://github.com/voxel51/fiftyone/issues/1803 and  https://github.com/voxel51/fiftyone/issues/2737
According to the [platform support matrix](https://www.mongodb.com/docs/manual/administration/production-notes/#platform-support-matrix), MongoDB 6.0.4+ now supports Ubuntu 22.04.
This PR adds a `fiftyone-db-ubuntu2204` build with MongoDB 6.0.5 for Ubuntu 22.04.
=> Adding fiftyone-db build for Ubuntu 22.04

app/packages/core/src/components/Modal/Looker.tsx
Fixes edge case where array urls weren't being transformed into objects.
Locally.
-   [ ] Other
=> fix sample url transformation edge case

app/packages/core/src/components/Actions/ActionsRow.tsx
```py
embeddings = np.random.randn(len(dataset), 512)
fob.compute_similarity(
dataset,
embeddings=embeddings,
model="clip-vit-base32-torch",  # hack so we can test text similarity
brain_key="sim",
)
```
=> video dataset should have access to similarity run

fiftyone/core/odm/database.py
The `patch_XXX()` utils needed to restrict to the appropriate `Run` class.
```py
from bson import ObjectId, DBRef
db = foo.get_db_conn()
dataset = foz.load_zoo_dataset("quickstart", max_samples=10)
dataset.evaluate_detections(
"predictions",
)
fob.compute_similarity(
dataset,
embeddings=np.random.randn(len(dataset), 12),
brain_key="sim",
)
dataset.save_view("test", dataset.limit(10))
dataset_dict = db.datasets.find_one({"name": dataset.name})
dataset_dict["saved_views"] = [ObjectId()]
dataset_dict["evaluations"] = {"eval": ObjectId()}
dataset_dict["brain_methods"] = {"sim": ObjectId()}
db.datasets.replace_one({"name": …
```
=> Restrict patching to correct Run class

app/packages/state/src/recoil/sidebar.ts, app/packages/utilities/src/index.ts
```py
dataset.add_sample_field("vector", fo.VectorField)
dataset.add_sample_field("array", fo.ArrayField)
```
=> Add ArrayField and VectorField to unsupported OTHER sidebar group

app/packages/components/src/components/Button/Button.module.css, app/packages/components/src/components/ThemeProvider/index.tsx, app/packages/core/src/plugins/OperatorIO/examples/Panel.tsx, app/packages/core/src/plugins/OperatorIO/examples/input.json, app/packages/core/src/plugins/OperatorIO/utils/index.ts, app/packages/core/src/plugins/SchemaIO/components/AutocompleteView.tsx, app/packages/core/src/plugins/SchemaIO/components/ListView.tsx, app/packages/operators/src/OperatorPalette.tsx, app/packages/operators/src/OperatorPlacements.tsx, app/packages/operators/src/OperatorPrompt.tsx, app/packages/operators/src/constants.ts, app/packages/operators/src/state.ts, app/packages/operators/src/types.ts, app/packages/operators/src/utils.ts, fiftyone/operators/types.py
- Adds hard-coded view name to all view classes
- Passes additional view options from JS operators
- Adds validate for operator input prompt
- Disables execute button if there are validation errors
(Details)
-   [ ] Other
=> additional operator prompt/types enhancements

app/packages/core/src/components/ColorModal/ColorFooter.tsx, app/packages/core/src/components/ColorModal/ColorModal.tsx, app/packages/core/src/components/ColorModal/FieldSetting.tsx, app/packages/core/src/components/ColorModal/GlobalSetting.tsx, app/packages/core/src/components/ColorModal/JSONViewer.tsx, app/packages/core/src/components/ColorModal/ShareStyledDiv.ts, app/packages/core/src/components/ColorModal/SidebarList.tsx, app/packages/core/src/components/ColorModal/colorPalette/AttributeColorSetting.tsx, app/packages/core/src/components/ColorModal/controls/ColorAttribute.tsx, app/packages/core/src/components/ColorModal/controls/RefreshColor.tsx, app/packages/core/src/components/Sidebar/Sidebar.module.css, app/packages/core/src/components/Sidebar/ViewSelection/ViewDialog.tsx, app/packages/looker-3d/src/Looker3d.tsx, app/packages/looker/src/overlays/base.ts, app/packages/spaces/src/App.css, app/packages/state/src/hooks/useClearSessionColorScheme.ts, app/packages/state/src/hooks/useSendEvent.ts, app/packages/state/src/hooks/useSessionColorScheme.ts, app/packages/state/src/recoil/color.ts
https://github.com/voxel51/fiftyone/assets/17770824/ab659f53-a6e5-4535-81e0-70846af851c0
(Details)
-   [ ] Other
=> ColorModal UI improvements + fix reset

fiftyone/core/state.py
Currently, sort by similarity fails to serialize the dataset when field info is defined.
```py
image_index = fob.compute_similarity(
dataset,
model="clip-vit-base32-torch",
brain_key="img_sim",
)
field = dataset.get_field("ground_truth")
field.info = {"test": 51}
field.save() 
```
=> Fix sort by similarity for datasets with field info

docs/source/cli/index.rst, fiftyone/core/cli.py, fiftyone/core/config.py, fiftyone/core/utils.py, fiftyone/plugins/__init__.py, fiftyone/plugins/core.py, fiftyone/plugins/definitions.py, fiftyone/server/routes/plugins.py, fiftyone/utils/github.py, tests/unittests/plugins/core_tests.py
Main updates
- Added `fiftyone plugins create` command to CLI
- Show plugin enabled status in `fiftyone plugins list`
- Adds optional `outdir` parameter to `creeate_plugin()` to create plugins in custom directories, if desired
- Adds a `plugin_names` parameter to `download_plugin()` to download specific plugins by name
- Entire interface now allows for `fiftyone.yaml` or `fiftyone.yml`
- Move `GitHubRepository` to `fiftyone.utils.github` as it is a general purpose utility
- Exposed all relevant function parameters in CLI
- Added CLI documentation for all new methods
Other things I encountered while making above changes:
- Fixed bugs
- Remove deprecated/unused/duplicate methods
- General implementation cleanup
```shell
fiftyone plugins list
fiftyone plugins create test
fiftyone plugins …
```
=> Plugin updates

fiftyone/server/routes/plugins.py
Fixes recent refactor regressed the contract for `GET /plugins` which should return `{plugins: []}`.
Note: this is not an issue in other form factors (teams).
=> Fix plugin route

fiftyone/server/app.py, setup.py
This is needed to fully support symlinks for plugin directories. Note: this also requires min version of 0.24.0 of starlette.
=> Plugins support symlinks

app/packages/operators/src/OperatorPalette.tsx, app/packages/operators/src/OperatorPrompt.tsx
Fixes view modal width and style for the operator palette
(Details)
-   [ ] Other
=> view modal width and palette base style fixes

app/gen-docs.js, app/packages/operators/src/types.ts, app/typedoc.js, docs/source/plugins/index.rst, docs/source/plugins/ts-api.rst
=> add initial jsdocs to operator types

app/packages/looker-3d/src/overlays/cuboid.tsx
add guards for invalid location or dimension in cuboid.tsx
Locally
-   [ ] Other
=> add guards for invalid location or dimension in cuboid.tsx

app/packages/core/src/components/ColorModal/ColorModal.tsx, app/packages/core/src/components/ColorModal/FieldSetting.tsx, app/packages/core/src/components/ColorModal/JSONViewer.tsx, app/packages/core/src/components/ColorModal/SidebarList.tsx, app/packages/core/src/components/ColorModal/colorPalette/AttributeColorSetting.tsx, app/packages/core/src/components/ColorModal/controls/ColorAttribute.tsx, app/packages/core/src/components/ColorModal/controls/OpacityAttribute.tsx, app/packages/core/src/components/FieldLabelAndInfo/index.tsx, app/packages/core/src/components/Sidebar/Entries/FilterablePathEntry.tsx, app/packages/state/src/recoil/atoms.ts
Fix a bug: previously colorbyattribute options failed to read frames.X fields attributes
(Details)
-   [ ] Other
=> bugfix: fix a frames related issue

fiftyone/core/odm/dataset.py, fiftyone/core/session/session.py, fiftyone/core/state.py
Change log
- `launch_app()` with no `dataset` was previously raising an error due to color scheme parsing, but should be allowed
- `session.color_scheme` should always be presented as a `ColorScheme` object. Previously it was presented as a string when updates were made in the App
- By convention, `session.color_scheme = None` should be allowed as shorthand for reverting to the default color scheme
- `session.color_scheme` was not updating when `session.dataset` is modified
```py
session = fo.launch_app()
print(session.color_scheme)  # default
dataset.app_config.color_scheme = fo.ColorScheme(
color_pool=["#ff0000", "#00ff00", "#0000ff", "pink", "yellowgreen"],
fields=[
{
"path": "ground_truth", …
```
=> Fixing color scheme bugs

app/packages/core/src/components/Schema/SchemaSettings.tsx, app/packages/relay/src/queries/__generated__/viewSchemaFragment.graphql.ts, app/packages/relay/src/queries/__generated__/viewSchemaFragmentQuery.graphql.ts, app/packages/relay/src/queries/viewSchema.ts, app/packages/state/src/hooks/useSchemaSettings.ts, app/packages/utilities/src/index.ts, app/schema.graphql, fiftyone/server/mutation.py, fiftyone/server/query.py
=> Schema field visibility bug fixes for datasets with frames and more

app/packages/core/src/components/Filters/BooleanFieldFilter.tsx, app/packages/core/src/components/Filters/LabelFieldFilter.tsx, app/packages/core/src/components/Filters/StringFieldFilter.tsx, app/packages/looker/src/elements/common/tags.ts
Fix sample tags do not respect field color issue.
https://github.com/voxel51/fiftyone/assets/17770824/c2044f71-b8f0-4cca-a41d-011642df69f4
(Details)
-   [ ] Other
=> Bugfix:sample tag color does not respect field color

app/packages/looker/src/elements/common/tags.ts
- Filters out empty list of classifications if any
problem
in `open-images-v7-validation-100` and other datasets, we saw `None` label/tags showing up in the Grid.
solution
filter empty lists of classifications
(Details)
-   [ ] Other
=> hide empty classification list as tags in looker

fiftyone/server/mutation.py
fixes a bug associated with `set_group_slice` mutation; the symptom on the app looking like:
Locally. To reproduce:
1. Open a dataset.
2. Add view stages / select a saved view.
3. Clear view stages.
4. Refresh the page.
There's also an e2e regression test that's part of dynamic groups e2e PR that checks for this.
-   [ ] Other
=> fix setGroupSlice mutation bug when refreshing page after clearing views

app/packages/core/src/components/Modal/Looker.tsx, app/packages/state/src/hooks/useCreateLooker.ts
`useCreateLooker()` expects `urls` as an object. But because of erroneous upstream transformation, it's sometimes received as an array of objects. This PR adds a guard so that urls passed as arrays are transformed into objects. This was previously done in `Looker.tsx` but there're other modules that also invoke `useCreateLooker()`, like `Grid.tsx` or flashlight, and it makes more sense for this transformation logic to be in `useCreateLooker()`.
Locally. …
=> fix urls transformation bug

app/packages/core/src/components/Sidebar/Entries/GroupEntries.tsx, app/packages/embeddings/src/tracesToData.tsx, app/packages/looker/src/elements/common/tags.ts, app/packages/looker/src/elements/common/util.ts, app/packages/looker/src/overlays/base.ts, app/packages/looker/src/overlays/classifications.ts, app/packages/looker/src/overlays/index.ts, app/packages/looker/src/worker/painter.ts, app/packages/state/src/recoil/color.ts
-Fixed overlay rendering issues of dynamic embeddedDoc fields
-Fixed a regression with rendering classification labels
-Fixed an issue that user cannot set color value for None/Undefined attribute values in color by value mode
Main change: updated the path and label to create overlay for dynamic embeddedDoc fields in this directory 
`app/packages/looker/src/overlays/index.ts`
How to test `DynamicEmbeddedDocument`: 
```
detections = fo.Detections(
detections=[
fo.Detection(
label="cat",
bounding_box=[0.018094074726104737, 0.5562847137451172, 0.17362892627716064, 0.15742950439453124],
foo="bar",
hello=True,
),
fo.Detection(
label="dog",
bounding_box=[0.217216157913208, 0.05954849322636922, …
```
=> Bugfix: fix overlay rendering issue for dynamic embeddedDoc fields

app/packages/core/src/components/Sidebar/Entries/FilterablePathEntry.tsx, app/packages/looker/src/elements/common/tags.ts, app/packages/looker/src/elements/common/util.ts, app/packages/looker/src/overlays/base.ts, app/packages/looker/src/overlays/classifications.ts, app/packages/looker/src/overlays/index.ts, app/packages/looker/src/overlays/util.ts, app/packages/looker/src/worker/painter.ts, app/packages/state/src/hooks/useUpdateSamples.ts, app/packages/state/src/recoil/aggregations.ts, app/packages/state/src/recoil/schema.ts, fiftyone/core/collections.py, fiftyone/server/routes/tag.py
Fix 1
The sample modal was not successfully tagging - unrelated to this work - @sashankaryal fixed that!
Fix 2
small backend tweak where dynamic fields with labels were coming in as `custom_document.detections` and getting suffixed with another detections causing DB filed error
Fix 3
With the recent introduction of allowing labels in embedded fields to be visualized/filtered, some redundant paths were added to the count and tagging paths. the schema is now flattened so that these dynamic fields can be recognized and visualized, etc. 
the flat schema is now bringing some unwanted/redundant label fields into labelPaths which eventually powers the tag label count and gets sent to /tag route when submitting a tag, causing a crash.
ex: labelPaths = [custom_document.detections, …
=> Filter out flattened and redundant sub fields to avoid overcounting label paths, failed tagging, etc.

app/packages/core/src/components/ViewBar/ViewStage/viewStageParameterMachine.ts, app/packages/looker/src/overlays/index.ts, app/packages/state/src/hooks/useSchemaSettings.ts
fixes 
- removes disabled/skipped fields for better hidden field count report.
- fixes the view stage to show the fields selected/excluded
(Details)
-   [ ] Other
=> view expression and count of hidden fields improved

fiftyone/utils/scale.py
I am working with labels from scale. In the following format.
```
"global_attributes": {
"traffic_density": "low",
"weather": [
"fog",
"rain"
]
},
```
While the string-based attribute "traffic_density" can be loaded with the fo dev branch, the list-based attribute "weather" throws an error as the list type is not compatible with `fol.Classification()`
The proposed changes support also the list type.
Import of private data into the database.
-   [] No. You can skip the rest of this section.
- Support for multi attribute labels for scale integration.
-   [x] Core: Core `fiftyone` Python library …
=> allow multi class classifications from scale.com labelling

fiftyone/server/mutation.py
teams stateless check before grabbing media_typ
(Details)
-   [ ] Other
=> undefined dataset error fix for stateless app

fiftyone/utils/yolo.py
Only load files if they end in `.txt`. This will ensure non-text files that are in the directory will not get loaded by accident.
Related to #1975, but takes changes from suggestion here: https://github.com/voxel51/fiftyone/pull/1975#issuecomment-1219818368.
Pass a folder with both `.txt` and non-text files like `.png` into `add_yolo_labels()`. …
=> Only match .txt files when reading YOLO labels

.github/workflows/pr.yml, fiftyone/core/labels.py, tests/unittests/sample_tests.py
The below is currently broken (may never have worked) on `release/v0.21.0`. Adding a `setter` for `_id` for labels with an id solves the issue, although I can't explain why it is only needed for raw label lists.
```py
dataset = fo.Dataset("tmp")
filepath="/tmp/image.png",
)
sample["custom"] = fo.DynamicEmbeddedDocument(
classifications=[fo.Classification(label="x")]
)
sample.save()
dataset.first()
```
=> Fix label list ids

app/packages/looker/src/elements/common/tags.ts
=> Bug: add label count back to the bubble grid view

app/packages/looker/src/elements/common/tags.ts
classification that is None should not show in Grid
With valid Classification shows `Right`
With None Classification shows nothing
(Details)
-   [ ] Other
=> remove None classifications from showing in Grid

fiftyone/core/json.py, fiftyone/core/session/client.py, fiftyone/core/session/events.py, fiftyone/core/state.py, fiftyone/operators/server.py, fiftyone/server/decorators.py, fiftyone/server/events.py, fiftyone/server/mutation.py, fiftyone/server/routes/samples.py, fiftyone/server/routes/sort.py
* Removes excess calls to `bson.json_util.dumps` and `bson.json_utils.loads`
* Removes `FiftyOneResponse` in favor of simplified`JSONResponse`usage
* Small fixes to prevent `len()` calls on sample collections
* `fiftyone.core.json` enhancements to prevent excess object creation
* `run_sync_tasks` additions where possible
* events serialization cleanup
=> Serialization cleanup

tests/unittests/server_tests.py
Updates hardcoded server test pipelines due to changes in generated expressions for `_label_tags` in #3133
=> Update server tests

fiftyone/operators/decorators.py
Check that a path is a directory in the case a plugins cache is enabled by env var, but plugins dir doesn't exist for whatever reason.
(Details)
-   [ ] Other
=> Plugins cache tweaks

app/packages/core/src/components/Actions/ActionsRow.tsx, app/packages/core/src/components/Modal/Group/DynamicGroup/UnorderedDynamicGroup.tsx, app/packages/core/src/components/Modal/Group/DynamicGroup/carousel/DynamicGroupCarousel.tsx, app/packages/core/src/components/Modal/Sample.tsx, e2e/cypress/support/e2e.ts
Move sample bar to modal from looker in dynamic groups. This also makes it possible to maximize carousel / image in dynamic groups modal.
All E2E tests green locally.
-   [ ] Other
=> move sample bar to modal from looker in dynamic groups

fiftyone/core/aggregations.py, fiftyone/core/clips.py, fiftyone/core/collections.py, fiftyone/core/dataset.py, fiftyone/core/odm/database.py, fiftyone/core/odm/mixins.py, fiftyone/core/patches.py, fiftyone/core/stages.py, fiftyone/core/video.py, fiftyone/server/samples.py, fiftyone/server/view.py, tests/unittests/server_tests.py
Replaces all usages of `$set` and `$unset` in aggregation pipelines with `$addFields` and `$project: {XXX: False}`, respectively.
This is being done as part of an effort to broaden the compatibility of FiftyOne with older MongoDB versions and other technologies like DocumentDB.
=> use $addFields and $project in aggregation pipelines

app/packages/core/src/components/ColorModal/SidebarList.tsx, app/packages/core/src/components/ColorModal/utils.ts, app/packages/core/src/components/FieldLabelAndInfo/index.tsx, app/packages/looker/src/elements/common/tags.ts, app/packages/looker/src/elements/common/util.ts
Added sample tags to colorScheme editor. User can now configure sample tags like other common ListField. 
https://github.com/voxel51/fiftyone/assets/17770824/526bdc8b-da1c-4a59-9e37-6230a629e4ab
-   [ ] Other
=> Add sample tags to colorScheme editor

.github/workflows/e2e.yml, app/packages/core/src/components/Actions/Options.tsx, app/packages/core/src/components/Modal/Group/GroupImageVideoSample.tsx, app/packages/core/src/components/Modal/Looker.tsx, app/packages/looker/src/elements/pcd.ts, app/packages/state/src/recoil/groups.ts, e2e/cypress.config.ts, e2e/cypress/e2e/dynamic-groups/dynamic-groups.cy.ts, e2e/cypress/support/commands.ts, e2e/cypress/support/e2e.ts, e2e/package.json, e2e/yarn.lock
- fix dynamic groups not working with pointcloud slices
- hide groups statistics selector when dynamic groups is on
- fix bug where 3d projected labels weren't showing when no orthographic projection was available
- add regression tests
- improve e2e
- install requirements to fix issue that was causing tests to fail because of missing deps
- catch rare and random known exceptions to reduce test flakiness
- make sure screenshots are always uploaded (previously was only uploaded on test success)
- locally, all e2e tests green
if this PR is part of a larger …
=> groups / dynamic groups bug fixes, fix e2e

app/package.json, app/packages/core/src/components/ColorModal/ColorModal.tsx, app/packages/core/src/components/ColorModal/ShareStyledDiv.ts, app/packages/core/src/components/Schema/SchemaSearchHelp.tsx, app/packages/core/src/components/Schema/SchemaSelectControls.tsx, app/packages/core/src/components/Schema/SchemaSelection.tsx, app/packages/core/src/components/Schema/SchemaSelectionRow.tsx, app/packages/core/src/components/Schema/SchemaSettings.tsx, app/packages/core/src/components/Sidebar/Entries/FilterEntry.tsx, app/packages/state/src/hooks/useSchemaSettings.test.ts, app/packages/state/src/hooks/useSchemaSettings.ts, app/packages/state/src/hooks/useSchemaSettings.utils.ts, app/vite.config.ts, app/yarn.lock
=> [1.3.1 Bug fixes]  Field visibility improvements

fiftyone/core/clips.py, fiftyone/core/collections.py, fiftyone/core/dataset.py, fiftyone/core/document.py, fiftyone/core/fields.py, fiftyone/core/labels.py, fiftyone/core/models.py, fiftyone/core/odm/document.py, fiftyone/core/odm/mixins.py, fiftyone/core/odm/utils.py, fiftyone/core/patches.py, fiftyone/core/stages.py, fiftyone/server/utils.py, fiftyone/server/view.py, fiftyone/utils/annotations.py, tests/unittests/dataset_tests.py, tests/unittests/import_export_tests.py, tests/unittests/label_tests.py, tests/unittests/sample_tests.py
Resolves https://github.com/voxel51/fiftyone/issues/3157
Resolves https://github.com/voxel51/fiftyone/issues/3183
Upgrades the SDK to fully support label fields stored as embedded document fields.
- Methods like `tag_labels()`, `select_labels()`, `export()`, and `draw_labels()` automatically detect and properly handle label fields stored within embedded documents
- All `Document` objects now support `doc["nested.field"]` key access, which ensures that methods that accept label fields as parameters will gracefully support nested label fields
- Fixes some bugs related to dynamic field expansion:
- https://github.com/voxel51/fiftyone/issues/3157
- https://github.com/voxel51/fiftyone/issues/3183
```py
import fiftyone.utils.annotations as foua …
```
=> Dynamic label field upgrades

fiftyone/core/dataset.py, tests/unittests/dataset_tests.py
I propose adding `persistent (default False)` and `overwrite (default False)` arguments to each of the Dataset factory functions (`fo.Dataset.from_*`), to mirror the parameters available in the `fo.Dataset` constructor.
Makes the solution for https://github.com/voxel51/fiftyone/issues/3016 a little more elegant
For reference, here is the args docstring for `class Dataset`
```
Args:
name (None): the name of the dataset. By default,
:func:`get_default_dataset_name` is used
persistent (False): whether the dataset should persist in the database
after the session terminates
overwrite (False): whether to overwrite an existing dataset of the same
name
```
- added to `DatasetFactoryTests`
```py
datadir = "/path/to/images"
dataset_name = "dataset"
dataset = …
```
=> Add persistent and overwrite arguments to dataset factory functions

fiftyone/constants.py
The compatibility version wasn't bumped with the 0.21 release.
This likely wasn't detected because `database_admin=True` by default in OSS, so compatibility version doesn't come into play (the compatibility version *was* bumped in Teams, where `database_admin=False` by default).
=> Bumping compatibility version

app/packages/looker-3d/src/Looker3d.tsx
Fix selector closing inconveniently as a result of container.onmouseleave triggering when looker3d re-renders. Removing `onMouseLeave` from `Container` has no real consequence, as `onMouseOver` subsumes what it intends to do.
Before:
After:
Locally.
-   [ ] Other
=> fix annoying pcd selector disappearing bug

app/packages/core/src/components/Actions/similar/utils.ts, fiftyone/server/query.py
Fixes the `/sort` route and other occurrences of serializing a dataset outside of graphql
=> Resolve saved views when serializing datasets

docs/source/user_guide/config.rst, fiftyone/core/config.py, fiftyone/core/context.py, fiftyone/core/session/notebooks.py, fiftyone/core/session/session.py
Resolves #2995 
Adds `proxy_url` to the `AppConfig` allowing for an override of the server URL. This only affect how the session resolves `session.url` for browser interactions, e.g. opening a tab or displaying a notebook cell
=> Session proxy url

fiftyone/server/routes/embeddings.py
Allows embeddings plots to be colored by list fields, eg sample or label tags.
This is useful, for example, in situations where each sample contains only one tag. IE train/test/val split. If there are multiple tags, the first one is used.
```py
dataset.untag_samples("validation")
fob.compute_visualization(dataset, brain_key="img_sim")
fob.compute_visualization(dataset, patches_field="ground_truth", brain_key="gt_sim")
for tag in "abcd":
dataset.take(100).tag_samples(tag)
dataset.take(100).tag_labels(tag, label_fields="ground_truth")
```
https://github.com/voxel51/fiftyone/assets/25985824/81c9ee70-bcf4-4e5a-acb2-091344ffb1e3
=> Allow coloring embeddings plots by list fields

app/packages/core/src/components/Filters/NumericFieldFilter.tsx
Fix a display bug for numeric field
Previously after I assign one value to float field, the value is shown as `none`. 
Fix: 
(Details)
-   [ ] Other
=> Fix numeric fields display bug

app/packages/core/src/components/ColorModal/ColorFooter.tsx, app/packages/core/src/components/ColorModal/ShareStyledDiv.ts
- Bugfix: `reset` button failed to set `can view` permission user setting back to dataset app_config setting on TEAMS. 
- Previously x-direction scroller shows up unnecessarily on color modal. 
(Details)
-   [ ] Other
=> Fix reset color

docs/source/user_guide/app.rst
Adds a compound indexes example for App filtering index usage
=> [DOCS] Compound indexes for group datasets

app/packages/state/src/recoil/sidebar.ts, app/packages/state/src/recoil/utils.ts, app/packages/state/tests/recoil/sidebar.test.ts
Fixes sidebar tests and some small regressions related to them (grouping unsupported/untyped list fields) and removing redundant group name updates
=> Update sidebar unit tests

app/package.json, app/packages/state/src/hooks/useSchemaSettings.test.ts, app/packages/state/src/hooks/useSchemaSettings.ts, app/packages/state/src/hooks/useSchemaSettings.utils.ts, app/packages/state/src/recoil/schemaSettings.atoms.ts, app/packages/utilities/src/index.ts, app/vite.config.ts
Disabling logic is an important piece of field visibility because if it has a wrong value, it can cause the app to crash (most probably due to select_fields or exclude_fields view stages failing to select or exclude unwanted fields).
Currently, we select and exclude fields based on path which can cause unintended disabling. it is improved to be based on path and type of self/parent field.
unit tests more granular selection of fields to avoid unintended selection.
(Details)
-   [ …
=> Unit tests for field visibility's disabling field logic

fiftyone/server/view.py
Since `0.21.1`, no label tag bubble counts are not shown when `label tags` is checked if sidebar filters are not present.
=> Fix label tags counts for filterless view

app/packages/state/src/recoil/groups.ts
In `0.21.1` and `0.21.2`, samples cannot be expanded (opened) when views a patches view in group datasets. Ensuring the `hasGroupSlices` is true for `group` media types resolves the issue
```py
view = dataset.select_group_slices("left").to_patches("ground_truth")
session = fo.Session(view)
```
=> Fix expanding samples in patches views for group datasets

fiftyone/core/session/client.py, fiftyone/core/session/session.py
Closes #3190 
Updates `Session.close()` to always kill the `ServerService` (and `AppService`, i.e. the Desktop App) and accordingly adds service restarts when calling `session.open()`
```py
session = fo.launch_app()
session.close()
session.open()
session = fo.launch_app(desktop=True)
session.close()
session.open()
```
=> Updating `Session.close()`

fiftyone/core/collections.py, fiftyone/core/stages.py, tests/unittests/label_tests.py
Fixes tagging and label filtering for embedded frame label fields. Also ensures `new_field` is properly assigned for frame label lists when using the `MatchLabels` stage.
```py
sample.frames[1]["dynamic"] = fo.DynamicEmbeddedDocument(
classification=fo.Classification(label="single")
)
sample.save()
dataset.add_dynamic_frame_fields()
dataset.tag_labels("classification", label_fields="frames.dynamic.classification")
assert dataset.count_label_tags()["classification"] == 10
```
=> Embedded frame label fixes

fiftyone/core/collections.py, fiftyone/core/dataset.py, fiftyone/core/odm/mixins.py, tests/unittests/dataset_tests.py
Resolves https://github.com/voxel51/fiftyone/issues/3273
Adds a `merge_sample()` method for merging a single sample into a dataset via the same basic interface as `merge_samples()`.
This method is useful for workflows that process one sample at a time, eg a cloud function that processes one sample at a time. It is *not* intended for use in a loop:
```py
for sample in samples:
dataset.merge_sample(sample, ...)
dataset.merge_samples(samples, ...)
```
=> Adding merge_sample() method

fiftyone/server/view.py
Ensures `only_matches` flag is set when creating the extended view from sidebar filters. This ensures a second matching is done **after** a label field list has been filtered. Also fixes `id` filtering by translating the path to `_id`
=> Fix sidebar matching on label fields

fiftyone/server/query.py
Avoid throwing hard errors that prevent loading a dataset in the app due to a missing field name
=> Suppress errors due to none fields

docs/source/integrations/lancedb.rst
=> Minor fixes

fiftyone/core/fields.py, fiftyone/core/labels.py, tests/unittests/label_tests.py
Fixes a bug when passing an RGB hex string to `Detection.to_segmentation(target=...)`.
Also adds some unit tests for Detection <> Polyline <> Segmentation conversions.
=> Label conversion bugfix/tests

fiftyone/core/session/client.py
In `0.21.3` a bug was introduced that prevents event emission due to changes in `Session.close()` (#3253 )
```py
session.view = dataset.limit(1)
```
=> Fix state updates from `Session`

fiftyone/utils/torch.py
added the functionality to do inference on the GPU on apple devices with the [metal backend in pytorch](https://pytorch.org/blog/introducing-accelerated-pytorch-training-on-mac/)
changed up the `_using_gpu` so it also checks for cuda and mps and then after also make the images go to `self._device` instead of going to `cuda()` directly
tested on some models in the zoo, I can not test if it conflicts on other devices 
(Details)
for Mac users have the ability to utilise more of their available hardware by utilising the MPS backend
(Details in 1-2 sentences. You can just refer to another PR with …
=> adding the ability to use any device trough parameter + apple's MPS automatic check

fiftyone/core/dataset.py, fiftyone/core/odm/document.py, fiftyone/core/odm/mixins.py
Resolves https://github.com/voxel51/fiftyone/issues/3185
As explained in the `@todo`, this is a bit of a hack to specifically avoid issues when concurrently modifying a dataset's schema. However, the underlying problem still exists whenever list fields other than `DatasetDocument.sample_fields` and `DatasetDocument.frame_fields` are concurrently edited without first reloading.
I think it makes sense to go ahead and merge this particular patch because schema updates are by far the most likely case where concurrent list edits may arise, since in many workflows `dataset` objects may be held in-memory for long periods of time without reloading them. Unlike samples, which are generally only loaded + modified on-demand.
=> Improved robustness of concurrent schema updates

fiftyone/core/models.py, fiftyone/utils/sam.py, fiftyone/utils/torch.py, fiftyone/zoo/models/manifest-torch.json, tests/intensive/model_zoo_tests.py
Add three [segment-anything](https://segment-anything.com/) models to the model zoo.
Added an extra intensive model test for sam backbone.
Segment-anything model is now available in the model zoo. It can perform automatic mask generation and guided mask generation with prompts.
-   [ ] Other
=> Add segment-anything models (SAM) to model zoo 

app/packages/operators/src/OperatorBrowser.tsx, app/packages/operators/src/OperatorIcon.tsx, app/packages/operators/src/OperatorPlacements.tsx, app/packages/operators/src/built-in-operators.ts, app/packages/operators/src/operators.ts, app/packages/operators/src/state.ts, fiftyone/operators/operator.py
Add support for custom operator icon
**Python:**
```py
class MyPyOperator(foo.Operator):
@property
def config(self):
return foo.OperatorConfig(
name="my_py_operator",
label="My Python Operator",
icon='/assets/icon.svg', # icon to use when dark_icon or light_icon is not provided
dark_icon='/assets/dark_icon.svg', # icon to use for when app is in the dark mode
light_icon='/assets/light_icon.svg', # icon to use for when app is in the light mode
)
```
**JavaScript**
```js
class MyJSOperator extends Operator {
get config() {
return new OperatorConfig({
name: 'my_js_operator',
label: 'My JavaScript Operator',
icon: '/assets/icon.svg', // icon to use when dark_icon or light_icon is not provided
darkIcon:'/assets/dark_icon.svg', // icon to use for when app is in the dark mode …
```
=> add support for custom operator icon

setup.py
Resolves #2210 
Removes the `starlette<0.27`. I am personally ok with removing this dependency, `starlette` seems stable now
=> Remove starlette ceiling

fiftyone/server/routes/embeddings.py
`ground_truth.detections` shouldn't be shown as a choice:
Now the only allowed list field is `tags`, which is valid:
=> Embeddings only color-by supported list fields

fiftyone/utils/labelbox.py
Labelbox has now fully deprecated "Queue mode" in favor of "batch mode". Previously, attempting to use the Labelbox integration would result in an error, this PR updates the integration to use batch mode and brings the integration back to its previous state.
Resolves #2654
=> Resolve errors with Labelbox integration

docs/scripts/make_model_zoo_docs.py, fiftyone/core/models.py, fiftyone/utils/sam.py, fiftyone/utils/torch.py, fiftyone/zoo/models/manifest-torch.json, tests/intensive/model_zoo_tests.py
Polishes up @Rusteam's work from https://github.com/voxel51/fiftyone/pull/3019.
[Segment Anything](https://segment-anything.com/) is now officially available in the [FiftyOne Model Zoo](https://docs.voxel51.com/user_guide/model_zoo/index.html)! 📈 
```py
"quickstart", max_samples=25, shuffle=True, seed=51
)
model = foz.load_zoo_model("segment-anything-vitb-torch")
dataset.apply_model(
model,
label_field="segmentations",
prompt_field="ground_truth",
)
```
```py
"coco-2017",
label_types="detections",
classes=["person"],
max_samples=25,
)
model = …
```
=> Adding Segment Anything to the model zoo!

fiftyone/core/fields.py, fiftyone/core/odm/document.py, fiftyone/core/odm/embedded_document.py, tests/unittests/dataset_tests.py, tests/unittests/label_tests.py
=> Ensure has_field() supports dynamic fields

fiftyone/zoo/models/manifest-torch.json, fiftyone/zoo/models/torch.py
- Use weights parameter when loading torchvision models for people with torchvision >= 0.13.0
- Use pretrained=true parameter for users with torchvision < 0.13.0.  
- Backwards compatible for users with older versions of torchvision.
Downloaded various torchvision models using torchvision==0.15.2 and then using torchvision==0.12.0.
Tested model with no entrypoint_args.
-   [ …
=> Use weights parameter instead of deprecated pretrained for torchvision models

docs/source/cli/index.rst, fiftyone/core/cli.py, fiftyone/factory/__init__.py, fiftyone/factory/repos/delegated_operation.py, fiftyone/factory/repos/delegated_operation_doc.py, fiftyone/operators/__init__.py, fiftyone/operators/delegated.py, fiftyone/operators/executor.py
- Adds a `fiftyone delegated` CLI command that supports a variety of useful actions related to delegated operators
- Adds a `foo.execute_operator()` method that supports programmatically execution of operators
Launch a local service that will run all delegated operations:
```shell
fiftyone delegated launch
```
List delegated operations:
```shell
fiftyone delegated list
fiftyone delegated list \
--dataset quickstart \
--operator @voxel51/io/export_samples \
--state COMPLETED \
--sort-by COMPLETED_AT \
--limit 2
```
Cleanup delegated operations that you no longer want to keep records for:
```shell
fiftyone delegated cleanup --dataset quickstart --state FAILED
fiftyone delegated cleanup --orphan
fiftyone delegated cleanup --orphan --dry-run        
```
```py
import …
```
=> Delegated operators CLI

fiftyone/core/stages.py, fiftyone/core/view.py, tests/unittests/group_tests.py
Resolves https://github.com/voxel51/fiftyone/issues/3334.
`select_group_slices()` emits unfiltered samples, since it applies a fresh `$lookup` to retrieve slice data. However, the current implementation does *intend* maintain any schema changes (select/exclude fields) that were applied prior to the `select_group_slices()` stage. https://github.com/voxel51/fiftyone/issues/3334 identified a gap in the enforcement of this convention, which this PR patches.
This PR is pretty ugly... which is a symptom of the tension between the inconsistency of *maintaining* schema changes while *not maintaining* field filters when selecting group slices.
Here's what it would look like to enforce a convention that `select_group_slices()` does *not* maintain schema changes (for consistency with how it does …
=> Reapply schema changes after selecting group slices

app/packages/core/src/components/ColorModal/FieldSetting.tsx, app/packages/looker-3d/src/Looker3d.tsx, app/packages/looker/src/elements/common/tags.ts, app/packages/looker/src/elements/common/util.test.ts, app/packages/looker/src/elements/common/util.ts, app/packages/looker/src/overlays/base.ts, app/packages/looker/src/overlays/util.ts
Support to customize color by ListFields (both embeddedDoc type and primitive type) in color modal.
Users should be allowed to configure custom Color by value rules for ListField, just like they can for other “primitive” fields like ints, strs, floats, etc.
For list fields, when a custom (value, color) pair is defined, simply apply the color if the list contains the value, rather than if the list equals the value.
Of course, the list field may contain multiple values with custom color pairs defined. No worries, any one of the colors is valid. 
Tip: If the list meets multiple color rules, looker will use the first applicable `valueColors` match in `ColorScheme` to render. 
Primitive List of StringField example: 
https://github.com/voxel51/fiftyone/assets/17770824/d4a96b8f-5293-4f54-869c-fcc …
=> Support to custom color by ListField with boolean, string, and int subfields 

app/packages/embeddings/src/fetch.tsx, app/packages/embeddings/src/useExtendedStageEffect.tsx, app/packages/embeddings/src/useSelectionEffect.tsx, app/packages/embeddings/src/useViewChangeEffect.tsx, fiftyone/server/routes/embeddings.py
Uses the current group slice to properly build a view for loading plot data for the embeddings panel. With this change you will now see corresponding samples that match the following:
1. the currently selected group slice
2. exist within the currently selected brain key (visualization)
Note: even with this change there is no simple "1 click" ux for showing multiple slices, even if they meet criteria 2.
=> Add support for viewing group slices within embedding panel

fiftyone/core/view.py, fiftyone/server/aggregations.py, fiftyone/server/routes/tag.py, fiftyone/server/routes/tagging.py, fiftyone/server/tags.py, tests/unittests/view_tests.py
When selecting multiple samples across slices in a group dataset in the modal, converting to a flat view ensures all samples are matched and no lookup occurs after the selection.
Supporting e2e and unit tests for `make_optimized_select_view` from @manivoxel51 and I will validate this change
=> Convert to mixed view for group datasets when making optimized sample collection

app/packages/core/src/components/Actions/similar/Similar.tsx, app/packages/core/src/components/ColorModal/ColorFooter.tsx, app/packages/core/src/components/Sidebar/Entries/Draggable.tsx, app/packages/core/src/components/Sidebar/ViewSelection/index.tsx
Improve the read-only mode in the app by extending it to actions below:
- Use the global read-only state for colour modal
- Use the global read-only state for saved views
- Disable the ability to similarity distance in a field
- Disable sidebar re-ordering
In the app with the global read-only mode enabled
-   [ ] Other
=> improve readonly mode in the app

fiftyone/core/json.py
Add try/except around bytes conversion 
I think some of the plugins are sending non-numpy arrays as bytes in the response object, causing an error that prevents other plugins from getting loaded/executed
For example:
```
ERROR:root:cannot import name 'StringIO' from 'io' (/Users/kacey/Dev/voxel51/fiftyone-plugins/plugins/io/__init__.py)
File "./fiftyone/server/decorators.py", line 29, in wrapper
response = await func(endpoint, request, data, *args)
File "./fiftyone/server/routes/samples.py", line 45, in post
"results": await run_sync_task(
File "./fiftyone/core/utils.py", line 1913, in run_sync_task
return await loop.run_in_executor(get_sync_task_executor(), func, *args)
File "/Users/kacey/.pyenv/versions/3.9.15/lib/python3.9/concurrent/futures/thread.py" …
```
=> Make stringify work for non np arrays

app/packages/operators/src/OperatorBrowser.tsx, app/packages/operators/src/OperatorPalette.tsx, app/packages/operators/src/OperatorPrompt.tsx, app/packages/operators/src/state.ts
- Add loading indicator when resolving input is in progress
- Disable execute button if resolving or there is unresolved changes or if it's resolving
- Immediately validate form on prompt
- Improve "Executing..." UI
(Details)
-   [ ] Other
=> improve operator form validation debounce

app/packages/relay/src/queries/__generated__/paginateSamplesQuery.graphql.ts, app/packages/relay/src/queries/paginateSamples.ts, app/schema.graphql, fiftyone/server/query.py
Adds missing `filters` variable to `paginateSamples` in the sample grid's flashlight parameters
https://github.com/voxel51/fiftyone/assets/19821840/ecdc07c8-5bf7-40f3-8d2f-08d5ed680666
=> Add back missing grid filters

app/packages/looker-3d/src/Looker3d.tsx, app/packages/looker-3d/src/containers.ts, e2e-pw/src/oss/fixtures/loader.ts, e2e-pw/src/oss/poms/action-row/grid-slice-selector.ts, e2e-pw/src/oss/poms/grid/index.ts, e2e-pw/src/oss/poms/modal/index.ts, e2e-pw/src/oss/specs/regression-tests/group-video/default-video-slice-group.spec.ts, e2e-pw/src/oss/specs/regression-tests/group-video/group-video-label.spec.ts, e2e-pw/src/shared/media-factory/image.ts, e2e-pw/src/shared/media-factory/index.ts, e2e-pw/src/shared/media-factory/pcd.ts
- Add regression test for video label bug
- Add pcd media factory
- Fix looker3d code that was causing media field bug (e2e coverage in upcoming PR)
Ran this spec with flake-analysis utility for ten runs, all green.
-   [ ] Other
=> regression test for video labels bug + media field bug fix

app/packages/core/src/components/Modal/Group/GroupSample3d.tsx
e2e test in progress
```py
dataset = fo.Dataset("pcd-only-sparse")
dataset.add_group_field("group", default="shared")
source = foz.load_zoo_dataset("quickstart-groups", max_samples=9)
source.group_slice = "pcd"
first = fo.Group()
one = source.first().copy()
one.group = first.element("shared")
two = source.skip(1).first().copy()
two.group = first.element("unique")
second = fo.Group()
three = source.skip(2).first().copy()
three.group = second.element("shared")
dataset.add_samples([one, two, three])
```
https://github.com/voxel51/fiftyone/assets/19821840/af987331-90d2-4484-a2ae-05aace2125db
=> Looker3D sparse slices handling

.github/workflows/e2e.yml, app/packages/components/src/components/ErrorBoundary/ErrorBoundary.tsx, app/packages/core/src/useFlashlightPager.ts, e2e-pw/src/oss/fixtures/loader.ts, e2e-pw/src/oss/poms/panel.ts, e2e-pw/src/oss/specs/groups/empty-groups.spec.ts, e2e-pw/src/shared/abstract-loader.ts
#3333 introduces the shared pagination hook for samples (grid and carousel) `useFlashlightPager`. Error handling for pagination requests is missing in this new hook.
Group datasets do not have defined slices until samples are added, so I've added an e2e test that asserts an expected error from the grid when paginating over the undefined default slice.
```py
dataset = fo.Dataset("empty-group-dataset")
dataset.add_group_field("group", default="empty")
```
=> Handle flashlight page errors

app/packages/core/src/components/ColorModal/ColorModal.tsx, app/packages/core/src/components/ColorModal/GlobalSetting.tsx, app/packages/core/src/components/ColorModal/ShareStyledDiv.ts
Adds helper text to custom color modal 
- explaining what color pool is
- A note that only color pool changes are saved (for now)
(Details)
-   [ ] Other
=> helper texts for custom color saving capabilities

app/packages/core/src/components/Actions/Tagger.tsx, app/packages/core/src/components/Actions/utils.tsx, app/packages/core/src/components/Filters/categoricalFilter/CategoricalFilter.tsx, app/packages/core/src/components/Modal/Looker.tsx, app/packages/state/src/hooks/useExpandSample.ts, app/packages/state/src/hooks/useSetExpandedSample.ts, fiftyone/server/routes/tag.py, fiftyone/server/routes/tagging.py, fiftyone/server/routes/values.py
Fixes and/or adds support for tagging all visible (selected) PCD slices. Also ensures modal state is configured correctly on expansion. Currently on `release/v0.21.5`, opening a group dataset sample and then closing, and switching to non-group dataset and _then_ opening the modal will crash the App.
Example multi-pcd slice group dataset
```py
dataset = fo.Dataset("pcd-only-sparse")
dataset.add_group_field("group", default="shared")
source = foz.load_zoo_dataset("quickstart-groups", max_samples=9)
source.group_slice = "pcd"
first = fo.Group()
one = source.first().copy()
one.group = first.element("shared")
two = source.skip(1).first().copy()
two.group = first.element("unique")
second = fo.Group()
three = …
```
=> PCD tagging and group modal resets

app/packages/plugins/src/index.ts
Changed the ok-condition from equal to not equal. As `warn()` prints the message if the ok-condition is false and we want the ok-condition to be false if `registration.type` equals `PluginComponentType.Plot`.
Compiled from source and warning `_______ is a Plot Plugin Component. This is deprecated. Please use "Panel" instead.`
Is gone for plugins which are not a Plot Plugin Component.
-   [ x ] No. 
-   [ x ] App: FiftyOne application changes
-   [ ] Other
=> Fixed warn condition plugin component registration

fiftyone/utils/activitynet.py, fiftyone/utils/kinetics.py, fiftyone/utils/youtube.py
Some video datasets in the zoo like ActivityNet and Kinetics will optionally download the videos directly from the sources on YouTube using `pytube`. However, with PyTube versions <15, the video downloads would fail with this error:
```
Failed to download video 'https://www.youtube.com/watch?v=-9l1Rh10bO8': 'streamingData' 
```
[Updating the minimum supported Pytube version to >=15 resolves this issue.](https://stackoverflow.com/a/76268388/14277626)
This also lets us get rid of the patching code we were using for pytube v11.0.2.
There is also a new error that pytube throws which was causing issues with the error parsing in the zoo datasets, the error handling of kinetics/activitynet was updated to properly log this error now.
=> Update pytube requirement to fix zoo YouTube download error

app/packages/core/src/components/Grid/Grid.tsx, app/packages/core/src/components/Modal/Group/GroupCarousel.tsx, app/packages/core/src/useFlashlightPager.ts, app/packages/looker-3d/src/Looker3d.tsx
Fixes empty grid resets, a regression introduced by `useFlashlightPager`. The attached recording shows how to currently reproduce the error on `release/v0.21.5`
https://github.com/voxel51/fiftyone/assets/19821840/8c07fbca-e22b-44f1-b5a4-dd69c6c3ba0e
=> Reset empty grid state

fiftyone/utils/yolo.py
@brimoor PR per https://github.com/voxel51/fiftyone/issues/3392. 
If we could squeeze this into `fiftyone==0.21.5` that would be awesome!
Replaced `nc` integer and `names` list with a `names` dictionary per the new format in https://docs.ultralytics.com/datasets/detect/. 
This new format works for all Ultralytics YOLO repos (v3/v5/v8) and has been in place for about a year, so this should be widely compatible with most forks and copies in the wild.
The old format is being maintained through 2023 and will be deprecated in 2024.
Not tested.
> Replaced deprecated `nc` integer and `names` list with a `names` dictionary per the new format in …
=> Update Ultralytics YOLO `dataset.yaml` format

app/packages/state/src/recoil/view.ts
Will follow up with e2e.
Dynamic grouping of a group dataset requires pagination over the dynamically grouped samples. These results require providing the current view while replacing the `GroupBy` stage with the matching stage and filtering limit and skip stages post matching stage.
```py
ds = foz.load_zoo_dataset('quickstart-groups',dataset_name='qsg-test')
scene_id = ['scene1','scene2','scene3','scene4']*50
frame = range(len(ds))
for slice in ds.group_slices:
ds.group_slice = slice
ds.set_values('scene_id',scene_id)
ds.set_values('frame',frame)
v = ds.limit(10)
view = v.group_by('scene_id', order_by='frame')
ds.save_view('dynamic-limit', view)
```
=> Fix dynamic groups modal of a view

app/packages/embeddings/src/EmbeddingsPlot.tsx, app/packages/embeddings/src/styled-components.tsx
Update embeddings colormap recoil state
=> Fix embeddings 

e2e-pw/src/oss/fixtures/index.ts, e2e-pw/src/oss/poms/grid/index.ts, e2e-pw/src/oss/poms/modal/index.ts, e2e-pw/src/oss/specs/regression-tests/group-video/default-video-slice-group.spec.ts, e2e-pw/src/oss/specs/regression-tests/group-video/group-video-label.spec.ts, e2e-pw/src/shared/event-utils/index.ts
Add a generic `EventUtils` fixture that can be used to wait on arbitrary events until a predicate is satisfied.
locally
-   [ ] Other
=> add event utils fixture

e2e-pw/package.json, e2e-pw/src/shared/python-runner/python-runner.ts, e2e-pw/yarn.lock
- Upgrade Playwright to 1.37 ([Release Notes](https://playwright.dev/docs/release-notes))
- Most relevant update = "UI Mode now respects project dependencies" 🎉
- Allow passing env to python command generator class
- Locally
-   [ ] Other
=> upgrade pw

app/packages/components/src/components/Selection/Option.tsx, app/packages/components/src/components/Selection/SearchBox.tsx, app/packages/components/src/components/Selection/Selection.tsx, app/packages/core/src/components/Sidebar/Sidebar.tsx, app/packages/core/src/components/Sidebar/ViewSelection/ViewDialog.tsx, app/packages/core/src/components/Sidebar/ViewSelection/index.tsx, e2e-pw/package.json, e2e-pw/src/oss/fixtures/index.ts, e2e-pw/src/oss/poms/saved-views.ts, e2e-pw/src/oss/specs/smoke-tests/saved-views.spec.ts
- Note: I still see intermittent failures when run locally.
- I have tried not used waitForTimeout as much as possible, but currently I have couple to wait for dialogs to close etc. I had a hard time use the locator.wait({ state: 'visible'}). 
(Details)
-   [ ] Other
=> E2E for saved views

app/packages/core/src/components/Actions/Common.tsx, app/packages/core/src/components/Actions/Patcher.tsx, app/packages/core/src/components/ImageContainerHeader.tsx, app/packages/core/src/components/ResourceCount.tsx, app/packages/core/src/components/index.ts, e2e-pw/src/oss/poms/action-row/grid-actions-row.ts, e2e-pw/src/oss/specs/smoke-tests/quickstart.spec.ts
If groupBy stage is active, we inject "groups of" in the count text if appropriate.
minor refactor to move Count into its own component
https://github.com/voxel51/fiftyone/assets/109545780/998f8d18-b783-47cd-bd55-4c8fd7d17135
(Details)
-   [ ] Other
=> Count text when toPatches, then groupBy fix + e2e

docs/source/plugins/index.rst
Fixed a small bug/ copy-paste mistake in the plugin docs.
Do you prefer small PRs like this, or should I write issues for stuff like this instead?
-   [ ] Other
=> [DOC] Bug in Plugins Placements JS-Example

fiftyone/core/cli.py
When running `fiftyone datasets export ...` from cli, dataset filters can be provided in order to export only a subset.
Running from cli to test it:
```
alias fod="fiftyone datasets"
fod export quickstart -d tmp -t fiftyone.types.ImageDirectory --filters tags=test
fod export quickstart -d tmp -t fiftyone.types.ImageDirectory --filters ground_truth=kite,bird,airplane
```
The output should only contain a subset that matches this sample tag and labels.
Fiftyone cli dataset export now supports sample tag and label filters in order to export only a subset.
-   [ ] Build: Build and test infrastructure …
=> add dataset tag and label filters when exporting a dataset from cli

fiftyone/utils/openlabel.py, tests/unittests/import_export_tests.py, tests/unittests/utils/openlabel.py
The OpenLABEL importer is designed to set `None` values for missing list attributes of keypoints. 
The issue is that setting None values like that for these attributes:
```python
keypoint = fo.Keypoint(
label="rectangle",
points=[
(0.3, 0.3),
(float("nan"), float("nan")),  # use nan to encode missing points
(0.7, 0.7),
(0.3, 0.7),
],
my_occluded_attr=[
"partially",
None,
"fully",
"partially",
]
)
```
Will result in errors when trying to add the attributes to the dataset schema (`dataset.add_dynamic_sample_fields()`)
This PR updates this logic to set them to be `""` instead for strings, `0` or `0.0` for numeric types, and `False` for booleans.
Also updated the OpenLABEL tests to check for this so it would have failed previously and now passes.
=> Fix OpenLABEL importer when given incomplete keypoint skeletons

fiftyone/core/session/session.py
When launching the via `fiftyone.core.session.session.launch_app()`, the current behavior is to close the existing global `_session` if it is defined.
This change proposes to omit that step for faster launches when `launch_app` is used multiple times. The previous `session` will be cleaned up when the main process exits.
=> Omit `close_app` in `launch_app`

fiftyone/core/cli.py
Updates the `fiftyone delegated` CLI commands, which were broken as `ExecutionRunState` is no longer an `enum`.
Also adds the FO welcome message when launching the delegated operation service locally:
```
$ fiftyone delegated launch
Welcome to
███████╗██╗███████╗████████╗██╗   ██╗ ██████╗ ███╗   ██╗███████╗
██╔════╝██║██╔════╝╚══██╔══╝╚██╗ ██╔╝██╔═══██╗████╗  ██║██╔════╝
█████╗  ██║█████╗     ██║    ╚████╔╝ ██║   ██║██╔██╗ ██║█████╗
██╔══╝  ██║██╔══╝     ██║     ╚██╔╝  ██║   ██║██║╚██╗██║██╔══╝
██║     ██║██║        ██║      ██║   ╚██████╔╝██║ ╚████║███████╗
╚═╝     ╚═╝╚═╝        ╚═╝      ╚═╝    ╚═════╝ ╚═╝  ╚═══╝╚══════╝ v0.21.6
If you're finding FiftyOne helpful, here's how you can get involved:
|
|  ⭐⭐⭐ Give the project a star on GitHub ⭐⭐⭐
|  https://github.com/voxel51/fiftyone
|
| …
```
=> Delegated operators CLI fix

fiftyone/core/cli.py, fiftyone/factory/__init__.py, fiftyone/factory/repo_factory.py, fiftyone/factory/repos/__init__.py, fiftyone/factory/repos/delegated_operation.py, fiftyone/factory/repos/delegated_operation_doc.py, fiftyone/operators/delegated.py, fiftyone/operators/executor.py, tests/unittests/delegated_operators_tests.py
Quick editing pass to apply our [Python style guide](https://github.com/voxel51/fiftyone/blob/develop/STYLE_GUIDE.md#python-style-guide) to delegated operators.
Notes
- convert `SortBy` and `SortDirection` to regular classes, not enums, for consistency with `ExecutionRunState`
- rename `DelegatedOpPagingParams` to `DelegatedOperationPagingParams` for consistency with how `Operation` is not abbreviated in other class names
- don't use type annotations in `fiftyone.operators.delegated`, for consistency with other modules in this subpackage
- apply 79 character line limit to docstrings and fix broken `:class:` links
- alphabetize imports
- adds some missing type annotations/docstrings in `fiftyone.factory`
=> Delegated operators linting

app/packages/core/src/components/Filters/NumericFieldFilter.tsx, app/packages/core/src/components/Filters/categoricalFilter/CategoricalFilter.tsx, app/packages/core/src/components/Filters/categoricalFilter/Wrapper.tsx
Fix bug: remove unnecessary refresh with visibility setting reset. 
https://github.com/voxel51/fiftyone/assets/17770824/de6d3851-ca86-4d1f-8a22-77a19b92fde2
-   [ ] Other
=> remove unnecessary refresh with visibility reset

app/packages/core/src/components/Actions/DynamicGroup.tsx, e2e-pw/src/oss/poms/action-row/grid-actions-row.ts, e2e-pw/src/oss/specs/dynamic-groups-cifar.spec.ts, e2e-pw/src/oss/specs/smoke-tests/quickstart.spec.ts
- This fixes the flaky behavior of some e2e tests related to dynamic groups caused by selecting a group-by field before it's populated.
- Locally
=> fix dynamic groups e2e bug

app/packages/core/src/components/Actions/Tagger.tsx, app/packages/core/src/components/Modal/Group/GroupImageVideoSample.tsx, app/packages/core/src/components/Modal/Group/GroupSample3d.tsx, app/packages/core/src/components/Modal/Sample.tsx, app/packages/core/src/useFlashlightPager.ts, app/packages/looker/src/state.ts, app/packages/state/src/hooks/useUpdateSamples.ts, fiftyone/server/routes/media.py, fiftyone/server/samples.py, tests/unittests/server_tests.py
Resolves #3431 
In `0.21.6`, modal sample data can be overwritten by the group carousel due to globally unique id store in relay. Adding a `-modal` suffix to sample IDs when they are requested without pagination data resolves the issue. The `-modal` naming is tentative.
The best way to add an e2e test is to screenshot the JSON panel in a group dataset, if it is practical.
=> Unique ID for full sample JSON in modal

fiftyone/factory/repos/delegated_operation_doc.py, fiftyone/internal/secrets/__init__.py, fiftyone/internal/secrets/providers/__init__.py, fiftyone/internal/secrets/providers/iprovider.py, fiftyone/internal/secrets/providers/local.py, fiftyone/internal/secrets/secret.py, fiftyone/operators/delegated.py, fiftyone/operators/executor.py, fiftyone/operators/operator.py, fiftyone/operators/registry.py, fiftyone/plugins/__init__.py, fiftyone/plugins/context.py, fiftyone/plugins/definitions.py, fiftyone/plugins/secrets.py
=> Add secrets to plugins

fiftyone/server/app.py
Resolves #3424 
Reverts the change in #3338 as it is causing 404 issues on some existing installations
=> Revert follow symlinks in `static`

fiftyone/operators/decorators.py, tests/unittests/operators/decorators_tests.py
Fix `ValueError: max() arg is an empty sequence` for when a plugin dir exists but is empty
=> early return for empty dir and ignore hidden files

fiftyone/utils/sam.py
Running SAM from the Model Zoo with the given [example code](https://docs.voxel51.com/user_guide/model_zoo/models.html#segment-anything-vitl-torch) was not working.
It turns out that it is because the model's weights were never loaded into the model.
Moreover, when running the unprompted inference, the _forward_pass_auto() was incorrect and yielded a unique Segmentation, discarding the whole hierarchy of masks.
This PR corrects both issues, by loading the model properly onto the chosen device, as well as producing Detections for each inference result produced by SAM.
```python
model_name = "segment-anything-vitb-torch"
model = foz.load_zoo_model(model_name)
label_field = …
```
=> Corrected SegmentAnythingModel's incorrect loading and unprompted inference.

app/packages/core/src/components/Grid/Grid.tsx, app/packages/core/src/components/Modal/Group/GroupSample3d.tsx, app/packages/core/src/components/Modal/Looker.tsx, app/packages/core/src/components/Modal/ModalNavigation.tsx, app/packages/core/src/components/Sidebar/Entries/FilterEntry.tsx, app/packages/looker-3d/src/Looker3d.tsx, app/packages/looker-3d/src/action-bar/ViewHelp.tsx, app/packages/looker-3d/src/action-bar/ViewJson.tsx, fiftyone/operators/delegated.py
Whereas previously we were just closing the modal on `Esc`, this PR makes sure we close the modal only after other sub-contexts have been properly closed.
Commit log:
- [fix hover sample bug in looker 3d](https://github.com/voxel51/fiftyone/pull/3473/commits/dcae6372bdd14b80487fb6360aaa020f2a04a85b)
- [remove redundant action handlers](https://github.com/voxel51/fiftyone/pull/3473/commits/0f638c357ee6af8e71a3c0550abb1de98a762077)
- [remove dynamically rendered component](https://github.com/voxel51/fiftyone/pull/3473/commits/553b43a6c97604cc9e2c510628a0d93095cabc6b)
- [fix grid esc race condition](https://github.com/voxel51/fiftyone/pull/3473/commits/d0faebb84af88027496eb37a9598a8ff7ca2fba6)
Locally.
Todo: add e2e coverage after routing PR (https://github.com/voxel51/fiftyone/pull/2742) is …
=> Fix esc hierarchy bug

app/packages/looker/src/lookers/abstract.ts
The default `lineJoin` algorithm is `miter`, which extends the two lines to meet at a point called the "miter point". A `miterLimit` parameter is used to control how far the miter point can extend before it's beveled to prevent overly long, sharp corners. Reducing `miterLimit` to a low value like `1` made the corners look significantly better, but they were still not completely gone. `bevel`, which creates a more rounded corner by adding a diagonal line between the endpoints of the connected lines, is a nice compromise between `miter` and `round`.
([link to w3 playground for `lineJoin`](https://www.w3schools.com/tags/canvas_linejoin.asp))
Visually, locally
notes …
=> fix polyline rendering artifact

fiftyone/operators/executor.py
Resolve secrets in context before resolve_input called to make secrets usable in resolve_input
Tested with secrets plugin and accessing ctx.secrets in an operator's ` resolve_input(self, ctx), ` resolve_output(self, ctx)`, and 'execute(self, ctx)'
=> add secrets to context before resolve_input called

app/packages/core/src/components/Schema/SchemaSelectionRow.tsx, app/packages/core/src/components/Schema/SchemaSettings.tsx, app/packages/core/src/components/Sidebar/Entries/AddGroupEntry.tsx, app/packages/core/src/components/Sidebar/Entries/Draggable.tsx, app/packages/core/src/components/Sidebar/Entries/FilterEntry.tsx, app/packages/core/src/components/Sidebar/Sidebar.tsx, app/packages/state/src/hooks/useSchemaSettings.ts, app/packages/state/src/recoil/schemaSettings.atoms.ts, app/packages/state/src/recoil/sidebar.ts, e2e-pw/src/oss/poms/field-visibility/field-visibility.ts, e2e-pw/src/oss/poms/sidebar.ts, e2e-pw/src/oss/specs/smoke-tests/field-visibility.spec.ts
Empty groups should be hidden if field visibility applied
https://github.com/voxel51/fiftyone/assets/109545780/d002535b-c2ea-4f41-9198-5298d08dbf45
E2E for disabling (not too clear in video)
https://github.com/voxel51/fiftyone/assets/109545780/1821bc0b-bbf3-44ea-aaf1-f4e9378bbbf9
(Details)
-   [ ] Other
=> empty groups should be hidden if field visibility active + e2e

fiftyone/core/session/session.py, fiftyone/core/utils.py
Generalize _is_docker() to is_container(), in order for same behavior using docker and podman. 
The is_docker() method allowed a host to connect to Fiftyone running in a docker container without extra config. Using podman, extra config was needed.
Tested by running is_container() using podman, docker, and without container. The function returns true for both podman and docker, and false without running as container.
-   [x] …
=> Generalize _is_docker() to is_container()

app/packages/core/src/components/Actions/ActionsRow.tsx, app/packages/core/src/components/Actions/DynamicGroup.tsx, app/packages/core/src/components/Actions/GroupMediaVisibilityContainer.tsx, app/packages/core/src/components/Actions/Options.tsx, app/packages/core/src/components/Actions/Patcher.tsx, app/packages/core/src/components/Actions/Popout.tsx, app/packages/core/src/components/Actions/Selected.tsx, app/packages/core/src/components/Actions/Tagger.tsx, app/packages/core/src/components/Actions/similar/Similar.tsx
Adds the `useAlign` hook to `left` aligned popouts for the grid, and `right` aligned popouts for the modal.
Before:
After:
=> Fix modal popout widths

app/packages/components/src/components/Selector/Selector.tsx, app/packages/core/src/components/Actions/DynamicGroup.tsx, app/packages/core/src/components/Actions/DynamicGroupAction.tsx, app/packages/core/src/components/Modal/Group/DynamicGroup/NestedGroup/GroupElementsLinkBar.tsx, app/packages/relay/src/queries/__generated__/aggregationsQuery.graphql.ts, app/packages/state/src/recoil/aggregations.ts, app/schema.graphql, e2e-pw/src/oss/fixtures/loader.ts, e2e-pw/src/oss/poms/action-row/dynamic-group.ts, e2e-pw/src/oss/poms/action-row/grid-actions-row.ts, e2e-pw/src/oss/poms/grid/index.ts, e2e-pw/src/oss/poms/modal/dynamic-group-pagination-bar.ts, e2e-pw/src/oss/poms/modal/group-actions.ts, e2e-pw/src/oss/poms/modal/modal-sidebar.ts, e2e-pw/src/oss/poms/selector.ts, e2e-pw/src/oss/specs/groups/sparse-dynamic-groups.spec.ts, e2e-pw/src/oss/specs/plugins/histograms.spec.ts, e2e-pw/src/oss/specs/smoke-tests/quickstart.spec.ts, fiftyone/server/aggregations.py
Fixes dynamic groups in the context of a sparse group dataset. In the below example, the non-default `right` slice should have pagination for the `third` and `fourth` groups. Adds e2e and includes new `DynamicGroup` and `DynamicGroupPagination` poms.
```py
dataset = fo.Dataset("sparse-dynamic-groups")
first = fo.Group()
second = fo.Group()
third = fo.Group()
fourth = fo.Group()
one = fo.Sample(
filepath="one.png",
group=first.element("left"),
scene="a",
frame=0,
)
two = fo.Sample(
filepath="two.png",
group=second.element("left"),
scene="a",
frame=1,
)
three = fo.Sample(
filepath="three.png",
group=third.element("right"),
scene="b",
frame=0,
)
four = fo.Sample(
filepath="four.png",
group=fourth.element("right"),
scene="b",
frame=1,
) …
```
=> Fix dynamic grouping for disjoint group datasets

fiftyone/core/odm/database.py
mongo command `isMaster` has been depreciated since v4.2 in favor of `hello` so num_connections always =0 for mongo versions >4.2 (for reference: https://www.mongodb.com/docs/v4.2/reference/method/db.isMaster/)
Mongo feature compatibility version:
```
In [66]: _client.admin.get_collection('system.version').find_one({'_id':'featureCompatibilityVersion'}).get('version',None)
Out[66]: '6.0'
```
Without hello:
```
In [68]: len(
...:             list(
...:                 _client.admin.aggregate(
...:                     [
...:                         {"$currentOp": {"allUsers": True}},
...:                         {"$project": {"appName": True, "command": True}},
...:                         {
...:                             "$match": {
...:                                 "appName": …
```
=> Fix _delete_non_persistent_datasets_if_allowed connection check

requirements/test.txt
Update test requirements so that async unit tests will run. Currently any async unit tests are skipped in the test runner: 
```
tests/unittests/utils_tests.py::UIDTests::test_log_import
/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_content.py:204: DeprecationWarning: Use 'content=<...>' to upload raw bytes/text content.
warnings.warn(message, DeprecationWarning)
tests/unittests/plugins/secrets_tests.py::TestExecutionContext::test_resolve_secret_values
tests/unittests/secrets/provider_tests.py::TestEnvSecretProvider::test_get_existing_secret
tests/unittests/secrets/provider_tests.py::TestEnvSecretProvider::test_get_non_existing_secret
tests/unittests/secrets/provider_tests.py::TestEnvSecretProvider::test_get_multiple_secrets_all_existing …
```
=> Enable async unit tests

fiftyone/utils/sam.py
Before this, if there were empty prompt fields, either detection or keypoint, the following errors would be passed to the user:
```
Batch: 64f8fb2b89625d1f64eb5449 - 64f8fb2b89625d1f64eb5449                       
Error: cannot reshape tensor of 0 elements into shape [0, -1, 256, 256] because the unspecified dimension size -1 can be any value and is ambiguous
```
Now, this case is handled separately by checking for the length of the `Detections` or `Keypoints` contents, and when 0, returning empty torch tensors to the `InstanceSegmentationOutputParser`.
To test empty detection bounding box prompts:
```
dataset = foz.load_zoo_dataset("quickstart", max_samples=25)
view = dataset.take(10)
for sample in view.iter_samples(): …
```
=> Gracefully handle empty SAM prompts V2

fiftyone/operators/operator.py, fiftyone/operators/types.py
This fixes an issue where non-dynamic operators would show `Execute` instead of `Schedule` for delegated operators.
=> Fix delegated operators schedule button

docs/source/plugins/index.rst
Fix internal ref links for `fiftyone-plugins` that were broken due to the name/label conflict with the link to the github repo
=> [Docs] fix fiftyone-plugins links

fiftyone/core/collections.py, fiftyone/core/dataset.py, fiftyone/core/stages.py, fiftyone/core/view.py, tests/isolated/service_tests.py, tests/unittests/group_tests.py, tests/unittests/view_tests.py
Enhancements
- Adds support for compound group-by operations via `dataset.group_by(["field1", "field2"])`
- This was previously possible _only_ via a more verbose syntax `dataset.group_by(E([F("field1"), F("field2")]))`
- Adds a `create_index=False` option for `sort_by()` and `group_by()` in case users do *not* want to create indexes
Bug fixes
- Fixes a bug where default indexes for grouped datasets were not created via `dataset.clone()` and `dataset.merge_samples()`
=> Compound group-by and better index creation control

app/packages/core/src/plugins/SchemaIO/components/MarkdownView.tsx, app/packages/core/src/plugins/SchemaIO/components/SwitchView.tsx, app/packages/operators/src/OperatorPlacements.tsx
=> fix MarkdownView, SwitchView, and Placement

fiftyone/server/app.py
In starlette, the `debug` flag for an `App` is documented as:
```
Boolean indicating if debug tracebacks should be returned on errors.
```
which is always useful 🚀
=> Always log stack traces in server

e2e-pw/src/oss/specs/smoke-tests/field-visibility.spec.ts
fixes bad merge conflict resolution for field visibility e2es
(Details)
-   [ ] Other
=> bad merge conflicts

fiftyone/utils/coco.py
This fixes the issue when the segmentation list is empty - e.g. cases with annotation.json containing:
```json
{
"id":7,
"image_id":9,
"category_id":1,
"segmentation":[
[
]
],
"area":0,
"bbox":[
503.3053894042969,
3167.2109375,
49.400482177734375,
119.207763671875
],
"iscrowd":0,
},
```
Pre-fix the dataset loader errors with pycocotools not knowing how to handle this type of segmentation.
```
File "/home/bot/.local/lib/python3.10/site-packages/fiftyone/utils/coco.py", line 2149, in _coco_segmentation_to_mask
rle = mask_utils.merge(mask_utils.frPyObjects(segmentation, height, width))
File "pycocotools/_mask.pyx", line 308, in pycocotools._mask.frPyObjects
Exception: input type is not supported.
```
-   [ ] Yes. Give a description of this …
=> Fix issue with empty segmentations in coco

.github/workflows/e2e.yml, e2e-pw/src/oss/poms/field-visibility/field-visibility.ts, e2e-pw/src/oss/specs/display-options/display-options.spec.ts, e2e-pw/src/oss/specs/smoke-tests/embeddings.spec.ts, e2e-pw/src/oss/specs/smoke-tests/quickstart-groups.spec.ts, e2e-pw/src/oss/specs/smoke-tests/tagger.spec.ts
We have added a lot poms and specs recently 🚀 . Proposing we add a lint stage to `e2e` to catch changes to poms, etc. I find myself tweaking constructors and methods a lot, so I think it's good to have the automation catch these changes so specs don't fall behind
=> [Proposal] Add lint step to e2e

app/packages/looker/src/overlays/detection.ts
Closes #1750 
It is already the case that segmentation and heatmap overlays safely avoid processing image data without defined dimensions, but instance masks are missing this check.
Without this check, users have been encountering the this error when their browser is creating the mask `ImageData`
```
Uncaught DOMException: Failed to construct 'ImageData': The source width is zero or not a number
```
=> Only process instance masks with width and height

.github/workflows/build-db.yml, .github/workflows/build-desktop.yml, .github/workflows/build-docs.yml, .github/workflows/build-graphql.yml, .github/workflows/build.yml, .github/workflows/e2e.yml, .github/workflows/publish.yml, .github/workflows/test.yml
There are a lot of unnecessary warnings in the GitHub Actions logs related to actions that are out of date:
Bumping the actions versions to eliminate those.
=> update Actions versions to reduce error noise

e2e-pw/.env.dev.template
Updating the playwright `.env.dev.template` to us `FIFTYONE_ROOT_DIR`, which has replaced `PYTHONPATH`
=> Update Playwright .env.dev.template

fiftyone/utils/torch.py, tests/intensive/model_tests.py
New parameter `feature_extractor=False` added to torch models. 
If set to True, then the model output is treated as features without
forward hooks. 
When using `dino` model with default forward hooks, its output
becomes 3-demensional and can't be used as embeddings. With 
this fix the output is expected 2-dimensional. 
Also, if `embeddings_layer=xxxx` is provided, then the model
is replaced with a feature extractor for that layer using torchvision.
Finally, added a check on `embeddings_layer` making sure it's
not an `Identity()` layer is it does not return anything with 
forward hooks.
Added a test with `dino` model from torch hub. …
=> treat torch models as feature extractors when feature_extractor=True

docs/source/user_guide/plots.rst, fiftyone/core/plots/plotly.py, requirements/common.txt, setup.py
* Closes https://github.com/voxel51/fiftyone/issues/2319
* Closes https://github.com/voxel51/fiftyone/issues/2950
* Closes https://github.com/voxel51/fiftyone/issues/3146
* Closes https://github.com/voxel51/fiftyone/issues/3408
Withe the latest jupyter or jupyterlab (see versions below) I am unable to reproduce reported issues with plotly and notebook sessions. Recommending we update the `ipywidgets` requirement to `>=8,<9` although 9 has not been released, it is anticipatory.
Tested with the below dependencies
```
ipywidgets                    8.1.1
jupyter                       1.0.0
jupyter_client                7.4.9
jupyter-console               6.6.3
jupyter_core                  5.3.1
jupyter-events                0.7.0
jupyter-lsp                   2.2.0
jupyter_server …
```
=> Plotting dependencies update

fiftyone/utils/coco.py
There are two types of invalid polygons - empty polygons and ones covering a single pixel, which can be made full by completing them. This allows for other corner cases to be later added.
After the patch, polygons with 4 values are correctly accepted.
Previously:
```bash
File "/home/bot/.local/lib/python3.10/site-packages/fiftyone/utils/coco.py", line 1088, in to_detection
mask = _coco_segmentation_to_mask(self.segmentation, self.bbox, frame_size)
File "/home/bot/.local/lib/python3.10/site-packages/fiftyone/utils/coco.py", line 2156, in _coco_segmentation_to_mask
rle = mask_utils.merge(mask_utils.frPyObjects(segmentation, height, width))
File "pycocotools/_mask.pyx", line 294, in pycocotools._mask.frPyObjects
TypeError: Argument 'bb' has incorrect type (expected numpy.ndarray, got list) …
```
=> Fix coco polygon with 4 points

app/packages/looker/src/elements/common/tags.test.ts, app/packages/looker/src/elements/common/tags.ts
- Primitives under a list of dynamic documents were not rendering because we are filtering everything out.
After fix
https://github.com/voxel51/fiftyone/assets/109545780/4dadeb0e-e8f3-4c75-88ae-28861f4ccafc
After fix with list of primitives
Uploading Screen Recording 2023-09-26 at 10.56.15 AM.mov…
With unit test
https://github.com/voxel51/fiftyone/assets/109545780/c16e7a37-1c48-45b5-8317-0a83ecd3d5d5
(Details)
-   [ ] Core: …
=> Visualize primitives nested under list of EmbeddedDocuments

fiftyone/core/frame.py
By convention, FO exposes all dunder methods like `del sample.frames[1]` as a public method like `sample.frames.delete_frame(1)`. The latter was missing so I added it.
=> Adding a delete_frame() method

app/packages/components/src/components/PillButton/PillButton.tsx, app/packages/components/src/components/Selection/Option.tsx, app/packages/core/src/components/Actions/ActionsRow.tsx, app/packages/core/src/components/Actions/similar/Similar.tsx, app/packages/core/src/components/ColorModal/ColorFooter.tsx, app/packages/core/src/components/ColorModal/ShareStyledDiv.ts, app/packages/core/src/components/Common/Input.tsx, app/packages/core/src/components/Sidebar/Entries/Draggable.tsx, app/packages/core/src/components/Sidebar/ViewSelection/index.tsx
Previously, when viewing the app in the read-only mode, action buttons and triggers would be hidden which caused some confusion to users. However, with the changes in this PR, buttons and triggers will be always displayed and will be disabled with an explanation in a tooltip.
Flows affected:
- Creating a saved view
- Editing a saved view
- Saving colour configuration as default
- Clearing saved colour settings
- Tagging
- Storing similarity distance in a field
- Dragging sidebar item
(Details)
-   [ ] App: FiftyOne …
=> improve read-only mode

app/packages/core/src/plugins/SchemaIO/components/FileExplorerView/FileExplorer.tsx, app/packages/core/src/plugins/SchemaIO/components/FileExplorerView/FileExplorerView.tsx
When using the `FileExplorerView` with read_only flag, display value for the property as an read-only ObjectView as shown below:
(Details)
-   [ ] Other
=> add support for read-only mode in FileExplorerView

app/packages/core/src/plugins/SchemaIO/components/FileExplorerView/FileExplorerView.tsx
Render read-only FileExplorerView style input Instead of rendering as a read-only ObjectView:
(Details)
-   [ ] Other
=> FileExplorerView read-only mode tweak

fiftyone/core/view.py
=> Lint parent media type

.github/workflows/test.yml
The Python `test` workflow has been updated on `develop` to increase the runner to `ubuntu-latest-m`, but PRs into `release/v0.22.1` are still facing "out of space" issues on the actions, e.g. https://github.com/voxel51/fiftyone/pull/3606
=> Fix release PRs

app/packages/looker-3d/src/Looker3d.tsx, app/packages/looker/src/overlays/base.ts, app/packages/looker/src/worker/painter.ts
Right now, color by value (index) is actually using id to get colors. 
Fix: Use label.index if there is a value in index field, otherwise use id. 
https://github.com/voxel51/fiftyone/assets/17770824/cd33a365-4c84-48de-af08-864b1124a095
-   [ ] Other
=> Bugfix: color by value (index) on video

app/packages/components/src/components/Popout/index.tsx, app/packages/components/src/components/index.ts, app/packages/core/src/components/ColorModal/FieldSetting.tsx, app/packages/core/src/components/ColorModal/GlobalSetting.tsx, app/packages/core/src/components/ColorModal/controls/ModeControl.tsx, app/packages/core/src/components/Common/RadioGroup.tsx, app/packages/core/src/components/FieldLabelAndInfo/index.tsx, app/packages/looker-3d/src/Looker3d.tsx, app/packages/looker/src/elements/common/tags.ts, app/packages/looker/src/elements/common/util.ts, app/packages/looker/src/overlays/base.ts, app/packages/looker/src/overlays/classifications.ts, app/packages/looker/src/overlays/util.ts, app/packages/looker/src/state.ts, app/packages/looker/src/worker/painter.ts
1. Add color by instance option back in the UI.
2. Fix a bug related to color by value (index). When there is an index value, use the index value, otherwise use id, to get the color value. 
Testing
Segmentation example:
https://github.com/voxel51/fiftyone/assets/17770824/5766f1cd-e532-48a0-9bbb-ffcd007cb0b5
-   [ ] Documentation: …
=> Color by instance

fiftyone/core/cli.py
Updating the `fiftyone delegated launch` command to only run one operation at a time.
This is functionality equivalent to the previous implementation (with a small delay between consecutive jobs) but is more parallel-friendly. Previously if a new service were launched while the first service was halfway through a batch of queued runs, the new service would start executing the same jobs and the original service would not realize that they are no longer in queued and re-execute them.
=> Only run one delegated operation at a time

app/packages/operators/src/constants.ts, app/packages/operators/src/state.ts
Use debounce instead of throttle for resolving operator type in prompt and placement
(Details)
-   [ ] Other
=> use debounce in operator prompt

.github/workflows/e2e.yml, app/packages/state/src/recoil/utils.test.ts, app/packages/state/src/recoil/utils.ts, app/packages/utilities/src/fetch.ts, docs/source/user_guide/plots.rst, fiftyone/core/plots/plotly.py
Fixes databricks notebook URLs. An effort was made to add support for interactive notebooks,  but it seems plotly support is also limited like in Google's Colab. Interactive `ipywidgets` with callbacks do not seem to be supported, and the officially recommend using plotly [offline](https://docs.databricks.com/en/visualizations/plotly.html)
=> Databricks update

fiftyone/plugins/core.py, fiftyone/plugins/utils.py, fiftyone/utils/github.py, setup.py
Adds a `fiftyone.plugins.utils` module with a few helpful utilities for parsing plugin info from GitHub repositories. All are used by https://github.com/voxel51/fiftyone-plugins/pull/66.
=> Plugin utils

MANIFEST.in, pyproject.toml
Due to [PEP 517](https://peps.python.org/pep-0517/), installing `fiftyone` from source occurs in an isolated build environment. For Python 3.7, this requires the `importlib-metadata` package. This build requirement has been added to the `pyproject.toml` per [PEP 518](https://peps.python.org/pep-0518/).
I've also updated the `MANIFEST.in` because unwanted directories are currently included in a build (`e2e`, etc.). More could be done here, but this update removes most of the unnecessary files
=> Add build system to pyproject.toml

fiftyone/core/stages.py
This PR fixes #3421.
The previous pipeline (somewhat inexplicably) outputs an unstable ordering of documents. While the `group` stage doesn't guarantee a stable sort, the absence of the `lookup` stage, which adds the sorted `frames` object from the frames collection, results in a stable order of documents. This might be due to the presence of a nested field object, such as `frames`, outputted by the `lookup` stage, which could be affecting how the `group` stage operates.
```
[
{
$lookup: {
from: "frames.samples.6421c8af194325086c697069",
let: {
sample_id: "$_id",
},
pipeline: [
{
$match: {
$expr: {
$eq: ["$$sample_id", "$_sample_id"],
},
},
},
{
$sort: {
frame_number: 1,
},
},
],
as: "frames",
},
},
{
$sort: {
"metadata.duration": 1,
"metadata.size_bytes": 1,
},
},
{
$group: {
_id: …
```
=> fix groups aggregation problem resulting in unstable ordering of documents

app/packages/plugins/src/index.ts
Fixes warning below:
```
Warning: Do not call Hooks inside useEffect(...), useMemo(...), or other built-in Hooks. You can only call Hooks at the top level of your React function
```
Removing of useMemo should not impact performance as it was mostly redundant due to always getting called.
(Details)
-   [ ] Other
=> fix react hooks warning for spaces

.github/workflows/e2e.yml, e2e-pw/src/oss/poms/sidebar.ts, e2e-pw/src/oss/specs/sidebar/sidebar-cifar.spec.ts
Improve the test stability of sidebar-cifar when selecting multiple checkboxes. 
(Details)
-   [ ] Other
=> improve e2e test stability (cifar sidebar)

fiftyone/core/dataset.py
While working on related sidebar/index features, I'm noticing that `Group` fields create an index on an `id` field, as opposed to `_id`. Looking at MongoDB compass (see recording) this results in collection scans when matching on a `group._id` value in `quickstart-groups`.
A migration should probably be added if this a change want. I can add after confirming that this is a bug
https://github.com/voxel51/fiftyone/assets/19821840/b6d3ddd0-f094-42c5-b538-61f88e9a475c
=> Fix group.id index

app/packages/app/src/Renderer.tsx, app/packages/app/src/pages/datasets/DatasetPage.tsx, app/packages/app/src/useSetters/onSetView.ts, app/packages/app/src/useSetters/registerSetter.ts, app/packages/app/src/useSetters/useSetters.ts, app/packages/core/src/components/ViewBar/ViewBar.tsx, app/packages/core/src/components/index.ts, app/packages/state/src/recoil/atoms.ts, fiftyone/core/stages.py
Adds a Snackbar alert when onSetView fails.
Before change
https://github.com/voxel51/fiftyone/assets/109545780/ad4ce15e-a5bb-466a-ab9d-b16a6407c1ea
After change
https://github.com/voxel51/fiftyone/assets/109545780/369e115d-e6f7-4f2e-aec6-7f9b0e83245b
@benjaminpkane @imanjra and anyone else, can you advise on the followings please,
- Is there a better way? I had to bypass ErrorBoundary because it was refreshing the page and getting tricky to show Alert and Children in ErrorBoundary without this refresh.
- How do I stop the loading state when onSetView --> onComplete returns data.errors? The top loader stays visible and the event call never gets cancelled. I tried setting AppState to Close in useEventSource.ts but no success.
(Details)
- …
=> Adds a Snackbar alert when onSetView fails.

app/packages/app/src/Sync.tsx, app/packages/app/src/useEvents/useSetColorScheme.ts, app/packages/app/src/useEvents/utils.ts, app/packages/state/src/recoil/color.ts
- move `ensureColorScheme` to `fiftyone/state`
- fix minor bugs related to colorBy global changes
(Details)
-   [ ] Other
=> Move ensureColorScheme to state and fix minor color related bugs

docs/source/user_guide/export_datasets.rst, fiftyone/utils/coco.py, fiftyone/utils/data/exporters.py, fiftyone/utils/patches.py, tests/unittests/import_export_tests.py
This syntax for exporting object patches was previously not possible, but should have been:
```py
patches = dataset.to_patches("ground_truth")
patches.export(
export_dir="/tmp/patches",
dataset_type=fo.types.ImageDirectory,
)
```
=> Adding support for directly exporting object patches

app/packages/operators/src/OperatorIcon.tsx
Use the `Fallback` icon when the operator is not executable to prevent missing plugin exceptions. The Lock icon for non-executable will be displayed instead
By disabling a plugin with an operator that has custom icon
-   [ ] Other
=> use fallback icon when operator is non-executable

app/packages/core/src/components/Actions/ActionsRow.tsx, app/packages/core/src/components/Grid/Grid.tsx
Fix error when pressing Esc button while in grid view with and without anything selected 
- reset to new set not array
- check selected.size exists 
run locally. no error when press escape
-   [ ] Other
=> Fix error with Esc key

requirements/common.txt
Dependabot complains about Flask but I don't think we even use it anywhere, so maybe we can just get rid of it. It's not included in the fiftyone package, only when built from source. Dep line last touched 3 yrs ago. @benjaminpkane confirm?
https://github.com/voxel51/fiftyone/security/dependabot/69
=> remove unneeded Flask dep

docs/source/cli/index.rst, docs/source/user_guide/config.rst, fiftyone/core/cli.py, fiftyone/core/collections.py, fiftyone/core/config.py, fiftyone/core/metadata.py, fiftyone/core/storage.py, fiftyone/core/utils.py, fiftyone/plugins/utils.py, fiftyone/utils/activitynet.py, fiftyone/utils/aws.py, fiftyone/utils/beam.py, fiftyone/utils/coco.py, fiftyone/utils/cvat.py, fiftyone/utils/data/base.py, fiftyone/utils/image.py, fiftyone/utils/kinetics.py, fiftyone/utils/kitti.py, fiftyone/utils/openimages.py, fiftyone/utils/sama.py, fiftyone/utils/youtube.py, fiftyone/zoo/datasets/base.py
- Adds new `fou.recommend_process_pool_workers()` and `fou.recommend_thread_pool_workers()` methods that standardize the processing of all `num_workers` arguments throughout the codebase
- Adds a new `fo.config.max_process_pool_workers` config setting to match `fo.config.max_thread_pool_workers` and wires up both of these settings to the aforementioned two methods so that users have a single place to limit the number of threads/processes used by FO
```py
fo.config.max_process_pool_workers = 1
dataset.compute_metadata(overwrite=True)
```
=> Standardizing handling of thread/process pool sizes

fiftyone/core/singletons.py, tests/unittests/synchronization_tests.py
Dataset singletons are currently keyed by name. The consequence of this is that when a dataset is deleted and recreated in one process, any other processes will raise a dataset is deleted exception if the original dataset singleton is still in memory. This causes the App server to remain in a persisted error state if the session is attached to the original (now deleted) dataset.
This is a sensitive change, but references to dataset singleton instances seem minimal, and keying by an immutable value seems more robust.
The below now works with this change.
```py
dataset.delete()
```
Screenshot of existing error
=> Fix dataset deletion/recreation across processes

fiftyone/core/context.py
This change ensures colab notebooks provide a functional URL when accessing the `session.url` property by including the required `polling` search param, i.e. `https://LONG_ID-5151-colab.googleusercontent.com/?polling=true`
=> Add polling to Colab session URL

app/packages/operators/src/types.ts, app/packages/operators/src/validation.ts, fiftyone/operators/executor.py, fiftyone/operators/types.py
When using the `String` for a field, the empty value `""` will now be considered invalid by default.
You may opt-out of this default behaviour by setting the `allow_empty` option to `True`:
```py
def resolve_input(self, ctx):
inputs = types.Object()
inputs.str("my_str", allow_empty=True, required=True)
inputs.define_property("my_str", types.String(allow_empty=True), required=True)
return types.Property(inputs)
```
Using a test operator in the app
-   [] No. You can skip the rest of this section.
See above …
=> primitive types validation enhancements

app/packages/operators/src/OperatorPlacements.tsx
Fix placement icon showing fallback icon even when the custom icon is provided. Regressed in #3661
In the App with an operator containing a placement with icon provided
-   [ ] Other
=> fix placement icon showing fallback icon

app/packages/operators/src/built-in-operators.ts, app/packages/operators/src/operators.ts, app/packages/operators/src/state.ts, app/packages/plugins/src/index.ts, fiftyone/operators/permissions.py, fiftyone/operators/server.py
When resolving list of operators, include the dataset name in body
Using operators browser in the app
-   [ ] Other
=> include dataset name when resolving operators list

app/packages/core/src/plugins/SchemaIO/components/FileView.tsx, fiftyone/operators/types.py
Cleanup the `UploadedFile` to now only included the base64 data and not the type prefix (if it exists).
=> strip b64 prefix from uploaded files

app/packages/operators/src/validation.ts, fiftyone/operators/executor.py
Fix non-required property validated as required. Regressed in https://github.com/voxel51/fiftyone/pull/3685
Tested using an operator with non-required primitive types
-   [ ] Other
=> fix require validation false positive

fiftyone/operators/decorators.py, tests/unittests/operators/decorators_tests.py
* check top level dir and add test
* cleanup
* remove glob and refactor tests
* cleanup
* add test for renaming and add wait
* add test for renaming and add sleep
(Details)
-   [ ] Other
=> [Cherrypick] Fix plugin cache check (#3676)

app/packages/core/src/plugins/OperatorIO/utils/index.ts, app/packages/operators/src/types.ts, fiftyone/operators/types.py
Tweak UploadedFile type to have a default view when no view is provided. 
Tested in the app with an example operator
Refer to https://github.com/voxel51/fiftyone/pull/3629
-   [ ] Other
=> default view and mappings for File and UploadedFile type

app/packages/app/src/Sync.tsx, app/packages/app/src/index.tsx
Changes from https://github.com/voxel51/fiftyone/pull/3706 seem to require that plugins are loaded after the page query and session info are ready.
This change ensures plugins are loaded after the App is initialized
=> Fix App on develop

requirements/docs.txt
Bumps the Sphinx docs requirement to 3.5.4. #2742 broke sphinx builds using 2.4.4 (only in Python 3.9)
=> Bump sphinx to 3.5.4

app/packages/app/src/pages/datasets/DatasetPage.tsx, app/packages/app/src/pages/datasets/__generated__/DatasetPageQuery.graphql.ts, app/packages/core/src/components/Actions/similar/GroupButton.tsx, app/packages/core/src/components/Actions/similar/Similar.tsx, app/packages/core/src/components/Actions/similar/utils.ts, app/packages/relay/src/fragments/__generated__/datasetFragment.graphql.ts, app/packages/relay/src/fragments/datasetFragment.ts, app/packages/relay/src/queries/__generated__/datasetQuery.graphql.ts, app/packages/state/src/recoil/selectors.ts, app/packages/state/src/recoil/types.ts, app/packages/state/src/recoil/utils.ts, app/schema.graphql, fiftyone/server/query.py
Fixed the regression that last used brain key was not loaded by default.
Updated the unique identifier of dataset when we store the key in local storage
https://github.com/voxel51/fiftyone/assets/17770824/339f86af-4135-4f3c-b432-a07f97bebb37
-   [ ] Other
=> bugfix: last used brain key should be loaded by default in similarity sort

app/packages/core/src/components/Actions/ActionsRow.tsx, app/packages/core/src/components/Grid/Grid.tsx, app/packages/core/src/components/Modal/ModalNavigation.tsx, app/packages/flashlight/src/index.ts, app/packages/flashlight/src/section.ts, app/packages/flashlight/src/state.ts, app/packages/looker/src/elements/common/actions.ts, app/packages/state/src/hooks/useExpandSample.ts, app/packages/state/src/recoil/atoms.ts
Shortcuts for selecting and deselecting samples quicker
https://github.com/voxel51/fiftyone/assets/109545780/3fbf35fe-4d6a-47b3-8d64-d37f0653c97f
(Details)
-   [ ] Other
=> sample (de)select keyboard shortcut for modal and Grid

fiftyone/utils/data/exporters.py
Reload dataset document before exporting metadata.json in case it has been updated by another process.
Samples are exported straight from database backing so we must reload dataset doc otherwise metadata.json may not match samples.json.
Note there could still be a race condition between 2 processes but the window for that is quite small.
Scripts below written by a reporting user. Thanks.
Run first script then run second script. Make sure `field` shows up in metadata.json as well as samples.json
```python
import time
DATASET_NAME = "quickstart"
EXPORT_PATH = "export-test"
dataset: fo.Dataset = fo.zoo.load_zoo_dataset(DATASET_NAME)
export_dir=EXPORT_PATH,
dataset_type=fo.types.FiftyOneDataset,
export_media=False,
)
print("SLEEPING, RUN …
```
=> Bugfix: out of sync metadata.json on export

app/packages/operators/src/OperatorInvocationRequestExecutor.tsx, app/packages/operators/src/built-in-operators.ts
Fixes race condition where startup operator executing flow is triggered before loading operators from server and preventing them from executing on launch
Using an example operator with `on_startup` set to `True`
```
- Fixed on startup operators not getting executed `#3731 <https://github.com/voxel51/fiftyone/pull/3731>`_
```
-   [ ] Other
=> fix on_startup operators not executed

fiftyone/core/stages.py, fiftyone/server/routes/embeddings.py
Avoids unnecessary duplicate calls to `SimilarityIndex.use_view(view)` in situations where the index was created for `dataset` and the `view` being passed is the trivial view: `view = dataset.view()`.
This is a worthy optimization for large datasets because `use_view(view)` requires calling `view.values("id")` to retrieve the IDs from the view.
For example, previously `dataset.sort_by_similarity(...)` would unnecessarily call `SimilarityIndex.use_view(...)` when creating its `SortBySimilarity` stage, since the view stage is technically appended to `dataset.view()`, not directly to `dataset`.
Using `a.view() != b.view()` instead of `a != b` allows `dataset` to be "equal" to `dataset.view()`, which *is* an equality we want in this case because `dataset.view()` is guaranteed to contain every …
=> Optimize use_view() usage

app/packages/state/src/recoil/schema.ts
Fixes active (checked) fields in the sidebar on view change and persists the value to session storage
https://github.com/voxel51/fiftyone/assets/19821840/d4c46813-b19e-4038-b93f-62fc9e5f6a9b
=> Fix active field on view change

.github/workflows/pr.yml, app/packages/core/src/components/Grid/Grid.tsx
Fixes a grid selection bug introduced by me in #3718. Also adds back `e2e` as a required check in pull requests to help prevent these regressions
=> Fix grid selection and e2e

app/packages/operators/src/OperatorCore.tsx, app/packages/operators/src/hooks.ts, app/packages/operators/src/state.ts
- Fix disappearance and re-appearance of placements when placements are re-resolved on context changes
- Fix multiple duplicate calls to resolve placements on the initial app load
Interactively within the app using an example operator and with network profiling
```
- Fixed disappearance and re-appearance of placements when placements are re-resolved on context changes `#3742 <https://github.com/voxel51/fiftyone/pull/3742 >`_
- Fixed multiple duplicate calls to resolve placements on the initial app load `#3742 <https://github.com/voxel51/fiftyone/pull/3742 >`_
``` …
=> fix placements flash and remove duplicate resolve

app/packages/core/src/components/Actions/ActionsRow.tsx
Add the browse operations button to the sample modal
Interactively within the app
Preview:
```
- Add the browse operations button to the sample modal `#3746 <https://github.com/voxel51/fiftyone/pull/3746>`_
```
-   [ ] Other
=> [Proposal] add browse operations button to sample modal

app/packages/operators/src/state.ts
Fixes #3740 
Using a test operator with some labels selected in looker 
```
- Fixed selectedLabels is missing in operator context when resolve type is invoked`#3745 <https://github.com/voxel51/fiftyone/pull/3745>`_
```
-   [ ] Other
=> add back the selected labels to operator context

app/packages/core/src/components/Sidebar/Sidebar.tsx
fixed sidebar group re-arranging issue where sample tags jumps to the moving group when the moving group is taken above tags group
By attempting to drag any of the group in sidebar above the sticky tags group
```
- Fixed sample tags jumping to sidebar group being re-arranged issue `#3753 <https://github.com/voxel51/fiftyone/pull/3753>`_
```
-   [ ] Other
=> fix sidebar re-arranging bug

e2e-pw/src/oss/specs/groups/sparse-groups-scenes.spec.ts
Fix for unstable e2e test (example [action](https://github.com/voxel51/fiftyone/actions/runs/6721054954/job/18265921208))
=> Ensure main looker is clicked in e2e test

fiftyone/operators/executor.py
Secrets should be available via `ctx.secrets` when `resolve_input` is called.
=> Plugin secrets available in resolve_input

fiftyone/core/collections.py, tests/unittests/view_tests.py
Alternative solution to https://github.com/voxel51/fiftyone/pull/3734 that should fix the App issue targeted there while also having the benefit of ensuring that 3D fields are not excluded by things like `select_fields("ground_truth.detections.label")`, which should never exclude fields that are required to visualize 3D data.
=> Ensure that 3D detection fields are treated as default by SelectFields

docs/source/cli/index.rst, fiftyone/core/cli.py, fiftyone/operators/decorators.py, fiftyone/plugins/core.py, tests/unittests/operators/decorators_tests.py
- update `@plugin_cache` so that it always changes whenever any addition/edit/removal of plugins occurs (including `touch PLUGINS_DIR`)
- remove `max_depth` flag from `download_plugin()`, for consistency with how `list_plugins()` searches infinitely deep, if necessary, to find plugins
=> Remove max_depth constraint from plugin listing/caching

app/packages/app/src/pages/IndexPage.tsx, app/packages/app/src/pages/datasets/DatasetPage.tsx, app/packages/core/src/components/Snackbar.tsx, app/packages/core/src/components/index.ts
Moves the new Snackbar component from #3613 to `@fiftyone/core` for reusability and adds the component to the `IndexPage`
https://github.com/voxel51/fiftyone/assets/19821840/ae6b8605-155f-4f49-937c-5bb6a33405ab
=> Move Snackbar to @fiftyone/core

docs/source/integrations/labelbox.rst, fiftyone/utils/labelbox.py
The Labelbox integration was updated some time ago to migrate from their dataset to queue mode for creating projects. This PR updates the cleanup method and deletion of Labelbox projects to not only delete the project itself, but also the associated data rows and ontologies created by FiftyOne. 
The API method to delete the project makes the deletion of data row batches and ontologies configurable kwargs, but the cleanup method will automatically delete batches and ontologies as the purpose of it is to automatically clean up fiftyone-generated artifacts.
=> Update Labelbox cleanup to support batch mode

app/packages/app/src/Sync.tsx, app/packages/app/src/routing/RouterContext.ts, app/packages/app/src/useEventSource.ts, app/packages/app/src/useEvents/index.ts, app/packages/app/src/useEvents/registerEvent.ts, app/packages/app/src/useEvents/useEvents.ts, app/packages/app/src/useEvents/useSetGroupSlice.ts, app/packages/app/src/useEvents/useStateUpdate.ts, app/packages/app/src/useEvents/utils.ts, app/packages/app/src/useWriters/useWriters.ts, app/packages/state/src/session.ts, e2e-pw/src/oss/specs/regression-tests/group-video/default-video-slice-group.spec.ts, fiftyone/core/session/session.py, fiftyone/core/state.py, fiftyone/server/events.py, fiftyone/server/mutation.py
* Fixes the `useSetGroupSlice` subscription event in `@fiftyone/app/useEvents`
* Fixes `groupSlice` persistence in multi-tab contexts and across page reloads/refreshes
The underlying goal of this change is to keep the group slice setting across page loads even when a view without a `group` media type is present
https://github.com/voxel51/fiftyone/assets/19821840/3c3c670b-bf3f-4cc1-8b16-022441c4b547
https://github.com/voxel51/fiftyone/assets/19821840/b695e480-b3db-4c6c-8220-1922b6be0bd9
=> Better App group slice persistence

docs/source/cli/index.rst, fiftyone/core/cli.py, fiftyone/core/session/session.py
Fiftyone works best in Chrome, while users might prefer other browsers for surfing the internet.
Add a `--browser <browser_name>` parameter to `fiftyone app launch` to use a non-default browser to open the App.
Running these commands:
```
fiftyone app launch -b chrome
fiftyone app launch --browser safari
fiftyone app launch --browser oper  # fails (no browser registered with this name)
fiftyone app launch --browser opera  # fails (non-executable found)
```
Launch the app in the non-default browser. 
-   [x] Core: Core `fiftyone` Python library …
=> Use non-default browser to launch the app

docs/source/teams/cloud_media.rst
Adds documentation for the new support for S3 media in our FiftyOne Teams Labelbox integration.
=> Add documentation for Labelbox S3 support

docs/source/integrations/labelbox.rst, fiftyone/utils/labelbox.py
In our Labelbox integration, each sample that is annotated is uploaded as a Labelbox data row with a global key that is equal to the FiftyOne sample id. However, these are globally unique, so if the same samples are being annotated twice, they cannot and should not be uploaded again.
This PR adds logic that checks if existing samples already exists in Labelbox by referencing existing global keys and avoids reuploading them if they are found.
=> Update Labelbox integration to handle existing data rows

fiftyone/core/collections.py, fiftyone/core/metadata.py
Optimizes `SampleCollection.compute_metadata()` in two ways:
1. Use thread pool instead of process pool when retrieving metadata
2. Use `set_values()` rather than `sample.save()` to save metadata to the DB
Benefits of 1
- Avoids unnecessary use of multiprocessing, which is not suitable for async environments (App server) and other situations (eg S3 Lambda) or on Windows in general
- This thread pool implementation has similar performance to the prior process pool implementation. I've tested both when the media are local and when the media are URLs that require HTTP requests
Benefits of 2
- Greatly improves performance in situations when DB connections have higher overhead, as requests are batched into single `values()` and  `set_values()` calls
=> Optimize metadata computation

fiftyone/operators/delegated.py, fiftyone/operators/executor.py
Fixes a bug where `foo.execute_operator()` would not exhaust generator operators. While fixing this, took the opportunity to remove code duplication, since the same logic was already in-place when executing delegated operations.
```py
import fiftyone.operators as foo
ctx = {
"dataset": dataset,
"params": {
"num_workers": 1,
"delegate": False,
}
}
foo.execute_operator("@voxel51/utils/compute_metadata", ctx)
```
=> Exhaust generator operators when executing directly

app/packages/core/src/plugins/SchemaIO/components/LazyFieldView.tsx, app/packages/core/src/plugins/SchemaIO/components/index.ts, app/packages/operators/src/types.ts, fiftyone/operators/types.py
Add a new LazyFieldView to OperatorIO which only applies changes in the input field when a save button within an input field is clicked or optionally (enabled by default) when you blur the input field. When a field is unsaved, reset button (to go back to the previously applied or initial state) and save button (to apply changes) will appear
Preview (unsaved state of a LazyFieldView):
Usage:
```
def resolve_input(self, ctx):
inputs = types.Object()
inputs.str("url", view=types.LazyFieldView(save_on_blur=False))
return types.Property(inputs)
```
Using a test operator in the app
```
- Added a new :class:`LazyFieldView …
```
=> add LazyFieldView to OperatorIO

app/packages/core/src/plugins/SchemaIO/components/Header.tsx, app/packages/operators/src/OperatorPrompt.tsx, app/packages/operators/src/utils.ts
Fixes an issue where validation errors are hidden in some operator views 
See above
-   [ ] Other
=> fix hidden validation error bug

app/packages/core/src/plugins/SchemaIO/components/DynamicIO.tsx, app/packages/operators/src/validation.ts, app/packages/utilities/src/type-check.ts
Fixes an issue where default value of a param is re-applied in some cases for OperatorIO
See above
-   [ ] Other
=> prevent re-applying default in OperatorIO

app/packages/operators/src/OperatorPalette.tsx, app/packages/operators/src/constants.ts, app/packages/operators/src/state.ts
Fixes a bug where typing a `Backtick` into an input or other operator field closes the operator palette. Before this change, pressing `Backtick` was supported for both opening and closing an operator browser and palette. With this change, `Backtick` will no longer support closing the palette. Instead, the `Escape` key should be used to close an OperatorPalette
Using a test operator with input filed such as MarkdownView
See above
-   [ ] …
=> prevent backtick key from closing operator palette

app/packages/operators/src/OperatorCore.tsx, app/packages/operators/src/hooks.ts, app/packages/operators/src/loader.tsx, app/packages/operators/src/state.ts, app/packages/plugins/src/index.ts, app/packages/plugins/src/state.ts
Sync loading of placements with native actions
PR depends on #3766
Interactively in the app by making sure app load waits for placement by introduce a loading delay temporarily 
-   [ ] Other
=> sync placement loading with native actions

app/packages/app/src/pages/IndexPage.tsx, app/packages/app/src/pages/__generated__/IndexPageQuery.graphql.ts, app/packages/app/src/pages/datasets/DatasetPage.tsx, app/packages/components/src/components/CodeBlock/index.tsx, app/packages/components/src/components/CodeTabs/index.tsx, app/packages/components/src/components/Loading/Loading.tsx, app/packages/components/src/components/index.ts, app/packages/core/src/components/Starter/content.ts, app/packages/core/src/components/Starter/index.tsx, app/packages/core/src/components/index.ts, app/packages/operators/src/OperatorCore.tsx, app/packages/operators/src/built-in-operators.ts, app/packages/operators/src/hooks.ts, app/packages/operators/src/index.ts, app/packages/operators/src/loader.tsx, app/packages/operators/src/state.ts, app/packages/plugins/src/index.ts, app/packages/plugins/src/state.ts
See preview above
See above
-   [ ] Other
=> new empty pages

fiftyone/internal/secrets/providers/iprovider.py, fiftyone/internal/secrets/providers/local.py, fiftyone/operators/executor.py, fiftyone/operators/server.py, fiftyone/operators/types.py, fiftyone/plugins/secrets.py, tests/unittests/plugins/secrets_tests.py, tests/unittests/secrets/provider_tests.py
- Currently, secrets are only resolved in the ExecutionContext via the `prepare_operator_executor()` method. This limits secret resolution to the execution phase when running an operator. 
- Adding sync methods for querying secrets enables on demand access to secrets anywhere in user defined code/plugin operator code via `ctx.secret(<KEY>)`
- added custom dictionary class `SecretsDictionary` for `ctx.secrets`:
-  enables `ctx.secrets[<key>]` to also resolve plugin secrets automatically
- adds some security by disabling copying or printing all values via .items() or .values()
- **Note**: `ctx.secret(<KEY>)` will only resolve a secret if the `KEY` is included in the secrets section of the plugin's `fiftyone.yml`. Will return None even if the value is set, but the key is not listed in the …
=> Synchronously resolve secrets via ctx.secret

fiftyone/utils/coco.py
Following up on [this thread](https://github.com/voxel51/fiftyone/issues/1581#issuecomment-1638313430), this PR adds support for parsing the keypoint visibility information:
```
v=0: not labeled / not in the image
v=1: labeled but not visible, and
v=2: labeled and visible.
```
When working with the COCO format. Specifically, the visibility from the COCO labels is parsed into a `field_name.keypoints.visible` attribute which is a list of integers for the visibility of each point corresponding to the points in the `field_name.keypoints.points` list. 
When exporting, if that attribute exists, then that visibility will be used for each keypoint in the resulting COCO labels, otherwise it falls back to the current approach where all `nan` points are visibility `0` and all others are visibility …
=> Add support for parsing and exporting COCO keypoint visibility

app/packages/operators/src/hooks.ts
Follow up to #3792. A small detail specifically for group datasets is that the recoil value may suspend for a PCD slice, as the value depends on a server query. Revealed by and fixes e2e
=> Use loadable for ctx.current_sample

app/packages/operators/src/built-in-operators.ts
Fixes built-in operators `set_selected_samples` and `show_samples`
Tested using an example operator which trigger both of these operators using ctx.trigger
-   [ ] Other
=> fix select/show samples built-in operator

fiftyone/core/dataset.py, tests/unittests/group_tests.py
Resolves https://github.com/voxel51/fiftyone/issues/3763
Fixes a bug with:
```py
dataset.merge_samples(samples, key_field=key_field, ...)
```
when `dataset` is a grouped dataset, `samples` is a list of samples, and a `key_field` is provided.
=> Fixes #3763

app/packages/operators/src/built-in-operators.ts, fiftyone/operators/builtin.py
Simplifies the interface of the builtin `clone_selected_samples` and `delete_selected_samples` operators:
- Removes the `Show selected samples` buttons, which didn't look good layout-wise. Also this is already possible by clicking the bookmark icon in the actions row
- Cleans up the UI copy
- Optimizes the implementation of cloning samples
Also fixes the builtin `set_selected_samples` and `show_samples` thanks to @imanjra merging https://github.com/voxel51/fiftyone/pull/3818 into this PR 🎉
=> Removing buttons from builtin operators

fiftyone/core/metadata.py, tests/unittests/sample_tests.py
Introduce exif orientation support when importing images into a dataset - see https://github.com/voxel51/fiftyone/issues/3778
Tested on the code posted in the Issue linked above.
Before the fix image dimensions are flipped and annotation is displayed in the wrong position:
After the fix dimensions are correct and annotation is displayed in the correct position:
-   [ ] Other
=> Add PIL image rotation according to exif info (PR 3779 alt)

app/packages/core/src/plugins/SchemaIO/components/AutocompleteView.tsx, app/packages/core/src/plugins/SchemaIO/components/CheckboxView.tsx, app/packages/core/src/plugins/SchemaIO/components/CodeView.tsx, app/packages/core/src/plugins/SchemaIO/components/ColorView.tsx, app/packages/core/src/plugins/SchemaIO/components/DropdownView.tsx, app/packages/core/src/plugins/SchemaIO/components/DynamicIO.tsx, app/packages/core/src/plugins/SchemaIO/components/Header.tsx, app/packages/core/src/plugins/SchemaIO/components/ImageView.tsx, app/packages/core/src/plugins/SchemaIO/components/JSONView.tsx, app/packages/core/src/plugins/SchemaIO/components/ListView.tsx, app/packages/core/src/plugins/SchemaIO/components/MapView.tsx, app/packages/core/src/plugins/SchemaIO/components/MarkdownView.tsx, app/packages/core/src/plugins/SchemaIO/components/ObjectView.tsx, app/packages/core/src/plugins/SchemaIO/components/PlotlyView.tsx, app/packages/core/src/plugins/SchemaIO/components/PopoutButton.tsx, app/packages/core/src/plugins/SchemaIO/components/RadioView.tsx, app/packages/core/src/plugins/SchemaIO/components/SliderView.tsx, app/packages/core/src/plugins/SchemaIO/components/SwitchView.tsx, app/packages/core/src/plugins/SchemaIO/components/TextFieldView.tsx, app/packages/core/src/plugins/SchemaIO/components/TupleView.tsx, app/packages/core/src/plugins/SchemaIO/hooks/index.ts, app/packages/core/src/plugins/SchemaIO/hooks/useKey.tsx, app/packages/core/src/plugins/SchemaIO/index.tsx, app/packages/core/src/plugins/SchemaIO/utils/generate-schema.ts, app/packages/utilities/src/type-check.ts
- Support passing a default value of a descendent schema
- Re-render non-modified fields when the default value is updated
> Note: updated default will no longer be applied if a value was modified by a user in IO
Usage:
> Code snippet below takes advantage of inheritance of default value to dynamically set default value for a property in an object within a list. 
```py
current_people = ctx.params.get("people", None)
people_default = None
if current_people is not None:
people_default = []
for person in current_people:
name = person.get("name")
people_default.append(
{"title": f"Mr. {name if name else 'Anonymous'}!"}
)
people = types.Object()
people.str("name", label="Name")
people.str("title", label="Title")
inputs.list("people", people, default=people_default)
```
Using various example …
=> improve default value control for OperatorIO

app/packages/looker/src/worker/index.ts
segmentation masks in a dynamic embedded document is not renderable (I believe a recent regression).
The sources map where the mask's path is picked up is expecting a full path as a key. for example `embedded_document.segmentation` instead of `segmentation`. 
create a dataset with top level segmentation mask and a nested segmentation mask within an embedded doc.
```
dataset = foz.load_zoo_dataset("quickstart", dataset_name="seg-embed-3", max_samples=1)
dataset.persistent = True # optional
sample["top_level_mask"] = fo.Segmentation(mask_path="/tmp/mask.png")
sample["filepath_mask_embed"] = fo.DynamicEmbeddedDocument(seg=fo.Segmentation(mask_path="/tmp/mask.png"))
sample.save()
dataset.add_dynamic_sample_fields()
``` …
=> [Fix] fixes the segmentation source key in embedded document

package/desktop/setup.py, setup.py
Now that the `release` branches have been thrown, work for this branche should be towards the next minor release
=> bump `develop` version for next minor release

app/packages/core/src/plugins/SchemaIO/components/AutocompleteView.tsx, app/packages/core/src/plugins/SchemaIO/index.tsx
- Fixes an issue where OperatorIO crashes every now and then due to infinite re-render
- Fixes an issue where AutocompleteView is re-rendered even when modified by the user
Using some test operators
-   [ ] Other
=> fix OperatorIO crash and changed field re-render

app/packages/core/src/plugins/SchemaIO/index.tsx
Fixes an exception in SchemaIO when onChange is not provided. Regressed in https://github.com/voxel51/fiftyone/pull/3833
Using OperatorIO debugging panel
-   [ ] Other
=> fix SchemaIO exception when onChange is missing

app/packages/app/src/useSetters/onSetColorScheme.ts, app/packages/state/src/recoil/color.ts, fiftyone/server/color.py, package/desktop/setup.py, setup.py
Moves `removeRgbProperty` to `@fiftyone/state` for reuse, and ensures an color scheme `id` in the `setColorScheme` mutation
handle scenarios that `ensureColorscheme` takes `null` as the first argument.
=> Set color scheme tweaks

fiftyone/server/mutation.py
`group_slice` can only be set when the dataset is defined
=> Fix set session dataset to None

fiftyone/utils/cvat.py
Resolves #3815
keeping old behavior for cvat versions < 2.4.6 because of cvat bug fix https://github.com/opencv/cvat/pull/5083
Change-Id: I542695437c05c09bb48023d598af479965abb384
For cvat server versions >= 2.4.6
- remove the sequence prefix added to maintain the lexographical order of older cvat versions.
Verified on our local cvat instance before and after patch
Solves issue #3815 addressing filename prefixing of cvat samples.
-   [ ] …
=> fix: #3815 remove cvat filename prefixing

app/packages/core/src/components/Actions/utils.tsx, app/packages/looker/src/elements/common/controls.ts, app/packages/state/src/hooks/useSetExpandedSample.ts, app/packages/state/src/recoil/modal.ts, fiftyone/core/stages.py, fiftyone/core/view.py, fiftyone/server/view.py, tests/unittests/view_tests.py
The Select samples stage is running before selectGroupSlices and causing the sample modal to crash (not open).
Make sure selectGroupSlices stage is computed before Select samples stage when making optimized view function is called.
https://github.com/voxel51/fiftyone/assets/109545780/5e8f12d0-985e-47a4-bf79-19599883a7e8
https://github.com/voxel51/fiftyone/assets/109545780/586f6c23-b25d-418c-b767-3b70b01915c2
- unit test making sure select group slices is computed before Select stage
- test script 
```
view = dataset.select_group_slices(["left", "right"])
```
- Try clicking on the second sample (right slice) and it should open modal
- Try tagging the second …
=> selectGroupSlices stage should 🏃 before Select samples stage

app/packages/operators/src/operators.ts
Fix an issue where generator operator is executed immediately even when requested to be scheduled
Using a generator operator with option to delegate
-   [ ] Other
=> include request_delegation for generator

app/packages/core/src/components/Actions/utils.tsx
As a user, when I go to the modal view, select labels and go to the next sample and select more labels, and tag labels, only labels from the last sample get actually tagged. 
This PR fixed the regression described above. 
https://github.com/voxel51/fiftyone/assets/17770824/6044348b-4c5c-4023-a1c9-cc9a47b76101
-   [ ] Other
=> bugfix: tag labels in multiple samples can only tag labels in the last sample successfully

app/packages/core/src/components/ViewBar/ViewStage/viewStageParameterMachine.ts, app/packages/relay/src/graphQLSyncFragmentAtom.ts, app/packages/relay/src/selectorWithEffect.tsx, app/packages/state/src/recoil/atoms.ts, app/packages/state/src/recoil/view.ts
Fixes Take seed changes in the App.
* Fix comma handling
* Process view changes from the bar and exclude `_rand` kwarg when seed changes
https://github.com/voxel51/fiftyone/assets/19821840/2692b77e-090e-43ab-bb75-83ebd2f6cb83
https://github.com/voxel51/fiftyone/assets/19821840/fcf5e003-2253-465a-9106-0812d3efa256
=> Fix Take seed in App

app/packages/state/src/hooks/useCreateLooker.ts
This PR fixes a bug where orthographic projections weren't showing because `sampleMediaFilePath` was being set after sample config was already instantiated.
=> Bugfix Orthographic projection

app/packages/state/src/recoil/aggregations.ts
Fixes numeric bounds requests for range sliders in the modal. The change ensures the bounds are calculated only using the current modal sample or group (when viewing a group a dataset)
=> Lightning numeric modal bounds

fiftyone/migrations/revisions/v0_23_0.py
fix the `NoneType` object (colorscheme.fields) is not iterable bug when migrating dataset.
(Details)
-   [ ] Other
=> Fix `NoneType` object error in migration

app/packages/components/src/components/TabOption/TabOption.tsx, app/packages/core/src/components/Filters/StringFilter/useSelected.ts
A regression from #3846, lightning search input should always be shown. Also improves Options popout sizing.
Before
After
=> Always show lightning search input 

fiftyone/migrations/revisions/v0_23_0.py
Resolves `'NoneType' object is not iterable` migration errors. Confirmed locally
=> Check for None fields value in migration

app/packages/app/vite.config.ts
The production build of the app is throwing many lines of `Module level directives cause errors when bundled, 'use client' was ignored. messages when fiftyone` warning. It seems to be coming from [this plugin](https://socket.dev/npm/package/rollup-plugin-preserve-directives) used by the libs. I am not sure what has caused the sudden burst.
solution: override the `onwarn` handler and ignore the directive's warning. 
sources
https://rollupjs.org/configuration-options/#onwarn
https://socket.dev/npm/package/rollup-plugin-preserve-directives
Run `yarn build` in `fiftyone/app` and the warning is gone.
(Details in 1-2 sentences. You can just …
=> Ignores the rollup-plugin-preserve-directives warning on app production

fiftyone/core/metadata.py
Remove `ExifTags.Base` usage in favor of the hardcoded value `0x0112 == 274`
This fixes broken support for older `pillow` versions.
Installed `pillow==6.2`, made sure function works.
Tests still pass
-   [ ] Other
=> [BUGFIX] remove PIL.ExifTags usage to support pillow==6.2

app/packages/app/src/pages/datasets/DatasetPage.tsx, app/packages/app/src/routing/RouterContext.ts, app/packages/app/src/routing/useRouter.ts, app/packages/app/src/useEvents/useStateUpdate.ts, app/packages/state/src/utils.ts
Fixes error boundary handling of the App query and retains view bar error handling introduced in #3613 
https://github.com/voxel51/fiftyone/assets/19821840/eb3c94d7-b5fb-47da-ba1c-48ffc2e93ba6
=> Handle App query errors

fiftyone/core/collections.py, tests/unittests/dataset_tests.py
Fixes a very subtle issue when inferring dynamic schemas for doubly-nested list fields. The new unit test fails on `develop` but passes on this branch.
=> Fixing bug when inferring doubly-nested dynamic list field types

fiftyone/utils/data/exporters.py
- pass `export_dir` as `export_path` in `ImageClassificationDirectoryTreeExporter` and `VideoClassificationDirectoryTreeExporter`. Not really used in this context but needed in Teams code.
- minor cleanup: `is True` is preferable to `== True` - changed in a few places in this file for export_mode.
https://www.flake8rules.com/rules/E712.html
Just minor cleanup - ran export unit tests. Nothing else to test.
-   [ ] Other
=> improvements to exporters.py

fiftyone/core/dataset.py
- Current dataset loading relies on getting the DatasetDocument from the local mongoengine queryset cache, which is problematic when using fiftyone in different processes
- This change should prevent errors like "Dataset does not exist" immediately after creating a dataset or "Dataset already exists" after deleting a dataset, especially when using the python sdk locally but connecting to a remote app.
```
As of MongoEngine 0.8 the querysets utilise a local cache. 
```
link to mongoengine doc: https://docs.mongoengine.org/guide/querying.html
(Details)
if this …
=> Remove loading from mongoengine cache

fiftyone/operators/builtin.py
Small tweak to the builtin `delete_selected_samples` and `clone_selected_samples` operators such that the `Execute` button will be disabled when there are no selected samples to delete/clone.
=> Invalidate builtin operators when there's nothing to do

app/packages/core/src/components/Actions/Options.tsx, app/packages/core/src/components/Modal/Modal.tsx, app/packages/core/src/components/Sidebar/Entries/PathValueEntry.tsx, app/packages/state/src/recoil/atoms.ts
Adds a new settings to sample modal Display Options. Toggling it, hides/ shows the fields with `path = 'None'` to reduce sidebar clutter.
Manual
https://github.com/voxel51/fiftyone/assets/109545780/ec054ac9-d3c7-44e9-8d0d-e6545b36dfba
-   [ ] Other
=> Adds a toggle to show/hide fields in sample modal that are undefined

fiftyone/factory/repos/delegated_operation.py, tests/unittests/delegated_operators_tests.py
Set dataset_id and dataset_name using the delegate op doc so executing queued operations via command handlers work (since context.dataset isn't serialized in the doc the handler uses to queue the op)
=> Set dataset_id in params from op doc

app/packages/core/src/components/Actions/similar/utils.ts, app/packages/state/src/recoil/groups.ts, app/packages/state/src/recoil/selectors.ts, app/packages/state/src/session.ts, fiftyone/server/routes/sort.py
Pass in the active session group slice as a parameter for similarity sort requests to update samples
Fixes a bug: similarity search only works on default_group_slice
https://github.com/voxel51/fiftyone/assets/17770824/264345d7-63cf-47e7-9fed-f20a942b224e
```
ds = foz.load_zoo_dataset('quickstart-groups',max_samples=50)
print(ds.default_group_slice) # prints 'left'
view = ds.select_group_slices('right')
fob.compute_similarity(view,model='clip-vit-base32-torch',brain_key='sim_right')
```
(Details in 1-2 sentences. You can just refer to another PR with a …
=> bugfix: similarity search only works on default_group_slice

app/packages/state/src/recoil/lightning.ts
Fixes the Lightning threshold `Reset` button by ensuring Recoil's `DefaultValue` is not converted to a string.
```shell
cd ./app/packages/app && yarn dev
``` 
```shell
FIFTYONE_APP_LIGHTNING_THRESHOLD=1 python fiftyone/server/main.py
``` 
```python
fo.app_config.proxy_url = "http://localhost:5173"
``` 
https://github.com/voxel51/fiftyone/assets/19821840/dc0197db-27bd-4019-9c61-f881c2cdf686
=> Fix Lightning threshold reset

app/packages/operators/src/built-in-operators.ts
Updates the the built-in operators that update the current sample selection. Due to routing updates, it is unnecessary to use the `useSetSelected` and update the `selectedSamples` atom as they are equivalent.
Tested locally
=> Update selected sample operators

fiftyone/core/collections.py, fiftyone/core/dataset.py, fiftyone/core/singletons.py
When performing `dataset._bulk_write()`, only reload the docs that were involved in the mutations, if known.
=> Optimize reload docs when performing bulk writes

docs/source/user_guide/config.rst, fiftyone/core/config.py, fiftyone/core/odm/database.py
Let batch size used for `bulk_write()` (previously hard coded 100k) be configurable.
Wrap `core.odm.database.bulk_write()` function in `fou.ProgressBar` to make it easier. Like this
```python
try:
batch_size = fo.config.bulk_write_batch_size
with fou.ProgressBar(total=len(ops)) as pb:
for ops_batch in fou.iter_batches(ops, batch_size):
coll.bulk_write(list(ops_batch), ordered=ordered)
pb.update(batch_size)
```
Test code
```python
ds=fo.zoo.load_zoo_dataset('coco-2017', splits='validation')
ds.set_values("new_field", [51] * len(ds))
fo.config.bulk_write_batch_size=10
ds.set_values("new_field", [52] * len(ds))
ds.delete()
```
=> Configurable batch size for bulk_write

docs/source/user_guide/config.rst, fiftyone/core/config.py, fiftyone/core/dataset.py, fiftyone/core/odm/database.py, fiftyone/core/utils.py, tests/unittests/utils_tests.py
- Add `StaticBatcher` as an option to use in place of `DynamicBatcher`. The latter attempts to optimize for a nice flowing progress bar, whereas the former optimizes for predictability and is better in cases where latency between machine and MongoDB is higher.
- Add `BSONSizeDynamicBatcher` as an option. Instead of using latency between calls as a target, attempts to achieve a target BSON content size. The caller must register "backpressure" with the batcher so it can adjust the batch size - by giving it an iterable of BSON-able items that would approximate the size you want to optimize for. In the main case, it would be `list[fo.Sample]` in the batches and corresponding `list[dict]` provided back to the batcher.
- Add configuration to allow switching from the default "latency" to new …
=> Toggle dynamic batcher for add_samples(), others

package/db/setup.py
Adds aarch64 an x86_64 downloads for Ubuntu 23 in the `fiftyone-db`. Resolves #3928 
Support for Ubuntu 23 using Ubuntu 22 downloads can be verified in a docker container
```shell
docker run -it ubuntu:23.10 /bin/bash
```
In the container
```shell
apt update
apt install libcurl4 wget
wget https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2204-7.0.4.tgz
tar -xvf mongodb-linux-x86_64-ubuntu2204-7.0.4.tgz
cd mongodb-linux-x86_64-ubuntu2204-7.0.4/bin/
./mongod --version
```
=> Add fiftyone-db support for Ubuntu 23

docs/source/integrations/labelstudio.rst, fiftyone/utils/labelstudio.py, tests/intensive/labelstudio_tests.py
Cherry picking https://github.com/voxel51/fiftyone/pull/3895 for v0.23.2 release.
=> Cherry picking label studio multiple fields support for 0.23.2

fiftyone/utils/open_clip.py, fiftyone/zoo/models/manifest-torch.json
Exposing prompt embedding capabilities for OpenCLIP model recently added to zoo
- Set `can_embed_prompts` to True
- Added an `embed_prompts()` method
Test the embedding directly:
```py
model = foz.load_zoo_model("open-clip-torch")
embeddings = model.embed_prompts(["dog", "cat"])
```
Now you can also do natural language image searches with OpenCLIP:
```py
fob.compute_similarity(dataset, model="open-clip-torch", brain_key="oc_sim")
dataset.sort_by_similarity("cat")
```
- We may want to go through the docs and wherever CLIP is used, offer this as an alternative
- Should add this to the model zoo listing
- At present, this …
=> Exposing OpenCLIP embeddings

e2e-pw/src/oss/specs/color-scheme/color-scheme.spec.ts
`locator.fill()` is not stable. Out of 10 tests, there are always 3 or 4 times of failed text inputs. 
Removed flaky e2e tests from color-scheme tests until there is a more reliable way of adding the color setting through UI. 
(Details)
-   [ ] Other
=> test: remove flaky color e2e tests

app/packages/core/src/components/Sidebar/Entries/PathValueEntry.tsx, app/packages/state/src/recoil/schema.ts
Fixes an issue where primitive values in DynamicEmbeddedDocument within ListField is displayed as `None` sample modal
Verified values are displayed as CSV in the sample modal for the embedded fields:
Primitive values in DynamicEmbeddedDocument within ListField will be displayed as comma separated values (previously, displayed as `None`) in the sample modal
-   [ ] Other
=> show primitive in embedded document in ListField

app/packages/core/src/components/Schema/SchemaSelectControls.tsx, app/packages/core/src/plugins/SchemaIO/components/InferredView.tsx, app/packages/core/src/plugins/SchemaIO/utils/generate-schema.ts, app/packages/core/src/utils/links.ts, e2e-pw/src/oss/poms/field-visibility/field-visibility.ts, fiftyone/utils/open_clip.py, fiftyone/zoo/models/manifest-torch.json
Adds #3960, #3926, and #3851 to v0.23.2
=> Release updates

app/packages/utilities/src/fetch.ts
This PR fixes the edge case in fetch URL construction where fetch `origin` is already encapsulated in `path`, in which case `origin` can be omitted.
=> fix url construction

app/packages/components/src/components/Results/Results.tsx, app/packages/components/src/components/Selector/Selector.tsx
- fix keyboard navigation for selectors
- add tweak to auto-scroll to active selector option when navigating to hidden options
Using the dataset selector in the app with both keyboard and mouse navigation
fix keyboard navigation for selectors in the app
-   [ ] Other
=> fix keyboard navigation for selectors

fiftyone/server/mutation.py, fiftyone/server/view.py
When a group dataset is created that has a video and image slice and frame fields (like frame detections) are added to the video slice, then images cause an error in the App when you try to open them in the sample modal. This PR fixes this bug.
This bug is a potential regression introduced by #3666.
Smoke tested with the following test code.
```
dataset = fo.Dataset('group-frame-fields-bug, persistent=True)
video_sample = fo.Sample(filepath='/Users/abc/video.mp4', group=fo.Group().element('video'))
dataset.add_sample(video_sample)
dataset.add_frame_field('boxes', fo.EmbeddedDocumentField, embedded_doc_type=fo.Detections)
thumbnail_sample = fo.Sample(
filepath='/Users/abc/image.jpg',
group=fo.Group().element('thumbnail')
)
dataset.add_sample(thumbnail_sample)
``` …
=> Use mixed mode in select_group_slices

docs/source/integrations/ultralytics.rst, fiftyone/core/collections.py, fiftyone/core/models.py, fiftyone/utils/ultralytics.py
Adds support for passing Ultralytics YOLO models directly to `sample_collection.apply_model()`!
Example Usage:
```py
from ultralytics import YOLO
yolov5n = YOLO('yolov5n.pt')
yolov8n = YOLO('yolov8n.pt')
yolov8seg = YOLO('yolov8n-seg.pt')
yolov8npose = YOLO('yolov8n-pose.pt')
dataset.apply_model(yolov5n, label_field="yolov5n")
dataset.apply_model(yolov8n, label_field="yolov8n")
dataset.apply_model(yolov8seg, label_field="yolov8seg")
dataset.apply_model(yolov8npose, label_field="yolov8npose")
```
Additionally, I found that the previous YOLO instance segmentation conversion was incorrect, so this patches that!
It would be pretty easy for us to do something similar for CLIP, SAM, OpenCLIP, YOLO-NAS, …
=> Apply YOLO Models Directly to FiftyOne Datasets

fiftyone/server/routes/sort.py
The `/sort` route is currently used only to ensure a `dist_field` is correctly populated if the parameter is provided. Before routing updates, this meant a new dataset scheme was needed in the response. Omitting the response prevents serialization errors when a dataset has a `color_scheme`
=> Fix sort by similarity for datasets with a color scheme

fiftyone/core/models.py, fiftyone/utils/super_gradients.py, fiftyone/utils/yolo_nas.py, fiftyone/zoo/models/manifest-torch.json
Hi FiftyOne Team 👋 
We're excited to announce the successful integration of YOLO-NAS into the FiftyOne Model Zoo, a collaborative effort with @jacobmarks. This addition enriches our model offerings with advanced vision capabilities from YOLO-NAS.
YOLO-NAS, sourced from [SuperGradients' GitHub](https://github.com/Deci-AI/super-gradients), is now seamlessly integrated into FiftyOne, offering users its state-of-the-art vision capabilities within the familiar FiftyOne environment.
This integration is designed for smooth compatibility and user-friendly interaction with existing FiftyOne features.
I've developed an informative Jupyter notebook to illustrate YOLO-NAS's functions in FiftyOne, focusing on its practical applications in vision tasks. Check out the [FiftyOne + YOLO-NAS …
=> Integration of YOLO-NAS into FiftyOne Model Zoo #3925

fiftyone/utils/open_clip.py
Added gpu support in the new open_clip models by adding checks for config.device
Running openclip model on gpu 
model = foz.load_zoo_model("open-clip-torch", device="cuda")
GPU now supported with OpenClip models
-   [ X] Core: Core `fiftyone` Python library changes
-   [ ] Other
=> Adding gpu support for openclip models

fiftyone/core/collections.py, fiftyone/core/runs.py
No change in default behavior; just adds support for a new syntax:
```py
run.register_run(dataset, key, overwrite=True, cleanup=False)
```
which overwrites an existing run without running the existing run's `cleanup()` method.
=> Add support for configuring whether run cleanup happens

app/packages/looker/src/overlays/index.ts, app/packages/looker/src/util.ts, app/packages/looker/src/zoom.ts, fiftyone/core/patches.py
Fixes patches views in the App. Note the `fiftyone.core.patches` changes are due to the `_cls` requirement by Looker for `DynamicEmbeddedDocument` values.
The changes should also support evaluation patches views. Though I am unable to confirm due to #3996
```python
dataset = foz.load_zoo_dataset("quickstart", max_samples=1)
sample["embedded"] = fo.DynamicEmbeddedDocument(
ground_truth=sample.ground_truth, predictions=sample.predictions
)
sample.save()
dataset.delete_sample_field("ground_truth")
dataset.delete_sample_field("predictions")
dataset.add_dynamic_sample_fields()
``` 
https://github.com/voxel51/fiftyone/assets/19821840/8b317873-27d8-4e00-bb90-ebd907ac3d78
=> Fix embedded patches fields in the App

app/packages/components/src/components/Selector/Selector.tsx, app/packages/components/src/components/Selector/index.ts, app/packages/components/src/components/index.ts, app/packages/core/src/components/Actions/Options.tsx, app/packages/core/src/components/Filters/StringFilter/StringFilter.tsx, app/packages/core/src/components/Filters/StringFilter/useOnSelect.ts, app/packages/core/src/components/Sidebar/Entries/FilterablePathEntry/Arrow.tsx, app/packages/core/src/components/ViewBar/ViewStage/utils.ts, app/packages/core/src/components/ViewBar/ViewStage/viewStageParameterMachine.ts, app/packages/state/src/recoil/lightning.ts, app/packages/utilities/src/type-check.ts, e2e-pw/src/oss/poms/action-row/display-options.ts, e2e-pw/src/oss/poms/sidebar.ts, e2e-pw/src/oss/specs/sidebar/lightning.spec.ts
Fixes two `id` field bugs related to lightning mode
* Ensures the root `id` field is enabled in lightning mode by looking up the schema db path in the `pathIndexes` selector
* Adds snackbar error handling for invalid `ObjectId` field searches in the sidebar
Related e2e tests have been added for verification
https://github.com/voxel51/fiftyone/assets/19821840/1f566ec2-64d8-4183-9e49-390147db25c2
=> Lightning bug fixes

app/packages/core/src/plugins/SchemaIO/components/KeyValueView.tsx, app/packages/core/src/plugins/SchemaIO/components/LabelValueView.tsx, app/packages/core/src/plugins/SchemaIO/components/TableView.tsx, app/packages/core/src/plugins/SchemaIO/components/TagsView.tsx
Fix some operator's read-only-views crashing when rendered in operator's input
Using all the affected views in a test operator to ensure they render without an issue
Fix some operator's read-only-views crashing when rendered in operator's inputs
-   [ ] Other
=> support output-only views in input

app/packages/core/src/plugins/SchemaIO/components/DynamicIO.tsx, app/packages/core/src/plugins/SchemaIO/utils/index.ts
- Fixes an issue where data is unset due to missing default in the output of an operator
- Fixes an issue where the default for the `List` type is not initialized when rendered as non-composite views
Using an example operator with rendering both scenarios above
See changes proposed above
-   [ ] Other
=> fix missing default/data propagation for operator views

app/packages/components/src/components/ThemeProvider/index.tsx, app/packages/operators/src/OperatorPalette.tsx
When samples modal is opened, operator palette is hidden behind the modal. PR increased zIndex of operator palettes to make it appear on top of modal
By launching operator palette while samples modal is opened
Fix operator palette appearing behind the samples modal
-   [ ] Other
=> show operator palette over modal

app/packages/operators/src/utils.ts
Use fetch path prefix instead of fetch origin for operator icon URL resolution
Using an operator placement and an operator with custom icon
-   [ ] Other
=> use fetch path prefix instead of origin for operator icon

app/packages/components/src/components/ThemeProvider/index.tsx, app/packages/core/src/plugins/SchemaIO/components/DropdownView.tsx, app/packages/core/src/plugins/SchemaIO/components/FileExplorerView/FileExplorer.tsx
Fix z-index conflicts between the operator palette and dropdown within oprator
With a test operator using various views which has component which may appear behind the palette
-   [ ] Other
=> fix z-index conflicts in operator palette

fiftyone/core/dataset.py, fiftyone/core/singletons.py, tests/unittests/dataset_tests.py
Primary intended usage here is situations like the following:
```py
dataset.add_samples(lots_of_samples)
dataset.clear_cache()
dataset.set_values("field", lots_of_values)
```
=> Include sample/frame singletons when clearing dataset cache

docs/source/user_guide/config.rst, fiftyone/core/collections.py, fiftyone/core/config.py, fiftyone/core/dataset.py, fiftyone/core/odm/database.py, fiftyone/core/utils.py, tests/unittests/utils_tests.py
- use `get_default_batcher()` inside `bulk_write()`
- removes now-unused `bulk_write_batch_size` config setting
- add optional ability to render progress bars on bulk write operations like `set_values()` and `set_label_values()`
```py
_ = dataset.add_samples([fo.Sample(filepath=f"{i}.jpg") for i in range(10000)])
dataset.set_values("int", [1] * len(dataset))
dataset.set_values("int", [1] * len(dataset), progress=True)
```
```py
values = {_id: True for _id in dataset.values("predictions.detections.id", unwind=True)}
dataset.set_label_values("predictions.detections.bool", values)
dataset.set_label_values("predictions.detections.bool", values, …
```
=> Add dynamic batching to bulk writes

package/db/setup.py
Resolves an `/etc/os-release` parsing issue mentioned in https://github.com/voxel51/fiftyone/issues/3975#issuecomment-1900421186
=> [`fiftyone-db`] Fix /etc/os-release files with empty lines

docs/source/plugins/developing_plugins.rst
`dataset.init_run()` should not take any arguments
(Details)
-   [ ] Other
=> Custom runs typo

app/packages/plugins/src/index.ts
fix fetch prefix being omitted when loading plugins from fiftyone server in a prefixed environment
By verifying JS plugins load in both prefixed and non-prefixed environment
Fix JavaScript plugins not loading in Fiftyone Teams
-   [ ] Other
=> fix fetch prefix for loading plugins

fiftyone/core/collections.py, fiftyone/core/runs.py, tests/unittests/run_tests.py
1. Adds support for passing kwargs to `init_run()` and `init_run_results()`:
```py
config = dataset.init_run(foo="bar", spam="eggs")
dataset.register_run("test", config)
results = dataset.init_run_results("test", foo="bar", spam="eggs")
dataset.save_run_results("test", results)
```
2. Adds support for defining the builtin `method` property of custom runs:
```py
config = dataset.init_run(method="albumentations")
dataset.register_run("test", config)
config = dataset.init_run(foo="bar")
dataset.register_run("other", config)
print(dataset.list_runs(method="albumentations"))  # ['test']
```
Note that `dataset.list_runs(key=value)` already allows you to search on any arbitrary key, even if it does not exist. The reason that I …
=> Add support for passing kwargs directly when creating custom runs

app/packages/looker/src/elements/util.ts
not "0" left padding the number 10, to avoid "0.010" after "0.9" and before "0.11"  
by rewatching the videos for more than 9 seconds 
-   [X] No. You can skip the rest of this section.
-   [X] App: FiftyOne application changes
-   [ ] Other
=> excluding 10 from zero-padding

fiftyone/utils/open_clip.py
Fixes when a user does not define a device, sometimes the model will be gpu is some but not all places due to config.device not being updated
Run openclip models on gpu without specifying the gpu. Can check with things like model._using_gpu and checking tensor devices.
=> Update Open CLIP to use parsed Torch device

fiftyone/core/stages.py
Cast floats to ints to fix https://github.com/voxel51/fiftyone/issues/4051
Verified that the bug in https://github.com/voxel51/fiftyone/issues/4051 has been resolved with updated source.  I could not find existing test code for `stages.py`, would be happy to amend this PR to begin them.
-   [ ] Other
=> Shuffle Stage Random Number Bug

docs/source/user_guide/annotation.rst, docs/source/user_guide/app.rst, docs/source/user_guide/basics.rst, docs/source/user_guide/brain.rst, docs/source/user_guide/config.rst, docs/source/user_guide/evaluation.rst, docs/source/user_guide/export_datasets.rst, docs/source/user_guide/plots.rst, docs/source/user_guide/using_aggregations.rst, docs/source/user_guide/using_datasets.rst, docs/source/user_guide/using_views.rst
Several clear spelling mistakes in the documentation are fixed.
-   [ ] Other
=> Fix several spelling errors in the documentation

app/packages/core/src/components/Sidebar/Sidebar.tsx, app/packages/state/src/recoil/sidebar.test.ts, app/packages/state/src/recoil/sidebar.ts, app/packages/utilities/src/styles.ts
Fixes sidebar groups resolution when the dataset app config setting is configured
Example snippet
```python
dataset.app_config.sidebar_groups = [fo.SidebarGroupDocument(name="ground truth", paths=["ground_truth"])]
dataset.save()
```
=> Fix sidebar groups configuration

fiftyone/server/routes/frames.py
This PR makes sure that for grouped datasets with videos, if `SelectGroupSlices` view stage is applied with only one slice, the resulting view is only assigned `group_slice` if it's media type is `fom.GROUP`.
```
dataset = fo.Dataset("video-slice-bug")
qsv = foz.load_zoo_dataset("quickstart-video", max_samples=1)
group = fo.Group()
sample = fo.Sample(qsv.first().filepath, group=group.element("video"))
view = dataset.select_group_slices(["video"])
fo.launch_app(view)
```
=> check if view is group before assigning slice

app/packages/core/src/components/Sidebar/Entries/PathValueEntry.tsx, app/packages/looker-3d/src/action-bar/SliceSelector.tsx, app/packages/state/src/recoil/groups.ts, e2e-pw/src/oss/poms/modal/index.ts, e2e-pw/src/oss/specs/groups/modal-multi-pcd.spec.ts
Fixes non-default pcd slice rendering in the modal
```py
dataset = foz.load_zoo_dataset("quickstart-groups", max_samples=3)
dataset.group_slice = "pcd"
extra = dataset.first().copy()
extra.group.name = "extra"
dataset.add_sample(extra)
```
https://github.com/voxel51/fiftyone/assets/19821840/ea703ee5-cfd9-4193-a53a-f745a4a866f3
https://github.com/voxel51/fiftyone/assets/19821840/6ab0b721-9a43-4054-af8d-9c0638d3d018
=> Fix multi PCD groups in the modal

docs/source/teams/installation.rst, docs/source/teams/management_sdk.rst
Add cloud credentials to FOM documentation
=> [DOCS] cloud credentials in FOM

fiftyone/operators/executor.py, fiftyone/operators/types.py
Enables this usage for adding the ability to select the source of the "target view`. This is a pattern that exists in many plugins.
```py
class MyOperator(foo.Operator):
def resolve_input(self, ctx):
inputs = types.Object()
inputs.select_view(ctx)
def execute(self, ctx):
selected_view = ctx.target_view()
ctx.ops.set_view(view)
view_target_property = ViewTargetProperty(ctx, view_type=Dropdown)
view_target_property.choices.entire_dataset.label = "My Custom Label"
view_target_property.choices.selected_samples.include = False # hide an option
inputs.define_property("view_target", view_target_property)
view = ctx.target_view("view_target")
```
Tested via [this example operator](https://github.com/voxel51/fiftyone-plugins/pull/108/files#diff-836176c6defe9a0b797ef30b54545233875a1ef48cbef6c5a3d28d …
=> Add target view utilities to operators

app/packages/core/src/components/Sidebar/ViewSelection/ViewDialog.tsx, e2e-pw/package.json, e2e-pw/src/oss/poms/color-modal/index.ts, e2e-pw/src/oss/poms/saved-views.ts, e2e-pw/src/oss/specs/groups/ima-vid.spec.ts, e2e-pw/src/oss/specs/smoke-tests/saved-views.spec.ts, e2e-pw/src/shared/event-utils/index.ts, e2e-pw/tsconfig.json
- Fixed a bug in saved views editor caused by https://github.com/mui/material-ui/issues/10341.
- The editor doesn't work without `disablePortal` prop. On e2e side, because of this change, MUI backdrop intercepts mouse clicks and keypresses, and tests fail. The broken tests in saved views spec have been annotated with `.fixme()` until we we have a fix.
- Update e2e dependencies, run linter, fix type issues, etc.
=> saved views bug fix + e2e fixes

docs/source/integrations/huggingface.rst, docs/source/release-notes.rst, fiftyone/utils/transformers.py, fiftyone/zoo/models/manifest-torch.json
Cherry picks the 4 commits from #4065 for adding Monocular Depth Estimation models to the Hugging Face Transformers integration.
(Details)
-   [x] Other
=> Cherry pick Hugging Face Depth Estimation Integration

fiftyone/core/plots/plotly.py
Add an optional argument named `map_type` to `location_scatterplot()` so that a user can choose between 
`roadmap` and `satellite`. Currently Fiftyone only supports `roadmap` (carto-positron).
The `satellite` option uses a public USGS imagery map with no token needed (see https://plotly.com/python/mapbox-layers/).
The `map_type` option is added through the following changes:
1. Add a method `_set_map_type_to_figure()` to set `mapbox_style` based on `map_type`.
2. Remove `mapbox_style="carto-positron"`  from `_plot_scatter_mapbox_numeric()`, `_plot_scatter_mapbox_density()`, `_plot_scatter_mapbox_categorical()`, and `_plot_scatter_mapbox_categorical_single_trace()`.
3. Call `_set_map_type_to_figure()` after the invoke of the `_plot_scatter_mapbox_*` methods.
The default value of `map_type` …
=> Added an optional argument map_type so that a user can choose between

fiftyone/utils/yolo.py
contour label support
- Another common YOLO label format is not boxes as `x y w h`, but polygons as `x1 y1 ... xn yn`. 
- Before this patch, they were misinterpreted, so user (me in particular 😬 ) may stuck with such questions as "why evaluation scores are in the neighbourhood of zero" or "why my GT labels have confidence" or "why groundtruth labels are not fitting in the image"
- This patch reduces such stuckness: polygon labels still will be converted to boxes, but as proper envelope, so you can use them in visualization, evaluation, et cetera.
On custom datasets with both kinds of labels.
I think this change deserves a little mention that users don't need change their labels outside …
=> Bugfix: YOLO contour labels were boxes of inadequate shape

fiftyone/core/odm/dataset.py, tests/unittests/odm_tests.py
Fixes `ColorScheme` serialization by using the [same ID field pattern used by Label classes](https://github.com/voxel51/fiftyone/blob/0b8c3bb04e0fa5fc7d702b6dbac9a81173e432f1/fiftyone/core/labels.py#L314-L333).
The existing logic did not satisfy the following requirement, which, for example, was causing the `@voxel51/utils/edit_dataset_info` operator to be unable to understand custom color schemes.
```py
color_scheme = fo.ColorScheme()
d = color_scheme.to_dict(extended=True)
also_color_scheme = fo.ColorScheme.from_dict(d, extended=True)
assert color_scheme == also_color_scheme
```
=> Fixing ColorScheme serialization

fiftyone/utils/labelstudio.py
Closes #3911 
Implements support for LS local storage
I couldn't create any way to test rather than manual....
Label Studio integration now support using local storage
-   [ ] Other
=> allow local files in LS

app/packages/core/src/components/Filters/StringFilter/state.ts
Fixes changing the group grid slice when a filter is present. Optional chaining was missing. See recording
https://github.com/voxel51/fiftyone/assets/19821840/8b65ea18-65c6-44fd-b0e4-0155e5e798f1
https://github.com/voxel51/fiftyone/assets/19821840/9cceaf95-7152-4a9a-b66a-d87cd07c6b45
Locally
* Fixed changing group slice in the grid when a sidebar filter is present
-   [ ] Other
=> Fix slice change when filters are present

fiftyone/utils/transformers.py
Zero-shot object detection transformers used for batch inference had shape mismatch issue. This reverts to naive implementation, just for zero-shot object detection transformers.
(Details)
-   [x] Other
=> Patch fix for zero-shot detection batching

docs/source/tutorials/dimension_reduction.ipynb
links like this: [`compute_visualization()`](https://docs.voxel51.com/api/fiftyone.brain.html#fiftyone.brain.compute_visualization) don't render properly in the docs. This PR removes the backticks.
-   [ ] Other
=> [DOCS] Updating hyperlink formatting for Dimensionality Reduction tutorial

fiftyone/operators/types.py
When there's no view or sample selection, the target view utility creates a radio group with no values. This results in the error in screenshot below because the default of `DATASET` isn't an enum in the radio group.
Proposed fix is to always put `DATASET` into the enum of options.
This will cause the radio group to appear with only one option though which is silly. So if there is only 1 option, we make it a `HiddenView`.
Also did some code tidying while I was here.
1. Use an operator that uses target view utility such as jacobmarks/image-quality-issues compute aspect ratio operator.
2. No view or selection: no target view input exists but execution is allowed and occurs over the entire dataset.
3. View or selection: target view input exists and offers entire dataset or view/selection - …
=> [BUGFIX] fix bug with operator target view utility when no view or selection

app/packages/operators/src/operators.ts
Fix `on_startup` not executing on startup due to race condition where on_startup operators are executed before the invocation queue is initialized. With the change in the PR, when a subscriber is added, it will be notified of the queue if there are any pending invocation requests in the queue
Using the VoxelGPT plugin and verifying that the VoxelGPT panel launches on startup 
Fix `on_startup` not executing on app startup
-   [ ] Other
=> notify new subscriber of pending operator invocation requests

docs/source/plugins/using_plugins.rst, fiftyone/operators/executor.py, fiftyone/operators/operator.py
`foo.execute_operator()` currently does not work in notebooks. Upon investigation, the reason is that notebooks internally use an async event loop to do their thing, and `foo.execute_operator()` uses `asyncio.run()`, which is not allowed when there is already an event loop running.
Using `asyncio.get_running_loop().create_task(...)` in place of `asyncio.run(...)` seems to do the trick when running in notebooks 💡 
https://github.com/voxel51/fiftyone/assets/25985824/47bf4c76-9e8a-48b9-834b-d265d2a75e58
=> Add support for executing operators programmatically in notebooks

fiftyone/core/dataset.py, tests/unittests/dataset_tests.py, tests/unittests/view_tests.py
`dataset.clone()` includes saved views and brain runs, so for consistency it would make sense that it would also include any custom indexes too (users have asked for this behavior). Now it does.
=> Include indexes when cloning datasets/views

fiftyone/core/media.py, fiftyone/core/validation.py, fiftyone/utils/annotations.py, fiftyone/utils/cvat.py, fiftyone/utils/eval/classification.py, fiftyone/utils/eval/detection.py, fiftyone/utils/eval/regression.py, fiftyone/utils/eval/segmentation.py, fiftyone/utils/labels.py
Adds validation to nudge users to use `select_group_slices()` if they are passing a grouped collection to a method that was not specifically designed to handle grouped datasets/views.
This is intended to avoid confusion where users might expect that all slices of a grouped dataset will "automatically" be processed, when in fact the method would only process the active slice.
=> Group dataset validation

fiftyone/utils/data/exporters.py
Small optimization to the `MediaExporter` class to avoid re-exporting the same media file multiple times, which would previously happen in situations like below where we are exporting a collection that contains multiple samples with the same `filepath`:
```py
dataset = foz.load_zoo_dataset("quickstart", max_samples=1)
view = dataset.to_patches("ground_truth")
assert len(view.distinct("filepath")) == 1
view.export(
export_dir="/tmp/test",
dataset_type=fo.types.COCODetectionDataset,
)
dataset_dir="/tmp/test",
dataset_type=fo.types.COCODetectionDataset,
)
assert len(dataset2.distinct("filepath")) == 1
```
=> Avoid re-exporting media unnecessarily

docs/source/integrations/ultralytics.rst, fiftyone/utils/ultralytics.py, fiftyone/zoo/models/manifest-torch.json
With our Ultralytics integration, it is currently possible to load a YOLOv8, YOLOv9, or YOLO-World model from Ultralytics and then apply it to a FiftyOne dataset. This PR goes a step further and directly adds these models to the model zoo.
One upside of this approach is that model location is managed by FiftyOne, as opposed to loading directly from Ultralytics, which results in the checkpoint being downloaded to your current working directory.
The PR updates the Ultralytics integration docs to reflect these new changes.
(Details)
Adds YOLOv8, YOLOv9, and YOLO-World models directly to the zoo
(Details in 1-2 sentences. You can just refer …
=> Add YOLOv8, YOLOv9, and YOLO-World to FiftyOne Model Zoo

.github/workflows/test.yml, docs/source/getting_started/install.rst, setup.py, tests/unittests/delegated_operators_tests.py
Declare support for python 3.11 and python 3.12.
With caveat that 3D in python 3.12 is not yet supported until `open3d` [supports 3.12](https://github.com/isl-org/Open3D/issues/6433)
For version in python3.11, python3.12 ...
- Unit tests passing
- Launched app with quickstart and did various cursory manual testing
- Read through documented release notes / breaking changes / deprecations to identify potential issues.
There is probably something I missed (if unit tests don’t cover). But mostly it seems to just work.
Officially support python 3.11 and 3.12 …
=> Declaring compatibility with python 3.11 and (partially) 3.12

fiftyone/core/dataset.py
Coming from a user issue / complaint.
If you are trying to create a dataset that clashes in slug, it's really unclear why. It just says "Dataset name is not available". Even if you try to delete the dataset name, you'll still be unable to create that name.
Proposing a more clear error message in the case that the name is unavailable due to slug clash. Open to wording suggestions.
Also changed to `find_one` because not sure why it used `list(find().limit(1))` in the first place. And use f-string over formatted string.
Before
```python
ds = fo.Dataset("test_dataset")
ds2 = fo.Dataset("test-dataset")
File "<stdin>", line 1, in <module>
File "/Users/stuart/dev/fiftyone/fiftyone/core/singletons.py", line 36, in __call__ …
```
=> Clashing dataset slug - better error message

app/packages/operators/src/built-in-operators.ts
add support for setting a saved view with the `set_view` built-in operator
```py
def execute(self, ctx):
ctx.trigger("set_view", {"name": "my-saved-view-name"})
```
Using an example operator with a snippet above
add support for setting a saved view with the `set_view` built-in operator
-   [ ] Other
=> add support for setting saved view in set-view operator

fiftyone/utils/labels.py
Adds Non-Maximum Suppression (NMS) utility to fiftyone.utils.labels through `perform_nms()`! :tada:
It can be loaded as follows:
```python
import fiftyone.utils.labels as fl
"coco-2017",
dataset_name="detector-recipe",
)
predictions_view = dataset.take(10, seed=51)
fl.perform_nms(sample_collection=predictions_view, in_field="predictions", out_field="nms_predictions", conf_threshold=0.65, iou_threshold=0.4, progress=True)
```
It has been thoroughly tested, as seen in this [nms_test.pdf](https://github.com/voxel51/fiftyone/files/14607543/nms_test.pdf)
Addition of perform_nms() utility to …
=> Adding Non-Maximum Suppression (NMS) utility to fiftyone.utils.labels through perform_nms()

app/packages/core/src/components/Common/Checkbox.tsx, app/packages/core/src/components/Filters/StringFilter/Checkboxes.tsx, app/packages/state/src/recoil/pathData/boolean.ts, app/packages/state/src/recoil/pathData/lightningBoolean.ts, app/packages/state/src/recoil/pathData/lightningNumeric.ts, app/packages/state/src/recoil/pathData/lightningString.ts
Fixes a regression introduced by #3973 where indexed `BooleanField`s will throw an error in the `pathSearchResults` selector
```python
dataset = foz.load_zoo_dataset("quickstart", max_samples=1)
dataset.create_index("$**")
sample["bool"] = True
sample.save()
``` 
Opening the filter currently raises an error (see recording)
https://github.com/voxel51/fiftyone/assets/19821840/04383ecd-7e41-46b5-b675-605b04d96848
* Fix indexed BooleanFields in Lightning Mode
-   [ ] Other
=> Fix indexed BooleanFields in Lightning Mode

app/packages/operators/src/operators.ts, app/packages/operators/src/state.ts, fiftyone/operators/operator.py, fiftyone/operators/server.py
=> resolve static operator IO at execute time

docs/source/teams/installation.rst
Adds documentation of environment variables FOT recognizes for GCS and AWS, which was missing.
=> [DOCS] Document GCS and AWS env var credential options

app/packages/operators/src/index.ts, app/packages/operators/src/loader.tsx, app/packages/operators/src/operators.ts, docs/source/plugins/developing_plugins.rst, docs/source/plugins/using_plugins.rst, fiftyone/core/cli.py, fiftyone/operators/operator.py
Add a new boolean OperatorConfig param `on_dataset_open` (`onDatasetOpen` in JS) to indicate if an operator should execute on opening a dataset. When set to `true`, the operator will execute for cases below:
- When a dataset is loaded on launching the app
- When a dataset is switched from dataset selector in the app
- When a dataset is switching using `session.dataset`
- When a dataset is switched using a trigger in the execution of an operator
- When a dataset is opened/switced by using a direct URL in the browser
Using cases listed above in the app
Add a new boolean OperatorConfig param `on_dataset_open` (`onDatasetOpen` in JS) to …
=> add ability to auto-execute operator on opening a dataset

docs/source/plugins/developing_plugins.rst, fiftyone/operators/executor.py, fiftyone/operators/operations.py
Adds a new collection of methods to the `ctx` via `ctx.ops`. This should eventually contain all built in operators - both JS and python.
=> Contextual operations

.github/workflows/test.yml
Simple addendum to previous python3.11/python3.12 support PR - this has been broken for a while.
=> Use py3.11 for codecov

app/packages/operators/src/operators.ts, app/packages/operators/src/state.ts
Consider the following execution request from the example `OpenHistogramPanel` python operator:
```py
ctx.trigger(
"open_panel",
params=dict(),
)
```
Prior to this PR, this would silently fail to execute in the browser. After this change validation is enforced regardless of how the JS operator was executed. In cases where the operator prompt was used, this would be redundant, but this change doesn't attempt to prevent that since the validation is essentially free in the browser context.
With this change, when a JS operator is executed and the inputs are not valid the following error is shown to the user:
...with these errors in the console:
=> Validate JS Operators on ctx.trigger()

fiftyone/core/labels.py
`numpy.int` is deprecated. It was an alias for `int`, so this change yields identical behavior and fixes the `AttributeError` that gets thrown with newer versions of NumPy.
The release notes for NumPy 1.20.0 list all the builtin aliases that were deprecated:
https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated
Replace `np.int` with `int`.
`np.int` was just an alias for `int`, so this change should yield identical behavior.
-   [ ] App: FiftyOne application …
=> np.int -> int in labels.py

docs/source/_templates/layout.html, docs/source/conf.py, docs/source/faq/index.rst
Adds the `og:image` meta tag to the docs for social purposes. Also updates the tracking FAQ as Python imports are no longer tracked.
-   [ ] Other
=> Add og:image to docs / FAQ update

app/packages/app/src/pages/datasets/DatasetPage.tsx, app/packages/core/src/components/Sidebar/ViewSelection/index.tsx, app/packages/core/src/hooks/index.ts, app/packages/core/src/hooks/useRefetchableSavedViews.ts, app/packages/core/src/index.ts, app/packages/operators/src/built-in-operators.ts, app/packages/operators/src/operators.ts, docs/source/release-notes.rst
add support for setting view by name and slug
```py
def execute(self, ctx):
ctx.trigger("set_view", {"name": "my-saved-view-name"})
```
```py
def execute(self, ctx):
ctx.trigger("set_view", {"name": "My Saved View Name"})
```
add support for setting view by name and slug
-   [ ] Other
=> add support for setting view by name and slug

fiftyone/core/labels.py, setup.py, tests/unittests/label_tests.py
`_segmentation_to_detections()`, `_segmentations_to_polylines()`, and `_transform_mask()` create a new full-sized mask for each object in the mask, which scales badly. In our use case we have images with dimension about 22,000 x 9,000, with tens of thousands of objects in them. Looping through each object and creating a new full-sized mask object in each iteration is extremely slow.
The proposed changes scale exponentially better. In a 10,000 x 10,000 image with 10,000 objects, the old method would have taken almost three hours, whereas the new method took only 8 seconds.
Here are timing comparisons with a mask of shape 10,000 x 10,000 on a MacBook M2 Air.
`_segmentation_to_detections()` and `_segmentations_to_polylines()` - similar numbers for both:
| method  | n objects | time (seconds) …
=> Speed up segmentation conversion and `_transform_mask()`.

app/packages/plugins/src/externalize.ts
externalize fiftyone spaces package to share context
Depends on https://github.com/voxel51/fiftyone-plugins/pull/124
Using a an externally built plugin with a Panel
Fix `usePanelState` not persisting state in session due to missing panel context
-   [ ] Other
=> externalize fiftyone spaces package to share context

app/packages/components/src/components/ThemeProvider/index.tsx, app/packages/spaces/src/SpaceNode.tsx, app/packages/spaces/src/SpaceTree.ts, app/packages/spaces/src/components/Space.tsx, app/packages/spaces/src/types.ts, app/packages/spaces/src/utils.ts, app/packages/spaces/src/utils/sizes.test.ts, app/packages/spaces/src/utils/sizes.ts, app/packages/state/src/hooks/useSessionSpaces.ts, fiftyone/core/spaces.py
Currently, if a space is resized in the app, the updated sizes of spaces is not persisted in session. As a result, if app reloads, the resizing is lost. PR adds changes to persist sizes of all spaces in the app. In addition, it also adds the ability to update the sizes of spaces from active Python session
- resizing in the app and refreshing the app
- setting sizes of a space from python shell
- unit test
https://github.com/voxel51/fiftyone/assets/25350704/9084d71a-a06a-49b2-b010-571a414fa0f7
Persist sizes of spaces in app session
-   [ ] Core: …
=> persist space sizes in session

app/packages/spaces/src/components/Space.tsx
When Ritchie was demoing, I noticed that joining spaces sometimes renders an invalid layout. See before and after below
https://github.com/voxel51/fiftyone/assets/25350704/b9fe4ca9-c1f0-44b7-9497-4a55e76e56ce
https://github.com/voxel51/fiftyone/assets/25350704/e4860f9e-0eef-48b7-af48-6b4fce4cca59
Fixed an issue where joining spaces sometimes renders an invalid layout
-   [ ] Other
=> joining spaces sometimes renders invalid layout

app/packages/spaces/src/components/Space.tsx
fix session not updated on space resize
By resizing spaces in the App and refreshing to make sure space sizes are preserved
-   [ ] Other
=> fix session not updated on space resize

fiftyone/operators/executor.py, fiftyone/operators/server.py
Currently, secrets are not being resolved in ExecutionContext for ResolveType and ResolveExecutionOptions routes. As a result, `ctx.secret` is not functional in `resolve_input`, `resolve_output` and `resolve_execution_options`
Using an example Python operator
Fix secrets not accessible in `resolve_input`, `resolve_output` and `resolve_execution_options` of a Python operator
-   [ ] Other
=> resolve secret for resolve operator type and options

app/packages/state/src/recoil/aggregations.test.ts, app/packages/state/src/recoil/aggregations.ts
Fixes a regression from #4182 
`release/v0.23.8`
https://github.com/voxel51/fiftyone/assets/19821840/30ddaf9e-f6c6-4741-b5f2-0d87b06bae4e
`bugfix/modal-tags-aggregation`
https://github.com/voxel51/fiftyone/assets/19821840/8a28ec3a-3411-410a-adbe-a9d3903f71bd
Amended recoil test
-   [ ] Other
=> Fix App modal tags in 'group' stats mode

docs/source/release-notes.rst, docs/source/teams/cloud_media.rst, docs/source/user_guide/config.rst, docs/source/user_guide/using_datasets.rst, docs/source/user_guide/using_views.rst, fiftyone/core/collections.py, fiftyone/core/dataset.py, fiftyone/core/frame.py, fiftyone/core/models.py, fiftyone/core/stages.py, fiftyone/core/storage.py, fiftyone/core/utils.py, fiftyone/core/view.py, fiftyone/utils/annotations.py, fiftyone/utils/cvat.py, fiftyone/utils/data/exporters.py, fiftyone/utils/data/parsers.py, fiftyone/utils/eval/detection.py, fiftyone/utils/eval/segmentation.py, fiftyone/utils/geojson.py, fiftyone/utils/image.py, fiftyone/utils/iou.py, fiftyone/utils/labelbox.py, fiftyone/utils/labelstudio.py, fiftyone/utils/patches.py, fiftyone/utils/scale.py, fiftyone/utils/utils3d.py, fiftyone/utils/video.py, tests/unittests/model_tests.py
- Autosave contexts now respect the default batching strategy and can be configured to use content size-based batching
- All SDK methods now use `autosave=True` or its equivalent rather than calling `sample.save()` in a loop
- Renames `export_media` parameter to `write_clips` in video sample parsers, for clarity
- Centralizes the application of `select_fields()` in `compute_embeddings()` and `compute_patch_embeddings()`, for consistency with how this is handled in the `apply_model()` utility.
- Adds support for sample collections to `fou.iter_slices()`
- Adds a `SampleCollection._resolve_media_field()` utility
- Adds a `fos.read_files()` method to efficiently read from multiple files in a threadpool
- Adds a warning when uploading large amounts of data to CVAT
- Removes unneeded `pylint: …
=> Export/model inference cleanup (for v0.23.8)

fiftyone/zoo/models/manifest-torch.json
Update model zoo metadata to include Open Images v7 pretrained Ultralytics YOLOv8 model weights.
Usage:
```py
dataset = foz.load_zoo_dataset("quickstart", max_samples=10)
model = foz.load_zoo_model('yolov8m-oiv7-torch')
dataset.apply_model(model, label_field="oi")
```
Fixes https://github.com/voxel51/fiftyone/issues/4399.
What do you think about the PR @jacobmarks?
Add Ultralytics YOLOv8 weights pretrained on Open Images v7 dataset with 600 target classes into Fiftyone Model Zoo.
- …
=> add ultralytics yolov8 open images v7 pretrained models into zoo

app/packages/core/src/plugins/SchemaIO/components/PlotlyView.tsx, app/packages/operators/src/built-in-operators.ts, fiftyone/operators/operations.py
- Adds new set_extended_selection operation, which is an advanced way of telling the grid which samples to display.
- Fixes an issue with plotly events where the panel_id was not properly included
=> Add set_extended_selection operation

fiftyone/core/session/session.py
Follow up to https://github.com/voxel51/fiftyone/pull/4423 to avoid `len(dataset)` calls which can be slow. Also adds `view` group slice handling
```py
dataset = fo.load_dataset("quickstart-groups")
dataset.group_slice = "pcd"
view = dataset.view()
view.group_slice = "right"
```
=> Avoid slow session launch

fiftyone/utils/annotations.py, fiftyone/utils/cvat.py, fiftyone/utils/labelbox.py, tests/intensive/cvat_tests.py
Adds support for passing clip views to `annotate()`.
So far only the CVAT backend supports clip views.
Unlike [frame views](https://github.com/voxel51/fiftyone/pull/4477), there may be a minor amount of backend-specific work required to support clips rather than full videos. For example, in the case of CVAT, a touch of work was required when uploading the videos (as frames) and then when mapping CVAT frame IDs to the correct frame numbers during annotation download.
```py
clips = dataset.limit(1).to_clips([[(10, 20), (30, 40), (50, 60)]])
anno_key = "test"
clips.annotate(
anno_key,
backend="cvat",
label_type="detections",
classes=["vehicle"], …
```
=> Add support for annotating clip views

fiftyone/core/dataset.py, fiftyone/core/fields.py, fiftyone/core/odm/dataset.py, fiftyone/core/odm/document.py, fiftyone/core/odm/mixins.py, fiftyone/core/odm/utils.py, fiftyone/utils/data/importers.py, tests/unittests/dataset_tests.py, tests/unittests/import_export_tests.py
Adds `created_at` property to all `fo.Field`s. Default is `None` but it is populated on newly-created fields.
This is only stored in the dataset doc `sample_field` and `frame_field` embedded document list fields, so the footprint is small.
**Note**: `created_at` is not propagated through to embedded document fields. Could add this on later if desired but for now the feature achieved what I needed without doing so.
Depends on branch `last-modified-at` so must be merged there.
Also depends on some other bug fixes such as https://github.com/voxel51/fiftyone/pull/4729. But that was copied into the commit. Might just have merge conflicts.
Added automated tests checking field created_at is only updated when the field is new.
```python
import time
import fiftyone as …
```
=> Fields have created_at attribute

fiftyone/operators/delegated.py
Cherry-picking #4715 for release.
**Benefits:** delegated operations will no longer emit spurious "failed to resolve output schema for the operation" warnings (regression in `fiftyone==0.25`).
**Risks:** none
=> Cherry pick #4715

fiftyone/zoo/models/manifest-torch.json
This PR simply adds the 3D Med-SAM2 model to the model zoo. This model is a fine-tuning of SAM2 hiera-tiny, published on [Hugging Face](https://huggingface.co/datasets/jiayuanz3/REFUGE/tree/main) and the [Med-SAM2 Github repo](https://github.com/MedicineToken/Medical-SAM2) along with their paper: [Medical SAM 2: Segment Medical Images As Video Via Segment Anything Model 2](https://arxiv.org/abs/2408.00874).
Simultaneously, I have collected the BTCV imagery used to train Med-SAM2 and converted it into a Fiftyone video dataset. This dataset has been (is being) [uploaded](https://huggingface.co/datasets/Voxel51/BTCV-CT-as-video-MedSAM2-dataset/tree/main) to the Hugging Face Hub into the Voxel51 organization.
Soon, I will add a tutorial that guides users to load the BTCV dataset, load the …
=> Draft: Adding Med-SAM2 model and Med-SAM2 dataset to HF Collection

fiftyone/core/dataset.py
The `delete_samples()` and `clear_frames()` methods did not currently handle the case where the user wants to delete >100k samples/frames. This patches that.
Unit tests should already cover these methods, but here's a quick test I ran live:
```py
dataset.delete_samples(dataset[:2])
assert len(dataset) == 8
dataset[:2].clear_frames()
assert dataset[:2].values(F("frames").length()) == [0, 0]
frame_ids = dataset[2:4].values("frames.id", unwind=True)
dataset._clear_frames(frame_ids=frame_ids)
assert dataset[2:4].values(F("frames").length()) == [0, 0]
view = dataset[4:6].to_clips([[(1, 7),  (3, 10)], [(1, 10)]])
view.keep_frames()
assert …
```
=> Support large deletions by sample/frame IDs

docs/source/brain.rst, fiftyone/core/collections.py, fiftyone/core/dataset.py, fiftyone/migrations/revisions/v1_0_0.py, fiftyone/operators/builtin.py, tests/unittests/dataset_tests.py
Added the following new builtin operators:
- `edit_field_info`
- `clone_frame_field`
- `rename_frame_field`
- `clear_frame_field`
- `delete_frame_field`
- `create_index`
- `drop_index`
- `create_summary_field`
- `update_summary_field`
- `delete_summary_field`
- `add_group_slice`
- `rename_group_slice`
- `delete_group_slice`
- `load_saved_view`
- `save_view`
- `edit_saved_view_info`
- `delete_saved_view`
- `edit_workspace_info`
- `sync_last_modified_at`
Enhancements to existing builtin operators
- Intelligent handling of read-only fields
- Intelligent handling of default fields
- Enhanced many fields' descriptions
Other updates
- Improved the robustness of the v1.0.0 migration (eg handle case where an existing dataset has an incompatible `created_at` or `last_modified_at` field)
- …
=> Adding builtin operators for more of the FO interface

fiftyone/core/odm/document.py
Remember [when I said](https://github.com/voxel51/fiftyone/pull/4597/files#r1731405270) that monkey-patching "should be fine"? Yeah turns out that was misguided in multithreaded environments. Gotta remove it.
=> No monkey business

docs/source/release-notes.rst
Release is tomorrow, not two days ago
(Details)
-   [ ] Other
=> time marches forward

app/packages/core/src/plugins/SchemaIO/components/TextView.tsx
tested locally
```
def render(self, ctx):
panel = types.Object()
text_view_0 = types.TextView(
title="Voxel",
variant="body1",
font_size="1.2rem",
color="primary",
bold=True,
text_transform="uppercase",
width="auto",
display_mode="inline-block",
padding={0}
)
text_view_01 = types.TextView(
title="Fiftyone",
variant="body1",
font_size="1.2rem",
color="red",
bold=False,
italic=True,
text_transform="uppercase",
width="auto",
display_mode="inline-block",
padding={0}
)
text_view_1 = types.TextView(
title="Primary Bold Text",
variant="body1",
font_size="1.2rem",
color="primary",
bold=True,
text_transform="uppercase",
align="center",
width="100%",
display_mode="block"
)
text_view_2 = types.TextView(
title="Italic Secondary Text",
variant="body2",
font_size="1rem",
color="secondary",
italic=True, …
```
=> snake_case the TextView component

fiftyone/core/odm/utils.py, requirements/common.txt
This ended up being a bizarre series of events that led to this bug now of all times, since the code in question is years old.
If you're not satisfied with just the fix without knowing why, like I wasn't, follow along here. Otherwise the fix is quite simple, go there!
Alright here we go ...
1. 9/1/2022 - brimoor [introduced](https://github.com/voxel51/fiftyone/pull/2051) `DocumentRegistry` which allows custom embedded document classes to reside anywhere that is found within `sys.modules`. It does something like this:
```python
for module in sys.modules.values():
try:
return getattr(module, name)
except AttributeError:
pass
```
2. 1/10/2024 sash introduced [pydantic](https://github.com/voxel51/fiftyone/pull/3985) as part of 3D support. This was an oversight because we had used pydantic …
=> Fix: quickstart3d load due to dict changed size during iteration

app/packages/spaces/src/components/AddPanelButton.tsx, app/packages/spaces/src/components/AddPanelItem.tsx
Improved padding / margin for panel metadata. Also fixed issue where NEW and BETA would show at the same time.
=> panel meta fixes

app/packages/core/src/components/Sidebar/Entries/QueryPerformanceIcon.tsx
fix query performance tooltip padding
-   [ ] Other
=> fix query performance tooltip padding

app/packages/looker-3d/src/labels/index.tsx, app/packages/looker/src/overlays/detection.ts, app/packages/looker/src/worker/threed-label-processor.ts
Although it's a violation of the contract if a 3D labels doesn't have `location` and `dimensions` property, the app shouldn't crash if that's the case. This PR adds resilience against that behavior.
Locally.
-   [ ] Other
=> add guards for missing location/dimensions while rendering 3d bounding boxes

docs/source/plugins/developing_plugins.rst
Adds links to the new js plugin repos in a new getting started developing JS plugins section.
=> add JS plugin getting started

fiftyone/server/lightning.py
Group slice information is not present in frame samples. Omit the slice filter in this case
```python
dataset = fo.Dataset("quickstart-video-group")
videos = foz.load_zoo_dataset("quickstart-video")
for video in videos:
video["group"] = fo.Group().element("only-slice")
dataset.add_sample(video)
``` 
https://github.com/user-attachments/assets/1fe949cf-3be4-4dc2-9555-39f4d12d5587
-   [ ] Other
=> Omit slice filter for frame collection QP

docs/scripts/make_model_zoo_docs.py
Fixes https://github.com/voxel51/fiftyone/issues/5221. Updated documentation:
Code tested in Colab: https://colab.research.google.com/drive/1Q5x-uhUcWoo9IVxR7bV-EESakcKWNy74?usp=sharing
Fix: Updated example in Doc for model `zero-shot-detection-transformer-torch`
-   [ ] Other
=> Fixed example for zero-shot-detection-transformer-torch

fiftyone/utils/torch.py
To reproduce (as of v2.1.3):
* Load the quickstart dataset and compute similarity with CLIP
* Create a view stage with Limit 200
* Sort by text similarity against dogs
This error gets raised by the App:
To catch this error, launch the path with:
```
python /path/to/your/install/of/fiftyone/server/main.py
```
```python
File "/home/eric/work/fiftyone/fiftyone-teams/fiftyone/utils/torch.py", line 580, in __exit__
self._no_grad.__exit__(*args)
AttributeError: 'NoneType' object has no attribute '__exit__'
```
TBD
Fixed a race condition when sorting by text similarity on a view in the App.
-   [X] App: FiftyOne application changes
-   [ ] …
=> Similarity race condition patch

app/packages/core/src/plugins/SchemaIO/components/NativeModelEvaluationView/Evaluation.tsx, fiftyone/operators/builtins/panels/model_evaluation/__init__.py
When evaluating object detections, confusion matrices need the ability to show an additional row/column to capture “missing” values:
- "missing": false negative ground truth (no matched prediction)
- "missing": false positive predictions (no matched ground truth)
```py
results = dataset.evaluate_detections(
"predictions",
classwise=False,
)
```
```py
from collections import Counter
freq = Counter(results.ytrue)
if results.missing in freq:
freq.pop(results.missing)
results.missing
classes = sorted(freq, key=freq.get, reverse=True)[:5]
cmat, labels, _ = results._confusion_matrix(
classes=classes,
include_other=False, …
```
=> Show "missing" counts in confusion matrices

fiftyone/core/utils.py, setup.py
This optimizes `dataset.first()` by ensuring that `len(dataset)` is not called unnecessarily.
=> Bump to ETA v0.13.1

fiftyone/zoo/models/manifest-torch.json
Simply modified manifest-torch.json to include [DINOv2 with registers](https://arxiv.org/abs/2309.16588) models:
- `"dinov2-vits14-reg-torch"`
- `"dinov2-vitb14-reg-torch"`
- `"dinov2-vitl14-reg-torch"`
- `"dinov2-vitg14-reg-torch"`
Untested, though considering `fiftyone.utils.torch.load_torch_hub_raw_model`'s code, this should work out of the box.
-   [ ] No. 
-   [x] Yes, see list of models added above.
-   [x] Other: Zoo
=> Add DINOv2 with registers to the model zoo

fiftyone/plugins/core.py, fiftyone/plugins/utils.py, fiftyone/utils/github.py
The [@voxel51/plugins/install_plugin](https://github.com/voxel51/fiftyone-plugins/tree/main/plugins/plugins) operator stopped working as a side effect of https://github.com/voxel51/fiftyone/pull/4614 because the operator tried to issue a command like this:
```py
import fiftyone.plugins as fop
url = "https://github.com/voxel51/fiftyone-plugins/tree/main/plugins/dashboard"
fop.download_plugin(url, plugin_names=["@voxel51/dashboard"])
```
where the `url` is pulled [directly from here](https://github.com/voxel51/fiftyone-plugins/blob/d458e19bf9141bb8cd68c0d382cda98fbb2e1169/plugins/dashboard/fiftyone.yml#L6).
When the operator was initially written, the above `download_plugin()` syntax worked, but only because the `GitHubRepository` class would automatically strip `main/plugins/dashboard` …
=> Handle tree paths in GitHub identifiers

fiftyone/core/collections.py, fiftyone/core/stages.py
Adds a `create_index` kwarg to `GeoNear` and `GeoWithin` stages, for consistency with the `SortBy` and `GroupBy` stages.
Note that, unlike sorting/grouping, the geo stages **require** the spherical index to exist in order to function. However, it feels appropriate to provide a `create_index=False` syntax to provide users a way to guarantee that nothing expensive like index creation will occur when creating/using a view.
=> Add `create_index` kwarg to geo stages

fiftyone/core/dataset.py, fiftyone/core/odm/mixins.py, plugins/operators/__init__.py
- Updates the builtin operators to use `list()` to allow users to act on multiple fields/entities wherever it makes sense
- Adopts the cleaner syntax made possible by https://github.com/voxel51/fiftyone/pull/5375
=> Allow lists wherever possible in builtin operators

app/packages/core/src/plugins/SchemaIO/components/NativeModelEvaluationView/Evaluation.tsx, fiftyone/operators/builtins/panels/model_evaluation/__init__.py, fiftyone/utils/eval/base.py, fiftyone/utils/eval/regression.py
Adds `Custom Metrics` to Summary in Model Evaluation panel
-   [ ] Other
=> Add custom metric to Summary in Model Evaluation panel

fiftyone/utils/eval/base.py
Resolves https://github.com/voxel51/fiftyone/issues/5399
```py
results = dataset.evaluate_detections(
"predictions",
classwise=False,
)
counts = dataset.count_values("ground_truth.detections.label")
classes = sorted(counts, key=counts.get, reverse=True)[:5]
_classes = classes + [results.missing]
_all_classes = list(results.classes) + [results.missing]
cmat = results.confusion_matrix(classes=classes)
assert cmat.shape == (5, 5)
cmat = results.confusion_matrix(classes=classes, include_missing=True)
assert cmat.shape == (6, 6)
_classes = classes + [results.missing]
cmat = results.confusion_matrix(classes=_classes)
assert cmat.shape == (6, 6)
cmat = …
```
=> Add `include_missing` argument to `confusion_matrix()`

app/packages/app/src/components/Setup.tsx
typo: forwaring -> forwarding
(you could probably setup a typo checker: https://github.com/crate-ci/typos)
-   [ ] Yes. Give a description of this change to be included in the release notes for FiftyOne users.
-   [ ] Other
=> fix "forwarding" typo in RemoteInstructions component

fiftyone/utils/labels.py
For frames segmentation fields, when exporting masks to disks, frame filepaths are required.
A cleaner alternative to this may be to make `frames.filepath` a default field.
Current error:
```python
AttributeError                            Traceback (most recent call last)
Cell In[78], line 1
----> 1 foul.export_segmentations(
2     dataset,
3     "frames.heatmap",
4     output_dir="/Users/ben/data/heatmaps",
5 )
File ~/code/fiftyone/fiftyone/utils/labels.py:236, in export_segmentations(sample_collection, in_field, output_dir, rel_dir, update, overwrite, progress)
233 elif isinstance(label, fol.Heatmap):
234     if label.map is not None:
235         outpath = filename_maker.get_output_path(
--> 236             image.filepath, output_ext=".png"
237         )
238 …
```
=> Fix exporting frame segmentations

docs/scripts/make_model_zoo_docs.py, docs/source/dataset_zoo/remote.rst, docs/source/model_zoo/remote.rst, docs/source/user_guide/evaluation.rst, fiftyone/operators/evaluation_metric.py, fiftyone/utils/ultralytics.py, fiftyone/zoo/models/__init__.py
- Adds `resolve_input()` and `parse_parameters()` methods to the remote zoo model interface. These methods allow remote zoo models to inject custom parameters into an operator's input form.
See https://github.com/voxel51/fiftyone-plugins/pull/201 for example usage.
=> Add support for remote zoo model parameters

fiftyone/factory/repos/delegated_operation.py, fiftyone/factory/repos/delegated_operation_doc.py, fiftyone/operators/delegated.py
Adding a log size field to DOs so that we can optionally provide a log size on upload to be returned by the backend if present. If the log size isn't present in the backend we will attempt to fetch it from the cloud storage location (less efficient but still works in cases where X customer has a custom log file but isn't storing that size in mongo like we are).
Ran executor locally and then tested that log file sizes were reflected / stored in mongodb: …
=> add do log file size

fiftyone/core/odm/runs.py, fiftyone/core/runs.py
Updates the `register_run()` and `load_run_view()` interface so that runs that are performed on full datasets will still reflect this fact when `load_run_view()` is called later.
The example below demonstrates a real world application of this. Previously, the last assertion would fail because `load_run_view()` would return `dataset.view()` rather than `dataset`. Now the fact that the index was generated on the full dataset is preserved forever! 🎉
```py
index = fob.compute_similarity(dataset, brain_key="img_sim")
assert index.samples is dataset
dataset.clear_cache()
index = dataset.load_brain_results("img_sim")
assert index.samples is dataset
```
=> Ensure runs remain associated will full datasets

fiftyone/core/map/process.py, fiftyone/utils/map.py
Bug fix for progress bar in map samples and updated map_samples type hinting
* Tested locally
-   [ ] Other
=> Bug fix for progress bar in map samples a

fiftyone/core/map/process.py, fiftyone/core/map/threading.py
When there are multiple workers there could be many empty queue events. Adding exponential backoff helps to reduce these events and allow queue processing to be more efficient.
Benchmarking number with evaluate_detections:
```
=== Performance Summary ===
Sorted by execution time:
configuration shard_method  num_workers backend  use_backoff    duration
id_16w_process_backoff           id           16 process         True  483.764559
id_16w_process_no_backoff           id           16 process        False  494.329092
id_8w_process_backoff           id            8 process         True  612.277136
id_8w_process_no_backoff           id            8 process        False  623.627703
id_4w_process_no_backoff           id            4 process        False 1093.151622
id_4w_process_backoff …
```
=> Exponenetial backoff to timeout

fiftyone/server/view.py, tests/unittests/server_view_tests.py
- fixes graphql error when invalid objectId searched in the sidebar id field
- FOEPD-688
- 
- added tests 
- verified running app locally and filtering by id
https://github.com/user-attachments/assets/84a596a3-06a2-4799-a115-4fc43a76aa78
-   [ ] Other
[FOEPD-688]: …
=> Fix error entering non-object id in sidebar id search

fiftyone/core/utils.py, fiftyone/utils/data/exporters.py, tests/unittests/utils/test_unique_filename_maker.py
Update `UniqueFilenameMaker` to work with multiprocessing. Added a new implementation and kept the old one for chunking and comparison tests. 
As you can see below the original filename maker (renamed from `UniqueFilenameMaker` to `InMemoryUniqueFilenameMaker`) does not return the same output in all cases when run with multiprocessing, while the new filename maker (`MultiProcessUniqueFilenameMaker`) does.
```
[InMemoryUniqueFilenameMaker-{idempotent=True}-empty-directory] PASSED               
[InMemoryUniqueFilenameMaker-{idempotent=True}-one-file-exists] PASSED               
[InMemoryUniqueFilenameMaker-{idempotent=True}-some-files-exist] PASSED              
[InMemoryUniqueFilenameMaker-{idempotent=True}-all-files-exist] PASSED …
```
=> Map Samples: UniqueFilenameMaker

fiftyone/utils/torch.py, requirements/test.txt, tests/unittests/torch_dataset_tests.py
I pulled the latest `develop` and got unit test failures due to the new `tests/unittests/torch_dataset_tests.py` tests that were added by @jacobsela in https://github.com/voxel51/fiftyone/pull/5703.
Upon inspection, the solution was to upgrade my `torch` and `torchvision` packages, so I've pinned sufficiently new versions to `requirements/test.txt` to ensure that others don't encounter this bug, assuming they follow the dev install instructions and run `bash install.bash -d`.
=> Add torch packages to test requirements

fiftyone/core/collections.py, fiftyone/core/dataset.py, fiftyone/core/document.py, fiftyone/core/frame.py, fiftyone/core/sample.py, fiftyone/utils/data/importers.py, tests/unittests/dataset_tests.py
- Adds a new `merge_embedded_docs=True` option to `merge_sample()` and `merge_samples()` that causes the attributes of embedded documents to be merged individually rather than the default behavior of treating the entire document as a single "value" 
- Unit tests are added to verify functionality in all relevant usage contexts
This little adventure started because I tried to merge labels from a top-level field into a dynamic embedded document field via this syntax:
```py
dataset.merge_labels("predictions", "data.predictions")
```
Prior to this PR, providing an embedded field `data.predictions` as the second argument to `merge_labels()` would raise an error (cf the first example below). Now it works as expected.
It turns out that, to make this work, we needed to add the concept of allowing …
=> Add support for merging embedded document fields

fiftyone/core/labels.py, fiftyone/core/sample.py, fiftyone/utils/torch.py
- Adds a `Keypoint.apply_confidence_threshold()` method that applies a confidence threshold to the keypoints
- Updates `Sample.add_labels(..., confidence_thresh=)` to correctly apply confidence thresholds to `Keypoint` instances
- Updates `KeypointDetectorOutputProcessor` to apply confidence thresholds to individual points
```py
"coco-2017",
label_types="detections",
classes=["person"],
max_samples=10,
)
model = foz.load_zoo_model("keypoint-rcnn-resnet50-fpn-coco-torch")
dataset.apply_model(
model,
label_field="predictions",
confidence_thresh=0.5,
)
```
=> Apply confidence to Keypoint instances correctly

app/packages/looker/src/overlays/detection.ts, app/packages/looker/src/overlays/keypoint.ts, app/packages/looker/src/overlays/polyline.ts, app/packages/looker/src/overlays/util.ts
- Standardizes hover and selection states across detection, keypoint, and polyline overlays
- Removes duplicate styling logic from individual overlay components
Gif below has keypoints and polylines for image samples, and detections for the 3d sample:
Locally
-   [ ] Other
=> labels correspondence bug fix: consistency in different label types hovering behavior

docs/source/user_guide/app.rst, fiftyone/core/collections.py, fiftyone/core/dataset.py, fiftyone/core/session/session.py, fiftyone/core/stages.py, fiftyone/utils/kitti.py, fiftyone/utils/labels.py, tests/unittests/label_tests.py, tests/unittests/view_tests.py
- Adds `instance_ids` argument to `select_labels()`, `match_labels()`, `exclude_labels()`, and `delete_labels()`
- Adds an `index_to_instance()` utility for converting old-style `index`s to `instance`s
- Fixes a bug with `set_values()` when setting frame fields via dict syntax where not all frame numbers are present
```py
from bson import ObjectId
import fiftyone.utils.labels as foul
foul.index_to_instance(dataset, "frames.detections", clear_index=True)
instance_id = dataset.first().frames.first().detections.detections[0].instance.id
view = dataset.select_labels(instance_ids=instance_id, fields="frames.detections")
instances = view.count_values("frames.detections.detections.instance._id") …
```
=> Add label `instance` to SDK 

fiftyone/utils/cvat.py
Resolves https://github.com/voxel51/fiftyone/issues/5917
```py
view = dataset.limit(2).to_frames(sample_frames=True)
results1 = view.annotate("test1", label_field="detections", launch_editor=True)
results2 = view.annotate(
"test2",
label_field="detections",
task_size=120,
)
```
```py
results1.cleanup()
results2.cleanup()
```
=> Avoid duplicate filenames when uploading to CVAT

app/packages/operators/src/CustomPanel.tsx, app/packages/operators/src/built-in-operators.ts, app/packages/operators/src/operators.ts, app/packages/operators/src/state.ts, app/packages/operators/src/useCustomPanelHooks.ts, docs/source/plugins/developing_plugins.rst, fiftyone/operators/executor.py, fiftyone/operators/operations.py, fiftyone/operators/panel.py
See [this fiftyone-plugins PR](https://github.com/voxel51/fiftyone-plugins/pull/232/files) for an example of how to use this new feature.
- adds `ctx.active_fields` which includes the currently active/visible fields in the sidebar
- adds `ctx.ops.clear_active_fields()` operator
- adds `on_change_active_fields` event for python panels
Local app with the plugin linked above.
Added a new property `active_fields` to the `ExecutionContext`. Operators and panels can now read the currently active fields. Added a new operator `clear_active_fields` for hiding all sidebar fields.
-   [ ] Build: Build and …
=> feat(ctx): active_fields

fiftyone/zoo/models/manifest-tf.json
The CenterNet MobileNet-V2 FPN checkpoint linked in manifest-tf.json ships as `centernet_mobilenetv2fpn_512x512_coco17_od.tar.gz` but the directory inside the archive is `centernet_mobilenetv2_fpn_od/`
Since FiftyOne matches the extracted folder name to `base_filename` (stem), loading failed with `FileNotFoundError` (see #1536).
**Updated the model manifest**
`centernet-mobilenet-v2-fpn-512-coco-tf2`  
`base_filename` → **`centernet_mobilenetv2_fpn_od.tar.gz`**
No code changes required; the loader now locates `saved_model/`correctly and the model can be loaded and applied to datasets as expected.
Resolves: #1536
* Fixes loading of **centernet-mobilenet-v2-fpn-512-coco-tf2** by aligning `base_filename` with the folder contained in the official TF-2 tarball.
* Cleared the local model cache …
=> fix(zoo): load centernet-mnv2 checkpoint (#1536)

docs/source/_static/css/custom.css, docs/source/conf.py, requirements/docs.txt
This PR adds a feedback widget to the documentation, powered by [PushFeedback](https://pushfeedback.com/).
All feedback submitted through the widget is directed to the PushFeedback account owned by @jimmyguerrero.
-   [ ] Other
=> Add feedback widget to docs

app/packages/map/package.json, app/yarn.lock
https://github.com/mapbox/mapbox-gl-draw/issues/1357 is causing issues for internal builds. Pinning to 1.4.3 should solve
Locally
-   [ ] Other
=> pin gl draw

fiftyone/core/utils.py, fiftyone/plugins/context.py, fiftyone/plugins/definitions.py, fiftyone/zoo/datasets/__init__.py, fiftyone/zoo/models/__init__.py, tests/unittests/utils_tests.py
Resolves https://github.com/voxel51/fiftyone/issues/6082
`os.path.relpath(a, b)` annoyingly raises a `ValueError` on Windows when `a` and `b` lie on different Drives. So we must manually handle that in a few places.
=> Handle different drives on Windows

fiftyone/zoo/models/manifest-torch.json
Replace null size values with size in bytes for ConvNeXt and EfficientNet models.
This PR updates the `torch-manifest.json` file to replace null file size values with actual file sizes in bytes for 13 models:
- 5 ConvNeXt variants (tiny, small, base, large, xlarge)
- 8 EfficientNet variants (b0-b7)
Manual testing by:
1. Verifying the byte sizes match the actual downloaded model files on HuggingFace
Fixed missing file sizes for ConvNeXt and EfficientNet models in the model zoo, enabling accurate download progress tracking and storage requirement validation. …
=> update torch-manifest.json with model sizes in bytes

fiftyone/zoo/models/manifest-torch.json
* `rtdetr-v2-s-torch` (ResNet-18 backbone)
* `rtdetr-v2-m-torch` (ResNet-50 backbone)
All models:
* Use existing `FiftyOneTransformerForObjectDetection` wrapper
* Support both CPU and GPU inference
* Tested on COCO object detection with validation images
* Successfully extract 256-dimensional embeddings
* Leverage HuggingFace hub for automatic model downloads
RT-DETRv2 brings improved real-time detection transformers with bag-of-freebies optimizations, offering better accuracy than v1 while maintaining the same inference speeds for edge and production deployments.
This PR adds 2 RT-DETRv2 object detection models to the FiftyOne model zoo by adding their configurations to `fiftyone/zoo/models/manifest-torch.json`. The models include:
* **RT-DETRv2 family**: Improved real-time detection …
=> Add RT-DETRv2 models to manifest-torch.json #6105

fiftyone/core/models.py
Resolves https://github.com/voxel51/fiftyone/issues/6137
The code in https://github.com/voxel51/fiftyone/issues/6137 now runs successfully on macOS **without** forcing `num_workers=0` or forcing `fork` multiprocessing to be used ✅
=> Fix #6137: use named function to avoid pickle error

fiftyone/zoo/models/manifest-torch.json
Added OWL-ViT base model with patch32 configuration to complete the OWL-ViT family:
- `owlvit-base-patch32-torch`
The model:
- Uses existing `FiftyOneZeroShotTransformerForObjectDetection` wrapper
- Supports both CPU and GPU inference
- Performs zero-shot object detection using text queries
- Successfully extracts embeddings for similarity matching
- Leverages HuggingFace hub for automatic model downloads
OWL-ViT base-patch32 completes the model family by providing the 32x32 patch variant alongside the existing patch16 option, giving users choice in the patch size/performance trade-off for their specific use cases.
This PR adds the OWL-ViT base-patch32 model configuration to `fiftyone/zoo/models/manifest-torch.json`, completing the OWL-ViT model offerings. The model uses the same wrapper …
=> Add OWL-ViT base-patch32 to zoo manifest

docs/source/user_guide/using_datasets.rst, fiftyone/core/collections.py, fiftyone/utils/data/base.py, plugins/operators/__init__.py, tests/unittests/utils_tests.py, tests/unittests/view_tests.py
The original goal of this PR was to update the builtin `edit_field_values` operator so that it could be applied to views that filter label fields (cf [FOEPD-1474](https://voxel51.atlassian.net/browse/FOEPD-1474)). This is achieved ✅ 
The underlying technical need to achieve that goal was to have an alternative to the `view.map_values(path, map).save(root)` pattern that can be safely applied when `view` filters the `root` field. In that case, we need to use either `set_label_values()` or `set_values()` as appropriate to perform the field edits as individual DB ops.
Achieving this technical need led me down a deeply satisfying rabbit hole of optimizing some of our core batch edit methods:
1. Added a new syntax to `set_label_values()` that allows users to provide sample IDs in addition to …
=> FOEPD-1759: Add optimized syntaxes for `set_values()`, `set_label_values()` and `map_values()` 

fiftyone/server/utils.py, plugins/operators/model_evaluation/__init__.py, plugins/panels/model_evaluation/__init__.py
The goal behind `fosu.load_and_cache_dataset()` and `fosu.cache_dataset()` is to ensure that `Dataset` objects are cached + reused between async calls in features like Embeddings and Model Evaluation panels that load potentially expensive brain/evaluation results and cache them on the `Dataset` object so that they are only loaded once (per pod, at least).
Note that we want the above behavior **even when** singletons are disabled for other use cases, which as of https://github.com/voxel51/fiftyone/pull/6161 they will now be in all App server + plugin contexts by default.
Disclaimer: I have not fully tested this PR, but I believe that it applies the desired logic.
=> Ensure that run results are cached + reused

fiftyone/zoo/models/manifest-torch.json
This PR adds the missing `size_bytes` field for three models in the manifest that previously had this field set to `null`. The byte sizes were obtained by downloading the actual model files from Hugging Face and measuring their exact sizes.
Tested by downloading each model using the Hugging Face Hub API and verifying the exact file sizes of the `pytorch_model.bin` files. The sizes were confirmed to match the values added to the manifest.
-   [x] Yes. Give a description of this change to be included in the release notes for FiftyOne users.
Fixed missing model size information in the model zoo manifest for vit-base-patch16-224-imagenet-torch, siglip-base-patch16-224-torch, and group-vit-segmentation-transformer-torch models.
-   [ ] App: …
=> add missing model sizes to manifest

fiftyone/zoo/models/manifest-tf.json
Update model categorization to mark TF1 models as legacy as per new model categorization schema. This helps users understand the current support status of these models.
Adds the "legacy" tag to all TensorFlow 1.x models in the `voxel51-tf-models.json` file. This update reflects the deprecated status of TF1 and ensures users are aware these models are no longer actively maintained.
Manually verified that:
- All TF1 models (identified by "tf1" tag or tensorflow<2 requirements) now include the "legacy" tag
- The JSON file remains valid
- Model zoo loads correctly with the updated tags
TensorFlow 1.x models in the model zoo are now marked as …
=> Add legacy tag to TF1 models in model zoo

fiftyone/zoo/models/manifest-torch.json
Fixed incorrect size_bytes value for convnext-xlarge-224-torch model.
Was: 31647540445603633486 bytes (31.6 exabytes - impossible)
Now: 1400917137 bytes (1.4 GB - verified from source)
This PR fixes a data entry error in the FiftyOne model zoo configuration for the ConvNeXt-XLarge model. The `size_bytes` field contained an impossible value of approximately 31.6 exabytes (31,647,540,445,603,633,486 bytes), which is corrected to the actual file size of 1.4 GB (1,400,917,137 bytes).
The correct file size was verified by:
1. Downloading the model from the official HuggingFace repository (facebook/convnext-xlarge-224-22k-1k)
2. Checking the pytorch_model.bin file size via HTTP headers
3. Cross-referencing with the model's parameter count (~350M) and comparing with other ConvNeXt variants …
=> correct ConvNeXt-XLarge model file size from 31.6EB to 1.4GB

fiftyone/zoo/models/manifest-torch.json
Added OWL-ViT large model with patch14 configuration:
- `owlvit-large-patch14-torch`
The model:
- Uses existing `FiftyOneZeroShotTransformerForObjectDetection` wrapper
- Supports both CPU and GPU inference
- Performs zero-shot object detection using text queries  
- Successfully extracts embeddings for similarity matching
- Provides ViT-L/14 backbone for improved accuracy over base models
OWL-ViT large-patch14 extends our zero-shot detection offerings by providing a higher-capacity model (compared to base) with improved accuracy, especially for smaller objects and complex scenes.
This PR adds the OWL-ViT large-patch14 model configuration to `fiftyone/zoo/models/manifest-torch.json`, extending our OWL-ViT offerings with a large variant. The model uses the same wrapper class as the existing …
=> Add OWL-ViT large-patch14 model to zoo (manifest-torch.json)

.github/workflows/build-docs.yml, docs/README.md, docs/source/_static/css/custom.css, docs/source/_static/js/custom.js, requirements/dev.txt, requirements/docs.txt
Addresses feedback received by @brimoor and @AdonaiVera :
* Removed class and method names from the module tree at the top of each API reference page.
* Restored newline spacing after media content blocks.
* Re-applied background color and padding to code blocks with line numbers.
* Fixed missing `pushfeedback.css` on child pages.
* Resolved rebase conflicts introduced in https://github.com/voxel51/fiftyone/commit/be5889872e0b820df117b574105f0ce498f88d8b.
* Fixed GitHub Pages script to include `requirements/commons.txt`.
Built the docs locally and verified all the changes are rendering as expected.
(Details in 1-2 sentences. You can just …
=> Address docs theme feedback

fiftyone/zoo/models/manifest-torch.json
Fix missing ultralytics package requirement for yolov5x-coco-torch.
Adds the missing `ultralytics` package to the requirements for the `yolov5x-coco-torch` model.
Verified build and that the model can be successfully downloaded and loaded after this change.
Fixed a bug where the `yolov5x-coco-torch` model from the zoo failed to load due to a missing package dependency.
=> Fix missing ultralytics package requirement

docs/source/_static/css/custom.css
Addresses https://github.com/voxel51/fiftyone/pull/6201#issuecomment-3137772116
Local build:
-   [ ] Other
=> Restore docs newline spacing after images

fiftyone/zoo/models/manifest-torch.json
* `segformer-b0-ade20k-torch` (15MB)
* `segformer-b1-ade20k-torch` (55MB)
* `segformer-b2-ade20k-torch` (110MB)
* `segformer-b3-ade20k-torch` (189MB)
* `segformer-b4-ade20k-torch` (256MB)
* `segformer-b5-ade20k-torch` (339MB)
All models:
* Use existing `FiftyOneTransformerForSemanticSegmentation` wrapper
* Support both CPU and GPU inference
* Trained on ADE20K dataset (150 classes)
* MIT licensed
Note: `nvidia/segformer-b0-finetuned-ade-512-512` is already FiftyOne's default segmentation model. This adds the complete model family.
Added 6 SegFormer model configurations to `fiftyone/zoo/models/manifest-torch.json` using the existing transformer wrapper.
Tested all 6 models:
* Loaded from HuggingFace hub
* Performed segmentation on COCO validation images
* Verified mask outputs and model …
=> Add SegFormer Model Family to Zoo

fiftyone/zoo/models/manifest-torch.json
In preparation for documenting each model's training datasets, this PR adds an empty "Training Data" array field to all model entries in the manifest. 
This establishes the schema that will contain:
- Dataset names
- Dataset URLs (where publicly available)
Future PRs will populate these fields with verified information for each model family. No existing fields or formatting have been changed.
This PR adds a new `"Training Data": []` field to all 169 models in the PyTorch model zoo manifest (`manifest-torch.json`). The field is currently an empty array that will be populated in subsequent PRs with structured dataset information. The field is positioned before the `date_added` field in each model entry to maintain logical ordering.
- Automated validation script confirms all 169 models have …
=> Add Training Data field to all model manifest entries

fiftyone/zoo/models/manifest-torch.json
- Change "Apache-2.0" to "Apache 2.0" for consistency
- Affected models: rtdetr-v2-s-coco-torch, rtdetr-v2-m-coco-torch
- Aligns with format used by other Apache-licensed models in the dataset
=> fix: standardize Apache license format in model metadata

fiftyone/zoo/models/manifest-torch.json
This commit populates the `training_data` field established in the previous pull request with verified dataset information for PyTorch model zoo entries. Each entry contains structured dataset references including canonical names and authoritative URLs. 
The `training_data` field in `manifest-torch.json` has been populated with dataset metadata for 163 models. Each populated field contains an array of dataset objects with `name` and `url` properties. Original JSON formatting has been preserved with modifications limited to `training_data` fields. Models utilizing multiple training datasets have all relevant datasets documented.
- JSON schema validation ensures the manifest remains valid
- Manual diff review confirms only `training_data` fields were modified
- FiftyOne builds successfully …
=> populate dataset information for all pytorch zoo models

fiftyone/zoo/models/manifest-tf.json
In preparation for documenting each model's training datasets, this PR adds an empty "Training Data" array field to all model entries in the manifest.
This establishes the schema that will contain:
- Dataset names
- Dataset URLs (where publicly available)
Future PRs will populate these fields with verified information for each model family. No existing fields or formatting have been changed.
This PR adds a new `"Training Data": []` field to all models in the TensorFlow model zoo manifest (`manifest-tf.json`). The field is currently an empty array that will be populated in subsequent PRs with structured dataset information. The field is positioned before the `date_added` field in each model entry to maintain logical ordering.
- Automated validation script confirms all 49 models have the …
=> Add Training Data field to all TF model manifest entries

fiftyone/zoo/models/manifest-torch.json
Add PubMedCLIP zero‑shot image classification model: **pubmed-clip-vit32-zero-shot-torch**
* Uses existing `FiftyOneZeroShotTransformerForImageClassification` wrapper (no new wrappers)
* CPU/GPU inference
* Zero‑shot classification + **512‑D** embeddings
* Public on Hugging Face (MIT license)
* Add `pubmed-clip-vit32-zero-shot-torch` entry to the Torch model zoo (`manifest-torch.json`)
* Local validation: loaded via zoo alias, ran predictions on demo images, confirmed **512‑D** embeddings
* Confirmed model appears in `foz.list_zoo_models()` and loads with zero‑shot prompts
Added **PubMedCLIP (ViT‑B/32)** zero‑shot medical image classifier to the Torch model zoo (public, MIT).
=> Add pubmed-clip-vit32

fiftyone/core/dataset.py
- Optimizes and hardens the implementation of `merge_samples()` when applied to video collections
- [FOEPD-2144](https://voxel51.atlassian.net/browse/FOEPD-2144)
- [FOEPD-413](https://voxel51.atlassian.net/browse/FOEPD-413)
- [FOEPD-443](https://voxel51.atlassian.net/browse/FOEPD-443)
- [FOECS-297](https://voxel51.atlassian.net/browse/FOECS-297)
The new behavior is functionally identical to the previous implementation, but much faster and without the possibility of "duplicate key" runtime errors 🎉 
The previous implementation was suboptimal for a number of reasons:
- a temporary `_merge_key` was populated on all frames of the source and destination collections ❌ 
- unique indexes on `(_merge_key, frame_number)` were created ❌ 
- these fields + indexes needed to be deleted when the merge …
=> Optimize and harden `merge_samples()` on video collections
