.github/workflows/chromatic.yml

The initial App design shipment has been released, and the working branch `team-setup` is no longer needed in the Chromatic workflow.
N/A

Remove deleted branch from Chromatic workflow PR branches

---

electron/app/components/ViewBar/ViewStage/viewStageMachine.ts

A regression fix to the `viewStageMachine` of the `ViewBar`. Currently, users cannot add stages to an existing view with more than one stage when the stage being added has more than one parameter.
A test framework has not been established for the App, yet.
Allow completing a new ViewStage in the ViewBar when more than one ViewStage already exists and the new ViewStage being added has more than one parameter. Previously, the ViewStage would fall back to stage selection.
-   [ ] …

App: Fixes adding ViewStages to the ViewBar

---

electron/app/utils/tile.ts

Fit the last row to match the tiling threshold when tiling.
A test framework for the App does not exist, yet.
Consistently size the last row of samples in the sample listing.
section
notes
-   [x] `bug-fix` - A user-facing bug fix worth mentioning in the release …

App: Fit last row to match tiling threshold in samples list

---

fiftyone/core/session.py
tests/isolated/server_tests.py

Some logic seems to have been written  in the `Session` class that ignored `StateDescription` updates from other clients (the App, in this case). This fixes that. So we now have true bidirectional state communication between a `Session` and the App.
I have removed the session singleton restriction in service of writing tests, primarily, although I can tweak that because it could certainly cause issues in messy scripting by users due to the asynchronous nature of these updates.
A basic test has been added to the server tests. Dataset and view checks are included in the test.
Feature
* `Session` is no longer a singleton, i.e. more than one …

Fix session updates from App changes

---

docs/source/user_guide/using_datasets.rst
fiftyone/__public__.py
fiftyone/core/cli.py
fiftyone/core/dataset.py
tests/unittests.py

Renames `fo.list_dataset_names()` to `fo.list_datasets()`.
The latter is cleaner, fewer characters, and also more consistent with other methods like `fo.load_dataset(name)` and `foz.load_zoo_dataset(name)`, which take dataset names as input but don't say, for example, `fo.load_dataset_by_name()`, which is unnecessary.

Renaming list_dataset_names() to list_datasets()

---

fiftyone/core/collections.py
fiftyone/core/stages.py

Makes `view.select("5f33069b96cd78e8c41a6fcb")` and `view.exclude("5f33069b96cd78e8c41a6fcb")` do the right thing.
Previously an error would be raised because "5f33069b96cd78e8c41a6fcb" was being converted to `["5", "f", ..., "b"]` and then MongoDB was complaining that ObjectID's must be 24 characters.
Humorously, the `_params` methods of these stages _already_ documented that either `list` or `str` inputs are permitted, which wasn't quite true yet.

Allowing a single sample ID in Select() and Exclude() stages

---

fiftyone/core/sample.py

Easy fix!
Here's the code to test it:
```python
sample = fo.Sample(filepath="image1.jpg", test_field1="testing")
print("test_field1" in dir(sample)) # True
print("test_field2" in dir(sample)) # False
sample["test_field2"] = 51
print("test_field1" in dir(sample)) # True
print("test_field2" in dir(sample)) # True
```
Closes #366

Adding sample fields to `dir(Sample)`

---

fiftyone/zoo/__init__.py

**BEFORE**
```py
dataset.name  # cifar10-test
```
**NOW**
```py
dataset.name  # cifar10-test
other_dataset = foz.load_zoo_dataset("cifar10", split="test", dataset_name="other-cifar10-test")
other_dataset.name  # other-cifar10-test
```
**FUTURE**
(after https://github.com/voxel51/fiftyone/pull/407 is finished)
```py
dataset.name = "cifar10-test-sandbox"
other_dataset = foz.load_zoo_dataset("cifar10", split="test")
other_dataset.name  # cifar10-test
```

Allowing zoo datasets to be loaded with custom names

---

fiftyone/core/dataset.py

Wow! we need to drop `mongoengine` asap! I just replaced the `mongoengine` querying in `Dataset.iter_samples()` with effectively the same thing in `pymongo` and it's almost 10X as fast. This is such a basic operation. Who knows what other things are unnecessarily slow...
```python
import time
dataset = fo.load_dataset("oibenchmark")
NUM_SAMPLES = 10
start = time.time()
iterator = dataset.iter_samples()
samples = []
for i in range(NUM_SAMPLES):
samples.append(next(iterator))
print("Dataset.iter_samples: %f" % (time.time() - start))
start = time.time()
iterator = dataset.view().iter_samples()
samples = []
for i in range(NUM_SAMPLES):
samples.append(next(iterator))
print("DatasetView.iter_samples: %f" % (time.time() - start))
start = time.time()
iterator = …
```

Dataset.iter_samples() 10X faster

---

fiftyone/core/utils.py
fiftyone/utils/eval/coco.py
fiftyone/zoo/torch.py
requirements/common.txt
setup.py

Addresses user feedback from Slack community:
> Hey, I had installed fiftyone. Then when I tried running the sample script in #announcements channel, I got the pycocotools import error (ImportError: The requested operation requires that 'pycocotools' is installed on your machine). I then fixed this with : pip install "git+https://github.com/philferriere/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI". In the next attempt, the script seems to be downloading the coco dataset (Downloading images zip to '/home/kritik/fiftyone/coco-2017/tmp-download/val2017.zip'). Perhaps the download progress should also be shown since it has not been downloaded in the past 10-15min and I cant figure out if it is working or not
Specifically, adds `pycocotools` as an explicit dependency (it's small), and …

Including pycocotools as explicit dependency

---

electron/app/components/ViewBar/ViewBar.tsx
electron/app/components/ViewBar/ViewStage/ErrorMessage.tsx
electron/app/components/ViewBar/ViewStage/ViewStage.tsx
electron/app/components/ViewBar/ViewStage/ViewStageParameter.tsx
electron/app/components/ViewBar/ViewStage/viewStageMachine.ts
electron/app/components/ViewBar/ViewStage/viewStageParameterMachine.ts
electron/app/components/ViewBar/viewBarMachine.ts
electron/app/shared/colors.ts

Stability improvements, more flexible parameter and stage editing, and a small set of keyboard shortcuts. A couple non-ideal behaviors (mostly with styles) have arise with these changes, but I think the pros outweigh the cons. They will be fixed with the next ViewBar PR.
Locally tested.
Features
* Initial keyboard shortcuts
* TAB, ENTER, and ESC submit parameters, and submit the stage or focus the next parameter depending on what has been filled out
* DEL and BACKSPACE delete the active stage
* ESC toggles ViewBar focus
* LEFT and RIGHT ARROW traverse stages and add buttons
* SHIFT LEFT and SHIFT RIGHT ARROW traverse stages
* General …

View bar feedback part 2

---

fiftyone/core/cli.py
fiftyone/core/dataset.py
fiftyone/core/odm/dataset.py

Fixes a bug in `Dataset.clone(name)` where a default dataset name was not being generated if `name == None` was passed.
Also, prevents dataset names from being `None`, which, along with the work in https://github.com/voxel51/fiftyone/pull/407, completely resolves https://github.com/voxel51/fiftyone/issues/205.
```py
dataset.name = None  # raises an error, does not change `dataset.name`
```

Preventing `None` dataset names

---

fiftyone/core/collections.py
fiftyone/core/expressions.py
fiftyone/core/stages.py

The App links directly into the docs when help icons for view bar stages are clicked. This PR adds plenty of examples to help the user understand how to use the various stages.

Adding View stage examples to docs

---

docs/source/user_guide/dataset_creation/zoo.rst
fiftyone/core/cli.py
fiftyone/core/utils.py
fiftyone/zoo/__init__.py
fiftyone/zoo/tf.py
fiftyone/zoo/torch.py

Previously the error would simply say "the requested operation requires that PyTorch is installed". Now it provides some more context specifically relating to the dataset zoo, and links into the docs for more details.
Experience when trying to download the `fashion-mnist` dataset from the zoo with no ML backends installed:
```shell
$ fiftyone zoo download fashion-mnist
Downloading split 'test' to '/Users/Brian/fiftyone/fashion-mnist/test'
Uncaught exception
...
ModuleNotFoundError: No module named 'torch'
The above exception was the direct cause of the following exception:
...
ImportError: 
You tried to download a dataset from the FiftyOne Dataset Zoo using the PyTorch
backend, but you do not have the necessary packages …
```

Display a friendly error when using the dataset zoo with no ML backend installed

---

fiftyone/core/utils.py
fiftyone/utils/eval/coco.py
fiftyone/zoo/torch.py
requirements/common.txt
setup.py

This package has C code but no wheels, so it's the only dependency that requires a compiler on all supported platforms, including Windows. Making it optional will make the installation process easier for Windows users.
This reverts #410 (commit 99d68df51149228931f32ab083fc37acdda74881).
Conflicts:
fiftyone/core/utils.py
See above
Not yet, waiting for build
Unsure
-   [ ] `App`: FiftyOne application changes
-   [x] `Core`: Core `fiftyone` Python library changes
-   [ ] `breaking-change` - The PR will be mentioned …

Revert "installing pycocotools by default"

---

README.md
WALKTHROUGH.md

Adds a "Getting Started with FiftyOne" walkthrough to the repo.
This is the script for a walkthrough video that I produced, and I thought it made sense to include this in the repo. It's similar to a tutorial, but doesn't go into as much detail on any one point. It also provides some more contextual motivation for the tool at the beginning.
This may ultimately wind up in the docs, we'll see.

Adding getting started walkthrough

---

electron/app/components/CheckboxGrid.tsx
electron/app/components/Player51.tsx

An option to hide/show confidence on detections and classifications
(most changes are in player51)
Closes #439 
Locally with {Classification,Detection}{,s}
See above
section
-   [x] `feature` - A new user-facing feature worth mentioning in the release
notes
-   [ ] `bug-fix` - A user-facing bug fix worth mentioning in the release notes
- …

Add option to display confidence

---

fiftyone/core/service.py
fiftyone/service/main.py

* Added error handling in `_wait_for_child_port`, specifically to address an error seen in https://github.com/voxel51/fiftyone/runs/1038315825#step:10:22. I'm unsure why an `AccessDenied` error would be raised for accessing a child process, but this should handle any psutil errors in a reasonable way now.
*  Changed the order in which subprocesses are terminated in an effort to fix an issue where a dev instance of the app would sometimes leave blank windows behind.
Ran `fiftyone app launch` several times to reproduce the second point, was unable to reproduce after https://github.com/voxel51/fiftyone/commit/20e732926348af796e77e24f25738594183bd9bc
Probably not

subprocess error handling improvements

---

docs/source/getting_started/install.rst
docs/source/index.rst
docs/source/user_guide/app.rst

Also fixes typo on main page 😓 and tweaks the remote session instructions.
**BEFORE**
**AFTER**
(Quickstart has its own section, and the note is simpler to read)

Highlight quickstart on install page

---

electron/app/components/CheckboxGrid.tsx
electron/app/components/DisplayOptionsSidebar.tsx
electron/app/components/DropdownCell.tsx
electron/app/components/DropdownHandle.tsx
electron/app/components/Filter.tsx
electron/app/components/ImageContainerHeader.tsx
electron/app/components/JSONView.tsx
electron/app/components/Player51.tsx
electron/app/components/Sample.tsx
electron/app/components/SampleModal.tsx
electron/app/components/Samples.tsx
electron/app/components/ViewBar/ViewStage/SearchResults.tsx
electron/app/containers/Dataset.tsx
electron/app/containers/SamplesContainer.tsx
electron/app/recoil/atoms.ts
electron/app/recoil/selectors.ts
electron/app/utils/colors.ts
electron/app/utils/labels.ts

Initial changes to the filtering controls for the sample modal. The underlying motivation is to be consistent with the UI components and design patterns displayed to the user. An obvious benefit is it reduces the number of controls a user has to learn. 
Any field that is not a list is handled somewhat differently than in the image grid display options, as displaying an aggregate value does not make sense. There is only one value. Instead, a checkmark or "x" is used to indicate existence. Or the value itself, if it is a `scalar` field.
TODOs:
-  [ ] test
-  [ ] display `label` value for `fo.Classification` if the value exists
-  [ ] fix regression in image grid sticky nav. it does not always stick at the moment
No App test framework. Still needs more human testing.
Display Options have …

Display options in the sample modal

---

electron/app/components/CheckboxGrid.tsx
electron/app/components/Player51.tsx
electron/app/components/SampleModal.tsx
electron/app/utils/labels.ts

Added support for displaying detections, as well as some corresponding player51-side changes to enable the relevant options to be configured more flexibly from the fiftyone side.
Closes #452 (except for overflow behavior, which should probably be split into a separate issue)
Locally, with a couple test datasets
Above
section
-   [x] …

Detection attribute display

---

electron/app/containers/App.tsx

Adds the port form modal back to `App.tsx`.
Locally.
section
notes
-   [ ] `bug-fix` - A user-facing bug fix worth mentioning in the release notes
-   [ ] `documentation` - A user-facing documentation change worth mentioning
in the release notes

Add back port form modal

---

.github/ISSUE_TEMPLATE/bug_report_template.md
.github/ISSUE_TEMPLATE/documentation_issue_template.md
.github/ISSUE_TEMPLATE/feature_request_template.md
.github/ISSUE_TEMPLATE/installation_issue_template.md
.github/pull_request_template.md

Changes for a couple things I've noticed with the existing templates:
- The changelog category options didn't match up to the ones used in the changelog
- People without write access to the repo can't add labels to issues, so the templates shouldn't suggest it
n/a
-   [ ] `App`: FiftyOne application changes
-   [x] `Other`

Adjust issue/PR templates

---

.github/workflows/build.yml
tests/unittests.py

Added a matrix entry to run tests on Windows. Other than installation, only one test was failing!
Note that this is considerably slower on Windows (as of the last run, a bit over 9 minutes, vs. 5 minutes on Linux). The zoo test seems to account for a decent amount of this (maybe disk I/O is slower on the Windows runners?), so we could disable that on Windows or try to cache whatever it downloads somehow.
I also disabled Python 3.5 on Windows because I didn't think it was necessary, although I'm open to discussion there. My experience is that Windows users are somewhat more likely to have a more recent Python version installed, and previous test-related issues we've had haven't been specific to Windows *and* Python 3.5.
GitHub tested it for me.
-   [x] No. You can skip the rest of this …

GitHub actions: test on Windows

---

electron/app/components/SampleModal.tsx

Resolves #490. This is probably not the best practice solution, but `e.stopPropagation()` did not work, and `e.preventDefault()` did too much.
Locally
Arrow key navigation is now disabled in the sample modal when using editing in a label filter input.
-   [ ] Other

Prevent modal navigation when an input is in focus

---

docs/source/user_guide/dataset_creation/datasets.rst
docs/source/user_guide/export_datasets.rst
fiftyone/types/dataset_types.py
fiftyone/utils/coco.py

Closes https://github.com/voxel51/fiftyone/issues/500.
The `COCODetectionDataset` format will now load the `categories` dict from COCO labels and use it (if present) to populate a `supercategory` attribute on each detection.
The `categories` field of the COCO labels is stored in the dataset's `info` field, so that this information can be included (if available) when exporting datasets in `COCODetectionDataset` format.
Test code:
```py
export_dir1 = "/tmp/coco-export1"
export_dir2 = "/tmp/coco-export2"
#
#
#
dataset = foz.load_zoo_dataset("coco-2017", split="validation")
#
#
dataset.limit(1).export(export_dir1, fo.types.COCODetectionDataset)
#
#
dataset1 = fo.Dataset.from_dir(export_dir1, fo.types.COCODetectionDataset) …
```

Import/export COCO categories

---

electron/app/components/SampleModal.tsx

Followup to #499 - allows arrow keys to work immediately after clicking a checkbox, but not when using a slider (since arrow keys also adjust sliders)

Sample modal focus tweaks

---

fiftyone/core/expressions.py
tests/unittests.py

Fixed some escaping issues:
* `\` was not properly escaped, so it could not be matched.
* Also, `[` needed to be escaped to avoid a warning in Python 3.7+: https://bugs.python.org/issue30349
An example of this warning:
```
fiftyone/core/expressions.py:769: FutureWarning: Possible nested set at position 2
_escape = lambda s: re.sub(r"([%s])" % "".join(regex_chars), r"\\\1", s)
```
Added a test (see diff)
Unlikely that anyone has run into this yet
-   [ ] Documentation: FiftyOne documentation …

Fix matching some special characters in string fields

---

electron/app/components/ImageContainerHeader.tsx
electron/app/components/Sample.tsx
electron/app/components/Samples.tsx
electron/app/components/SelectionMenu.tsx
electron/app/components/Tags/DropdownTag.stories.tsx
electron/app/components/Tags/DropdownTag.tsx
electron/app/components/Tags/Menu.tsx
electron/app/containers/App.tsx
electron/app/recoil/atoms.ts
electron/app/shared/colors.ts
fiftyone/server/main.py

A new menu that allows some basic operations to be performed from the UI
Clearing is new (and could only be done previously by manually unselecting everything). The other two can also be done by creating stages from Python. Note that they are implemented by creating view stages for simplicity.
Closes #391
Related: #113 
Local testing
-   [X] Yes. Give a description of this change to be included in the release
Added the ability to clear, select, and exclude the selected samples from the app
-   [ ] Other

Selection options

---

fiftyone/core/collections.py
fiftyone/core/odm/sample.py
fiftyone/core/stages.py
fiftyone/utils/data/base.py
fiftyone/utils/data/exporters.py

Adds support for exporting `Classification` labels in `Detections` format.
For example, you can now export CIFAR-10 in COCO format:
```py
dataset.take(10).export("/tmp/cifar10-in-coco-format", fo.types.COCODetectionDataset)
```
Output:
```
UserWarning: Dataset exporter expects labels in <class 'fiftyone.core.labels.Detections'> format, but found <class 'fiftyone.core.labels.Classification'>. Converting labels to detections whose bounding boxes span the entire image
100% |███████████████████████| 10/10 [71.5ms elapsed, 0s remaining, 139.9 samples/s]     
```
There is also a `fiftyone.utils.data.convert_classification_field_to_detections()` method that allows for explicit conversion of a …

Adding support for exporting classification labels in detection format

---

fiftyone/core/cli.py
fiftyone/core/session.py
tests/session_tests.py
tests/utils/session_helper.py

* Fixes #281 by attempting to detect when a session is destroyed soon after it is created and printing a message suggesting the use of `.wait()`.
* Fixes #451 by allowing `.wait()` to work for remote sessions. See the issue for rationale. Note that this never returns under normal circumstances, so a warning about that might be helpful.
Tests + some additional local testing
Added support for calling `wait()` on remote sessions
(The other point from above may not be worth mentioning, since it's fairly self-explanatory to anyone who sees the message)
-   [ ] Build: Build and test infrastructure …

Session.wait(): add support for remote sessions and attempt to detect when it should be used

---

electron/app/components/JSONView.tsx
electron/app/components/Player51.tsx
electron/app/components/SampleModal.tsx
electron/app/recoil/selectors.ts
electron/app/utils/labels.ts

Ability to filter the JSON view. Closes #387.
This is enabled by default when opening the modal, but can be disabled.
Locally
-   [X] Yes. Give a description of this change to be included in the release
Title
-   [ ] Other

Add support for filtering sample JSON

---

electron/app/components/Player51.tsx
electron/app/components/Sample.tsx
electron/app/utils/hooks.ts

Some responsiveness improvements when selecting images.
Note that removing the custom click/double-click logic causes images to sometimes briefly display as selected/unselected when opening the modal by double-clicking on them. Their actual state doesn't change, as the click event fires twice in this case. This is a tradeoff that needs to be made to improve single-clicking speed, and is worth prioritizing since double-clicking will eventually be replaced.
Locally
Made selecting samples in the app faster
-   [ ] Core: Core `fiftyone` Python …

Speed up image selection

---

electron/app/components/ViewBar/ViewStage/ViewStageParameter.tsx
electron/app/components/ViewBar/ViewStage/viewStageMachine.ts
electron/app/components/ViewBar/ViewStage/viewStageParameterMachine.ts
electron/app/components/ViewBar/viewBarMachine.ts
fiftyone/core/stages.py

Switches view stage parameter placeholders to user-friendly hints. Type annotations are retained in error messages.
Follows:
```
Exclude: list,of,sample,ids
ExcludeFields: list,of,fields
Exists: field
FilterClassifications: field and (blank)
FilterDetections: field and (blank)
Limit: int
Match:  (blank)
MatchTag: tag
MatchTags: list,of,tags
Mongo: (blank)
Shuffle: seed (default=None)
Select: list,of,sample,ids
SelectFields: list,of,fields
SortBy: field and reverse (default=False)
Skip: int
Take: int and seed (default=None)
```
Locally.
Friendly parameter placeholders that describe valid view stage parameter inputs.
-   [x] App: FiftyOne …

App::ViewStageParameter: Simpler parameter placeholders

---

docs/source/_static/css/custom.css
docs/source/_static/css/voxel51-website.css
docs/source/_templates/layout.html
docs/source/conf.py
setup.py

Updates for the docs header to match voxel51.com
Note that the "Try FiftyOne" button is left out here, because it links to a page which links to the installation page, which is already linked directly in the sidebar on all docs pages. Open to alternatives, though.
Once https://github.com/voxel51/fiftyone/runs/1097314125 is done, you can get a pre-built copy by downloading the docs.zip artifact.
Local build
-   [ ] Core: Core …

Docs header updates

---

electron/app/components/DisplayOptionsSidebar.tsx
electron/app/components/JSONView.tsx
electron/app/components/utils.tsx
electron/app/shared/global.ts

Some scrollbar styling:
They're only shown on hover. Making them fade in gradually is apparently very hard. I also wasn't able to make the background when the scrollbar is hidden match both the header background and grid background, so I opted for the latter.
Locally
-   [X] No. You can skip the rest of this section.
-   [ ] Other

Style scrollbars

---

fiftyone/core/state.py
tests/isolated/server_tests.py

Skips bounds calculations when there are no fields that need bounds to calculated. Previously, an empty dataset would fail to load in the App because the server would fail to calculate these bounds and the state would never get sent to the app.
MongoDB expects at least one entry (pipeline) in a `$facet` stage.
`step_empty_derivables()` in `isolated/server_tests.py`.
Datasets without numeric scalars or labels will now successfully load in the App.
-   [ ] Documentation: FiftyOne documentation …

Server: Skip bounds calculations when no fields are present

---

fiftyone/utils/coco.py

The COCO Importer currently looks at all the files in the `data/` directory to determine the dataset's filenames.  However, this is unnecessary as the filenames are already specified in the `labels.json`'s images (which are saved as the keys to `_images_map`).  Furthermore (as in my case), any extra files in `data/` will mess with the import.  I believe any files not listed in `labels.json` should be ignored by the importer.
Assuming `labels.json` specifies all the correct filenames, this should not break anything.  It allows for `data/` directories with extra files, as well as `data/` directories of different structures, such as ones with sub-directories.
I have tested this patch locally with a few of my own datasets, but not sure if there's a test case that covers this... Let me know if …

Update COCO importer to use label.json filenames

---

electron/app/recoil/selectors.ts

* Fixed an error when a view was empty
* Some selectors could throw errors when switching between empty and non-empty views. This tended to happen in development when the server and app live-reloaded at the same time, and not always predictably. These changes should cut down on the number of "oops" screens seen during development, even if they wouldn't come up in normal use.
Locally - verified directly that some changed selectors are still getting called and working
(first point above)
-   [ …

Fix some errors related to empty datasets/views

---

fiftyone/core/dataset.py
fiftyone/core/sample.py
tests/unittests.py

Adds support for merging datasets by joining on `filepath`.
This allows, for example, to merge two copies of a dataset that contain predictions from two different versions of a model in appropriately named (i.e., different) label fields into a single dataset with two label fields.
```py
_zoo_dataset = foz.load_zoo_dataset("cifar10", split="test")
dataset.add_samples(_zoo_dataset.take(10))
_dataset = fo.Dataset()
_dataset.add_samples(dataset.take(5))
_dataset.add_samples(
_zoo_dataset
.match(
~F("filepath").is_in([s.filepath for s in dataset.select_fields()])
).take(5)
)
_dataset.rename_field("ground_truth", "predictions")
_dataset.compute_metadata()
dataset.merge_samples(_dataset) …
```

Adding support for merging dataset contents

---

.github/workflows/build.yml

Intended to be used as a job that is required for PRs to be merged.
Currently, PRs cannot be merged because both "test" and "test (ubuntu-18.04, 3.8)" (as well as others in the test matrix) are required. These criteria are impossible to meet because "test" is only present when tests are skipped (e.g. on draft PRs), and the others are only present when tests are run. Requiring the "publish" job apparently does not work either because it is skipped even when tests fail.

GitHub actions: add another job that requires all tests to pass

---

fiftyone/server/json_util.py
tests/isolated/server_tests.py

Resolves #556. This is not the cleanest solution, but currently we rely on MongoEngine for field serialization, and changing that would be quite the lift.
A check has been added to the encoder step in the server tests.
NumPy arrays are now serialized and sent to the App. Previously, an error was raised by the server when a dataset contained `VectorField`s or `ArrayField`s. 
-   [ ] Other

Serializes numpy arrays as lists for server

---

WALKTHROUGH.md
docs/source/tutorials/evaluate_detections.ipynb
docs/source/user_guide/basics.rst
docs/source/user_guide/using_datasets.rst
fiftyone/__public__.py
fiftyone/core/labels.py
fiftyone/core/utils.py
fiftyone/utils/kitti.py
fiftyone/utils/tf.py

Closes https://github.com/voxel51/fiftyone/issues/567.
The issue is that bounding boxes were previously stored as `VectorField`s, which were serialized to the DB as lists but then loaded as numpy arrays. Now that `VectorField`s are always serialized as numpy arrays, bounding boxes need to be represented as `ListField`.
Fortunately, this change is backwards compatible with any datasets that may exist out in the wild. The next time a user loads their dataset, `bounding_box` will be a list instead of a numpy array in-memory, but the documentation already implies that bounding boxes are, in fact, stored as "lists", so it should be fine.

Fixes bounding box bug

---

fiftyone/core/dataset.py
fiftyone/core/sample.py
fiftyone/core/view.py

```py
import fiftyone.zoo as foz                                                                                                                                                   
print(dataset)
```
```
Name:           quickstart-video
Media type      video
Num samples:    10
Persistent:     False
Info:           {'description': 'quickstart-video'}
Tags:           []
Sample fields:
media_type: fiftyone.core.fields.StringField
filepath:   fiftyone.core.fields.StringField
tags:       fiftyone.core.fields.ListField(fiftyone.core.fields.StringField)
metadata:   fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.metadata.Metadata)
frames:     fiftyone.core.fields.FramesField
Frame fields:
frame_number: …
```

Including frame field schemas in summaries for video datasets/views

---

fiftyone/core/dataset.py
fiftyone/utils/data/importers.py

Existing datasets on disk in `FiftyOneDataset` format may not have the `media_type` key in their `metadata.json` files. This PR makes that field optional.

Allowing missing media_type when importing FiftyOneDataset

---

docs/source/user_guide/using_views.rst
electron/app/components/Filter.tsx
fiftyone/core/collections.py
fiftyone/core/stages.py
fiftyone/server/main.py

Works like a charm:
```py
DATASET_DIR = "/path/to/bdd100k/validation"
dataset = fo.Dataset.from_dir(
DATASET_DIR,
fo.types.BDDDataset,
expand=True,
shuffle=True,
max_samples=25,
)
session.view = dataset.filter_polylines("polylines", F("label") == "lane")
session.view = dataset.filter_polylines("polylines", F("label") == "drivable area")
```

Adding support for filtering polylines and keypoints

---

docs/source/recipes/draw_labels.ipynb
docs/source/user_guide/config.rst
docs/source/user_guide/draw_labels.rst
fiftyone/core/collections.py
fiftyone/core/config.py
fiftyone/core/frame.py
fiftyone/core/utils.py
fiftyone/utils/annotations.py

Labels can now be rendered on video samples.
See the new video section of the drawing labels recipe for more details.
Example usage:
```py
import fiftyone.utils.annotations as foua
ANNO_PATH = "/tmp/video-anno.mp4"
ANNO_DIR = "/tmp/video-anno"
dataset = foz.load_zoo_dataset("quickstart-video", max_samples=5)
foua.draw_labeled_video(sample, ANNO_PATH)
dataset.take(2).draw_labels(ANNO_DIR)
```

Add support for drawing labels on video samples

---

.github/workflows/build-docs.yml
.github/workflows/build.yml
package/gui/setup.py
tests/utils/command_wrapper.py
tests/utils/github_actions_flags.py
tests/utils/setup_config.py

* Some integration tests that run variations of `fiftyone quickstart`. These currently only run on release branches, but the logic could be customized to also run on commits matching a certain message, for instance. They also only test the backend currently (the app is replaced by a stub that immediately exits).
* Some additional test cleanup - fixed a couple warnings due to GitHub deprecating `set-env`, and a potential issue that could cause subprocesses to not shut down cleanly.
Several GitHub actions runs 
-   [x] Build: Build and test infrastructure changes
-   [ ] Core: Core `fiftyone` …

GitHub actions: test quickstart

---

fiftyone/core/_sample.py
fiftyone/core/dataset.py
fiftyone/core/document.py
fiftyone/core/fields.py
fiftyone/core/frame.py
fiftyone/core/frame_utils.py
fiftyone/core/odm/frame.py
fiftyone/core/odm/mixins.py
fiftyone/core/odm/sample.py
fiftyone/core/sample.py

Change log:
- Renames `fiftyone.core._sample._Sample` to `fiftyone.core.document.Document`, to reflect the fact that this class is a base class for all user-facing objects backed by documents in the DB
- Adds a `Document.merge()` method for merging fields of arbitrary `fiftyone.core.document.Document` instances together
- Updates `Dataset.merge_samples()` to properly merge the frame-by-frame contents of video samples
- Fixes a bug where `sample.copy()` would not create a copy of the `frames` of a video sample
- Adds a variety of usability improvements to `sample.frames` for video samples, including:
- `print(sample.frames)` will print the actual frame contents (`repr(sample.frames)` still just shows # frames, for readability)
- `frame_number in sample.frames # True/False` now works
- Adds …

Data model improvements

---

requirements/common.txt
setup.py

https://github.com/voxel51/fiftyone/pull/594 added a dependency on `scikit-image` in `fiftyone/utils/coco.py`.
This is also a dependency of (the bleeding edge `develop` of) ETA, so will be implicitly available for future releases. However, for completeness, it should be added as an explicit dependency of `fiftyone` itself.
Unlike `scikit-learn`, this package is pretty small at only 17.2MB for the version I just downloaded, so it shouldn't be an issue to force all users to install this. However, if we don't want this explicit dependency, we could adopt a `fou.lazy_import("skimage.measure")` strategy for importing this library JIT, as per things like `pycocotools`.

Adding scikit-image as dependency

---

fiftyone/core/collections.py
fiftyone/core/state.py
fiftyone/utils/data/parsers.py

Label counts are not computed on `develop` for video datasets . This fixes that.
Introduced by https://github.com/voxel51/fiftyone/commit/114351f1a38a96143cb631eb3215a0ec90138bac.
Locally.

Fix label counts for video datasets in the App

---

docs/source/user_guide/using_views.rst
fiftyone/core/collections.py
fiftyone/core/stages.py

Adds a boolean `only_matches` parameter to all filter stages that enables the user to specify that a view should only contain samples that match the given filter.
The typical use case for this is to do something like `filter_detections(..., only_matches=True)`, which only returns samples with at least one detection that matches the provided filter.
For example, using `only_matches=True` allows the `match()` stage below to be removed:
```py
dataset = foz.load_zoo_dataset("coco-2017", split="validation")
person_view1 = (
dataset
.filter_detections("ground_truth", F("label") == "person")
.match(F("ground_truth.detections").length() > 0)
)
person_view2 = dataset.filter_detections(
"ground_truth", F("label") …
```

Adding support for only including samples that match filters

---

fiftyone/core/dataset.py
fiftyone/core/frame.py

Adds an optional `insert` flag to the private `fiftyone.core.Frames._save()` method.
This flag can be used to use `insert_many` when we are sure that the frames are new and can be inserted (not replaced).

Allow for insertion case when saving frames

---

electron/app/components/SampleModal.tsx
electron/app/recoil/selectors.ts
fiftyone/core/dataset.py
fiftyone/core/frame.py
fiftyone/core/state.py
fiftyone/server/main.py

This is a very quick approach to supporting sample-level labels for video datasets in the App.
Sample labels are copied into ETA frame labels for player51 visualization, and some checks are made to prevent field name collisions (field names must be unique among the frame schema and sample schema). Collisions are still possible when adding the samples/frames that have already been added to a dataset.
Much, if not all, of this code will be changed or removed when the next iteration of video optimizations are ready. I am hoping to support a field name at the sample level and frame level in the next set of optimizations.

Minimal sample-level labels support for video datasets in the App

---

electron/app/components/Player51.tsx
fiftyone/utils/data/importers.py
fiftyone/utils/video.py

Adding a utility to re-encode the videos in a sample collection so that they will be visualizable in the FiftyOne App.
Example usage of making HMDB51 viewable:
```py
import fiftyone.utils.video as fouv
"hmdb51", split="test", shuffle=True, max_samples=10
)
dataset2 = dataset.clone("hmdb51-mp4")
fouv.reencode_videos(dataset2)
session.dataset = dataset2
```

Adding util to re-encode videos in a sample collection

---

electron/app/containers/App.tsx
electron/app/utils/hooks.ts

Route changes don't always cause the App component to re-render, so not all pageviews were being reported (although at least one per session would be, since useEffect also runs when the component mounts)
Locally + dev GA
-   [ ] Other

Fix hash change detection

---

fiftyone/core/dataset.py
fiftyone/core/labels.py
fiftyone/utils/torch.py
tests/misc/torch_tests.py

Adds a `fiftyone.utils.torch.TorchImagePatchesDataset` dataset that emits tensors of patches extracted from images defined by sets of `Detections` associated with the images.
A test was added to `tests/misc/torch_tests.py` that verifies the functionality, although it must be run manually.
Also includes two other minor things:
- makes `sample_parser` arg optional for methods like `Dataset.ingest_images()`, where the typical case is to directly pass in  images (for which the default `ImageSampleParser` works just fine)
- Allows `Polyine.to_detection()` and `Detection.to_polyline()` to ignore instance masks

Adding utils for working with image patches in Torch

---

fiftyone/core/expressions.py
fiftyone/core/labels.py
fiftyone/core/odm/document.py
fiftyone/core/stages.py
fiftyone/utils/selection.py

Closes https://github.com/voxel51/fiftyone/issues/636.
Introduces a `fiftyone.core.expressions.ObjectId` class that can be used to refer to object IDs when constructing `ViewExpression`s, which must be JSON serializable (the error message being shown was reasonable; the offending code just needed to be fixed).
Tested by running `pytest tests/misc/selection_tests.py` and verifying that the views created within can be successfully viewed in the App.

Fixing ObjectId bug in selection utils

---

fiftyone/core/collections.py
fiftyone/core/dataset.py
fiftyone/core/expressions.py
fiftyone/core/frame_utils.py
fiftyone/core/stages.py
fiftyone/core/state.py
tests/unittests/view_tests.py

Change log
- Adds a `filter_labels()` view stage that will perform the same action as `filter_classifications/detections/polylines/keypoints` without the user having to hard-code the field type in the stage name
- Adds a `limit_labels()` view stage that can be used to set an upper bound on the number of labels (e.g., detections) you want to see in each field of a sample
- Adds some additional `ViewExpression`s, including `max()`, `min()`, `mean()`, `reverse()`, and `apply()`
Now that `filter_labels()` exists, I wish we could just delete the other `filter_XXX` methods; but I fear that users are likely using those...
There are unit tests for `filter_labels()` and `limit_labels()` in the PR. For the others, I just ran the following:
```py
from …
```

Adding support for filtering generic label fields, limiting labels, and other related expressions

---

electron/app/components/CheckboxGrid.tsx
electron/app/components/Filter.tsx
electron/app/components/SampleModal.tsx
electron/app/components/SelectObjectsMenu.tsx
electron/app/recoil/atoms.ts
electron/app/recoil/selectors.ts
electron/app/utils/context.ts

Closes #644 
The only thing left is to highlight the relevant filters when this control is available - @benjaminpkane what controls that color?
Extension of #637
-   [ ] Other

Allow clearing hidden objects in filter widgets

---

electron/app/components/ImageContainerHeader.tsx

Resolves #652 . Only shows the total when no filtered count has been calculated, or the filtered count is equal to the total count.
Locally.

Only show filtered count when informative

---

electron/app/components/ViewBar/viewBarMachine.ts

Resolves #647. Previously, view equality in the view bar was only informed by `kwargs` and not the classes of the stages. This meant that the view bar considered different stage classes with the same arguments to be equal.
Locally.

Compare _cls and kwargs when comparing view stages in the App

---

fiftyone/core/view.py
fiftyone/server/main.py

* Removes improper `_stages =` usage from the server, which skips stage validation
* Removes redundant validation from `SampleCollections.aggregate()`

Remove stage validation from aggregate

---

docs/source/cli/index.rst
docs/source/user_guide/dataset_creation/zoo.rst
fiftyone/__public__.py
fiftyone/core/cli.py
fiftyone/core/dataset.py
fiftyone/utils/bdd.py
fiftyone/utils/cityscapes.py
fiftyone/utils/data/exporters.py
fiftyone/utils/imagenet.py
fiftyone/zoo/__init__.py
fiftyone/zoo/base.py
fiftyone/zoo/tf.py
fiftyone/zoo/torch.py

Adds the [Cityscapes dataset](https://www.cityscapes-dataset.com) to the dataset zoo.
Also adds some documentation to the user guide about working with zoo datasets whose source files must be manually downloaded from the web (eg b/c accounts must be created to download them). Towards this end, the implementation of BDD100k and ImageNet were updated slightly to make their syntax consistent with Cityscapes.
Example of loading the validation split of Cityscapes into FiftyOne:
```py
foz.download_zoo_dataset("cityscapes", source_dir="/path/to/cityscapes-downloaded-files")
dataset = foz.load_zoo_dataset("cityscapes", split="validation")
```

Adding Cityscapes dataset to the zoo

---

electron/app/components/Filter.tsx
fiftyone/server/main.py

With video in the mix now, a field's path, e.g. `frames.field` for frame labels and `field` for sample labels must be used to uniquely identify a field.
Resolves #660 
Resolves #673

Use entry paths for storing filters

---

electron/app/components/Filter.tsx
electron/app/components/ViewBar/ViewStage/SearchResults.tsx
electron/app/components/ViewBar/ViewStage/ViewStageParameter.tsx
electron/app/components/ViewBar/ViewStage/viewStageMachine.ts
electron/app/components/ViewBar/ViewStage/viewStageParameterMachine.ts

* Fixes the SortBy `field_or_expr` caret (it expands into Object mode when clicked now).
* Limits results in the view bar to at most 10
Resolves #663 
Resolves #665 
Locally.
* Fixes the SortBy  `field_or_expr` caret by expanding into Object mode when clicked
* Limits results in the view bar to at most 10
-   [ ] Other

View Bar fixes

---

fiftyone/server/main.py

The previous check for expanding sample labels into frames for the App was not robust and only assumed an embedded document field needed a `_cls` to deserve conversion into frame labels. Resolves #626.

Only expand sample labels to frames for App

---

fiftyone/utils/labelbox.py
fiftyone/utils/scale.py
tests/misc/labelbox_tests.py
tests/misc/scale_tests.py

Adds support for importing labels in [Scale AI format](https://docs.scale.com/reference#general-image-annotation), as well as exporting labels in a format that can be uploaded as pre-annotations via Scale AI tasks' `hypothesis` parameter.
All of the following label types are supported:
Images
- [General image annotation](https://docs.scale.com/reference#general-image-annotation), including boxes, polylines, polygons, and keypoints
- [Semantic segmentation](https://docs.scale.com/reference#semantic-segmentation-annotation)
Videos
- [General video annotation](https://docs.scale.com/reference#general-video-annotation)
- [Video playback](https://docs.scale.com/reference#video-playback)
Here's an example of exporting BDD labels into Scale AI format and then importing them back into the same …

Adding support for exporting/importing labels to/from Scale AI

---

docs/source/environments/index.rst
docs/source/faq/index.rst
docs/source/getting_started/troubleshooting.rst
docs/source/index.rst
docs/source/user_guide/app.rst

Added top-level sections in the Docs for Environments and FAQ. The FAQ is fairly limited at the moment but is expected to grow as we get more questions. 
The environments doc currently goes through how to work with local, remote, or cloud data and goes into step-by-step detail of how to mount your cloud data in a cloud instance and use a FiftyOne remote sessions from there. Having tried out AWS, Azure, and GCP, the results worked surprisingly well. The data was loaded at least as fast as working on a remote server, and it felt like it was even a bit faster than when I used to use BB1 but I didn't benchmark it.

Environments and FAQ Doc updates

---

electron/app/Routes.tsx
electron/app/app.global.css
electron/app/components/DisplayOptionsSidebar.tsx
electron/app/components/Distributions.tsx
electron/app/components/DropdownHandle.tsx
electron/app/components/Header.tsx
electron/app/components/HorizontalNav.stories.tsx
electron/app/components/HorizontalNav.tsx
electron/app/components/ImageContainerHeader.tsx
electron/app/components/Sample.tsx
electron/app/components/Samples.hooks.ts
electron/app/components/Samples.tsx
electron/app/components/utils.tsx
electron/app/constants/routes.json
electron/app/containers/App.tsx
electron/app/containers/Dataset.tsx
electron/app/containers/SamplesContainer.tsx
electron/app/recoil/atoms.ts
electron/app/utils/hooks.ts
electron/app/utils/tile.ts
electron/package.json
electron/yarn.lock

Per official design documents, encapsulate plots within an expandable window in the main dataset page.
In order to simplify things, sticky nav behavior was dropped. Resolves #546.
Locally.
Plots are now held within an expandable window of the main dataset page as opposed to their own pages.
-   [ ] Other

Expandable plots

---

fiftyone/zoo/tf.py
fiftyone/zoo/torch.py

Resolves https://github.com/voxel51/fiftyone/issues/697.
The issue was that `COCODetectionSampleParser`'s base class was changed away from `ImageDetectionSampleParser` in some recent work, since it can also support loading segmentations as `Polylines` instead. This PR adopts a safer practice of choosing the dataset format based on the `label_cls` of the labels in the dataset.

Resolves dataset zoo type bug

---

docs/source/cli/index.rst
docs/source/environments/index.rst
docs/source/user_guide/app.rst
fiftyone/core/cli.py

Be able to call use the CLI to connect to a remote app instead of having to manually open the ssh connection if you need to use an ssh key instead of password login.
```
fiftyone app connect --destination <destination> --ssh-key </path/to/key>
```
Also updated environment, CLI, and remote session docs with this and best practices of adding the `IdentityFile` to your `ssh_config` if it is used often.

Add ssh-key kwarg to CLI app connect

---

docs/source/cli/index.rst
docs/source/environments/index.rst
docs/source/user_guide/app.rst
fiftyone/core/cli.py

Previously when using `fiftyone app connect`, the _local port_ used was hard-coded to 5151, which prevented a user from launching two separate App instances using `fiftyone app connect` on the same machine.
Below is an example of connecting to two different remote App sessions from the same machine via pure CLI commands:
**On remote machine**
```shell
fiftyone app launch <dataset1> --remote --port 1111
```
```shell
fiftyone app launch <dataset2> --remote --port 2222
```
**On local machine**
```shell
fiftyone app connect --destination <destination> --port 1111 --local-port 3333
```
```shell
fiftyone app connect --destination <destination> --port 2222 --local-port 4444
```

Adding support for customizing local port when connecting to App via CLI

---

electron/app/components/Distributions.tsx
electron/app/components/Header.tsx
electron/app/components/Sample.tsx
electron/app/components/Samples.hooks.ts
electron/app/components/Samples.tsx
electron/app/components/ViewBar/ViewStage/ErrorMessage.tsx
electron/app/components/ViewBar/ViewStage/SearchResults.tsx
electron/app/containers/App.tsx
electron/app/containers/Dataset.tsx
electron/app/recoil/atoms.ts
electron/app/recoil/selectors.ts
fiftyone/core/session.py
fiftyone/core/state.py
fiftyone/server/main.py

Code is still being cleaned, but ready for feedback. I found the previous logo and title layout to be prohibitively small when trying to add selection functionality, so the dataset name now lies in the row as its own element.
I also found the arrow dropdown to be clunky. I can add it, but I don't think our users need that to understand that is where to change datasets.
* Adds dataset selection via a FiftyOne style input/dropdown
* Label graphs now include Fields Sidebar filters (the extended view). See #693 
* Refresh the App by clicking the Logo or `FiftyOne`
Locally.
* Added the ability to change datasets via the dataset name input in …

Dataset dropdown

---

electron/app/components/CheckboxGrid.tsx
electron/app/components/FieldsSidebar.tsx
electron/app/components/Filter.tsx
electron/app/components/HorizontalNav.tsx
electron/app/components/NotificationHub/NotificationHub.tsx
electron/app/components/NumericFieldFilter.tsx
electron/app/components/RangeSlider.tsx
electron/app/components/SampleModal.tsx
electron/app/containers/App.tsx
electron/app/containers/Dataset.tsx
electron/app/containers/SamplesContainer.tsx
electron/app/recoil/atoms.ts
electron/app/recoil/selectors.ts
fiftyone/core/stages.py
fiftyone/server/main.py

Resolves #693 
What is lacking right now is that all new extended statistics need to be computed when a confidence slider is changed, which shows loading indicators for all fields. This does not need to happen, as only the counts for the label field in question will change. Then again, when an `only_matches` option (blocked by only matches support for frame labels) is added, all extended statistics do need to be recomputed...
I think more granular loading will be best addressed when the Fields Sidebar is generalized.
Locally
TBD
-   [x] Core: …

Improved range sliders and loading states

---

docs/source/faq/index.rst

Upon closer inspection, Chromium does not seem to support viewing TIFF images. This PR updates the FAQ question about this and links to a better article on the topic.

Clarifying image format support

---

docs/source/environments/index.rst
docs/source/faq/index.rst
docs/source/getting_started/install.rst
docs/source/getting_started/troubleshooting.rst
fiftyone/core/dataset.py
fiftyone/core/session.py
fiftyone/utils/quickstart.py
fiftyone/utils/uid.py

* Adds `auto` and `height` kwargs to `Session()` and `launch_app`.
* Setting `session.view` or `session.dataset` (and `session.clear_view()`) shows the App when `auto` is `True` in a notebook.
* Moved `pip`, `setuptools`, and `wheel` upgrade steps to notes in installation docs

Session tweaks

---

fiftyone/core/dataset.py

```py
dataset = fo.Dataset("test")
dataset = fo.Dataset("test")
dataset = fo.Dataset("test", overwrite=True)
```

Adding support for overwriting an existing dataset

---

docs/source/cli/index.rst
docs/source/environments/index.rst
docs/source/user_guide/app.rst
docs/source/user_guide/config.rst
fiftyone/core/cli.py
fiftyone/core/config.py
fiftyone/core/session.py
fiftyone/server/main.py
fiftyone/utils/quickstart.py

Allows the default App port to be customized via your FiftyOne config:
```shell
fiftyone quickstart
export FIFTYONE_DEFAULT_APP_PORT=2222
fiftyone quickstart
```
Also allows the App to be launched via the CLI with no dataset loaded:
```shell
fiftyone app launch
```

Making default App port configurable via fiftyone config

---

docs/source/faq/index.rst

Adds a note to the FAQ explaining how to work with TIFF images (and other image types for which browser extensions are available) in the FiftyOne App

Adding note for working with TIFF images

---

fiftyone/__init__.py
fiftyone/constants.py
fiftyone/server/main.py

This PR ensures new COLAB import events are recorded. Currently, when first importing in COLAB, the DB service would register an new NONE import event, and then a returning COLAB import event would register. In general, almost all COLAB import events will be new.
It also removes on redundant import events from services, in general.
* Restricts import events to the main process by skipping service processes
* Changes release candidate installs to be considered development installs with respect to GA tracking

Analytics fixes

---

app/src/components/CheckboxGrid.tsx
app/src/components/SampleModal.tsx
app/src/components/ViewBar/ViewBar.tsx
app/src/components/ViewBar/ViewStage/SearchResults.tsx
app/src/components/utils.tsx
app/src/containers/App.tsx

Proposing we hide scrollbars in firefox until a proper JS library can be used. Things are fairly consistent beyond scrollbars.
Before:
After:

Firefox tweaks

---

fiftyone/core/collections.py
fiftyone/core/dataset.py
fiftyone/core/view.py
tests/unittests/view_tests.py

Fixes https://github.com/voxel51/fiftyone/issues/760, and adds a unit test to ensure it stays this way.
```py
session.view = dataset.sort_by("ground_truth.label")  # now works again
```

Adding back support for indexing by embedded fields

---

app/src/components/ViewBar/ViewStage/viewStageParameterMachine.ts
tests/isolated/service_tests.py

Resolves #754.
* Convert int field submission to number when parsing
* Remove commas when casting from string to int

Fix int field parsing in App

---

package/db/setup.py
setup.py

Resolves #765 as much as possible.
Publishing `fiftyone-db` version `0.3.0` as version `0.2.1` allows a downgrade from `fiftyone` version `0.7.1` to version `0.7.0` to retain the new version of mongodb (4.4). This prevents the issue in #765.
`fiftyone` versions `0.7.1`, `0.7.1.1`, and `0.7.1.2` will continue be affected by #765 unless the user upgrades to `0.7.1.3` before downgrading to `0.7.0`.
This should have been the original requirements scheme, my mistake. Note that this has nothing to do with running admin migrations, as admin migrations were just introduced in `0.7.1`. The downgrade will never be run. It is merely opportunistic versioning, as previous versions of `fiftyone` can use mongodb 4.4 without issue.

Patch release 0.7.1.3

---

docs/source/tutorials/label_mistakes.ipynb

[PyTorch_CIFAR10](https://github.com/huyvnphan/PyTorch_CIFAR10) was recently updated and breaks the label mistakes tutorial when the `master` branch is used..
Cloning the repository at tag `v2.1` resolves the issue.

Fix label mistakes tutorial

---

docs/source/cli/index.rst
docs/source/user_guide/config.rst
fiftyone/core/cli.py
fiftyone/core/config.py
fiftyone/zoo/datasets/__init__.py

A couple small tweaks here:
- Allow FiftyOne config path to be customized by setting the `FIFTYONE_CONFIG_PATH` environment variable
- If `max_samples` is provided to `foz.load_zoo_dataset()`, include this in the dataset's default name to avoid clashing with other copies of the dataset that may have been loaded
The latter change is a small convenience for those that often experience the workflow below
```py
dataset = foz.load_zoo_dataset("coco-2017", split="validation")
dataset.name  # "coco-2017-validation"
"coco-2017",
max_samples=100,
)
"coco-2017",
dataset_name="extra-characters-to-type",
max_samples=100,
)
```

A couple small tweaks

---

fiftyone/core/expressions.py

Allows for checking whether fields exist and are not None in view operations.
Previously this didn't work as expected due to subtleties in how MongoDB treats comparison with `null`.
```py
dataset.add_samples(
[
fo.Sample(
filepath="/path/to/image1.png",
classification=fo.Classification(label="cat"),
detections=fo.Detections(
detections=[
fo.Detection(label="fox", confidence=0.5),
fo.Detection(label="squirrel", confidence=0.7),
]
),
),
fo.Sample(
filepath="/path/to/image2.png",
classification=fo.Classification(label="dog", confidence=0.9),
detections=fo.Detections(
detections=[
fo.Detection(label="cow", confidence=0.3),
fo.Detection(label="emu"),
]
),
),
]
)
dataset.match(F("classification.confidence") == …
```

Adding support for checking whether a field exists

---

fiftyone/core/labels.py

Per our documentation, bounding box coordinates are floats in `[0, 1] x [0, 1]`, so we declare as such in the data model.

Declaring float type of bounding box coordinates

---

docs/source/user_guide/using_datasets.rst
docs/source/user_guide/using_views.rst
fiftyone/__public__.py
fiftyone/core/aggregations.py
fiftyone/core/collections.py
fiftyone/core/dataset.py
fiftyone/core/odm/mixins.py
fiftyone/core/stages.py
fiftyone/core/view.py

Adds a `HistogramValues` aggregation stage that allows for computing histograms of numeric fields. See below for example usage.
**Example usage**
```py
import matplotlib.pyplot as plt
def plot_hist(counts, edges, cumulative=False, density=False):
counts = np.asarray(counts)
edges = np.asarray(edges)
if cumulative:
heights = np.insert(np.cumsum(counts), 0, 0.0)
if density:
heights = heights / heights[-1]
plt.step(edges, heights, where="pre")
else:
left_edges = edges[:-1]
widths = edges[1:] - edges[:-1]
if density:
heights = (counts / np.sum(counts)) / widths
else:
heights = counts
plt.bar(left_edges, heights, width=widths, align="edge")
#BINS = [0.0, 0.25, 0.50, 0.75, 1.01]
#RANGE = None
BINS = 28
RANGE = [0, 1]
#BINS = 28 …
```

Adds HistogramValues aggregation stage and exposes aggregations directly on SampleCollection

---

fiftyone/core/cli.py

My response to https://github.com/voxel51/fiftyone/issues/790.
```shell
$ fiftyone app launch
App launched. Point your web browser to http://localhost:5151
To exit, press ctrl + c
```
```
$ fiftyone app launch --desktop
Desktop App launched.
To exit, close the App or press ctrl + c
```
```shell
$ fiftyone app launch --remote
You have launched a remote App on port 5151. To connect to this App from another
machine, issue the following command:
fiftyone app connect --destination [<username>@]<hostname> --port 5151
where `[<username>@]<hostname>` refers to your current machine. Alternatively,
you can manually configure port forwarding on another machine as follows:
ssh -N -L 5151:127.0.0.1:5151 [<username>@]<hostname>
The App can then be viewed in your browser at http://localhost:5151.
See …
```

Clarifying how to close browser App sessions

---

fiftyone/core/cli.py
fiftyone/utils/quickstart.py

Resolves https://github.com/voxel51/fiftyone/issues/790, specifically https://github.com/voxel51/fiftyone/issues/790#issuecomment-763920999.
Now `fiftyone quickstart` will gracefully accept keyboard interrupts, allowing the quickstart to exit without errors when the user follows the instruction to press `ctrl + c` to exit.
The `interactive` keyword is also removed from `quickstart()`, which was really only there to conditionally include some information in the quickstart help message that's printed. But, I decided its fine to always print the whole message.

Gracefully handle keyboard interrupts when app exits

---

fiftyone/server/main.py

Turns cache control off for all server requests in Colab. This prevents the responses from being saved in the notebook json.
Without Colab's cache control turned off, Colab notebook jsons will become huge while using the App, quickly becoming unusable.
See [here](https://colab.research.google.com/notebooks/snippets/advanced_outputs.ipynb#scrollTo=R8ZvCXC5A0wT)

Prevent Colab from caching requests in notebooks

---

app/src/components/Distributions.tsx
fiftyone/server/main.py

Resolves #798.
Changes:
* Empty counts are filtered from plots
* Integers are binned up to 100, and then floating points take over
* ~5 tick marks are used when binning in floating point values
I can decrease the max number of integer bins, of course. Really, I could make nice clean bins for all integer ranges...maxing out at say 25 bins.

Improved plotting

---

docs/source/faq/index.rst

Added a section to the FAQ on how to use the FiftyOne App in a notebook that is connected to a remote machine. Resolves https://github.com/voxel51/fiftyone/issues/805

[DOCS] Update FAQ, use App in remote notebook

---

fiftyone/core/odm/mixins.py

There is a bug in the logic here: https://github.com/voxel51/fiftyone/blob/a07d3ddb4b4b20143b67f08b9bcf27a6e9311d5a/fiftyone/core/odm/mixins.py#L708
The goal is to match
```
```
But if the field name includes a number, then this will fail. For example,
```
```
Code to replicate:
``` python
dataset.clone_sample_field("predictions", "predictions1")
view = dataset.filter_detections("predictions1", F("confidence") > 0.01)
sample = view.first()
for det in sample.predictions1.detections:
det["test"] = "test"
sample.save()
```
```
ValueError: Modifying root of filtered list field 'predictions1.detections.1.test' is not allowed
```
The problem was that `k.lstrip(ff)` would strip the `1` in …

lstrip error when saving sample

---

README.md

The README is directly used to populate the PyPI homepage https://pypi.org/project/fiftyone, so it needs to have absolute links to everything or else they won't work on PyPI.
**Broken images currently on pypi**

Replacing links/images in README with absolute paths

---

fiftyone/core/collections.py
fiftyone/core/dataset.py
fiftyone/core/stages.py

- Allows any notion of sample (`Sample`, `SampleView`, `SampleCollection`, list of `Sample`s, etc) to be passed to methods like `remove_samples()`, `select()`, and `exclude()`
- Always converts tags to a list in `match_tags()`, and updates kwarg names to be consistent
```py
dataset.exclude(tuple(s.id for s in dataset.take(5)))
dataset.exclude(dataset.take(1).first())
dataset.exclude(dataset.take(4))
dataset.select(tuple(s.id for s in dataset.take(5)))
dataset.select(dataset.take(1).first())
dataset.select(dataset.take(4))
dataset.remove_sample(dataset.take(1).first())
dataset.remove_sample(dataset.take(1).first().id)
dataset.remove_samples(dataset.take(1).first())
dataset.remove_samples(dataset.take(1).first().id) …
```

Dataset and ViewStage method args improvements

---

docs/source/user_guide/using_aggregations.rst
fiftyone/__public__.py
fiftyone/core/aggregations.py
fiftyone/core/collections.py
fiftyone/core/expressions.py
fiftyone/core/stages.py

Adds support for aggregating on *expressions* applied to fields. 
Any expression is allowed, but here's a simple example:
```py
num_objects = F("detections").length()
print(dataset.bounds("predictions", expr=num_objects))
print(dataset.mean("predictions", expr=num_objects))
```
This new `Aggregation(field, expr)` syntax is available on all `Aggregation` classes and is effectively shorthand for operations that previously required a `set_field()` view stage to create the new field being aggregated over:
```py
view = dataset.set_field("predictions.num_objects", F("detections").length())
print(view.bounds("predictions.num_objects"))
print(view.mean("predictions.num_objects"))
```
Other …

Adding support for aggregating on expressions

---

docs/source/getting_started/troubleshooting.rst

Resolves #845.
These commands should have been updated when the transition to PyPI first occurred (v0.7.0).

Remove `--index` flag from troutblshooting page installs

---

docs/source/user_guide/using_datasets.rst
docs/source/user_guide/using_views.rst
fiftyone/core/collections.py
fiftyone/core/dataset.py
fiftyone/core/view.py

Adds support for accessing samples via `dataset[filepath]` and `view[filepath]`.
I wanted to get this out there and think about it a bit. Let's start with the impetus: I was training a model with `fastai` and wanted to add the predictions to my dataset. Here was my workflow:
**Step 1:** Load data into FiftyOne:
```py
DATASET_DIR = "/path/to/dataset"
dataset = fo.Dataset.from_dir(DATASET_DIR, fo.types.ImageClassificationDirectoryTree)
```
**Step 2:** Load data into fastai, train model, and get predictions on a split of the dataset
```py
from fastai.data.all import *
from fastai.vision.data import *
from fastai.vision.all import *
path = Path(DATASET_DIR)
splitter = RandomSplitter(valid_pct=0.2)  # splits into train and val
data_block = DataBlock(splitter, ...)
data = …
```

Adding support for accessing samples by filepath

---

fiftyone/core/collections.py

Adds a `SampleCollection.one()` method that returns a single `Sample` matching a given expression.
`collection.one(expr)` is essentially shorthand for `collection.match(expr).first()`, with an additional `exact=True` argument if you would like to strictly enforce that a single match must exist.
The impetus for this was trying to find a suitable replacement for accessing a sample by filepath over in https://github.com/voxel51/fiftyone/pull/841:
```py
sample = dataset.match(F("filepath") == filepath).first()
```
which could now be written as:
```py
sample = dataset.one(F("filepath") == filepath)
```
Of course it has to be said that https://github.com/voxel51/fiftyone/pull/841 would enable the *even* shorter `dataset[filepath]` syntax, but I can imagine cases where extracting a sample based …

Adds support for returning a single sample matching an expression

---

app/src/components/Player51.tsx
app/src/components/Sample.tsx
app/src/containers/Dataset.tsx
fiftyone/server/main.py
fiftyone/server/util.py
tests/isolated/server_tests.py

Improves static file handling (images and videos).
Changelog:
* Adds graceful failing for missing images and video in the App (see screenshots)
* Adds drive specific file handling for Windows
* Adds support for unsafe media filepaths, e.g. `%20.png`
Issues:
* Resolves #861 
* Resolves #860
* Resolves #839

Filehandling

---

fiftyone/__public__.py
fiftyone/core/collections.py
fiftyone/utils/eval/__init__.py
fiftyone/utils/eval/classification.py
fiftyone/utils/eval/detection.py
fiftyone/utils/eval/segmentation.py

This PR adds support for evaluating semantic segmentation models via `SampleCollection.evaluate_segmentations()`.
The method returns a `SegmentationResults` object that supports the ability to generate the usual classification reports, confusion matrices, etc.
The evaluation can either be performed on the full masks (the default) or on a thin boundary around the ground truth masks (by specifying an optional `bandwidth` parameter). The latter is a better measure of the accuracy of the shape of large regions.
In addition, if an `eval_key` is specified, then per-sample accuracy/precision/recall values are written to each sample, to enable sorting the dataset by these various metrics to identify particularly strong- or weak-performing samples.
Example usage:
```py
import …
```

Adding support for evaluating segmentation models

---

fiftyone/core/aggregations.py
fiftyone/core/collections.py
fiftyone/core/stages.py
tests/unittests/aggregation_tests.py

The `values()` aggregation previously did not support cases where there were two or more array fields involved, for example extracting the labels for all detections of frame-level fields. This PR adds support for this.
This arose as I was working on evaluation for video datasets, where I wanted to write aggregations to extract all classifications or detections at the frame-level.
mea culpa: I haven't added aggregation tests for frame-level fields, but there are fairly comprehensive tests for sample-level fields, and this PR passes those. So at best this PR adds full support for video datasets, and at worst it replaces existing video bugs with new ones.
```py
import random
dataset = …
```

Adding support for extracting values from nested array fields

---

fiftyone/core/aggregations.py
fiftyone/core/collections.py
fiftyone/core/dataset.py
fiftyone/core/expressions.py
fiftyone/core/stages.py
fiftyone/server/main.py
fiftyone/utils/eval/base.py
fiftyone/utils/eval/classification.py
fiftyone/utils/eval/detection.py
fiftyone/utils/eval/segmentation.py
tests/intensive/collections_tests.py
tests/intensive/evaluation_tests.py

This PR adds support for running classification evaluation on frame-level labels.
I also added a `select_fields` flag to `SampleCollection.load_evaluation_view()` that will automatically select only the fields involved in the evaluation, excluding any other evaluation fields (even embedded fields on the same GT/pred fields that were populated by other evaluation runs). The utility here is that it enables you to easily load up a view that only contains the results of one evaluation, in case you have run multiple evaluations on the same dataset. 
In order to implement the frame-level evaluation cleanly, I invested some time in upgrading the `SampleCollection.set_values()` method so that it now supports setting batches of frame-level fields and batches of sample- or frame-level array fields. …

Adding support for evaluating video classifications

---

fiftyone/core/uid.py
setup.py
tests/unittests/utils_tests.py

Import logging is broken in v0.7.3 through v0.7.3.3 and fails silently due to a bare except.
This patch fixes the bug, and replaces the bare except with network exception errors only. I have added a test case as well so logging can be tested throughout development.
My mistake for not catching this earlier. The original bare except was of course inappropriate, as well.
Publishing patch release v0.7.3.4 now.

Patch python import logging

---

fiftyone/core/context.py
fiftyone/core/utils.py

Limits the width of progress bars in notebook contexts to 90 characters. This is done to avoid the pesky problem of progress bars wrapping multiple lines in the HTML versions of notebooks that we publish to the web (the reader's viewport will never match the code runner's, so the fit-to-terminal option doesn't make sense for publishing content).
On a related note, you may have noticed that our progress bars expand gradually as their percentage increases. This is due to [a known Jupyter bug](https://github.com/jupyter/notebook/issues/4354) and I discuss this a bit in https://github.com/voxel51/fiftyone/issues/885. In any case, the 90 character limit comes in handy here too, since the buggy expansion caps out at about 100 characters, which doesn't cause wrapping for most practical browser …

Limit progress bar width to 90 characters in notebook contexts

---

app/README.md

Adds missing App installation steps to the App README, specifically node version installation and setup, and yarn installation.

Add missing installation steps to App README

---

.github/workflows/build.yml
app/src/components/Player51.tsx
app/src/components/SelectObjectsMenu.tsx
app/src/containers/App.tsx
app/src/containers/Dataset.tsx
app/src/utils/selection.ts
docs/source/user_guide/using_aggregations.rst
fiftyone/__public__.py
fiftyone/core/aggregations.py
fiftyone/core/client.py
fiftyone/core/collections.py
fiftyone/core/dataset.py
fiftyone/core/expressions.py
fiftyone/core/labels.py
fiftyone/core/sample.py
fiftyone/core/session.py
fiftyone/core/stages.py
fiftyone/core/state.py
fiftyone/server/main.py
fiftyone/utils/plot/__init__.py
fiftyone/utils/plot/location.py
fiftyone/utils/plot/scatter.py
fiftyone/utils/plot/selector.py
fiftyone/utils/plot/utils.py
tests/intensive/collections_tests.py
tests/intensive/utils_plot_tests.py
tests/misc/selection_tests.py
tests/unittests/view_tests.py

Resolves https://github.com/voxel51/fiftyone/issues/891.
**BREAKING CHANGE**
- All notions of "object" have been replaced by "label" in reference to entities with `id` attributes that can be selected in the App. This includes the following changes:
- `session.selected_objects` -> `session.selected_labels`
- `SampleCollection.select_objects()` -> `SampleCollection.select_labels()`
- `SampleCollection.exclude_objects()` -> `SampleCollection.exclude_labels()`
- `SelectObjects` -> `SelectLabels`
- `ExcludeObjects` -> `ExcludeLabels`
**DESCRIPTION**
This PR adds more full-featured support for tagging sample as well as individual labels, which I believe will be pretty heavily used by users as we roll out more upcoming features that make it easy to identify groups of samples/labels of interest …

Utilities for tagging and visualizing samples and labels

---

fiftyone/core/view.py

Resolves https://github.com/voxel51/fiftyone/issues/910.
The issue was that `DatasetView._pipeline()` was passing the final view to `ViewStage.to_mongo(view)`, but technically it should have been passing a view that contains only stages `1-n` when serializing the `n`th stage. In most cases the two are equivalent, but not when certain view stages modify the schema, for example.
```py
view = dataset.filter_labels("ground_truth", F("label") == "person")
view.select_fields("filepath")
```

Build view along with pipeline when aggregating views

---

app/src/containers/Setup.tsx
docs/docs_guide.md
docs/source/cli/index.rst
docs/source/environments/index.rst
docs/source/user_guide/app.rst
fiftyone/core/cli.py
fiftyone/core/session.py

Resolves https://github.com/voxel51/fiftyone/issues/208.
This PR updates the remote session instructions to first recommend manual port forwarding on your local machine, which doesn't require a local FiftyOne install.
It also resolves https://github.com/voxel51/fiftyone/issues/208 by re-implementing the `fiftyone app connect` CLI method to simply execute the port forward command and then open a browser tab without calling `fo.launch_app()`.
I thought about removing `fiftyone app connect` completely, but, now that it is harmless, I think its okay to keep it as a convenience to users (as a second option). The one thing that *is* removed is the `--desktop` flag, which goes too far.
```py
session = …
```

Updating remote session instructions

---

setup.py

Bump ETA requirement to >=0.4 to match ETA's version on develop.

Bump ETA requirement

---

docs/source/user_guide/config.rst
fiftyone/core/config.py

Per user feedback, it makes sense to not render attributes in detection bounding boxes now that the tooltip exists and is shown by default.

Hide label attributes by default in Player51

---

fiftyone/core/aggregations.py
fiftyone/core/collections.py
fiftyone/core/dataset.py
fiftyone/core/view.py
tests/intensive/merge_tests.py

Adds support for efficiently merging video datasets using aggregations, as opposed to explicit iteration over the samples.
This efficient implementation is automatically used when `Dataset.merge_samples()` is called as long as no optional kwargs are passed that prevents its use.
The examples below can be reverted to the non-efficient implementation by passing `overwrite=False` to `merge_samples()`. Here are the benchmarking results for each example:
Image example
- This PR: `63.7 ms`
- Previous: `6.1 seconds`
Video example:
- This PR: `2.6 seconds`
- Previous: `34.0 seconds`
```py
import os
import eta.core.utils as etau
IMAGES_DIR = "/tmp/quickstart" …
```

Adding support for efficiently merging video datasets

---

fiftyone/core/expressions.py

Adds `ViewExpression`s for computing trigonometric functions `cos()`, `sin()` and `tan()` and their hyperbolic and inverse variants.
Also adds a `ViewExpression.randn()` expression that can generate Gaussian random numbers.
Example usage:
```py
import matplotlib.pyplot as plt
import scipy.stats as sps
from fiftyone import ViewExpression as E
def plot_hist(counts, edges, normalized=False):
counts = np.asarray(counts)
edges = np.asarray(edges)
left_edges = edges[:-1]
widths = edges[1:] - edges[:-1]
if normalized:
counts = counts / (counts * widths).sum()
plt.bar(left_edges, counts, width=widths, align="edge")
dataset.add_samples(
[fo.Sample(filepath="image%d.jpg" % i) for i in range(10000)]
)
dataset.add_sample_field("randn", …
```

Adding trigonometric ViewExpressions and Gaussian random variable support

---

fiftyone/core/session.py

Resolves https://github.com/voxel51/fiftyone/issues/944.
```py
other_dataset = dataset.clone()
session.view = dataset.view()
session.view = other_dataset.view()
session.dataset = other_dataset
session.config = session.config.copy()
session.view = None
session.dataset = None
session.config = None
session.dataset = dataset.view()
session.view = other_dataset
session.config = {}
session.plots = {}
```
I thought about performing the following silent "type casts", but I think its preferable to force the user to provide the correct type data to ensure they understand the difference between changing a view into a dataset versus changing the entire dataset
- `session.view …

Adding type checks for Session property setters

---

fiftyone/core/session.py

Adds validation to `Session.__init__` keyword arguments
```py
session = fo.launch_app(dataset=fo.Dataset().view())
```

Validate keyword arguments in Session's init

---

fiftyone/migrations/revisions/v0_8_0.py

The bleeding edge migrations had been accumulating under v0.7.5, but the next release ended up being v0.8.0.

Updating migration revision

---

fiftyone/core/collections.py
fiftyone/core/stages.py
tests/unittests/view_tests.py

Adds an optional `ordered=True` flag to `Select()` that will cause the samples in the returned view to appear in the same order as the list of IDs you provide:
```py
view = dataset.limit(3)
reversed_view = dataset.select(view.values("id")[::-1], ordered=True)
print(view.values("id"))
print(reversed_view.values("id"))
```

Adding ordered flag to select stage

---

.github/workflows/build-db.yml
package/db/setup.py

A `0.2.1` `aarch64` wheel has been [published](https://pypi.org/project/fiftyone-db/0.2.1/#files).

Add `aarch64` wheel for `fiftyone-db`

---

app/src/components/ViewBar/ViewBar.tsx
app/src/components/ViewBar/ViewStage/ViewStageParameter.tsx
app/src/components/ViewBar/ViewStage/viewStageParameterMachine.ts
app/src/utils/generic.ts
fiftyone/core/aggregations.py
fiftyone/core/collections.py
fiftyone/core/expressions.py
fiftyone/core/stages.py

* Resolves #962
* Resolves #948
```py
upper_bbox = [F("bounding_box")[0], F("bounding_box")[1], F("bounding_box")[2], F("bounding_box")[3] / 2]
view = dataset.set_field("predictions.detections.bounding_box", upper_bbox)
session = fo.launch_app(view=view)
```

Proper handling of lists of expressions in view stages

---

app/src/components/Actions/ActionsRow.tsx
app/src/components/Actions/Popout.tsx
app/src/components/Actions/Selected.tsx
app/src/components/Actions/utils.tsx
app/src/components/FieldsSidebar.tsx
app/src/components/Filters/LabelFieldFilter.tsx
app/src/components/Filters/LabelFieldFilters.state.tsx
app/src/components/JSONView.tsx
app/src/components/SampleModal.tsx
app/src/components/utils.tsx

* Resolves #672  (although, I believe this was mostly resolved already)
* Resolves #651
With respect to #651, `Clear selection` and `Hide selected` are the only actions that do not account for the current visibility of labels. Actions that would result in a noop are not shown (e.g. no visible labels means that are not selected means `Select visible (current sample)` will not be shown.

Expanded view counts and selection

---

app/src/components/ViewBar/ViewStage/viewStageParameterMachine.ts
fiftyone/core/stages.py

Resolves #971 
Obviously, there is so much to improve in the view bar, including parameter handling. This band-aid requires the `str` type to not be valid JSON...
* `iamastring` -> valid
*  `"notastring"` -> invalid
* `1` -> invalid
* `"[1]"` -> invalid
* `'{ "one": 1}'` -> invalid
Allows for proper handling of `str|json` types.

Stricter `str` stage parameter validation

---

fiftyone/core/collections.py
fiftyone/core/dataset.py
fiftyone/core/stages.py
tests/unittests/dataset_tests.py

Adds a `Dataset.delete_labels()` method that allows for efficiently deleting `Label`s from datasets via a variety of natural syntaxes:
- Selected labels in the App: `dataset.delete_labels(labels=session.selected_labels)`
- By ID: `dataset.delete_labels(ids=list_of_ids)`
- By tag: `dataset.delete_labels(tags=list_of_tags)`
- By constructing a view: `dataset.delete_labels(view=view_of_labels_to_delete)`
Also renames `Dataset.remove_samples()` to `Dataset.delete_samples()` for consistency, and marks both `Dataset.remove_sample()` and `Dataset.remove_samples()` as deprecated.
- I believe the original reasoning for choosing "remove" over "delete" is that if a deleted `Sample` exists in-memory, it will still technically exist but have `in_dataset == False`, but I now consider this an …

Adding method to delete labels from datasets

---

docs/source/conf.py

Resolves https://github.com/voxel51/fiftyone/issues/975.
Adds method/attribute summary tables to all class definitions in the API docs.
For example, with this change, clicking on the `Dataset` class in the summary table of the `fiftyone.core.dataset` module will link to the `CLASS Dataset` section, which now contains a similar table summarizing the methods/attributes of the `Dataset` class:
The `fiftyone.core.dataset` module:
The `Dataset` class:

Adding class summaries to API docs

---

fiftyone/__public__.py
fiftyone/core/collections.py
fiftyone/core/runs.py
fiftyone/core/stages.py
fiftyone/core/view.py

Requires the corresponding similarity PR from `fiftyone-brain` in order to function.
Adds a `sort_by_similarity()` view stage that enables sorting by visual similarity based on the results of a `fiftyone.brain.compute_similarity()` brain run.
```py
fob.compute_similarity(dataset, brain_key="similarity")
query_id = dataset.first().id
session.view = dataset.sort_by_similarity(query_id, brain_key="similarity")
session.view = dataset.sort_by_similarity(session.selected, brain_key="similarity")
```
```py …
```

Adding a sort_by_similarity() view stage

---

docs/source/user_guide/plots.rst
docs/source/user_guide/using_aggregations.rst
fiftyone/core/aggregations.py
fiftyone/core/collections.py
fiftyone/core/plots/base.py
fiftyone/core/plots/matplotlib.py
fiftyone/core/plots/plotly.py
fiftyone/core/plots/views.py
tests/unittests/aggregation_tests.py

It has been bugging me for awhile that you couldn't pass expressions directly to aggregations, such as `dataset.bounds(F("ground_truth.detections").length())`. You can currently compute this, but you must use the syntax `dataset.bounds("ground_truth.detections", expr=F().length())`, which is less clean.
With this PR, all aggregations now accept field strings or arbitrary expressions as their first argument. The `expr` keyword is now redundant and unnecessary, but I left it to avoid a breaking change.
This also enables plots like `scatterplot(..., labels=field_or_expr, sizes=field_or_expr, ...)` and `CategoricalHistogram(field_or_expr, ...)` to accept expressions defining the values to use in the plots. The examples at the end demonstrate the utility of this 😄 
The reason I didn't …

Adding support for passing expressions directly to aggregations

---

docs/source/user_guide/using_aggregations.rst
fiftyone/core/aggregations.py
fiftyone/core/collections.py
fiftyone/core/dataset.py
fiftyone/core/fields.py
fiftyone/core/odm/__init__.py
fiftyone/core/odm/document.py
fiftyone/core/odm/mixins.py
fiftyone/utils/eval/classification.py
tests/unittests/view_tests.py

Adds full support for passing/retrieving embedded documents using `values()` and `set_values()`. Previously these methods only supported setting/getting primitive fields like `int`, `float`, `str`, etc. that required no conversion between Python and Mongo representations.
With this PR, `values()` is now a proper dual of `set_values()` in the sense that objects like `Detections`, `list(Detection)`, and so forth can be passed to `values()` and then directly retrieved from `set_values()`:
```py
dataset.set_values("embedded.field", values)
also_values = dataset.values("embedded.field")
values == also_values  # true, even if values is, say, a nested list of `Detections` objects
```
With this work, `set_values()` also now more fully delivers on the promise of equivalent loop-based syntaxes that …

Adding support for embedded documents in values() and set_values()

---

fiftyone/core/utils.py
fiftyone/utils/tf.py

I recently tried exporting a dataset in `fo.types.TFObjectDetectionDataset` format on a new machine and found errors related to eager vs non-eager TF execution mode.
I struggle to understand why this hasn't been an issue before, but it seems that the `fiftyone.utils.tf` module *requires* eager execution mode, so I updated the code to enable if necessary and raise a helpful error if that couldn't be achieved.
This issue is only relevant for TF 1.X users. Things have and will continue to work as expected for TF 2.X users.
Tested by verifying that the snippet below runs under TF 1.12, 1.15, and 2.X.
```py
dataset.export("/tmp/test", fo.types.TFObjectDetectionDataset, label_field="ground_truth")
```

Require eager execution mode when exporting datasets in TF format

---

fiftyone/core/client.py
fiftyone/core/session.py
fiftyone/server/main.py

Resolves #998 
This is a relatively minor feature, so it has a minimal implementation.
Desktop waiting has not changed. An exit is triggered when the `AppService` (process) is closed.
For browsers, if a session waits, all browser connections (windows/tabs) must be lost (closed) for the wait to exit.
Snippet:
```py
session.wait()
print("CLOSED")
```

`Session.wait()` support for browsers

---

fiftyone/core/dataset.py
fiftyone/core/view.py

Resolves #1002
In dataset and view `iter_samples()`, if a cursor has timed out we continue with a new view offset from the last index.
I can't think of any other likely reason `CusorNotFound` would raise in this try/except. I suppose a recursion limit would be reached if that was the case.

Recover from cursor timeouts

---

fiftyone/zoo/models/manifest-tf.json

I believe #995 caused the `vgg16-imagenet-tf` zoo model to no longer support TF2.
In any case, I now get an error when trying to run it in TF2. This is an old model and an old implementation that was written in TF 1.12 or something, so it was mostly miraculous that we managed to get it to run under TF2 in the first place using `tf.compat.v1` tricks.
So, this PR renames `vgg16-imagenet-tf` to `vgg16-imagenet-tf1` (per existing convention) and updates the install requirements to reflect TF1-only support. The name change is breaking, but I'm okay with it for consistency with the naming convention in-place.
I checked other models that promise to support TF1 and TF2 and they still seem to work in both environments.
Tested by verifying that the autogenerated code snippet in the zoo model …

TensorFlow VGG zoo model only supports TF1

---

fiftyone/utils/openimages.py

Resolves https://github.com/voxel51/fiftyone/issues/1035.
Fixes a bug in the way that the `multiprocessing` module was being used that was causing Mac users running Python >= 3.8 to encounter an error when downloading the Open Images dataset.
Verified that this fixes the bug under Python 3.8:
```
conda create -n fifty3 python=3.8
conda activate fifty3
git clone https://github.com/voxel51/fiftyone
cd fiftyone
git checkout --track origin/oi-hotfix
bash install.bash
```
```py
"open-images-v6", 
split="validation", 
label_types=["detections"], 
max_samples=10,
)
```

Fixing multiprocess initialization bug when loading Open Images dataset (#1)

---

app/package.json
app/src/recoil/selectors.ts
app/src/utils/colors.ts
app/yarn.lock

Resolves #1042 
For context, previously the colors were generated with respect to a provided list of values. Now the colors are generated automatically and a cached color is returned if a value is encountered again.
A result of backend searches against string fields, which includes labels.

Color by label fixes

---

fiftyone/utils/labelbox.py

Resolves #1046 
The json format of exported Labelbox annotations follows this format:
```
[
{
"DataRow ID": <labelbox-id>,
"Labeled Data": <url-or-None>,
"Label": {...},
....
}
]
```
Where the `labelbox_id_field` of the FiftyOne Samples stores the "DataRow ID" field of the Labelbox JSON, not the "ID" field as was previously implemented.
Labels can now be properly imported into an existing FiftyOne dataset from Labelbox annotations.

Fix the Labelbox ID used when importing samples

---

fiftyone/__public__.py
fiftyone/core/collections.py
fiftyone/core/expressions.py
fiftyone/core/stages.py
tests/unittests/view_tests.py

Adds a new `match_labels()` view stage that enables matching samples that have specific labels, but without actually filtering the non-matching labels.
Matches can be specified via either `ids` or `tags`, like `select_labels()`, or via a `filter` expression that defines the matching labels, like `filter_labels()`.
This stage is useful in cases such as inspecting detection evaluation results where one may want to inspect an *entire* sample that contains a false positive prediction without actually filtering the true positives, since one needs to see the whole situation to diagnose why a particular label was deemed a false positive.
- Adds an optional `bool` flag to `MatchTags()` that allows for optionally matching samples **without** the specified tags
- Adds missing implementations of …

Adding a match_labels() stage

---

fiftyone/core/collections.py
fiftyone/core/dataset.py
fiftyone/core/metadata.py
fiftyone/core/patches.py
fiftyone/core/stages.py
fiftyone/utils/eval/classification.py
fiftyone/utils/labelbox.py
fiftyone/utils/scale.py

Adds support for executing an aggregation on multiple fields via an abbreviated syntax:
```
tuple, of, results = SampleCollection.<aggregation_method>(("tuple", "of", "fields"), **kwargs)
```
Example usage:
```py
ids, filepaths = dataset.aggregate([fo.Values("id"), fo.Values("filepath")])
ids, filepaths = dataset.values(["id", "filepath"])
```

Syntax sugar for running multiple aggregations of the same type

---

fiftyone/core/utils.py

Adds support for using `hashlib` to compute filehashes.
This is useful because it allows for computing filehashes of very large files with a fixed amount of RAM.
```py
import fiftyone.core.utils as fou                                                                                                                                            
filepath = "/path/to/video.mp4"
fou.compute_filehash(filepath)                                                                                                                       
fou.compute_filehash(filepath, method="md5")  # 64kb chunks by default                                                                  
fou.compute_filehash(filepath, method="md5", chunk_size=-1)  # no chunking
```

Adds support for using hashlib to compute filehashes

---

fiftyone/core/plots/plotly.py
fiftyone/core/plots/views.py

Adds an optional `edges` argument to the `scatterplot()` and `location_scatterplot()` methods of `fiftyone.core.plots.plotly.scatterplot()` that enables drawing undirected edges between scatterpoints.
Edges are always rendered in a separate trace, which has no selection callbacks (the corresponding nodes should be selected).
Also gets rid of the `ManualInteractiveScatter` class, which wasn't actually being used, because it was going to be a slight pain to support edges traces for that class.
This will be useful for upcoming brain features 😄

Adding support for rendering edges on plotly scatterplots

---

fiftyone/server/main.py

Resolves #1060 
Tornado, our web server, relies on the `mimetypes` package to set mime types for static files served. And `mimetypes` relies on system configuration which, at least on Windows, is unreliable.
Currently, the override only accounts for `.js` files, which is the only known issue.

Server: Always set mime type to text/javascript for .js files

---

docs/source/user_guide/export_datasets.rst
docs/source/user_guide/using_views.rst
fiftyone/core/collections.py
fiftyone/core/labels.py
fiftyone/core/models.py
fiftyone/core/utils.py
fiftyone/utils/bdd.py
fiftyone/utils/data/exporters.py
fiftyone/utils/data/ingestors.py
fiftyone/utils/data/parsers.py
fiftyone/utils/labelbox.py
fiftyone/utils/patches.py
fiftyone/utils/scale.py
fiftyone/zoo/datasets/__init__.py

Resolves #1049.
When a dataset export involving a spatial field (eg `Detections`) and a classification dataset format (eg `ImageClassificationDirectoryTree`) is detected, the export routine will automatically assume that the user wants to export the *image patches*.
Also adds support for automatically coercing single label fields like `Detection` into `Detections` if the exporter expects list-type fields.
One more thing: previously label type coercions were only applied when a single `label_field` is being exported. Now, label coercions are applied if possible even when multiple fields are being exported.
```py
dataset = foz.load_zoo_dataset("quickstart").limit(5).clone()
for idx, sample in enumerate(dataset):
sample["attribute"] = …
```

Adding support for exporting image patches

---

fiftyone/core/collections.py
fiftyone/core/dataset.py
fiftyone/core/document.py
fiftyone/core/expressions.py
fiftyone/core/frame.py
fiftyone/core/sample.py
fiftyone/core/utils.py
tests/intensive/merge_tests.py
tests/unittests/dataset_tests.py
tests/unittests/sample_tests.py
tests/unittests/video_tests.py

Adds a number of useful options to `Dataset.merge_samples()` and `Document.merge()`, including:
- `fields (None)`: an optional field or iterable of fields to which to restrict the merge. If provided, fields other than these are omitted from `samples` when merging or adding samples. Can also be dict mapping source field names to destination field names
- `omit_fields (None)`: an optional field or iterable of fields to exclude from the merge. If provided, these fields are omitted from `samples`, if present, when merging or adding samples
- `merge_lists (True)`: whether to merge the elements of list fields (e.g., `tags`) and label list fields (e.g., `Detections` fields) rather than  merging the entire top-level field like other field types. For label lists fields, existing `Label` elements …

Adding support for merging list fields, plus other goodies

---

fiftyone/utils/openimages.py

On Windows, issues can arise when attempting to open UTF-8 encoded files with specifying the encoding when calling `open()`. 
This PR fixes that issue when loading open images.
```shell
Uncaught exception
File "move.py", line 40, in <module>
dataset = foz.load_zoo_dataset("open-images-v6", split="validation",)
File "C:\Users\hkeglovi\Miniconda3\envs\ims\lib\site-packages\fiftyone\zoo\datasets\__init__.py", line 206, in load_zoo_dataset
**download_kwargs
File "C:\Users\hkeglovi\Miniconda3\envs\ims\lib\site-packages\fiftyone\zoo\datasets\__init__.py", line 120, in download_zoo_dataset
cleanup=cleanup,
File "C:\Users\hkeglovi\Miniconda3\envs\ims\lib\site-packages\fiftyone\zoo\datasets\__init__.py", line 962, in download_and_prepare
) = …
```

Open csv files related to open images with a utf8 encoding

---

app/src/components/FieldsSidebar.tsx
app/src/components/Sample.tsx
app/src/recoil/selectors.ts
app/src/utils/labels.ts

Previously, the `sample_id` tag would not show up on samples in the grid. `None` would also be displayed in the expanded view  for the `sample_id` field.

Fixes display issues for the `sample_id` patches view field

---

fiftyone/__public__.py
fiftyone/core/collections.py
fiftyone/core/stages.py

Adding variants of `Select()` and `Exclude()` that allow for selecting/excluding by categorial fields other than just `id`.
These are useful, for example, when your dataset contains an "external" ID field like `coco_id` (int) or `open_images_id` (str) and you'd like to add predictions to your dataset based on these external IDs.
```py
dataset.add_samples(
[
fo.Sample(filepath="image%d.jpg" % i, int=i, str=str(i))
for i in range(100)
]
)
#
#
view = dataset.select_by("int", [1, 51, 11, 41, 21, 31])
print(view.head(6))
#
#
view = dataset.select_by(
"str", ["1", "51", "11", "41", "21", "31"], ordered=True
)
print(view.head(6))
```

Adding select_by() and exclude_by() stages

---

docs/source/user_guide/using_aggregations.rst
fiftyone/core/aggregations.py
fiftyone/core/collections.py
tests/unittests/aggregation_tests.py

A common pattern in various places in the codebase are batch aggregations like this:
```py
list, of, results = dataset.values(["list", "of", "fields"])
list, of, results = dataset.aggregate([fo.Values("list"), fo.Values("of"), fo.Values("fields")])
```
For aggregations **other than** `Values()`, such operations are already quite efficient, as they are executed via `$facet` with a single pass over the documents in the DB.
For `Values()`, `$facet` is not an option because it returns results in a single document, which could easily violate the 16MB limit. Thus, currently, if an aggregation is executed that contains multiple `Values()` instances, those aggregations are run in series, each requiring a separate pass over the DB.
For `Values()` operations that involve unwinding of fields, I …

Optimizing implementation of batch aggregations

---

fiftyone/server/main.py

Adds a one second timeout before closing waited sessions (`session.wait()`). Resolves premature closes due to page refreshes.
Resolves #1090

Disconnect timeout before closing waited sessions

---

fiftyone/utils/openimages.py

At the moment, an error 404 is raised when calling "_download_images_if_necessary" on windows, since windows style paths are used when downloading from the s3 storage. This changes should prevent this bug. For details, see stackoverflow: https://stackoverflow.com/questions/68229288/fail-to-load-a-subpart-of-open-images-v6-with-fiftyone/
Added a regex to convert windows stype paths to linux for s3 downloads.
Tested on windows 10 with python 3.9. Changes should not have any effect on other os.
-   [X] No. You can skip the rest of this section. …

Fixed aws error 404 bug on windows

---

fiftyone/core/session.py

Resolves #1102
Allows notebooks sessions to open a tab, and changes pure remote sessions to warn (can revert, but I'm thinking this is more friendly). Comments/changes in the language are welcome.
Tested in Colab.

`Session.open_tab()` in notebooks and remote warning

---

fiftyone/core/collections.py
fiftyone/core/dataset.py
fiftyone/core/view.py
tests/unittests/dataset_tests.py
tests/unittests/view_tests.py

Adds an optional `progress` flag to `SampleCollection.iter_samples()` that provides a convenient way to render a progress bar tracking the progress of an operation:
```py
for sample in dataset.iter_samples(progress=True):
pass
for sample in dataset.take(100).iter_samples(progress=True):
pass
```

Add progress flag to track iter_samples() progress

---

fiftyone/utils/coco.py

Previously, providing a `classes` requirement to `COCODetectionDatasetImporter` when loading an unlabeled dataset would raise an error. Now, the `classes` will be ignored in this case and a warning to this effect printed.
This change allows the code below to successfully run (with a warning), which is a better behavior than an unhelpful error message:
```py
"coco-2017",
splits=["train", "test"],
classes=["person", "dog", "car", "clock", "horse"],
include_id=True,
max_samples=100,
)
print(dataset)
```

Handling unlabeled datasets in COCODetectionDatasetImporter

---

fiftyone/utils/coco.py
fiftyone/utils/openimages.py
tests/intensive/dataset_zoo_tests.py
tests/intensive/import_export_tests.py

This PR makes some improvements to how `classes` and `attrs` requirements are handled for partial downloads of the Open Images dataset.
The changes are as follows:
- "classifications" are excluded from `classes` requirements, since they only describe the label schema and do not actually indicate the presence of that label type. The exception to this is that, if **only** "classifications" labels are requested, then the `classes` requirement **will** be applied
- `classes` requirements were previously being AND-ed across all label types that support classes ("detections" and "segmentations"), but the more natural behavior is to OR across label types. In other words, if you want samples containing particular classes, they can appear across any label type you requested, not necessarily ALL …

Improvements to Open Images partial downloads

---

docs/source/integrations/coco.rst
docs/source/integrations/open_images.rst
docs/source/user_guide/evaluation.rst
fiftyone/core/collections.py
fiftyone/core/dataset.py
fiftyone/core/labels.py
fiftyone/core/models.py
fiftyone/core/odm/mixins.py
fiftyone/core/patches.py
fiftyone/core/runs.py
fiftyone/core/utils.py
fiftyone/core/validation.py
fiftyone/utils/eval/classification.py
fiftyone/utils/eval/coco.py
fiftyone/utils/eval/detection.py
fiftyone/utils/eval/openimages.py
fiftyone/utils/eval/segmentation.py
fiftyone/utils/eval/utils.py
tests/intensive/evaluation_tests.py

Resolves https://github.com/voxel51/fiftyone/issues/1101.
The `evaluate_detections()` method now supports evaluating `Polylines` and `Detections` with instance masks. Both COCO and Open Images flavored evaluations are supported, as the only difference for these new cases is how IoU is computed.
The user will be prompted to install [Shapely](https://github.com/Toblerity/Shapely) the first time they run an evaluation that requires polgyon computations. Thanks to the awesome Shapely library, IoU computation on polygons should be quite robust, as things like self-overlapping and self-intersecting shapes will be appropriately handled.
**Note:** I decided against including `shapely` as a builtin requirement because, while it is cross-platform and stable, is does rely on compiled C++ code and …

Adds support for evaluating polygons and instance segmentations

---

setup.py

[Interactive plotting](https://voxel51.com/docs/fiftyone/user_guide/plots.html) seems to be broken by some backwards incompatible changes introduced in `plotly>=5`... The plots still render, but selection callbacks are no longer triggered.
We'll need to investigate further, but, for now, I've verified that requiring `plotly>=4.14,<5` is sufficient to regain callbacks.

Adding plotly<5 requirement to fix interactive plotting

---

.github/workflows/build-db.yml
docs/source/getting_started/troubleshooting.rst
package/db/setup.py
package/test-envs/dockerfiles/centos7

This patch fixes the install issue  #1097 when installing fiftyone on RHEL7.
The changes include adding download url option to the db package's `setup.py` for rhel7 distribution.
```python 
MONGODB_DOWNLOAD_URLS = {
"linux-x86_64": "https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-4.4.2.tgz",
"linux-aarch64": "https://fastdl.mongodb.org/linux/mongodb-linux-aarch64-ubuntu1804-4.4.2.tgz",
"mac": "https://fastdl.mongodb.org/osx/mongodb-macos-x86_64-4.4.2.tgz",
"win": "https://fastdl.mongodb.org/windows/mongodb-windows-x86_64-4.4.2.zip",
"ubuntu1604": {
"manylinux1_x86_64": "https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1604-4.4.2.tgz",
},
"debian9": {
"manylinux1_x86_64": "https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian92-4.4.2.tgz",
},
"rhel7": { …
```

Added RHEL7 install for fiftyone-db

---

docs/source/integrations/coco.rst
docs/source/user_guide/dataset_creation/datasets.rst
docs/source/user_guide/dataset_zoo/datasets.rst
fiftyone/types/dataset_types.py
fiftyone/utils/coco.py

Resolves https://github.com/voxel51/fiftyone/issues/1108.
`COCODetectionDatasetImporter` now provides an optional `include_license` flag that will load the license data for the images, if available.
```
include_license (False): whether to include the license ID of each
sample in the loaded labels, if available. Supported values are:
-   ``"False"``: don't load the license
-   ``True``/``"name"``: store the string license name
-   ``"id"``: store the integer license ID
-   ``"url"``: store the license URL
Note that the license descriptions (if available) are always loaded
into ``dataset.info["licenses"]`` and can be used to convert
between ID, name, and URL later
```
Example usage:
```py
dataset = …
```

Adding support for loading COCO license data

---

fiftyone/core/plots/plotly.py

Patching plotly fails when running in a read-only filesystem (e.g. inside [Singularity](https://sylabs.io/guides/3.8/user-guide/)).
This just catches the exception and logs it. 
Tested by running fiftyone in Singularity and verifying that it doesn't crash the process anymore.
-   [ ] Other

Catch exception when trying to patch plotly on read-only FS

---

docs/source/getting_started/install.rst
fiftyone/migrations/runner.py
tests/unittests/utils_tests.py

Resolves https://github.com/voxel51/fiftyone/issues/1094
Resolves https://github.com/voxel51/fiftyone/issues/1095
Running a migration that involves a future version of the FiftyOne package should not be allowed, since the currently installed version of `fiftyone` is not aware of any upward/downward migrations that may be introduced in future versions of the package.
**For discussion:**
Although this is technically correct, I wonder if there is some middle ground we can achieve here, since this will now *always* raise an error whenever anyone tries to downgrade their installation without following the docs instructions, while many times no migration would be required...
This can be tested as follows:
```shell
pip install -e .
fiftyone zoo datasets load quickstart
pip install -e .
fiftyone …
```

Don't allow migrations involving future FiftyOne versions

---

fiftyone/utils/coco.py

Found a bug where for non-square images the bounding boxes were being imported wrong into Voxel51.  Found that width and height had been swapped in one line of the coco utils.  All the documentation gives a `(width, height)` format, which matches coco format, but one line has the `frame_size` swapped to a `(height, width)` format.
Swapped width and height normalization parameters in test data and observed that although the numbers in the prediction file don't match pixel locations the boxes are drawn correctly. 
Bugfix in MSCOCO Detection Import Utility to correctly draw bounding boxes.
-   [x] …

width height mismatch from coco formatted data

---

fiftyone/utils/coco.py

Resolves #1138.
If an object instance is too small to be rendered when exporting in COCO format, it will now be given an empty `segmentations` field, where previous an image resizing error would have been raised.

Handling degenerate masks when exporting COCO segmentations

---

fiftyone/utils/cityscapes.py
fiftyone/utils/data/exporters.py

Resolves #1146.
We unfortunately don't have unit tests for zoo datasets that require manually downloaded source files. Cityscapes is one of those and some recent changes caused a regression. This particular bug is specific to Cityscapes; no other zoo datasets.
Verified by running the following successfully:
```py
source_dir = "/path/to/source/files"
dataset = foz.load_zoo_dataset("cityscapes", split="validation", source_dir=source_dir)
```

Fixing #1146

---

fiftyone/utils/coco.py
tests/intensive/dataset_zoo_tests.py

Resolves #1149.
I didn't track down the details, but it seems that there was a broken merge commit last week because [these lines](https://github.com/voxel51/fiftyone/blob/93ccdd139ad7803b85cae29199b70817e82bdcf8/fiftyone/utils/coco.py#L1408-L1410) from #1133 did not make it into develop, which still has [these lines](https://github.com/voxel51/fiftyone/blob/171d4c1c38edb523a82bfb6d66357f20287a92de/fiftyone/utils/coco.py#L1482-L1488)...

Fixing #1149

---

fiftyone/utils/openimages.py
setup.py
tests/intensive/dataset_zoo_tests.py

Fixes a bug where label files were not being downloaded when running a `load_zoo_dataset()` call that does not include `classes` or `attrs` options in an environment where Open Images has never been downloaded:
```py
foz.delete_zoo_dataset("open-images-v6", split="validation")
dataset = foz.load_zoo_dataset("open-images-v6", split="validation", max_samples=5)
```

Open Images download hotfix

---

fiftyone/utils/openimages.py

Resolves https://github.com/voxel51/fiftyone/issues/1153.
Fixes a bug where `classes/attrs` requirements were being ignored when loading the Open Images dataset with no `max_samples` requirement.
The *download* portion of the code was respecting the requirements, but the *import* portion was not (when no `max_samples` requirement was provided), so, as the example below demonstrates, running multiple loads could currently cause issues:
```py
foz.load_zoo_dataset(
"open-images-v6",
max_samples=50,
)
"open-images-v6",
classes=["House"],
)
```

Only load matching samples when classes/attrs requirements are provided

---

README.md
docs/source/faq/index.rst
docs/source/getting_started/install.rst
docs/source/index.rst
docs/source/user_guide/app.rst

A common user issue is using `launch_app()` in a script without including `session.wait()`.
This PR attempts to document the correct usage of the FiftyOne App from scripts in the primary places where (I think?) new users might be going wrong:

Adding session.wait() instructions in key places

---

fiftyone/core/dataset.py
fiftyone/core/frame.py
fiftyone/core/labels.py
fiftyone/core/runs.py
tests/unittests/dataset_tests.py
tests/unittests/video_tests.py

The impetus for this PR is that I wanted the following to work (which it now does):
```py
samples = [
fo.Sample(filepath="image1.jpg", ground_truth=None),
fo.Sample(filepath="image2.jpg", ground_truth=fo.Classification()),
]
dataset.add_samples(samples)
print(dataset)  # has `ground_truth` field
```
Previously, an error would be raised because we weren't able to infer an appropriate field type for `ground_truth` after only seeing the first sample.
A consequence of this change is that, in the following example, no `ground_truth` field will be added to the dataset, since we don't know what type to use for the field:
```py
sample = fo.Sample(filepath="image.jpg", ground_truth=None) …
```

Gracefully ignore None-valued new fields when expanding dataset schemas

---

docs/source/user_guide/using_datasets.rst
docs/source/user_guide/using_views.rst
fiftyone/core/collections.py
fiftyone/core/session.py
fiftyone/utils/geojson.py
tests/misc/selection_tests.py

Adds some documentation for various "batch" operations that can be performed on datasets and views via methods like `set_values()`, `tag_samples()`, `tag_labels()`, `clone_sample_field()`, and so on.
Also adds `Session.selected_view` property that returns a view containing only the currently selected samples/labels in the App, if any.

Documenting batch actions

---

docs/source/user_guide/using_datasets.rst
fiftyone/utils/yolo.py

This commit fixed loading yolov5 yaml with multiply paths for one dataset split. 
The change is minimum, and I have tested it with my own yolov5 yaml.
The yolov5 yaml supports using a list of paths in each data split. e.g.
```yaml
train: [/path/to/split/one,
/path/to/split/two]
test: /path/to/test/set
```
Current yolov5 yaml load function will  raise `AttributeError` as follow:
```python
AttributeError: 'list' object has no attribute 'endswith'
```
-   [X] No. You can skip the rest of this section.
-   [X] Core: Core `fiftyone` Python library changes …

fixed loading yolov5 yaml with multiply paths

---

fiftyone/__public__.py
fiftyone/core/collections.py
fiftyone/core/stages.py

Adds a `group_by()` stage that allows for reorganizing the samples in a collection so that they are grouped by a specified field or expression. The groups can also be sorted.
A use case for this came up last night as I was working on brain stuff; happy to discuss offline if anyone is interested.
A note of warning here is that, since the `$group` aggregation used here stores a list of sample documents in each group, this stage could easily produce documents internally in the MongoDB pipeline that exceed 100MB and must therefore leverage the `useDiskSpace = true` option (which we have enabled). So, for very large collections with large groups, this stage could be quite intensive. But, I didn't see any easy way to avoid this when implementing the stage. Anybody know if I missed any easy …

Adding a group_by() view stage

---

fiftyone/core/dataset.py
fiftyone/core/odm/mixins.py

Resolves https://github.com/voxel51/fiftyone/issues/1192.
The issue was that the `name` of renamed fields was being updated in `DatasetDocument`, but not its corresponding `db_field`.
Also adds an easier to read error when trying to rename a dataset to a name that is already in use, and fixes a bug with `Dataset.add_archive()` where archives were being extracted to `/path/to/dir/dir` rather than `/path/to/dir`.
Mea culpa, there was (and still is no) unit test that checked for the issue that gave rise to https://github.com/voxel51/fiftyone/issues/1192, but I manually verified that things are now correct.

Fixing Issue #1192

---

app/package.json
app/packages/desktop/package.json
fiftyone/core/service.py

Resolves #1177 
The app needs to be built for changes to take effect in the desktop app
```
bash install.bash # or "yarn build" in "./app"
```
```
fiftyone app launch --desktop
```

Update desktop app source launches

---

app/packages/looker/src/index.ts

Resolves #1175 
```py
view = dataset.select_fields()
session = fo.launch_app(view=view)
```

Zoom fix for empty samples

---

fiftyone/core/session.py

* Resolves #1187 
* Resolves #1126 
`Session` objects now create `DisplayHandle()` instances directly when working in IPython notebooks. Using the convenience function `display()` seems to cause an unwanted initial display object (App window).
This issue does not seem to arise in source installs, but I have tested with a built package and things are working correctly now in VSCode, Jupyter Lab, etc.

Fix duplicate app rendering in IPython notebooks

---

app/packages/looker/src/elements/base.ts
app/packages/looker/src/elements/common/actions.ts
app/packages/looker/src/elements/common/canvas.ts
app/packages/looker/src/elements/common/controls.ts
docs/source/user_guide/app.rst

Resolves #1174
Fixes the click arrows for next/previous actions in notebook Lookers.
Regarding the arrow keys, notebooks currently require the shift key for wheeling and arrow shortcuts, as the App is within an iframe and these events interfere with scrolling (horizontal or vertical) unless `Shift` key is active.
I am unaware of any horizontal scrolling that could be possible, so I could remove the shift key requirement for left/right arrows. But it would interfere, if horizontal scrolling is available.

Fix next/previous click controls in notebooks

---

app/packages/looker/src/index.ts

On `develop`, patches are not set in the thumbnails. Not an issue in v0.12.0.

Fix initial patch zoom for grid thumbnails

---

docs/source/user_guide/dataset_creation/datasets.rst
docs/source/user_guide/export_datasets.rst
fiftyone/utils/bdd.py

Resolves #1206.
```py
import os
data_path = os.path.dirname(dataset.first().filepath)
labels_path = "/tmp/bdd.json"
labels_path=labels_path,
dataset_type=fo.types.BDDDataset,
)
data_path=data_path,
labels_path=labels_path,
dataset_type=fo.types.BDDDataset,
)
sample = dataset.select_fields("ground_truth").first()
sample2 = dataset2.one(F("filepath") == sample.filepath)
print(sample)
print(sample2)
```

Adding support for BDD score field

---

docs/source/integrations/coco.rst
docs/source/integrations/open_images.rst
docs/source/user_guide/dataset_zoo/datasets.rst

We document the parameters that can be passed to `load_zoo_dataset()` for the COCO and Open Images datasets in a couple places in the docs. We do this because:
- The possible parameters are defined in a few different classes and thus linking directly to any one class doesn't fully cover the options
- These two datasets are quite popular, so we want to minimize friction in learning how to download and start using them
This PR switches from ``monospace``-style formatting to **bold** (*default*) style formatting, for consistency with how function arguments are rendered in the actual API docs. This visually helps make the parameters more readable, I think.

Docs formatting tweaks

---

fiftyone/core/collections.py
fiftyone/core/stages.py

Adds support for specifying compound sort criteria when using the `sort_by()` stage.
Example usage:
```py
#
#
view = dataset.sort_by(
[
(F("predictions.detections").length(), -1),
("uniqueness", 1),
]
)
num_objects, uniqueness = view[:5].values(
[F("predictions.detections").length(), "uniqueness"]
)
print(list(zip(num_objects, uniqueness)))
```

Adding support for compound sort criteria

---

docs/source/cli/index.rst
fiftyone/core/cli.py
fiftyone/core/session.py

Adds an integer keyword argument `wait` to `Session.wait()` and a corresponding `--wait` argument to relevant CLI commands.
`session.wait(-1)` permanently blocks execution until a keyboard interrupt, which is useful in cases where you are running an App session that you want to serve "forever".
`session.wait(10)` might be more appropriate than the default wait time (3 seconds) for remote sessions over slow internet connections, where refreshing the App via ctrl + R in the browser could take >3 seconds to re-establish a connection.
```py
session.wait(-1)
session.wait(10)  
```

Configurable session waiting

---

fiftyone/utils/cvat.py

Fixes error that is thrown when loading a `CVATImageDataset` if any of the attributes of the label schema do not contain a list of specified values.

[BUG] Fix error when loading CVATImageDataset with None values

---

fiftyone/server/utils.py

Resolves https://github.com/voxel51/fiftyone/issues/1218.
When tagging/untagging samples/labels from the App, a view stage is now created which first selects only samples/labels whose tags need to be edited, and then the edits are applied to this minimal list.
Since the view stage is significantly faster than the equivalent no-op bulk write operations, this change effectively makes tagging workflows run in `O(# edits)` time, while the previous runtime was `O(# samples/labels)`.
This assertion was verified by applying many variants of tagging/untagging to the BDD100K validation split, which has 10K samples and 300K labels.
Tagging/untagging all 300K labels across all 5 label fields still takes some time (in fact slightly more than before, since a relatively complex view stage that ends up …

Select only relevant objects before editing in App tagging workflow

---

fiftyone/core/collections.py
fiftyone/core/dataset.py
fiftyone/core/odm/database.py
fiftyone/server/main.py

Replaces `$facet` pipelines with logically equivalent multi-threaded aggregation pipelines. 
Facet pipelines in MongoDB run serially, which is not ideal. Moving facets into our own client-side parallelized aggregations leads to much better results.
```py
from time import time
from fiftyone.core.state import DatasetStatistics as DS
bdd = fo.load_dataset("BDD")
start = time()
bdd.aggregate(DS(bdd).aggregations)
end = time()
print(end - start)
``` 
`develop`: 11.538496732711792
`facet-optimization`: 1.7972187995910645
```py
from time import time
import asyncio
from fiftyone.core.state import DatasetStatistics as DS
bdd = fo.load_dataset("BDD")
loop = asyncio.get_event_loop()
start = time() …
```

Facet optimization

---

fiftyone/utils/coco.py
fiftyone/utils/voc.py

Exporting annotations from CVAT creates artifacts that slightly differ from existing formats. This PR updates existing importers to avoid errors and allow importing of attributes when exported from CVAT.
For example, the COCO format when exported from CVAT contains:
```json
{
"id": 34,
"image_id": 9,
"category_id": 2,
"segmentation": [],
"area": 6499.0,
"bbox": [
28.0,
254.0,
97.0,
67.0
],
"iscrowd": 0,
"attributes": {
"label_id": "5f452471ef00e6374aac53ca",
"attribute:iscrowd": "0.0",
"attribute:area": "4827.32605",
"occluded": false
}
},
```
The Pascal VOC format contains:
```
<annotation>
<folder></folder>
<filename>000000.jpg</filename>
<source>
<database>Unknown</database>
<annotation>Unknown</annotation>
<image>Unknown</image>
</source>
<size>
<width>640</width>
<height>480</height> …
```

[BUG] Fix importing COCO, VOC formats when exported from CVAT

---

fiftyone/core/collections.py
fiftyone/core/odm/database.py

Inspired by #1242, updates the aggregation framework to run all pipelines multi-threaded, even ones that aren't facet-able.
```py
import eta.core.utils as etau
dataset = fo.load_dataset("bdd100k-validation")
with etau.Timer():
ids = dataset.values("id")
with etau.Timer():
filepaths = dataset.values("filepath", _big_result=False)
with etau.Timer():
ids, filepaths = dataset.values(["id", "filepath"])
with etau.Timer():
ids, filepaths = dataset.values(["id", "filepath"], _big_result=False)
with etau.Timer():
results = dataset.aggregate(
[
fo.CountValues("detections.detections.label"),
fo.Distinct("detections.detections.label"),
fo.Distinct("scene.label"),
fo.Values("id"),
fo.Values("filepath", _big_result=False), …
```

Aggregation optimizations

---

docs/source/release-notes.rst
docs/source/user_guide/dataset_zoo/datasets.rst
fiftyone/zoo/datasets/base.py

Fixes a documentation bug discovered when resolving https://github.com/voxel51/fiftyone/issues/1252.

Adding missing zip to cityscapes docs

---

fiftyone/utils/cvat.py

This simply includes the subset parameter of each image entry of a cvat dataset, in addition to its filename. The subset was already used in the _image_paths_map of the dataset, but not in the _cvat_images_map. This led to key errors when trying to retrieve an item.
This pull requests makes the _image_paths_map and _cvat_images_map consistent avoiding runtime errors when trying to read a cvat dataset with subdirectories.
This was tested on a local project.
-   [ ] Build: Build …

Fix image map keys when using subset/subdirectory in cvat dataset

---

app/packages/app/src/components/Distributions.tsx
fiftyone/core/aggregations.py
fiftyone/server/main.py

Limits string field histogram results to the first 200, sorted by count in descending order.
```py
F = fo.ViewField
dataset = foz.load_zoo_dataset("cifar100")
dataset.add_sample_field("list_str", fo.ListField, subfield=fo.StringField)
dataset.set_field("list_str", [F("filepath")]).save() # currently crashes the App when `Other fields` is opened
session = fo.Session(dataset)
```

Limit stats results

---

fiftyone/core/collections.py
fiftyone/core/plots/base.py
fiftyone/core/plots/manager.py
fiftyone/core/plots/matplotlib.py
fiftyone/core/plots/plotly.py

Resolves https://github.com/voxel51/fiftyone/issues/1265.
The previous implementation of interactive plotting callbacks relied on all session/plot updates finishing within 0.5 seconds. However, as https://github.com/voxel51/fiftyone/issues/1265 demonstrates, loading views created, for example, by selecting cells in a confusion matrix containing many thousands of labels in a large dataset can easily exceed 0.5 seconds. In such cases, a race condition currently ensues that causes an infinite chain of session/plot updates.
This PR improves the callback logic to prevent such self-update loops. The time-based threshold is still there (now 1 second rather than 0.5) but it's primary function now is just to prevent unnecessary updates due to incessant clicking in the App/plots.
This PR also makes …

Fixing #1265

---

fiftyone/core/collections.py
fiftyone/core/dataset.py

Adds `split_labels()` and `merge_labels()` methods that provide convenient syntaxes for moving labels between new and existing label fields of a dataset.
A typical use case here might be to split off low confidence predictions into a separate field, or split polylines and polygons into separate fields.
```py
print("Total predictions: %d" % dataset.count("predictions.detections"))  # 5620
dataset.split_labels("predictions", "low_conf", filter=F("confidence") < 0.10)
print("Low confidence: %d" % dataset.count("low_conf.detections"))  # 1552
print("Remaining: %d" % dataset.count("predictions.detections"))  # 4068
dataset.merge_labels("low_conf", …
```

Split labels and merge labels

---

docs/source/faq/index.rst
docs/source/user_guide/config.rst
fiftyone/core/odm/database.py

Motivated by https://github.com/voxel51/fiftyone/issues/1268, this PR tweaks the database version verification logic to allow MongoDB versions greater than v4.4 to be used when connecting to a self-installed database, since the preliminary investigations in https://github.com/voxel51/fiftyone/issues/1268 seem to indicate that this will work, and users in environments like Apple Silicon may find it easier to install MongoDB v5 than older versions.
The documentation for connecting to a self-installed database is also improved, including a full example.

Allowing MongoDB v5 custom database usages

---

setup.py

Removes the pin on `opencv-python-headless`. The original reason for this was to prevent building wheels from source for new installs during the few hours the source dist was available, but binary dists were not.
`opencv-python-headless` is popular package, only updated a few times a year, and therefore a loose requirement is likely best.
* Resolves #1282

Relax `opencv-python-headless` version requirement

---

docs/source/conf.py
docs/source/faq/index.rst
docs/source/user_guide/dataset_creation/datasets.rst
docs/source/user_guide/using_datasets.rst
fiftyone/types/dataset_types.py
fiftyone/utils/geotiff.py

Adds a `GeoTIFFDataset` format with support for loading datasets of GeoTIFF images and storing their geolocation data in a `GeoLocation` field.
Since the GeoTIFF standard dictates that GeoTIFF images should be viewable as regular TIFF images, no image type conversion is performed during import. The example below demonstrates that, at least for the example images I found, this assumption is true; i.e., the dataset can be viewed in the App as expected (as long as you have an appropriate TIFF viewer browser extension installed, which I believe is required in browsers like Chrome to view any TIFF image in the first place!)
The [rasterio](https://github.com/mapbox/rasterio) package must be installed in order to work with GeoTIFF images, which seems to be a reasonably popular and stable …

Adding support for loading GeoTIFF images

---

docs/source/integrations/cvat.rst
docs/source/user_guide/annotation.rst
fiftyone/utils/annotations.py
fiftyone/utils/cvat.py

When annotating object tracks on videos in CVAT, the `mutable` property of the attributes determines if the attribute can change in value from one frame to another (`mutable=True`) or if the value of the attribute must remain fixed throughout the track (`mutable=False`). At the moment (and by default in the future unless specified), all attributes are set to `mutable=True`.
This PR allows you to configure the mutable property of attributes in the label schema. It is expected that any future backend that allows for object attribute annotation in video will also support some notion of `mutable`.
Annotating new immutable attributes:
```python
dataset = foz.load_zoo_dataset("quickstart-video", max_samples=1)
attrs = {
"occluded": {
"type": …
```

Expose the mutable property for CVAT attributes

---

docs/source/integrations/cvat.rst
fiftyone/utils/cvat.py

When uploading data to CVAT manually, the options for `use_cache` and `use_zip_chunks` are checked by default. https://openvinotoolkit.github.io/cvat/docs/manual/basics/creating_an_annotation_task/#advanced-configuration
Through the CVAT REST API, these options are set to `False` by default. This PR exposes these parameters to the user when calling `SampleCollection.annotate()` with the CVAT backend similar to the existing `image_quality`.
The primary issue that this resolves is that when `use_zip_chunks` is False, there is a noticeable smoothing and reduction in quality when uploading videos at an `image_quality` of 100.
When `use_zip_chunks=True`:
When `use_zip_chunks=False`:
This can be tested with the following code:
```python
dataset = …
```

Expose CVAT API parameters to upload higher quality video

---

docs/source/integrations/cvat.rst
docs/source/user_guide/annotation.rst
fiftyone/core/collections.py
fiftyone/core/dataset.py
fiftyone/core/labels.py
fiftyone/core/patches.py
fiftyone/core/runs.py
fiftyone/core/video.py
fiftyone/core/view.py
fiftyone/utils/annotations.py
fiftyone/utils/cvat.py
fiftyone/utils/data/exporters.py
fiftyone/utils/data/importers.py
fiftyone/utils/labels.py

Change log
- Renames `semantic_segmentation` label type to `segmentation`
- Renames `segmentation(s)` label types to `instance(s)`
- Added support for supplying mask targets for semantic segmentation tasks
- Added support for polyline vs polygon annotations
- Added a `mask_types="stuff"/"thing"` argument to `Segementation.to_detections()` that allows for control over whether to generate one instance per class (stuff) or one instance per connected region (thing) when converting segmentation masks to detections
- Added a `Segmentation.to_polylines()` method
- Added support for importing/exporting segmentation masks with > 256 classes as uint16 masks when working with `ImageSegmentationDirectory` format
- Fixed a bug that prevented multiple imports of the same annotation run from working as …

Annotation improvements

---

fiftyone/utils/cvat.py

Adds support for interpolating detection, polyline, polygon, and point shapes when loading video annotation tracks from CVAT.
Previously the last keyframe shape was simply repeated between keyframes; now the CVAT interpolation protocol is used instead.
```python
dataset = foz.load_zoo_dataset("quickstart-video", max_samples=1).clone()
dataset.clear_frames()
"video",
classes=["vehicle"],
attributes={
"occluded": {
"type": "radio",
"values": [0, 0.2, 0.5, 1],
"default": 0,
"mutable": False,
}
},
)
input()
dataset.load_annotations("video", cleanup=True)
dataset.delete_annotation_run("video")
session.wait()
```
```python
import …
```

Interpolate CVAT object tracks

---

docs/source/user_guide/config.rst
fiftyone/core/config.py
fiftyone/core/odm/database.py

Relaxes `mongod` validation to only warn if an incompatible version is found. One reason for this change is it enables connections to Amazon DocumentDB (no promises).
Tested with this [guide](https://docs.aws.amazon.com/en_us/documentdb/latest/developerguide/connect-ec2.html)

Only warn during `mongod` compatibility validation

---

fiftyone/utils/eval/base.py

Makes a small change to the default behavior of confusion matrices plotted via the following syntax:
```py
plot = results.plot_confusion_matrix(classes=classes)
plot.show()
```
Previously, if `classes` are provided, no row/column for missing GT/predictions would be included in the confusion matrix unless you explicitly included `results.missing` in the `classes` list.
Now, the row/column for missing GT/predictions is *always* included if there are any, unless you pass the optional `include_missing=False` flag to explicitly remove them.
I think this is a better default behavior, especially for detection evaluation. The issue arose because "missing" is not generally an issue for classification evaluation, and both cases share the same code.
As the examples below demonstrate, the new default …

Including missing GT/predictions by default in confusion matrices

---

fiftyone/core/collections.py
fiftyone/core/stages.py
tests/unittests/view_tests.py

Adds an optional `filter_labels(..., trajectories=True)` flag that allows for matching entire object trajectories (ie, a sequence of labels with the same `index` in a video) for which a given filter matches the object in at least one frame of the video.
This is useful, for example, for matching object trajectories based on time-varying attributes, eg., viewing object trajectories that are occluded at some point during the video.
This example is a bit contrived since one would expect `type` to be an immutable attribute:
```py
view = dataset.filter_labels("frames.detections", F("type") == "sedan", trajectories=True) …
```

Adding support for filtering object trajectories

---

docs/source/cli/index.rst
docs/source/user_guide/config.rst
docs/source/user_guide/using_datasets.rst
fiftyone/core/cli.py
fiftyone/core/dataset.py
fiftyone/core/odm/dataset.py
fiftyone/migrations/revisions/v0_14_0.py
fiftyone/utils/data/importers.py

Adds `created_at` and `last_loaded_at` properties to FiftyOne datasets, which are automatically populated/updated.
**Example dataset**
```py
print(dataset.created_at)  # 2021-08-26 01:57:12.378000
print(dataset.last_loaded_at)  # 2021-08-26 01:57:12.378000
```
**Example use case**
One can use this information, for example, to locate recently used/created datasets. The `fiftyone datasets info` command shown below sorts by last loaded date (if known) as a helpful way to locate datasets that you've recently worked with.
```shell
fiftyone datasets info
fiftyone datasets info --sort-by created_at
fiftyone datasets info --sort-by name --reverse
```
```
name                               created_at …
```

Adding created_at and last_loaded_at properties to datasets

---

fiftyone/core/aggregations.py
fiftyone/core/expressions.py
fiftyone/core/stages.py

Adds `ViewExpression` methods for some previously missing set operations, including `is_subset()`, `set_equals()`, `unique()`, `union()`, `intersection()`, `difference()`, and `contains(..., all=True)`.
See the added documentation for example usages.

Adding set operation expressions

---

docs/source/integrations/cvat.rst
docs/source/integrations/index.rst
docs/source/user_guide/annotation.rst
fiftyone/core/service.py
fiftyone/utils/annotations.py
fiftyone/utils/cvat.py

Adds support for specifying per-class attributes when defining annotation schemas (see below for syntax), and adds support for this to the CVAT backend.
```py
dataset = foz.load_zoo_dataset("quickstart").select_fields().clone()
view = dataset.take(1)
label_schema = {
"animals": {
"type": "detections",
"classes": [
{
"classes": ["cat"],
"attributes": {
"surly": {
"type": "checkbox",
"default": False,
}
}
},
{
"classes": ["dog"],
"attributes": {
"fluffy": {
"type": "checkbox",
"default": False,
}
}
},
],
"attributes": {
"cute": {
"type": "radio",
"values": [True, False],
"default": True,
}
},
},
}
view.annotate("animals", label_schema=label_schema, launch_editor=True)
print(dataset.get_annotation_info("animals")) …
```

Adding support for per-class attributes in annotation schemas

---

fiftyone/utils/annotations.py
fiftyone/utils/cvat.py

Small update that allows the annotation backend to recommend a widget type based on the name/value of an observed attribute.
This feature is used when `attributes=True` is passed (the default) when uploading existing labels for editing.
Note that providing `name` as well as `value` may be useful in situations like detecting that an `occluded` attribute should be wired up to CVAT's dedicated occlusion button.
For example, in the snippet below, a `checkbox` widget type is used for `kite.colorful`, since boolean attribute values are detected.
```py
import random
dataset = dataset[-1:].select_fields("ground_truth").clone()
for detection in …
```

Adding support for annotation backend to recommend attribute widget type

---

fiftyone/core/service.py

Increase the default timeout to allow for the worst case, e.g. windows workflows.
Obviously, even 10 seconds is far slower than what we want for user experience. In due time.

Increase service listener timeout

---

app/packages/app/src/recoil/selectors.ts
app/packages/app/src/utils/labels.ts
app/packages/looker/src/constants.ts
app/packages/looker/src/elements/base.ts
app/packages/looker/src/elements/common/error.ts
app/packages/looker/src/elements/common/tags.ts
app/packages/looker/src/index.ts
app/packages/looker/src/overlays/classifications.ts
app/packages/looker/src/overlays/index.ts
app/packages/looker/src/processOverlays.ts
app/packages/looker/src/state.ts
app/packages/looker/src/util.ts
docs/source/_includes/substitutions.rst
docs/source/user_guide/basics.rst
docs/source/user_guide/dataset_creation/datasets.rst
docs/source/user_guide/export_datasets.rst
docs/source/user_guide/using_datasets.rst
fiftyone/__public__.py
fiftyone/core/fields.py
fiftyone/core/labels.py
fiftyone/core/metadata.py
fiftyone/types/dataset_types.py
fiftyone/utils/data/exporters.py
fiftyone/utils/data/importers.py
fiftyone/utils/data/parsers.py
tests/unittests/import_export_tests.py

Adds a `TemporalDetection` label type that allows a label to be assigned a `[first, last]` frame support in a video.
Also adds support for importing/exporting datasets with `TemporalDetection(s)` label fields in a new `FiftyOneTemporalDetectionDataset` type with format documented at the bottom of this PR.
Finally, for consistency with other `FiftyOne*Dataset` formats, adds support for importing/exporting predictions confidences in `FiftyOneImageClassificationDataset` format. On the export side, this is on an opt-in basis by passing an optional `include_confidence=True` flag during export.
```py
filepath="video1.mp4",
events=fo.TemporalDetections(
detections=[
fo.TemporalDetection(label="party", support=[30, 60]), …
```

Adding a temporal detection label type

---

docs/source/integrations/cvat.rst
docs/source/user_guide/annotation.rst
fiftyone/core/collections.py
fiftyone/utils/annotations.py
fiftyone/utils/cvat.py

Adds optional `allow_additions`, `allow_deletions`, and `allow_spatial_edits` parameters to `annotate()` that allow for configuring whether certain types of edits are allowed in an annotation run.
For example, suppose you have an existing `ground_truth` field that contains objects of various types and you would like to add new `sex` and `age` attributes to all people in this field while also strictly enforcing that no objects can be added, deleted, or have their bounding boxes modified.
You can configure an annotation run for this as follows:
```py
view = (
dataset
.match_labels(filter=F("label") == "person", fields="ground_truth")
.limit(1)
)
anno_key = …
```

Adding support for configuring whether label additions/deletions/spatial edits are allowed during annotation

---

docs/source/integrations/cvat.rst
docs/source/user_guide/annotation.rst
fiftyone/core/collections.py
fiftyone/utils/annotations.py

Adds optional flags that allow for configuring whether labels/attributes can be edited during an annotation run:
- Passing `allow_label_edits=False` to `annotate()` declares that existing object's `label`s cannot be changed
- Including the  `read_only=True` key when uploading existing label attributes declares that the attribute's value should be uploaded to the annotation backend for informational purposes, but the attribute's value cannot be changed
As noted in the docs, annotation backends may not be able to obey these parameters in their editing interface, but these settings will always be enforced when the annotations are imported back into FiftyOne.
For example, the snippet below uploads the vehicle tracks in a video dataset along with their existing `type` attributes and requests …

Adding support for read-only labels/attributes during annotation

---

fiftyone/core/dataset.py

Fixes a subtle bug in the implementation of cloning runs (annotations, evaluations, brain runs) when things like `dataset.clone()` or `dataset.merge_samples(..., include_info=True)` are invoked.
On `develop`, the code below fails, but now works:
```py
files = ['one', 'two', 'three']
classif_1 = ['a', 'a', 'c']
classif_2 = ['a', 'b', 'c']
data = [('first_classif', classif_1), ('second_classif', classif_2)]
full_ds = fo.Dataset()
for dataset_name, labels in data:
samples = []
for sample_name, label in zip(files, labels):
sample = fo.Sample(filepath = sample_name)
annotation = fo.Classification(label=label)
sample[dataset_name] = annotation
samples.append(sample)
ds =  fo.Dataset()
ds.add_samples(samples)
full_ds.merge_samples(ds)
results = …
```

Fixing a subtle run results cloning bug

---

docs/source/integrations/cvat.rst
fiftyone/utils/cvat.py

Resolve #1290 
When annotating videos in CVAT, each video is uploaded to a separate task (unlike images that are loaded into one task). The annotation parameter `task_assignee` allows you to specify the username to assign to the generated task. 
This PR allows `task_assignee` to accept a list of usernames that will be applied, round robin-style, to the created video tasks.
If a single string username is provided to `task_assignee`, it will be applied to all created tasks like before.
```python
dataset = foz.load_zoo_dataset("quickstart-video", max_samples=3).clone()
anno_key = "task_assignees"
anno_key,
task_assignee=["user1", "user2"],
) …
```

Allow a list of task assignees for CVAT

---

fiftyone/utils/annotations.py

Setting `allow_additions` to `False` raised an error when a sample or frame is empty by default.
This example previously raised this error, but now works:
```python
dataset = (
foz.load_zoo_dataset("quickstart", max_samples=2).select_fields("ground_truth")
).clone()
sample.ground_truth = None
sample.save()
anno_key = "empty_test"
anno_key,
allow_additions=False,
)
input()
dataset.load_annotations(anno_key)
```
```
Downloading labels from CVAT...
Download complete
Loading labels for field 'ground_truth'...
0% |/------------------------------| 0/2 [1.4ms elapsed, ? remaining, ? samples/s]
Uncaught exception
File …
```

Fix bug when annotating and allow_additions is False

---

fiftyone/core/dataset.py
fiftyone/core/runs.py
fiftyone/utils/data/importers.py
tests/unittests/import_export_tests.py

Resolves #1385 
```py
view = dataset.limit(1)
view.evaluate_detections("predictions", gt_field="ground_truth", eval_key="test")
view.annotate("test", label_field="ground_truth")
export_dir="/tmp/quickstart",
dataset_type=fo.types.FiftyOneDataset,
)
dataset_dir="/tmp/quickstart",
dataset_type=fo.types.FiftyOneDataset,
)
assert dataset.list_evaluations() == dataset2.list_evaluations()
assert dataset.list_annotation_runs() == dataset2.list_annotation_runs()
```

Fixing import of FiftyOneDataset instances with run results

---

fiftyone/core/dataset.py
fiftyone/core/odm/mixins.py
fiftyone/core/odm/sample.py
fiftyone/utils/beam.py

This PR adds some utilities that leverage [Apache Beam](https://beam.apache.org) to parallelize import, merge, and export operations:
- `beam_import()`: a parallelized alternative to `Dataset.add_samples()`
- `beam_merge()`: a parallelized alternative to `Dataset.merge_samples()`
- `beam_export()`: a parallelized alternative to `SampleCollection.export()`
For now these are just standalone utilities, but in the near future I think it could make sense to add an optional `num_workers` parameter to the main API methods that will optionally leverage Beam to accelerate the operations.
The current implementation of `beam_export()` is only well-suited for export formats that are inherently sharded. For example, it is ideal for exporting a sharded TF record dataset, but not ideal for exporting in …

Apache beam I/O

---

docs/source/integrations/cvat.rst
fiftyone/utils/cvat.py

Labels IDs must be tracked when annotating existing labels in CVAT so that the annotations can be merged back into FiftyOne properly. Previously, the `label_id` of each label was only tracked through a text attribute. This raises issues where the `label_id` attribute can easily be erased when:
1) The class of a label is changed
2) An annotator accidentally modifies the `label_id` attribute
Internally, CVAT stores it's own unique ID for each label. However, this ID was not used in the original implementation of this integration since the CVAT server ID is [subject to change](https://github.com/openvinotoolkit/cvat/issues/893#issuecomment-578020576). 
This PR adds support for tracking the CVAT server ID in addition to the `label_id` attribute in order to add redundancy to the tracking of …

Track label IDs using CVAT server IDs

---

fiftyone/utils/cvat.py

This PR fixes a bug preventing the `server_id_map` from being created when annotating a new label field in CVAT.
This now works:
```python
dataset = foz.load_zoo_dataset("quickstart", max_samples=5).clone()
anno_key = "new_field"
anno_key,
label_field="new_field",
label_type="detections",
classes=["test"],
)
dataset.load_annotations(anno_key, cleanup=True)
session.refresh()
```

[BUG] Fix bug when annotating new fields in CVAT

---

docs/source/environments/index.rst

The `gcsfuse` command didn't work for me.
The help says:
```
USAGE:
gcsfuse [global options] [bucket] mountpoint
```
Reordering the arguments the command worked.
(Details)
-   [ ] Other

bug: gcsfuse command

---

fiftyone/utils/torch.py
fiftyone/zoo/models/manifest-torch.json
tests/misc/torch_tests.py

Added a function "MaxResize" in utils.torch.py and added support for the pipeline to allow an optional parameter "image_max_dim" and "image_max_size" (very similar to image_min_dim and image_min_size". 
This parameter was also added for the model zoo for models with variable image size and was set to 2048 for largest dim of the image.
The MaxResize function is tested in "tests/misc/torch_test.py" but no test is added to verify the full pipeline.
Maybe this test should be located in the "unit-test".
-   [x] Core: Core `fiftyone` Python library …

Fixed model oom

---

fiftyone/server/utils.py

Resolves #1399
```py
sample = fo.Sample(filepath="/path/to/img")
session = fo.Session(sample)
```
In the case of images, the App will work as images are the default, but there is an expectation of properly named media files (with extensions) to distinguish between videos and images in both the Python API and App...

[Server] Handle `None` when guessing mime type

---

fiftyone/utils/annotations.py

When uploading to an existing project in CVAT, you can let the `label_field` and `label_schema` parameters be `None` so any annotations that are made will prompt a new label field upon calling `samples.load_annotations()`.
This PR fixes a bug in this workflow when using video dataset. Previously, an error was raised by the call to `samples._handle_frame_field(lable_field)` when `label_field` is `None`. This PR assumes that all annotations loaded into a video dataset are frame-level labels when `label_field` is `None`.
This now works:
```python
dataset = foz.load_zoo_dataset("quickstart-video", max_samples=2).clone()
anno_key = "anno_none"
project_name="test_none_label_field"
anno_key, …
```

Fix bug when annotating videos in CVAT with None label field

---

.github/workflows/build-docs.yml
.github/workflows/build.yml
docs/source/user_guide/using_datasets.rst
requirements/dev.txt
requirements/docs.txt
requirements/extras.txt

Adds `requirements/extras.txt` for extra packages that can be cross-platform installed via pip for certain optional features.
These requirements are now installed in docs/package build workflows (these had gotten out-of-date and were breaking the docs builds of late).
Unfortunately things like `torch`, `tensorflow`, and `pycocotools` can't be included in this because they require Windows-specific installs.

Updating dependencies for build workflows

---

docs/source/integrations/cvat.rst
fiftyone/utils/cvat.py

This PR adds the `occluded_attr` parameter to the CVAT annotation backend.
This parameter accepts a string of the attribute name used to upload and download to the occlusion widget for all spatial label fields.
The primary use of this is when uploading tasks to an existing CVAT project. In this case, the label schema is ignored in favor of the CVAT schema which does not contain information regarding the attribute(s) linked to the occlusion widget. The `occluded_attr` can be used in this case to upload and download boolean values indicating occlusion to the same attribute for all spatial fields that support the occlusion widget.
```python
import random
random.seed(51)
dataset = foz.load_zoo_dataset("quickstart", max_samples=1).clone()
for …
```

Add global occlusion widget parameter for CVAT annotation runs

---

fiftyone/core/config.py

Requires https://github.com/voxel51/eta/pull/532.
Allows for `~` to be included in config settings such as `database_dir`.
```shell
export FIFTYONE_DATABASE_DIR=~/fiftyone/database
fiftyone config
```

Better handling of relative and user paths

---

fiftyone/core/metadata.py
fiftyone/core/utils.py
requirements/extras.txt

Previously `ImageMetadata.build_for()`---which was used by `SampleCollection.compute_metadata()` to populate metadata for image samples---required loading the entire image into memory.
This PR optimizes the implementation to use `PIL.Image.open()`, which only reads the bare minimum content.
Also, all `Metadata.build_for()` methods can now accept publicly GET-able URLs.
```py
dataset.compute_metadata(overwrite=True)
```

Optimizing image metadata calculation

---

fiftyone/utils/cvat.py

Resolves #1432 
CVAT data is sorted alphabetically by filename after they are uploaded. This can cause issues when uploading annotations that are not in the same order. To resolve this, we modify the filenames of the media to ensure the correct ordering in CVAT. 
Previously, the filenames were simply overwritten with an increasing integer value. This PR prepends this integer value to the filenames in order to retain the original filename while ordering the media correctly.
The alternative is to re-order the annotations to match the original filenames sorted alphabetically, however, the view that is being annotated may be ordered in a specific way for a reason so we should not re-order it ourselves upon upload.

Retain original filenames when annotating in CVAT

---

fiftyone/utils/voc.py

Without the fix contained in this PR, running `fiftyone zoo datasets download voc-2012` fails with an error message saying that a list is not hashable. While the fix itself seems naive (I unfortunately didn't have enough availability to explore the codebase for a longer time) - it seems to be working fine, fixing the original issue.
I've tested it manually, by running the download for `voc-2012` and then loading the dataset and looking at the samples. …

Fix error when downloading VOC dataset

---

fiftyone/utils/annotations.py

This PR raises an error when requesting spatial annotations and the `label_field` doesn't start with `frames.`, as expected.
```py
dataset = foz.load_zoo_dataset("quickstart-video", max_samples=1).clone()
"frames_test",
label_field="new_field",
label_type="instances",
classes=["test"],
)
```
```
ValueError: Invalid label field 'new_field'. Spatial labels of type 'instances' being annotated on a video must be stored in a frame-level field, i.e., one that starts with 'frames.'
```

Raising error when annotating video label field not starting with "frames."

---

docs/source/integrations/cvat.rst
fiftyone/utils/cvat.py

This PR adds support for configuring custom headers to be included in all requests to a CVAT server.
This can be useful for self-hosted CVAT servers in environments like AWS that may require such headers in order to make properly authenticated requests.
Store custom headers in `~/.fiftyone/annotation_config.json`:
```
{
"default_backend": "cvat",
"backends": {
"cvat": {
"config_cls": "fiftyone.utils.cvat.CVATBackendConfig",
"url": "http://localhost:8080",
"username": "...",
"password": "...",
"headers": {"hello": "world"}
}
}
}
```
Then use the annotation API like normal:
```py
dataset = dataset.select_fields("ground_truth").limit(1).clone()
results = dataset.annotate("test", …
```

Adding support for passing headers to CVAT API

---

fiftyone/core/collections.py
fiftyone/core/fields.py
fiftyone/core/frame_utils.py
fiftyone/core/odm/mixins.py
tests/unittests/dataset_tests.py

This PR adds support for implicitly casting int-like and float-like field values to `int` and `float` so they can be stored in the database.
Previously all of the operations below would raise errors but now are allowed:
```py
filepath="image.png",
float1=1.0,
float2=np.float32(1.0),
float3=np.float64(1.0),
int1=1,
int2=np.uint8(1),
int3=np.int64(1),
list_float1=[1.0],
list_float2=[np.float32(1.0)],
list_float3=[np.float64(1.0)],
list_int1=[1],
list_int2=[np.uint8(1)],
list_int3=[np.int64(1)],
)
print(dataset)
print(sample)
sample["float1"] = 2.0
sample["float2"] = np.float32(2.0)
sample["float3"] = np.float64(2.0)
sample["int1"] = 2
sample["int2"] = np.uint8(2)
sample["int3"] = …
```

Gracefully cast all int/float types to python primitives

---

docs/source/integrations/lightning_flash.rst

Until https://github.com/voxel51/fiftyone/issues/1482 is addressed, this PR simply documents the version of Flash/PyTorch-Lightning for which our Flash integration was implemented.

Note explicit Flash version dependency

---

docs/source/user_guide/dataset_creation/datasets.rst
docs/source/user_guide/export_datasets.rst
fiftyone/utils/yolo.py
tests/unittests/import_export_tests.py

YOLOv4 and YOLOv5 import/export with confidence. [Issue](https://github.com/voxel51/fiftyone/issues/1460)
Assert equal detection confidence bounds between base and after export/import.
Updated tests in `tests/unittests/import_export_tests.py` to handle default `include_confidence=False`
and non-default `include_confidence=True` cases in `test_yolov4_dataset` and `test_yolov5_dataset`
Set `include_confidence=False` when exporting a dataset in YOLOv4/YOLOv5 formats to include confidence.
Importing datasets in YOLOv4/YOLOv5 formats automatically loads confidence if it's present in a txt file with detections.
-   [ ] App: FiftyOne …

Adding support for importing/exporting confidence in YOLO formats

---

fiftyone/utils/cvat.py

This PR fixes a bug when annotating multiple track segments and the first segment is of length 1.
This works now:
```python
dataset = foz.load_zoo_dataset("quickstart-video", max_samples=1).select_fields().clone()
dataset.ensure_frames()
det = fo.Detection(label="test", bounding_box=[0.1,0.2,0.3,0.4], index=1)
dets = fo.Detections(detections=[det])
frame_list = [1, 3] 
for frame_num in frame_list:
frame = sample.frames[frame_num]
frame["detections"] = dets
sample.save()
"test",
)
```
The root cause of this error is that an `outside` shape cannot be the first shape in a track (even though the frame number is an attribute of the shape so the ordering of shapes in the …

Fix CVAT single frame track bug

---

docs/source/integrations/cvat.rst
docs/source/user_guide/annotation.rst
fiftyone/core/collections.py
fiftyone/utils/annotations.py

Resolves #1477
When unexpected annotations have been added during an annotation run, the only way to load them currently is with access to an interactive prompt which may not always be available in all workflows. This PR replaces the old `skip_unexpected=True/False` parameter of `load_annotations()` with a more powerful `unexpected` parameter with the following options:
```
unexpected ("prompt"): how to deal with any unexpected labels that
don't match the run's label schema when importing. The supported
values are:
-   ``"prompt"``: present an interactive prompt to direct/discard
unexpected labels
-   ``"ignore"``: automatically ignore any unexpected labels
-   ``"return"``: return a dict containing all unexpected labels,
or ``None`` if there aren't any
```
Example usage:
```python
import …
```

Return sample IDs with unexpected annotations

---

requirements/docs.txt

The current section highlight in the RHS table of contents in the docs is currently broken in production. I believe the `nbsphinx` version change in https://github.com/voxel51/fiftyone/pull/1411 was the culprit.

Reverting nbsphinx version

---

docs/source/user_guide/dataset_creation/datasets.rst

Users have (rightly) been confused by the fact that `COCODetectionDatasetImporter` defaults to `label_types="detections"`.
This PR updates the documentation to explicitly mention this and to clearly document how to load additional label types like segmentations if they are present.

Documenting default COCO label_types

---

docs/source/user_guide/config.rst

Adds a note to the docs about connecting to custom MongoDB databases with authentication enabled.

Adding admin DB note to docs

---

fiftyone/core/dataset.py
fiftyone/utils/bdd.py
fiftyone/utils/coco.py
fiftyone/utils/cvat.py
fiftyone/utils/data/importers.py
fiftyone/utils/geojson.py
fiftyone/utils/kitti.py
fiftyone/utils/voc.py

Adds support for directly passing a `filename -> filepath` mapping dict to the `data_path` parameter of importers.
Previously one could only pass the path to a JSON path on disk containing the mapping, but in many workflows it is more natural to construct + provide the mapping in-memory.

Adding support for passing data map directory to importers

---

fiftyone/utils/cvat.py

This PR allows CVAT server URLs to contain a trailing `/` without raising errors when working with our CVAT API.
```python
import fiftyone.utils.cvat as fouc
url = "https://cvat.org"
api = fouc.CVATAnnotationAPI("cvat", url)
url = "https://cvat.org/"
api = fouc.CVATAnnotationAPI("cvat", url)
```

Sanitize CVAT URLs

---

docs/source/integrations/cvat.rst
fiftyone/utils/cvat.py

Resolves #1448
The CVAT REST API imposes a limit on the size of requests. This can cause errors when uploading annotation runs for sample collections with many images or labels to CVAT.
In order to break an annotation run into smaller segments, this PR adds a `task_size` parameter that limits the number of samples that can be uploaded to a single task in CVAT. Due to the creation of multiple tasks when `task_size` is provided, we recommend providing a `project_name` to group the created tasks together.
The `task_size` parameter can be used in conjunction with `segment_size` to both define the number of images per task and the number of images per job within the task.
```python
dataset = foz.load_zoo_dataset("quickstart", …
```

Add task_size parameter to CVAT backend

---

fiftyone/core/odm/document.py
fiftyone/core/odm/mixins.py

I spent more time than I'd like to admit trying to properly fix https://github.com/voxel51/fiftyone/issues/1462, but this is where I got.
Ideally we would update the implementation of our `Document` classes so that fields can have arbitrary names and can always be accessed via `document[field]`, which is important in the case where a field clashes with a method name on the class, like `field="to_dict"`, which currently breaks things, since `document.to_dict` will currently return the user's data rather than invoke the method. This needs to be updated so that `document.to_dict` will always reference the method rather than the user's data in the case of clashes. Unfortunately, that's not easily achievable until we get rid of MongoEngine.
For now, I just removed the error that prevents …

Partial work on #1462

---

fiftyone/utils/torch.py
tests/misc/torch_tests.py

Resolves #1496.
#1444 introduced a regression that prevented `TorchImagePatchesDataset` from handling patches defined by `Polyline`/`Polylines` label fields. This PR fixes that.
```py
dataset = foz.load_zoo_dataset("quickstart").select_fields().limit(1).clone()
model = foz.load_zoo_model("mobilenet-v2-imagenet-torch")
points = [
(0.7416666666666667, 0.28055555555555556),
(0.6984375, 0.325),
(0.6619791666666667, 0.2759259259259259),
(0.7057291666666666, 0.2324074074074074),
]
polyline = fo.Polyline(
label="diamond", points=[points], closed=True, filled=True
)
polylines = fo.Polylines(polylines=[polyline])
sample["polyline"] = polyline
sample["detection"] = polyline.to_detection()
sample["polylines"] = polylines …
```

Fixing bug in computing patch embeddings defined by polylines

---

fiftyone/zoo/models/manifest-tf.json

The following models are added:
centernet-hg104-1024-coco-tf2
centernet-resnet101-v1-fpn-512-coco-tf2
centernet-resnet50-v2-512-coco-tf2
centernet-mobilenet-v2-fpn-512-coco-tf2
efficientdet-d0-512-coco-tf2
efficientdet-d1-640-coco-tf2
efficientdet-d2-768-coco-tf2
efficientdet-d3-896-coco-tf2
efficientdet-d4-1024-coco-tf2
efficientdet-d5-1280-coco-tf2
efficientdet-d6-1280-coco-tf2
efficientdet-d7-1536-coco-tf2
ssd-mobilenet-v2-320-coco17
ssd-mobilenet-v1-fpn-640-coco17
```
dataset = foz.load_zoo_dataset("quickstart").select_fields().clone()
view = dataset.limit(10)
print(foz.list_zoo_models())
model = foz.load_zoo_model("<base-name>")
view.apply_model(model, label_field="predictions")
```
-   [X] No. You can …

Adding TF2 models to zoo

---

fiftyone/core/expressions.py
fiftyone/core/utils.py
tests/unittests/view_tests.py

Resolves https://github.com/voxel51/fiftyone/issues/1502.
The issue was that apparently MongoDB's `{$toDate: arg}` for some reason seems to require `arg` to be a `float` or a `long` but **NOT** an `int`. The lack of `int` support meant that expressions involving datetimes too close to the epoch would result in MongoDB expressions involving ints that would raise an error!
```py
dataset.add_samples(
[
fo.Sample(
filepath="image1.png",
capture_date=datetime(1970, 1, 1, 1, 0, 0),
),
fo.Sample(
filepath="image2.png",
capture_date=datetime(1970, 1, 1, 2, 0, 0),
),
fo.Sample(
filepath="image3.png",
capture_date=datetime(1970, 1, 1, 3, 0, 0),
),
]
)
print(dataset.match(F("capture_date") …
```

Fixing expressions containing near-epoch dates

---

docs/source/integrations/cvat.rst
fiftyone/utils/annotations.py
fiftyone/utils/cvat.py

An alternative implementation of https://github.com/voxel51/fiftyone/pull/1456 that also implements the TODO items mentioned there.
Other changes
- Added new ``unexpected="keep"`` option to `load_annotations()`
- `%06d_` is no longer prepended to video filenames in CVAT, since it is not necessary (always one video per task)
- Optimized database I/O in `_create_shapes_tags_tracks()` and `_build_frame_id_map()`
```py
import os
import fiftyone.core.utils as fou
import fiftyone.utils.cvat as fouc
dataset = dataset.select_fields("ground_truth").clone()
task_size = 10
"test",
task_size=task_size,
segment_size=3,
project_name="test",
)
#
#
# …
```

Import existing CVAT datasets into FiftyOne (#2)

---

docs/source/integrations/cvat.rst
fiftyone/utils/cvat.py
fiftyone/utils/video.py

Adds a `download_media=True` option to `import_annotations()`  that downloads the media associated with a given CVAT project or tasks along with the annotations.
[CVAT force re-encodes all videos as MP4s at 25fps](https://github.com/openvinotoolkit/cvat/blob/cde33acf5da2c29b5c70dec7df688af60734e1a7/cvat/apps/engine/media_extractors.py#L590-L595), so, in general, this workflow is not an advisable way to distribute video datasets.
```py
import fiftyone.utils.cvat as fouc
"test",
segment_size=3,
project_name="test",
)
fouc.import_annotations(
dataset,
project_name="test",
data_path="/tmp/cvat_example", …
```

Adding support for downloading media from existing CVAT tasks/projects

---

fiftyone/utils/coco.py

Previously an error would arise when importing segmentation data from a COCO JSON that contains an object with `segmentation: []`. Now, such an empty list will be gracefully handled as missing segmentation data.
```py
import eta.core.serial as etas
d = {
"info": {},
"licenses": [],
"categories": [
{
"id": 0,
"name": "bird",
"supercategory": None,
}
],
"images": [
{
"id": 1,
"file_name": "/path/to/image.jpg",
"height": 480,
"width": 640,
"license": None,
"coco_url": None,
}
],
"annotations": [
{
"id": 1,
"image_id": 1,
"category_id": 0,
"bbox": [135.0, 2.0, 296.0, 453.0],
"segmentation": [],
},
]
}
labels_path = "/tmp/coco.json"
etas.write_json(d, labels_path)
dataset = fo.Dataset.from_dir(
labels_path=labels_path,
dataset_type=fo.types.COCODetectionDataset, …
```

Gracefully handle empty segmentation data in COCO format

---

.github/workflows/build.yml
MANIFEST.in
setup.py

Adds a source distribution for the published package, which can installed with:
```
pip install fiftyone --no-binary fiftyone
```
in which case, the opencv dependency is dynamically configured based on the environment, .e.g. Google's Colab.

Publish source distributions

---

docs/source/user_guide/export_datasets.rst

Updates documentation examples of exporting in `CVATVideoDataset` format to use `frame_labels_path` instead of `labels_path` to export frame-level labels.
```python
export_dir = "/path/for/cvat-video-dataset"
label_field = "frames.ground_truth"  # for example
dataset_or_view = fo.Dataset(...)
dataset_or_view.export(
export_dir=export_dir,
dataset_type=fo.types.CVATVideoDataset,
label_field=label_field,
)
```
Changed to
```python
export_dir = "/path/for/cvat-video-dataset"
label_field = "ground_truth"  # for example
dataset_or_view = fo.Dataset(...)
dataset_or_view.export(
export_dir=export_dir,
dataset_type=fo.types.CVATVideoDataset,
frame_labels_field=label_field,
)
````

Update CVATVideoDataset export argument documentation

---

docs/source/user_guide/config.rst
fiftyone/core/config.py
fiftyone/core/labels.py
fiftyone/core/metadata.py
fiftyone/core/odm/document.py

Adds support for defining custom `EmbeddedDocument` and `DynamicEmbeddedDocument` classes, which can then be used to populate arbitrary top-level sample fields or nested fields.
A new `module_path` config setting is added where you can register the modules in which your custom embedded document classes are defined. Any modules in this list will automatically be imported whenever FiftyOne is imported so that datasets with your custom fields can be loaded.
First, define some custom embedded document classes in a `foo.bar` module:
```py
import fiftyone.core.fields as fof
class Test(foo.EmbeddedDocument):
field = fof.IntField()
class DynamicTest(foo.DynamicEmbeddedDocument):
field = fof.IntField()
```
Next, add `foo.bar` to FiftyOne's `module_path` config …

Adding support for defining custom EmbeddedDocument classes

---

fiftyone/core/collections.py
fiftyone/core/dataset.py
fiftyone/core/stages.py
fiftyone/core/view.py

Adds a boolean view indexing syntax:
```py
view = sample_collection[bool_array]
```
as a shorthand for:
```py
ids = itertools.compress(sample_collection.values("id"), bool_array)
view = sample_collection.select(ids)
```
Also adds a boolean expression indexing syntax:
```py
view = sample_collection[bool_expr]
```
as shorthand for:
```py
view = sample_collection.match(bool_expr)
```
```py
expr = F("uniqueness") > 0.7
view1 = dataset.match(expr)
print(view1)
bools = dataset.values(expr)  # list/array of booleans
view2 = dataset[bools]
print(view2)
view3 = dataset[expr]
print(view3)
```

Adding support for boolean view indexing

---

fiftyone/core/view.py

Solves #1223 
Visual similarity now updates the stage if the k value is unchanged from the previous one. 
Quick test:
```py
fob.compute_similarity(dataset, brain_key="image_sim")
query_id = dataset.first().id
stage = fo.SortBySimilarity(query_id)
view = dataset.add_stage(stage)
query_id = dataset.last().id
stage = fo.SortBySimilarity(query_id)
view = view.add_stage(stage)
session.view = view
session.wait()
```
Before:
After:
Additionally, you can try the click image + sort by similarity UI workflow. 
notes for …

Update visual similarity stage in-place when possible in App workflows

---

docs/source/user_guide/dataset_creation/datasets.rst
docs/source/user_guide/dataset_creation/index.rst
fiftyone/utils/yolo.py
tests/unittests/import_export_tests.py

When adding yolo labels, a user can set missing predictions to empty detections `fo.Detections(detections=[]`.
[Issue](https://github.com/voxel51/fiftyone/issues/1543)
```
fouy.add_yolo_labels(
dataset2,
"predictions",
"/tmp/yolov4/predictions",
classes=classes,
include_missing=False, # or set include_missing=True to treat missing labels as empty detections
)
```
Added a new unit-test for both `add_yolo_labels` and `add_coco_labels`.
-   [ …

optionally treat missing labels as empty detections when adding yolo labels

---

fiftyone/utils/annotations.py

When annotating an existing label field, there is logic in place to automatically detect the type of the label field being annotated. Some label fields can be associated with multiple annotation label types (detections can be bounding boxes or segmentation instances, polylines can be polylines or polygons). 
There is a bug when annotating an existing label field but all samples in the view have `None` values for the field. This PR resolves this bug by simplifying the logic to detect existing label types.
```python
d1 = foz.load_zoo_dataset("quickstart", max_samples=4).clone()
dataset = d1[:3].clone()
anno_key="anno_key"
anno_key, 
label_field="segs", 
label_type="polylines",
classes=["a", "b"], 
) …
```

Resolve bug when annotating existing fields with multiple label types

---

fiftyone/core/labels.py
fiftyone/utils/coco.py
fiftyone/utils/eta.py
fiftyone/utils/labels.py
fiftyone/utils/patches.py

Uses https://github.com/voxel51/eta/pull/545.
Change log:
- Adds a new `fiftyone.utils.labels.instances_to_polylines()` method that can convert instance segmentations (or just bboxes) to `Polylines` format
- Adds support for frame labels to all conversion methods in the `fiftyone.utils.labels` module
- Updates the implementation of `Detection.to_polyline()` so that all attributes are included rather than just ETA-supported ones
```py
import fiftyone.utils.labels as foul
"coco-2017",
label_types=["segmentations"],
max_samples=100,
shuffle=True,
)
classes = dataset.distinct("ground_truth.detections.label")
mask_targets = {idx: label for idx, label in enumerate(classes, 1)} …
```

Label conversion utility improvements

---

Dockerfile

[Installing Python through apt results in packages](https://stackoverflow.com/questions/9387928/whats-the-difference-between-dist-packages-and-site-packages) being stored in `dist-packages` instead of `site-packages`. This PR updates the Dockerfile example of automatically launching the App.

Update Dockerfile example

---

fiftyone/utils/cvat.py

Cleans up the usage of requests in the CVAT API and updates the message for authentication errors.
```python
dataset = foz.load_zoo_dataset("quickstart").take(1).clone()
"anno_key",
url="https://cvat.org",
username="fake_username",
password="fake_password",
)
```

Update CVAT request error handling

---

.github/workflows/build.yml
fiftyone/core/collections.py
fiftyone/core/stages.py
tests/unittests/import_export_tests.py

Resolves https://github.com/voxel51/fiftyone/issues/1545.
Adds an optional `dist_field` parameter that can specify the name of a (new or existing) float field in which to store query distances when [sorting by similarity](https://voxel51.com/docs/fiftyone/user_guide/using_views.html#visual-similarity):
```py
fob.compute_similarity(dataset, brain_key="img_sim")
view = dataset.sort_by_similarity(dataset.shuffle().first().id, dist_field="dist")
```
This feature can be used when [sorting by similarity in the App](https://voxel51.com/docs/fiftyone/user_guide/app.html#sorting-by-visual-similarity), but currently the `dist_field` must be added …

Adding support for populating query distances when sorting by similarity 

---

README.md

Fixes the README's slack link. I checked the website, docs, and app slack links and they are functional.

Fix README slack link

---

fiftyone/utils/activitynet.py
fiftyone/utils/youtube.py

There was a recent update from YouTube that is causing issues with video downloading utilities like Pytube used in FiftyOne. This PR adds a patch to work around this issue for the current version of Pytube.
```python
import fiftyone.utils.youtube as fouy
urls = ["https://www.youtube.com/watch?v=---9CpRcKoU"]
fouy.download_youtube_videos(urls, download_dir="/tmp/youtube_test")
```
Previously would raise error:
```
Failed to download video 'https://www.youtube.com/watch?v=---9CpRcKoU': 'NoneType' object has no attribute 'span'
```

Apply patch to YouTube download utilities

---

docs/source/recipes/custom_importer.ipynb

A minor typo in the docs was corrected. (from "FiftyOne either the TensorFlow..." to  "FiftyOne either uses the TensorFlow..."
Not tested.
-   [ ] Other

Fix typo in docs (notebook for Writing Custom Dataset Importers)

---

fiftyone/core/aggregations.py
tests/unittests/aggregation_tests.py

Resolves an aggregation bug that would previously cause an error when writing aggregations on video datasets that involve applying expressions directly to `F("frames")`.
Examples:
```py
num_objects = F("frames").map(F("detections.detections").length()).max()
print(dataset.count_values(num_objects))
clips = dataset.to_clips(F("detections.detections").length() > 5)
duration = F("frames").length() / F("$metadata.frame_rate")
print(clips.bounds(duration))
```

Fixing frame aggregations

---

fiftyone/core/labels.py
fiftyone/utils/coco.py
fiftyone/utils/eta.py
fiftyone/utils/torch.py

Fixes #1581 
Replacing Keypoint.confidence to Keypoint.confidences
Fixing COCO import to not skip over v=0, instead set visible to false
Populating optional visible field in coco.py/torch.py
Tested locally on COCO-2017 with keypoint import. This is the sample output from COCO import
```
<Keypoint: {
'id': '61fc66d8c50045c0978ff8ed',
'attributes': BaseDict({}),
'tags': BaseList([]),
'label': 'person',
'points': BaseList([
BaseList([0.585480093676815, 0.3328125]),
BaseList([0.629976580796253, 0.2625]),
BaseList([0.4894613583138173, 0.271875]),
BaseList([nan, nan]),
BaseList([0.26697892271662765, 0.2796875]),
BaseList([0.9391100702576113, 0.5359375]),
BaseList([0.09836065573770492, 0.6109375]),
BaseList([nan, nan]),
BaseList([nan, nan]), …
```

Add support for per-point confidences in Keypoint class

---

docs/source/integrations/cvat.rst
fiftyone/utils/cvat.py

CVAT provides the ability to link a task to the arbitrary URL of an issue tracker. This PR exposes the `issue_tracker` argument when annotating with the CVAT backend to pass in one or more URL strings to attach to the created task(s).
```python
dataset = foz.load_zoo_dataset("quickstart", max_samples=1).clone()
"anno_key",
issue_tracker="https://fiftyone.ai",
)
dataset.load_annotations("anno_key", cleanup=True)
```

Add argument to link issue tracker to CVAT tasks

---

fiftyone/core/odm/__init__.py
fiftyone/core/odm/database.py
fiftyone/migrations/runner.py

Stores the database version in a new `config` collection.
Previously, the DB version was stored on disk in a `${fiftyone.config.database_dir}/config.json` file, which was problematic when connecting to centralized databases via `database_uri`, because each new client would think it was connecting to a new database and run all upward admin migrations.
Upgrading to and downgrading from this branch is seamless.

Storing database version in the db

---

docs/source/user_guide/using_views.rst
fiftyone/core/clips.py
fiftyone/core/dataset.py
fiftyone/core/patches.py
fiftyone/core/video.py
fiftyone/core/view.py
tests/unittests/patches_tests.py
tests/unittests/video_tests.py
tests/unittests/view_tests.py

Adds a `keep_fields()` method to `DatasetView` and its subclasses that complements the existing `save()` and `keep()` methods:
- `view.save()`: saves the **contents** of (only) the samples/fields in the view to the source dataset
- `view.keep()`: deletes all **samples** not in the view from the source dataset
- `view.keep_fields()`: deletes all **fields** not in the view from the source dataset's schema
The behavior of `keep_fields()` for patch/frame/clip views is a bit subtle, but things are implemented in a logically consistent way. For example, calling `keep_fields()` on a frames view will delete fields from the *sample schema* of the frames view but the *frame schema* of the source video dataset.
```py
dataset = …
```

Adding a keep_fields() method

---

fiftyone/core/dataset.py
fiftyone/core/odm/__init__.py
fiftyone/core/odm/database.py
fiftyone/migrations/revisions/admin/v0_15_0.py
fiftyone/migrations/runner.py
setup.py

Previously `dataset.delete()` would delete all documents from the dataset's sample/frame collections, but the actual collections would not be dropped. This PR resolves that.
A consequence of the previous behavior is that all FiftyOne users have 2 empty collections hanging around in their database for every dataset they've ever created and then deleted (ie non-persistent datasets that are automatically deleted when exiting a session). Therefore, an admin migration is included that deletes all of these orphan collections.

Drop collections when deleting datasets

---

docs/source/cli/index.rst
docs/source/recipes/convert_datasets.ipynb
fiftyone/core/cli.py
fiftyone/core/collections.py
fiftyone/utils/data/converters.py
fiftyone/utils/tf.py
tests/unittests/import_export_tests.py

Change log
- Resolves https://github.com/voxel51/fiftyone/issues/1606
- Adds an optional `force_rgb=True` syntax when importing/exporting/creating TF records using all relevant methods in `fiftyone.utils.tf`
- Adds support for passing additional kwargs to the `fiftyone convert` method
`force_rgb=True` usage:
```py
import os
import cv2
import eta.core.image as etai
import eta.core.utils as etau
rgb_dataset1 = foz.load_zoo_dataset(
"cifar10", split="test", max_samples=100, shuffle=True
)
rgb_dataset1.export(
export_dir="/tmp/color",
dataset_type=fo.types.ImageClassificationDirectoryTree,
)
etau.ensure_empty_dir("/tmp/grayscale", cleanup=True)
for idx, sample in enumerate(rgb_dataset1, 1):
label = sample.ground_truth.label …
```

TF records and conversion utility improvements

---

fiftyone/utils/tf.py

Simple modification to enable TFExampleGenerator to remove alpha channel if `force_rgb=True`. This addresses a current bug where attempting to export the patches of 4-channel images errors even if `force_rgb=True`.
I have not implemented automatic tests.
-   [ ] Other

in TFExampleGenerator, remove alpha channel if force_rgb=True

---

fiftyone/utils/coco.py

Redefined "info" variable initialization in line 1273 _parse_coco_detection_annotations definition so that it will always be a dictionary type even if info in the annotation json file is defined as null, NoneType, or anything other than DictType.
This avoids value assignment issues with line 1280 or 1283 in coco.py
Tested by trying to load Objects365 object detection database, which in its annotation json files, defines:
```
"info":  null,
```
Code used to test fix:
```
val_name = "obj365Val"
val_data_path = "C:/Users/UserName/Datasets/Objects365/Images/val"
val_labels_path = "C:/Users/UserName/Datasets/Objects365/Annotations/val.json"
obj365ValDataset = fo.Dataset.from_dir(
name = val_name,
dataset_type=fo.types.COCODetectionDataset,
data_path=val_data_path, …
```

Update fiftyone/utils/coco.py to fix bug #1629

---

fiftyone/core/aggregations.py
fiftyone/core/expressions.py
tests/unittests/view_tests.py

This PR adds the ability to slice by ViewFields and fixes a bug with expressions.
Figure out why unwinding produces different results:
```python
filepath="test.png",
slice_size=5,
test_list=list(range(10)),
)
print(dataset.values(F("test_list")[:5], unwind=True))
print(dataset.values(F("test_list")[:F("slice_size")], unwind=True))
```
Slicing by ViewFields:
```python
filepath="test.png",
slice_size=5,
test_list=list(range(10)),
)
print(dataset.values(F("test_list")[:5]))
print(dataset.values(F("test_list")[4:5])) …
```

ViewExpression slice updates

---

.github/ISSUE_TEMPLATE/bug_report_template.md
docs/source/getting_started/troubleshooting.rst

Changelog:
* Adds troubleshooting notes about `ulimit` and `libssl` related to MongoDB issues
* Adds note to use screenshots in the bug report issue template

Add `ulimit` and `libssl` troubleshooting notes 

---

fiftyone/utils/image.py

Add documentation about outdated metadata after resizing images with `transform_images`.
Not tested. It's documentation only. Please LMK if the format is off.
-   [ ] Other

Add note about outdated metadata in transform_images

---

fiftyone/core/aggregations.py
fiftyone/core/expressions.py
tests/unittests/aggregation_tests.py

Fixes a bug that prevented frames from being attached to video collections when aggregating expressions like the following:
```py
values = dataset.values((F("field") > 0) | (F("frames").length() > 10))
```
that involve both sample-level and frame-level fields.
A unit test is added to verify correct behavior going forward.

Frame expressions fix

---

fiftyone/utils/annotations.py
fiftyone/utils/cvat.py
fiftyone/utils/labelbox.py

Resolves #1430 
Adds a property to annotation backends to decide whether to allow annotation of video-level labels. CVAT does not provide a way to annotate labels at a video-level, and while Labelbox does, there is currently a bug that needs to be resolved before the annotations can be loaded: #1654 
Note: This primarily refers to classifications, spatial label can never be annotated at a video-level as that concept is not well defined.
```python
dataset = foz.load_zoo_dataset("quickstart-video", max_samples=1).clone()
"anno_key",
label_field="class",
classes=["test"],
label_type="classification",
)
dataset.load_annotations("anno_key", cleanup=True)
```
Previously would raise an error when loading annotations which …

Disallow video-level annotation

---

fiftyone/utils/annotations.py
tests/intensive/cvat_tests.py

When creating an annotation task, there is currently a bug where views using the `MapLabels` stage will result in labels that were mapped not being uploaded to the annotation backend. This PR ensures that labels that were mapped are uploaded and that the mapping is reversed upon loading the annotated labels.
This is only applicable for labels where the class was not modified, any labels that were created or the class was modified will use the mapped class name. This is because a label mapping can result in multiple class names mapped to one, so there is no way to reverse the mapping for labels that were changed or created.
```python
dataset = (
foz.load_zoo_dataset("quickstart", max_samples=1)
.select_fields("ground_truth")
.clone()
) …
```

Resolve bug when annotating views with mapped labels

---

fiftyone/core/collections.py
fiftyone/core/dataset.py
fiftyone/core/document.py
fiftyone/core/stages.py
tests/unittests/dataset_tests.py

Adds a `Dataset.delete_frames()` method that allows for deleting frames by ID.
Example usage:
```py
print(dataset.count("frames"))
dataset1 = dataset.clone()
sample1 = dataset1.first()
sample2 = dataset1.last()
dataset1.delete_frames([sample1, sample2])
print(dataset1.count("frames"))
dataset2 = dataset.clone()
sample = dataset2.first()
dataset2.delete_frames(sample)
print(dataset2.count("frames"))
dataset3 = dataset.clone()
del_view = dataset3.take(5)
dataset3.delete_frames(del_view)
print(dataset3.count("frames"))
dataset4 = dataset.clone()
del_view = dataset4.match_frames(F.rand() < 0.5)
frame_ids = del_view.values("frames.id", unwind=True) …
```

Adding a delete_frames() method

---

fiftyone/utils/coco.py

Previously exporting in [COCO format](https://voxel51.com/docs/fiftyone/user_guide/export_datasets.html#cocodetectiondataset) would only include the `iscrowd` attribute in the JSON if the attribute is actually populated on the collection being exported. This was problematic for certain downstream stages of COCO workflows, which will assume that `iscrowd: 0` is always populated if no crowd data is available.
This PR will now export `iscrowd: 0` if now crowd data is available.
```py
dataset = foz.load_zoo_dataset("quickstart", max_samples=1)
dataset.delete_sample_field("ground_truth.detections.attributes")
labels_path="/tmp/labels.json",
dataset_type=fo.types.COCODetectionDataset,
)
```
```shell …
```

Always populate iscrowd field when exporting COCO labels

---

docs/source/integrations/coco.rst
docs/source/user_guide/basics.rst
docs/source/user_guide/evaluation.rst
docs/source/user_guide/using_datasets.rst
docs/source/user_guide/using_views.rst
fiftyone/core/dataset.py
fiftyone/migrations/revisions/v0_16_0.py
setup.py

Change log
- Adds a database migration that infers embedded document schemas for existing datasets
- Updates the schema of the `metadata` field when a dataset's `media_type` is set

Embedded document schema updates (take 2)

---

docs/source/cli/index.rst
docs/source/getting_started/install.rst
docs/source/user_guide/config.rst
fiftyone/core/cli.py
fiftyone/core/config.py
fiftyone/migrations/revisions/v0_16_0.py
fiftyone/migrations/runner.py

Adds a `database_admin` config setting that can optionally be used to disallow database/dataset migrations.
Also fixes some migration edge cases that were missed in https://github.com/voxel51/fiftyone/pull/1666.

Adding database admin config setting

---

fiftyone/utils/cvat.py

Resolves #1668 
Automatically add the `Referer` header to CVAT requests session if it does not exist to avoid the CSRF error.
This now works without needing to manually provide the `Referer` header.
```python
dataset = foz.load_zoo_dataset("quickstart", max_samples=1).clone()
anno_key = "csrf_bug"
anno_key,
url="https://cvat.org",
username=USERNAME,
password=PASSWORD,
)
dataset.load_annotations(anno_key, cleanup=True)
```

Fix CVAT CSRF bug

---

fiftyone/resources/cvat_image_annotation_template.xml
fiftyone/utils/cvat.py

Resolves #1682 
Exports classification attributes as tag attributes in `CVATImageDataset` format.
```python
dataset = foz.load_zoo_dataset("quickstart", max_samples=1).select_fields().clone()
sample["cls"] = fo.Classification(label="test", attr1="val1")
sample.save()
labels_path="/tmp/coco_test.xml",
dataset_type=fo.types.CVATImageDataset,
)
```
`/tmp/coco_test.xml`:
```
...
</task>
<dumped>2022-04-15T11:35:21.237133</dumped>
</meta>
<image id="0" name="000880.jpg" width="640" height="480">
<tag label="test">
<attribute name="attr1">val1</attribute>
</tag>
</image>
</annotations>
```

Export tag attributes for CVATImageDatasets

---

fiftyone/core/utils.py
fiftyone/utils/bdd.py
fiftyone/utils/coco.py
fiftyone/utils/cvat.py
fiftyone/utils/data/importers.py
fiftyone/utils/geojson.py
fiftyone/utils/kitti.py
fiftyone/utils/openlabel.py
fiftyone/utils/voc.py
fiftyone/utils/yolo.py

Resolves https://github.com/voxel51/fiftyone/issues/1675.
Also, all import formats will support Unix (`"path/to/image.jpg"`) or Windows-style (`"path\\to\\image.jpg"`) paths in labels files and data manifests, which will be properly normalized on all OSes.

Fixing #1675

---

fiftyone/__init__.py
fiftyone/__public__.py
fiftyone/constants.py
fiftyone/core/odm/database.py
fiftyone/core/service.py
fiftyone/service/main.py

Resolves https://github.com/voxel51/fiftyone/issues/1345
This is an alternate solution to #1687. 
Automatically delete non-persistent datasets upon sole connection to the database. This happens on connection time instead of exit.
Quickly test by running the following steps:
1. Open a new terminal session (Session # 1) and run `python`:
```python
fo.list_datasets()  # non-persistent dataset is listed
```
2. Keep Session # 1 running.
3. Open another terminal session (Session # 2):
```bash
fiftyone datasets list  # non-persistent dataset is listed
```
4. Exit `python` in  Session # 1.
5. Back to Session # 2:
```bash
fiftyone datasets list  # non-persistent dataset should no longer be listed
```
Should work for both a built-in and external Mongo …

Automatically delete non-persistent datasets when using custom database URIs

---

.pre-commit-config.yaml
requirements/dev.txt

The FiftyOne project currently supports Python 3.6+, and I currently do my development with Python 3.6.
Unfortunately, `blacken-docs==1.12.1` and `pre-commit==2.18.1` aren't available for Python 3.6, so https://github.com/voxel51/fiftyone/pull/1703 and https://github.com/voxel51/fiftyone/pull/1704 break our-pre-commit hooks for me.
This PR reverts to the latest versions of `blacken-docs`, `black`, and `pre-commit` that are available on Python 3.6 and avoid [this blacken-docs issue](https://github.com/psf/black/issues/2829) that occurs when using `black>22.1.0`.
```shell
pre-commit uninstall
rm -rf ~/.cache/pre-commit
pre-commit install
```

Adding Python 3.6 back to pre-commit hooks

---

fiftyone/core/dataset.py

The previous implementation of `delete_non_persistent_datasets()` required reading every `DatasetDocument` into memory, which was wasteful. Now only non-persistent datasets are loaded.

Optimizing non-persistent dataset deletion

---

fiftyone/core/dataset.py
fiftyone/core/odm/database.py

Every so often, a user will report that they've managed to get a dataset with `name==None` into their database, despite the code's best efforts to prevent this from occurring. This currently results in an error:
```
In fiftyone/core/dataset.py", line 4591, in _list_datasets:
return sorted(conn.datasets.distinct("name"))
TypeError: '<' not supported between instances of 'str' and 'NoneType'
```
because `sorted()` does not like None. This PR patches that.
More generally, this PR throws a try-except around everything in the non-persistent dataset cleanup routine that runs at import time, because errors that prevent `import fiftyone as fo` from succeeding are catastrophic! The user has no access to the rest of the library to potentially fix any non-critical errors that exist.

Avoid non-critical errors in startup services

---

fiftyone/utils/geotiff.py

Previously an error would occur when passing a list of GeoTIFF images to the `image_path` argument of `GeoTIFFDatasetImporter`. Now this works as expected:
```py
dataset = fo.Dataset.from_dir(
image_path=["/path/to/image.tif"],
dataset_type=fo.types.GeoTIFFDataset,
)
```

Fixing GeoTIFF list bug

---

fiftyone/core/runs.py

https://github.com/voxel51/fiftyone/commit/01bd3e72afca8db737fa2506a10ce94bd918ccd0 removed the use of `json_util.dumps()` when serializing `RunResults`, which means that run results must now contain only valid JSON, not BSON constructs like `ObjectId`. However, some users have reported errors with this limitation because their `RunResults` do contain BSON. In particular, their `CVATAnnotationResults` contain `ObjectId`s.
I didn't have time to actually reproduce the error, nor test this PR, but I believe it should add BSON support back.
**Open question**: in looking at https://github.com/voxel51/fiftyone/commit/01bd3e72afca8db737fa2506a10ce94bd918ccd0, I'm confused because, while `save_run_results()` used to use `json_util.dumps()`, `load_run_results()` did not use `json_util.loads()`, so …

Allow RunResults to contain BSON

---

requirements/dev.txt

The existing pylint version mishandles various typing scenarios. For example when using Optional[T] you will receive Value 'Optional' is unsubscriptable. The latest version resolves this issue.

updating pylint to 2.13.9

---

requirements/docs.txt

Jupyter doesn't pull in ipython_genutils automatically thus producing a module not found error during the docs build.  This explicitly adds it as a dependency to resolve the issue.

adding missing ipython_genutils dependency

---

fiftyone/core/plots/base.py

The ValueError raised when asking for an unsupported plotting backend was specified in a way that caused the following error: `TypeError: not enough arguments for format string`. I put the pair of format string arguments in a tuple following the example of a similar ValueError on [line 873](https://github.com/voxel51/fiftyone/blob/1a9c9bf0fe3f1a5a332629e2f711ab8d4358a7c4/fiftyone/core/plots/base.py#L873).
I ran the same code that revealed the error (edited from [here](https://voxel51.com/docs/fiftyone/user_guide/evaluation.html#map-and-pr-curves)), and this time saw the correct error message.
```python
print(dataset)
results = dataset.evaluate_detections(
"predictions", …
```

Fix bad format string

---

app/packages/app/src/Root/Root.tsx
app/packages/app/src/components/Flashlight.tsx
app/packages/components/src/components/Header/Header.tsx

v0.16.0 introduced a bug in the App where labels in the grid are not drawn until statistics data has loaded for the sidebar. The unintended loading state is noticeable on larger datasets like BDD.
This PR fixes the issue by creating a version of the Looker options that does not depend on statistics while they load. Ideally, the options would not depend on statistics at all, and could be fixed by improving the Recoil dataflow.
Also fixes some TypeScript errors.

Fix initial label renders

---

fiftyone/migrations/revisions/v0_16_1.py
setup.py

The intention of the v0.16.0 revision was to add definitions for embedded document field schemas within the dataset document. The revision contains a bug that omits list fields like `Detections`, though.
This v0.16.1 revision accounts for list fields.

v0.16.1 Revision

---

fiftyone/core/utils.py

Currently when an invalid or malformed xml file is parsed an `ExpatError` will be raised.  This change logs the filename that produced this error before re-raising it to the calling code.

adding filename exception logging for failed xml parsing

---

requirements/common.txt

bump matplotlib to latest - without this change I am unable to `bash install.bash -d` apple silicon.
I've only tested install on mac+arm64 python 3.10.4.
-   [ ] Other

bump matplotlib to latest

---

app/packages/app/src/Root/Root.tsx

v0.16.0 and v0.16.1 configure GA but do not send the `pageview` event.
Will publish a patch today or tomorrow.

Fix App page views

---

fiftyone/core/odm/mixins.py
tests/unittests/dataset_tests.py

Fixes a small bug I encountered where `Field.db_field` was not being properly updated when `Dataset.clone_sample_field()` and `Dataset.clone_frame_field()` are invoked.
The unit tests are now properly updated to validate the correct behavior, and I ran them locally to verify correctness. However, these tests are still not included in CI because they're being skipped due to Windows errors (and tbh I don't know how to fix them).
```py
dataset.clone_sample_field("ground_truth", "gt")
assert dataset.count("ground_truth.detections") == 1232
assert dataset.count("gt.detections") == 1232
assert sample.ground_truth is not None  # fails on `develop`, now succeeds
assert sample.gt …
```

Fixing DB field bug

---

app/README.md
app/package.json
app/yarn.lock

This is internal / dev facing only.
This adds a new script for starting the app and python server in the same parent process.
Note: this keeps the `yarn dev` functionality the same.

add concurrent app+backend run script

---

fiftyone/utils/labels.py

Adds `fiftyone.utils.labels.classifications_to_detections()` converting a `Classifications` field into a `Detections` field where each classification corresponds to one detection with a bounding box surrounding the entire image (`[0,0,1,1]`), just like `classification_to_detections()`
```python
import fiftyone.utils.labels as foul
"open-images-v6",
max_samples=50,
label_types=["classifications"],
)
foul.classifications_to_detections(dataset, "positive_labels", "dets")
print(dataset.first())
```
```
<Sample: {
'id': '62a0b31a79f8993392beb816',
'media_type': 'image',
'filepath': '/home/eric/fiftyone/open-images-v6/validation/data/0001eeaf4aed83f9.jpg',
'tags': BaseList(['validation']),
'metadata': None, …
```

Add utility to convert classifications to detections

---

fiftyone/zoo/models/manifest-torch.json
fiftyone/zoo/models/torch.py

Resolves #1789
We monkey patch the `load_state_dict_from_url` function used by torch models in the FiftyOne Model Zoo so that we can choose to load them from the model zoo directory on disk. As of torchvision v0.12.0, the structure of some models has been changed so the existing monkey patch no longer worked. This PR updates the location of the `load_state_dict_from_url` in the torchvision module and changes the namespace where it is applied.
To test, you can run this code from the evaluate segmentations example:
```python
"quickstart",
max_samples=3,
).clone()
model = foz.load_zoo_model("deeplabv3-resnet50-coco-torch")
dataset.apply_model(model, "resnet50")
```

Fix bug when using zoo models with newest version of Torchvision

---

fiftyone/core/metadata.py
fiftyone/core/utils.py
fiftyone/utils/data/base.py
fiftyone/utils/image.py

See comment in code for details.
```py
import eta.core.utils as etau
import fiftyone.utils.image as foui
foz.download_zoo_dataset("quickstart")
dataset_dir = foz.find_zoo_dataset("quickstart")
tmp_dir = "/tmp/quickstart"
etau.copy_dir(dataset_dir, tmp_dir)
dataset = fo.Dataset.from_dir(
dataset_dir=tmp_dir,
dataset_type=fo.types.FiftyOneDataset,
)
foui.transform_images(dataset, size=(32, -1))
```

Always use fork for multiprocessing on macOS

---

fiftyone/utils/tf.py

Let the shard enumeration of the tfrecord export start from 0 rather than 1. Fixes  #1847 
tested locally exporting a fiftyone dataset to tfrecord shards
TFRecord shards enumeration now starts from 0 rather than 1.
-   [ ] Other

Let shard enumeration start from 0

---

docs/source/integrations/coco.rst
docs/source/integrations/cvat.rst
docs/source/user_guide/annotation.rst
docs/source/user_guide/dataset_creation/datasets.rst
docs/source/user_guide/dataset_creation/index.rst
docs/source/user_guide/export_datasets.rst
fiftyone/core/collections.py
fiftyone/utils/annotations.py
fiftyone/utils/coco.py
fiftyone/utils/data/exporters.py
fiftyone/utils/eval/classification.py
fiftyone/utils/eval/detection.py
fiftyone/utils/eval/segmentation.py
fiftyone/utils/labels.py
fiftyone/utils/tf.py
fiftyone/utils/yolo.py
tests/unittests/import_export_tests.py

Resolves https://github.com/voxel51/fiftyone/issues/1722.
This is scratching a pretty deep itch, and it feels oh so good 🥇 
The fact that certain API methods would silently search for class lists on `Dataset.classes` and `Dataset.default_classes` often caused unexpected behavior for users that had first used something like `filter_labels()` to select a subset of classes to work with (see https://github.com/voxel51/fiftyone/issues/1722 for details).
**Lesson learned**: don't be fancy, let the user store class lists, but prefer relying on the user to explicitly request certain behavior:
```py
dataset.some_method(...)
dataset.some_method(..., classes=dataset.default_classes)
```
~~**NOTE**: there's still one important place that *will* silently infer class lists: the annotation API. My …

Stop passing classes and default_classes to export and evaluation methods

---

app/packages/looker/src/elements/common/thumbnail.module.css
app/packages/looker/src/elements/frame.ts
app/packages/looker/src/elements/image.ts
app/packages/looker/src/elements/video.ts

Resolves #1865
```py
dataset = fo.Dataset("bad")
sample = fo.Sample(filepath="bad.png")  
session = fo.Session(dataset)
dataset = fo.Dataset("bad-video")
sample = fo.Sample(filepath="bad.mp4")  
session.dataset = dataset
```

Fix selection and expansion for bad media files

---

app/packages/app/relay.config.json
app/packages/app/schema.graphql
app/packages/app/src/Root/Datasets/Dataset.tsx
app/packages/app/src/Root/Datasets/__generated__/DatasetQuery.graphql.ts
app/packages/app/src/mutations/__generated__/setViewMutation.graphql.ts
app/packages/app/src/mutations/setView.ts
fiftyone/core/state.py
fiftyone/server/mutation.py
fiftyone/server/query.py
fiftyone/server/scalars.py

Views should always be serialized as BSON, i.e. using `bson.json_util` in order for `ObjectId` values to be properly loaded. Resolves #1854

Serialize views as BSON

---

docs/source/environments/index.rst
docs/source/user_guide/config.rst

The default bind address has changed from `None` to `localhost` - this updates the documentation to reflect that change.
Doc update only, sphinx files built
-   [ ] Other

updates `FIFTYONE_DEFAULT_APP_ADDRESS` documentation

---

docs/source/integrations/cvat.rst
fiftyone/utils/annotations.py
fiftyone/utils/cvat.py
tests/intensive/cvat_tests.py

Resolves https://github.com/voxel51/fiftyone/issues/1849
In CVAT, you can group objects and tracks together allowing them to be visualized with the same color as well as populating the `group` attribute in the backend. This PR exposes this attribute and functionality similar to the occlusion widget #1321 letting you specify an object attribute in FiftyOne that will be used as this group id parameter in CVAT, which can then also be loaded back into the same attribute when loading annotations.
This PR also now introduces an error when attempting to start an annotation run linked to an existing project but where either the `label_schema`, `classes`, or `attributes` contains the occluded or group_id attributes. This is because when using existing projects, the label schema is overwritten with …

Adds the ability to upload and download group ids from CVAT

---

fiftyone/utils/cvat.py
fiftyone/utils/kitti.py
fiftyone/utils/voc.py

Resolves #1778. CVAT, KITTI and CVATVideo will import only label files with valid extensions (.xml or .txt). 
I created 4 datasets (CVAT, KITTI, CVATVideo, YOLOv5) with files that have non-standard extensions in the label folder and imported those datasets with `fo.Dataset.from_dir()`. After that I checked which labels where imported.
`YOLOv5Importer` did not require any modifications since it looks first at the available images in the dataset and imports only the corresponding labels. I can also modify the importers for CVAT, KITTI and CVATVideo to work this way. Just let me know :smiley: 
(Details in 1-2 sentences. You can just refer …

eliminate non-XML or non-TXT files from CVAT, KITTI, CVATVideo

---

docs/source/_static/js/custom.js

Resolves https://github.com/voxel51/fiftyone/issues/1552!
@benjaminpkane why did https://github.com/voxel51/fiftyone/commit/39315eb3d0914fc4877627424e06df99f76de97a introduce the change that this reverts? Am I breaking something else?
```bash
bash docs/generate_docs.bash -c
open docs/build/html/user_guide/using_datasets.html
```

Bringing back the current section highlight!

---

docs/source/user_guide/evaluation.rst
docs/source/user_guide/using_datasets.rst
docs/source/user_guide/using_views.rst
fiftyone/core/cli.py
fiftyone/core/dataset.py
fiftyone/core/odm/dataset.py
fiftyone/core/view.py
fiftyone/migrations/revisions/v0_16_3.py
setup.py
tests/unittests/dataset_tests.py

```py
dataset.tags = ["foo", "bar"]
print(dataset)
```
```
Name:        quickstart
Media type:  image
Num samples: 200
Persistent:  False
Tags:        ['foo', 'bar']
Sample fields:
id:           fiftyone.core.fields.ObjectIdField
filepath:     fiftyone.core.fields.StringField
tags:         fiftyone.core.fields.ListField(fiftyone.core.fields.StringField)
metadata:     fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.metadata.ImageMetadata)
ground_truth: fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.labels.Detections)
uniqueness:   fiftyone.core.fields.FloatField
predictions:  fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.labels.Detections) …
```

Adding dataset tags

---

app/packages/app/src/Root/Datasets/Dataset.tsx
app/packages/app/src/utils/hooks.ts
fiftyone/server/query.py

Maintain active dataset fields

---

fiftyone/__public__.py
fiftyone/core/aggregations.py
fiftyone/core/stages.py
tests/unittests/aggregation_tests.py

Adds support for serializing `Aggregation` instances.
This is primarily an internal-facing feature at this time, which allows, for example, for communicating aggregation definitions between Python and the App.
Example usage:
```py
bbox_area = (
F("bounding_box")[2] * F("$metadata.height")
* F("bounding_box")[3] * F("$metadata.width")
)
aggregations = [
fo.Bounds("predictions.detections.confidence"),
fo.Count(),
fo.Count("ground_truth.detections"),
fo.CountValues("ground_truth.detections.label"),
fo.Distinct("ground_truth.detections.label"),
fo.HistogramValues("predictions.detections.confidence", bins=50, range=[0, 1]), …
```

Adding support for serializing Aggregations

---

fiftyone/utils/cvat.py
tests/intensive/cvat_tests.py

The group id is stored at the track-level rather than the shape-level when annotating videos in CVAT which was not previously accounted for. This PR fixes that bug and adds a test that will now pass but would previously fail.
The error that has been resolved:
```
File "/home/eric/work/fiftyone/cvat_tests.py", line 1132, in test_group_id_video
dataset.load_annotations(anno_key, cleanup=True)
File "/home/eric/work/fiftyone/fiftyone/fiftyone/core/collections.py", line 6581, in load_annotations
return foua.load_annotations(
File "/home/eric/work/fiftyone/fiftyone/fiftyone/utils/annotations.py", line 988, in load_annotations
annotations = results.backend.download_annotations(results)
File "/home/eric/work/fiftyone/fiftyone/fiftyone/utils/cvat.py", line 3211, …
```

Fix bug when loading group ids in CVAT video tasks

---

app/packages/app/src/recoil/aggregations.ts

Resolves #1916 
```py
dataset.tag_samples("hello.world")
session.refresh()
```

Handle sample tags with "." in App

---

fiftyone/utils/cvat.py
tests/intensive/cvat_tests.py

When uploading to an existing CVAT project, you can choose not to provide a label schema or label field and instead use the CLI prompt to specify the names of fields into which to load annotations. This PR resolves a bug when attempting to upload to a CVAT project and no label schema is provided. 
```
Traceback (most recent call last):                                                                                                                                                                                                                                                 
File "/home/eric/work/fiftyone/fiftyone/tests/intensive/cvat_tests.py", line 498, in test_project …
```

[BUG] Resolve bug when uploading to projects in CVAT

---

fiftyone/server/query.py

Resolves #1942 
Target conversion was overlooked when migrating to GraphQL. The fix was straighforward, and isolated, though.

Fix App mask targets

---

fiftyone/server/query.py

Resolves a bug introduced in #1943.
Mask values are dicts, not lists. Fixes the default value.

Fix App masks

---

docs/source/user_guide/using_aggregations.rst
fiftyone/__public__.py
fiftyone/core/aggregations.py
fiftyone/core/collections.py
fiftyone/core/expressions.py
tests/unittests/aggregation_tests.py

Resolves https://github.com/voxel51/fiftyone/issues/1935.
Adds a `Quantiles` aggregation that can be used to compute the quantiles of numeric data.
- Unfortunately, MongoDB has no builtin method for computing quantiles, so the implementation performs a full sort of the values. Thus `quantiles()` requires `O(n)` memory (DB-side, not client-side), not `O(1)` like other aggregations
- I benchmarked `$group` + `JS sort` versus `$sort` + `$group` on a dataset of 100K samples, and the JS sort version was faster
- I also tried https://stackoverflow.com/a/60694525/16823653, which was extremely slow
```py
print(dataset.quantiles("uniqueness", [0.25, 0.50, 0.75]))
print(dataset.quantiles("uniqueness", …
```

Adding quantiles aggregation

---

requirements/common.txt

Upgrade version of tabulate to 0.8.10 to fix source install issue #1978 
The changes were tested by performing a developer installation of FiftyOne from source using Python 3.10.5
-   [x] Build: Build and test infrastructure changes
-   [ ] Other
Resolves #1978

update tabulate to 0.8.10 for source install

---

docs/source/integrations/cvat.rst

Small update to `annotate` documentation to close #1748 
No tests are needed to verify documentation updates
-   [x ] Documentation: FiftyOne documentation changes
-   [ ] Other

CVAT Annotate attribute documentation update

---

docs/source/integrations/coco.rst
docs/source/integrations/labelbox.rst
fiftyone/utils/yolo.py

Resolves #1951
Resolves #1952 
#1951 is resolved by simply removing a stray `label_field=""` from the docs.
#1952 is resolved by adding an informative error message when trying to export multiple YOLOv5 splits without providing the `classes` parameter to ensure a common class list is used.
```py
import fiftyone.utils.splits as fous
dataset = dataset.select_fields("ground_truth").clone()
dataset.untag_samples("validation")
classes = dataset.distinct("ground_truth.detections.label")
fous.random_split(dataset, {"train": 0.65, "test": 0.2, "val": 0.15})
for split in ["train", "test", "val"]:
dataset.match_tags(split).export(
export_dir="/tmp/yolov5",
dataset_type=fo.types.YOLOv5Dataset, …
```

#1951 and #1952

---

docs/source/integrations/cvat.rst
fiftyone/utils/annotations.py
fiftyone/utils/cvat.py
fiftyone/utils/labelbox.py

@ehofesmann I upgraded the `connect_to_api()` notion to an interface-level thing. So, for example, now the Labelbox backend can use the same API-sharing features "for free". The updated docs show the idea.
LMK what you think about this proposed upgrade to add to #1944 before merging it 😄

Upgrading AnnotationAPI reuse to interface level

---

fiftyone/__public__.py
fiftyone/core/dataset.py
fiftyone/core/fields.py
fiftyone/core/odm/dataset.py
fiftyone/core/odm/views.py
fiftyone/core/utils.py
fiftyone/migrations/revisions/v0_16_6.py
fiftyone/utils/data/exporters.py
fiftyone/utils/data/importers.py
tests/unittests/dataset_tests.py
tests/unittests/utils_tests.py

Makes some changes to the saved view dataset model that will be necessary to implement the frontend design we'd like to have for this feature:
- Switches to list-based storage of saved views on `DatasetDocument` so that views can be ordered and reordered in the frontend
- Adds `created_at`, `last_modified_at`, and `last_loaded_at` fields
- Adds `color` (with validation) and `description` fields
- Adds a `url_name` field that contains a `url-friendly-name` for view names `URL Friendly Name!`
- Adds a `get_view_info()` method to retrieve the editable info about a saved view
- Adds an `update_view_info()` method to edit a saved view's info
Relevant private methods that the App backend can use:
- `_reorder_views()`: change the order of the saved views on a dataset
- `_validate_view_name()`: …

Switching to list-based storage of saved views

---

docs/source/user_guide/plots.rst
fiftyone/core/plots/plotly.py
requirements/common.txt
requirements/extras.txt
setup.py

Resolves #1099
Resolves #1319
This PR removes the `plotly<5` restriction that exists in FiftyOne's current dependencies (currently we require `plotly>=4.14,<5`).
After doing some digging, it turns out [this small regression](https://github.com/plotly/plotly.py/issues/3292) introduced in `plotly==5.0.0` was breaking the selection callbacks of our [interactive plots](https://voxel51.com/docs/fiftyone/user_guide/plots.html).
The plotly maintainers patched this regression in [plotly==5.2.1](https://github.com/plotly/plotly.py/releases/tag/v5.2.1), so this PR could have just updated our dependency to `plotly>=5.2.1`. However, it was simple to patch the regression and thus support `plotly>=4.14`.
I also added a `jupyterlab>=3` requirement to the recommended JupyterLab setup instructions in the …

Adding plotly v5 support!

---

fiftyone/core/dataset.py
tests/unittests/dataset_tests.py
tests/unittests/video_tests.py

Adds an optional `new_ids=True` option to `Dataset.add_collection()` that generates new sample/frame IDs when adding the samples to the collection.
This is useful, for example, to quickly exponentiate the size of a dataset for testing:
```py
for _ in range(4):
dataset.add_collection(dataset, new_ids=True)
```
```py
new_ids = dataset.add_collection(dataset, new_ids=True)
assert len(dataset) == 400
assert len(set(dataset.values("id"))) == 400
```
```py
new_ids = dataset.add_collection(dataset, new_ids=True)
assert len(dataset) == 20
assert len(set(dataset.values("frames.id", unwind=True))) == 2558 …
```

Adding new_ids=True option to Dataset.add_collection()

---

docs/source/cli/index.rst
fiftyone/core/cli.py
fiftyone/core/utils.py
fiftyone/utils/image.py
fiftyone/utils/video.py

Small enhancement that adds support for optionally writing transformed images/videos to a new output location, and storing the resulting filepaths in a new field.
This new syntax is useful, for example, for quickly generating thumbnail images for a dataset.
```py
import shutil
import fiftyone.utils.image as foui
import fiftyone.utils.video as fouv
foui.transform_images(
dataset,
size=(-1, 64),
output_field="thumbnail_path",
output_dir="/tmp/thumbnails",
rel_dir=fo.config.dataset_zoo_dir,
)
print(dataset.select_fields("thumbnail_path").first())
fouv.transform_videos(
dataset,
size=(-1, 128),
output_field="thumbnail_path", …
```

Adding support for writing transformed images/videos to new location/field

---

docs/source/user_guide/using_datasets.rst
docs/source/user_guide/using_views.rst
fiftyone/__public__.py
fiftyone/core/clips.py
fiftyone/core/collections.py
fiftyone/core/dataset.py
fiftyone/core/document.py
fiftyone/core/frame.py
fiftyone/core/odm/document.py
fiftyone/core/odm/mixins.py
fiftyone/core/patches.py
fiftyone/core/sample.py
fiftyone/core/singletons.py
fiftyone/core/video.py
fiftyone/core/view.py
tests/unittests/dataset_tests.py
tests/unittests/video_tests.py
tests/unittests/view_tests.py

Completes the implementation of the dataset save context started in https://github.com/voxel51/fiftyone/pull/1727.
- Added support for dynamically batching samples to achieve a target number of database connections per second
- Updated the default batching strategy to save batches every 0.2 seconds (this is the same strategy used by `add_samples()`)
- Added a `save_context()` syntax
- Added proper reloading of `Sample`/`Frame` singletons when applying save contexts to dataset *views*
- Added documentation
- Added unit tests
The `iter_samples(autosave=True)` syntax is the same:
```py
import random as r
import string as s
def make_label():
return "".join(r.choice(s.ascii_letters) for i …
```

Save context tweaks

---

docs/source/user_guide/plots.rst
fiftyone/core/plots/plotly.py

`ipywidgets==8.0.0` was [released August 18th](https://pypi.org/project/ipywidgets/#history), but unfortunately [it looks like](https://pythontechworld.com/issue/plotly/plotly.py/3686) it is not compatible with `plotly<=5.9.0`, as the following error is raised (confirmed locally):
```
AttributeError: type object 'DOMWidget' has no attribute '_ipython_display_'
```
Therefore, this PR adds an `ipywidgets<8` requirement to FiftyOne.

Adding ipywidgets<8 requirement

---

docs/source/user_guide/config.rst
fiftyone/__init__.py
fiftyone/__public__.py
fiftyone/core/config.py
fiftyone/core/logging.py

https://github.com/voxel51/eta/pull/567 removed ETA's configuration of the root logger, which was a good change because the root logger shouldn't have been touched.
However, FiftyOne was implicitly built assuming all of its `logging.INFO` messages would be printed, which is no longer true:
```py
```
This PR re-introduces package-wide logging at `INFO` level by default, and exposes a `fo.config.logging_level` setting that can be used to customize this behavior if desired:
```shell
export FIFTYONE_LOGGING_LEVEL=WARNING
```

Package-wide logging config

---

docs/source/user_guide/dataset_creation/datasets.rst
docs/source/user_guide/export_datasets.rst
fiftyone/utils/yolo.py

Adds support for `path`  variable in `dataset.yaml` for YOLOv5 datasets, as mentioned in Issue #1903.
The docs have been updated too. 
Created a dataset and tested the new possible file structures e.g. `dataset.yaml` located outside of the actual dataset directory.
-   [ ] Other

Fix Issue #1903 path variable

---

docs/source/cli/index.rst
fiftyone/constants.py
fiftyone/core/cli.py
fiftyone/core/odm/database.py
fiftyone/core/odm/dataset.py
fiftyone/core/odm/document.py
fiftyone/core/odm/embedded_document.py
fiftyone/core/odm/runs.py
fiftyone/migrations/runner.py
tests/unittests/utils_tests.py

This PR introduces a `fiftyone.constants.COMPATIBLE_VERSIONS` constant that allows a given FiftyOne version to declare that it is compatible with a range of other versions.
When clients running this patch encounter a dataset with a compatible version, they will not migrate the dataset (unless a migration was specifically requested via `fiftyone migrate`); instead the dataset will be loaded and used as-is.
For example, since this patch declares its compatibility as `>=0.16.3,<0.17`, you can connect to a database at version `0.16.3` without causing anything to be migrated.
This PR also converts all of the classes used in `DatasetDocument` to be non-strict, meaning that they will no longer raise a `ValidationError` if unknown fields are encountered when loading dataset docs from the …

Adding client compatibility versions

---

fiftyone/core/dataset.py

For some reason, `add_samples()` and `add_collection()` had logic in-place to merge annotation/brain/evaluation runs into the destination dataset, but that doesn't make sense as runs are only valid for the particular `view` on which they were applied, which will not be the same (in general) when merging datasets.
There was already logic in-place to prevent merges when the destination dataset was non-empty, but there wasn't any logic to prevent runs from being merged when the source collection was a view, not a full dataset, which was definitely a bug. So the only valid use case is:
```py
new_dataset = fo.Dataset()
new_dataset.add_collection(dataset)
```
but that is better expressed as:
```py
new_dataset = dataset.clone()
```
So, I just removed this code :)

Don't include runs when merging collections

---

fiftyone/utils/coco.py
fiftyone/utils/kitti.py
fiftyone/utils/yolo.py
fiftyone/zoo/datasets/__init__.py

- Fixes a bug that prevented `load_zoo_dataset("kitti-multiview", split="train")` from working properly
- Fixes the `itemRotation` setting for both `kitti-multiview` and `quickstart-groups` (the latter was achieved by uploading a new zip to Google Drive

Groups zoo fixes

---

fiftyone/core/stages.py
tests/unittests/view_tests.py

Fixes a bug in `match_frames()` that was causing `sample.frames` to lookup all frames, even if the view filters the frames:
```py
num_objects = F("detections.detections").length()
view = dataset.match_frames(num_objects == 28)
sample = view.first()
assert len(view) == 1
assert len(sample.frames) == view.count("frames")
```

Fixing match_frames() bug

---

docs/source/_includes/substitutions.rst
docs/source/release-notes.rst
docs/source/user_guide/dataset_creation/datasets.rst
docs/source/user_guide/dataset_creation/samples.rst
docs/source/user_guide/export_datasets.rst
docs/source/user_guide/plots.rst
fiftyone/core/collections.py
fiftyone/core/dataset.py
fiftyone/core/odm/__init__.py
fiftyone/core/plots/__init__.py
fiftyone/core/plots/manager.py
fiftyone/core/session/__init__.py
fiftyone/core/session/client.py
fiftyone/core/session/events.py
fiftyone/core/session/notebooks.py
fiftyone/core/session/session.py
fiftyone/migrations/__init__.py
fiftyone/types/__init__.py
fiftyone/utils/cityscapes.py
fiftyone/utils/data/__init__.py
fiftyone/utils/data/base.py
fiftyone/utils/data/converters.py
fiftyone/utils/data/exporters.py
fiftyone/utils/data/importers.py
fiftyone/utils/eval/__init__.py
fiftyone/utils/openimages.py
fiftyone/zoo/__init__.py
fiftyone/zoo/datasets/__init__.py

This PR adds the following block of code to all `__init__.py` files that import symbols that are intended to be exposed in FiftyOne's public namespace using `path.to.package.symbol` rather than `path.to.package.module.symbol`:
```py
__all__ = [
k
for k, v in globals().items()
if not k.startswith("_") and not isinstance(v, types.ModuleType)
]
```
The reason I'm adding this code is to allow Sphinx to understand references to imported symbols. For example, we allow users to use `fiftyone.types.Dataset` rather than the full `fiftyone.types.dataset_types.Dataset`. But, prior to this PR, docstrings had to use the full `:class:fiftyone.types.dataset_types.Dataset`. Now docstrings may choose to use the abbreviated `:class:fiftyone.types.Dataset` (and I updated all such references in the docs to …

Adding support for linking directly to imported subpackage contents

---

fiftyone/core/view.py
fiftyone/server/view.py

Optimizes group selection in `fiftyone.server.view.get_view()`, similar to what is done for sample selection.

Optimizing group selection in server get_view()

---

fiftyone/core/cli.py
fiftyone/core/dataset.py
fiftyone/core/odm/dataset.py
fiftyone/migrations/revisions/v0_17_0.py

The original impetus for this PR was to update the v0.17.0 migration so that a valid `DatasetAppConfig` is inserted by the migration itself. Previously `app_config == {}` was being inserted, which led to default values being populated by `load_dataset()` but *not* getting persisted to the database because `doc.save()` wasn't detecting any changes. This is bad because anything (eg GraphQL) that tries to pull directly from the DB wouldn't have the correct data available to it.
Along the way, I removed some unnecessary code from `_load_dataset()` that was redeclaring `sample_fields` and `frame_fields` and then immediately re-saving the dataset doc, even though this data was already properly defined. The implementation of `_load_dataset()` now has the property that the only field that may be …

Improving groups migration

---

docs/source/_includes/substitutions.rst
docs/source/release-notes.rst
fiftyone/core/odm/utils.py
tests/unittests/dataset_tests.py

Fixes a regression introduced in v0.16.6 when working with [custom embedded documents](https://voxel51.com/docs/fiftyone/user_guide/using_datasets.html#custom-embedded-documents) that would raise an error when a custom `EmbeddedDocument` class was used to populate a dynamic attribute of a `Label` field:
```py
import fiftyone.core.fields as fof
class CameraInfo(foo.EmbeddedDocument):
camera_id = fof.StringField(required=True)
quality = fof.FloatField()
description = fof.StringField()
class LabelMetadata(foo.DynamicEmbeddedDocument):
created_at = fof.DateTimeField(default=datetime.utcnow)
model_name = fof.StringField()
filepath="/path/to/image.png",
camera_info=CameraInfo( …
```

Fixing custom embedded documents regression

---

app/packages/plugins/README.md
docs/source/user_guide/app.rst
docs/source/user_guide/config.rst
fiftyone/core/config.py
fiftyone/server/app.py
fiftyone/server/routes/plugins.py

Change log
- Adds `plugins_dir` to the FiftyOne config (env var `FIFTYONE_PLUGINS_DIR`)
- Adds a pointer to the plugin README to the App User Guide page
- Editorial pass over plugin README 🤓

Adding plugins docs/env var

---

docs/source/getting_started/install.rst
docs/source/user_guide/dataset_creation/datasets.rst
docs/source/user_guide/export_datasets.rst
fiftyone/core/collections.py
fiftyone/core/utils.py
fiftyone/utils/annotations.py
fiftyone/utils/bdd.py
fiftyone/utils/coco.py
fiftyone/utils/cvat.py
fiftyone/utils/data/exporters.py
fiftyone/utils/data/importers.py
fiftyone/utils/geojson.py
fiftyone/utils/kitti.py
fiftyone/utils/voc.py
fiftyone/utils/yolo.py
tests/unittests/import_export_tests.py

Resolves https://github.com/voxel51/fiftyone/issues/2000
Other goodies:
- Added a `rel_dir` parameter on `draw_labels()` and `export()`---as well as all builtin exporters---which allows for the possibility of preserving nested subdirectory structure of the input dataset's media
- Adds an optional `abs_paths` parameter to all relevant exporters that allows for storing absolute paths to media in the exported labels

Adding rel_dir to export() and draw_labels()

---

fiftyone/utils/cvat.py
tests/intensive/cvat_tests.py

On CVAT > v2.0 servers, when checking if a task exists, the existing method would fail if there are too many tasks. 
Previously, this was accomplished by searching for a task id by `cvat_url/api/task?id=XXX` which would return the query task for CVATv1 servers, but may not for CVATv2 servers. This error would result in annotation runs unable to be loaded
After this PR, the `task_exists()` method now attempts to get the status of a task and returns `False` if it encounters a 404 error. 
A test was added to capture this issue on CVATv2 servers.
Note: This also fixes a bug where annotations were being duplicated to other images in a task due to the fact that images also contain an `outside` property now in CVATv2 servers.

Fix CVAT bug when checking if a task exists

---

docs/source/recipes/convert_datasets.ipynb
docs/source/recipes/creating_views.ipynb
docs/source/recipes/custom_exporter.ipynb
docs/source/recipes/custom_importer.ipynb
docs/source/recipes/custom_parser.ipynb
docs/source/recipes/draw_labels.ipynb
docs/source/recipes/image_deduplication.ipynb
docs/source/recipes/merge_datasets.ipynb
docs/source/tutorials/classification_mistakes.ipynb

Removes the warning below, since I'm no longer seeing this issue in Colab 🥳 🎈 
> If the above import fails due to a `cv2` error, it is an issue with OpenCV in Colab environments. [Follow these instructions to resolve it.](https://github.com/voxel51/fiftyone/issues/1494#issuecomment-1003148448)
~~Adds a suggestion to install `fiftyone==0.15.1` when working in Google Colab, since the App is currently buggy in Colab with `fiftyone>=0.16,<0.17`~~ <-- no longer needed, thank you https://github.com/voxel51/fiftyone/pull/2069!

Removing cv2 colab fix

---

fiftyone/utils/labelstudio.py

Alternative to #2066 
When deserializing the `uploaded_tasks` dict that maps labelstudio task ids to FiftyOne sample ids, the keys were previously not converted back from strings to integers.
```
KeyError                                  Traceback (most recent call last)
<ipython-input-1-b67eda7559a6> in <module>
2
3 dataset = fo.load_dataset("ls_test")
----> 4 dataset.load_annotations("anno_key", cleanup=True)
5 dataset.delete()
~/work/fiftyone/fiftyone/fiftyone/core/collections.py in load_annotations(self, anno_key, dest_field, unexpected, cleanup, **kwargs)
7016             found, in which case a dict containing the extra labels is returned
7017         """
-> 7018         return foua.load_annotations(
7019             self,
7020             anno_key, …
```

Resolve Labelstudio task_map key error

---

docs/scripts/make_model_zoo_docs.py
fiftyone/utils/clip/__init__.py
fiftyone/utils/clip/model.py
fiftyone/utils/clip/tokenizer.py
fiftyone/utils/clip/zoo.py
fiftyone/zoo/models/manifest-torch.json
fiftyone/zoo/models/torch.py

Small editing pass over @Rusteam's **amazing** work from https://github.com/voxel51/fiftyone/pull/1691.
Example usage below. Zero shot prediction is so cool 🔥 🤗 
```py
"coco-2017",
max_samples=51,
shuffle=True,
seed=51,
)
model = foz.load_zoo_model(
"clip-vit-base32-torch",
text_prompt="A photo of a",
classes=["person", "dog", "cat", "bird", "car", "tree", "chair"],
)
dataset.apply_model(model, label_field="predictions")
```

CLIP tweaks

---

app/packages/app/src/components/Modal/Group.tsx

In a group modal, selecting the point cloud sample would not be cleared. This would cause a graphql query to execute in an unexpected state (non-groups). This patch clears out the selected sample when the modal is closed.

fix pinned sample not clearing

---

app/packages/looker-3d/src/Looker3d.tsx

Fixes case where "keyboard shortcuts shouldn’t have “focus” when using the tagging menu (eg as I type the tag “test”, the E and T shortcuts take effect behind)"

fix L3D hotkey targeting

---

fiftyone/core/groups.py

Alternative to https://github.com/voxel51/fiftyone/pull/2085 that makes it so that *only* `Group` instances don't have their IDs changed when they are copied.
Why is this change needed? Because it is normal to have multiple `Group` instances with a shared `id`, and regenerating this ID in a `sample.copy()` operation would break the group association.

Don't regenerate IDs when copying Group instances

---

fiftyone/core/collections.py
fiftyone/core/runs.py
fiftyone/utils/annotations.py
tests/intensive/cvat_tests.py

Currently, a bug can arise when load annotation results through the following:
* Create a view that adds a stage referencing a field being annotated
* Create an annotation run with this view
* Delete the field
* Load the annotation run
* ERROR: The annotation results cannot be loaded since the run view needs to be constructed [here](https://github.com/voxel51/fiftyone/blob/e94ccf26703bde87be16cd5143bd54014001ef2b/fiftyone/core/runs.py#L472) in order to load the run results, but one of the fields doesn't exist.
The workaround is for the user to manually add the sample/frame field back on the dataset and rerun `load_annotations()`, however, this seemingly should not be necessary since we allow brand new fields to be annotated in the same manner.
Since the annotation run view is never …

Add the option to load a view or dataset for run results

---

fiftyone/core/collections.py
fiftyone/core/runs.py
fiftyone/utils/annotations.py
fiftyone/utils/cvat.py
tests/intensive/cvat_tests.py

This PR resolves an issue with CVAT >v2.0 servers where `import_annotations()` can fail to list tasks for existing projects due to a change in the CVAT API. Previously, the tasks for a project were listed as a dictionary of tasks that we needed to access the `id` of, now they are stored as a list of integer ids directly.
This PR fixes that bug as well as adds a progress bar when downloading annotations from CVAT for more than one task.

Fix CVAT task id bug and add task download progress bar

---

docs/source/tutorials/qdrant.ipynb

Updates Qdrant tutorial to use `fiftyone.utils.random` instead of `fiftyone.utils.splits`.

Update Qdrant tutorial

---

fiftyone/utils/coco.py

Added the option to import the COCO annotation id using the COCODetectionDatasetImporter. This might be relevant for downstream processing as otherwise the link between the detection/segmentation (in 51) to the annotations in the COCO file might be lost. PR is after short Slack discussion with Brian Moore.
I ran a small script trying to import a COCO dataset with the option turned on and off. If you want to have a more formal test please let me know. …

Add option to import COCO annotation id

---

app/packages/state/src/hooks/useHelpPanel.ts
app/packages/state/src/hooks/useJSONPanel.ts

When embeded, the `Dataset` component will refresh on all clicks, since this window handler causes a perceived state change.

Dataset Reloading on Click

---

app/packages/dataset/src/Dataset.tsx
app/packages/state/src/hooks/useSetView.ts

Since the embed version does not use a router, any deep usage of the router will cause issues. In this case the viewbar was referring to a router context that did not exist.

avoid using router context

---

fiftyone/core/stages.py
tests/unittests/view_tests.py

Fixes a bug when using `select_by()` with `ObjectIdField`s.

Fixing select_by() ID bug

---

Dockerfile
README.md
docs/source/environments/index.rst
docs/source/user_guide/app.rst
fiftyone/core/session/session.py
fiftyone/core/utils.py

- Automatically sets `address="0.0.0.0"` when running in Docker. Thanks @ritch for the idea!
- Moves the Docker instructions from the GitHub README to the docs
- Explicitly documents that `session = fo.launch_app(..., address="0.0.0.0")` is required when working inside Docker (in case `is_docker()` doesn't work for any reason)
- Adds a note + pointer to the Docker documentation under the App docs where `launch_app()` is introduced

Automatic Docker address + moving instructions to the docs

---

fiftyone/utils/image.py

This pull request adds the option to add cv2 interpolation methods when resizing images
Tested locally with a script that calls _transform_image()
-   [x] Other

add interpolation option for image resizing

---

docs/source/user_guide/using_views.rst

View expressions have a `.sort()` method, `.sort_by()` is to sort samples at the dataset-level.

Fix view expression sort documentation

---

app/packages/app/vite.config.ts

Local proxy has recently failed to connect on localhost. Switching to `127.0.0.1` fixes the issue. This is only for the `/aggregate` and `/plugin` routes. Eventually I'd like to move these to the other local development env vars we use else where. Until then this will unblock plugin development.
For google searches:
```
[dev] 9:20:23 AM [vite] http proxy error:
[dev] Error: connect ECONNREFUSED ::1:5151
[dev]   at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1237:16)
```
and
```
Error: connect ECONNREFUSED ::1:5151
```

use 5151 local address instead of localhost

---

fiftyone/utils/labelstudio.py

Creating an annotation run works fine, but when you add new images to the dataset and want to create a new annotation run with all the images, both the new and old, labelstudio crashes. This PR fixes this since labels are only imported from samples that have labels. 
Versions:
fiftyone version: 0.17.2
Tested with both label-studio-sdk 0.0.14 and 0.0.15 
-   [ ] Documentation: …

fix:  create annotation run crashes if some but not all samples are labeled

---

app/packages/plugins/src/index.ts

Originally a plugin registered with the same name would cause an assertion to throw. This relaxes that to a warning, since in some environments HMR causes plugins to re-register without issue.
The original intent was to prevent multiple plugins from sharing the same name. The warning will replace the assertion/error.

only warn when plugin re-registered

---

app/packages/core/src/components/Actions/ActionsRow.tsx
app/packages/dataset/src/Dataset.tsx
app/packages/dataset/src/index.tsx
app/packages/state/src/recoil/atoms.ts

In order to support cases where the app should not display actions that write to mongodb, this PR adds the ability to load the app in a "readOnly" mode. For now this only applies to the Tagging functionality, but any new or other features which behave similarly should be hidden in this mode.

add support for readOnly mode

---

CONTRIBUTING.md

Minor fixes to contributing.md

---

fiftyone/core/clips.py
fiftyone/core/collections.py
fiftyone/core/dataset.py
fiftyone/core/frame.py
fiftyone/core/patches.py
fiftyone/core/video.py
fiftyone/core/view.py

This PR fixes some group-related bugs that were identified originally in the context of running `to_frames()`.
```py
img_data = foz.load_zoo_dataset("quickstart")
vid_data = foz.load_zoo_dataset("quickstart-video")
keys = ["video"] + ["image%d" % i for i in range(9)]
datasets = [vid_data] + [img_data.shuffle().limit(10) for i in range(9)]
sample_dicts = [dict(zip(keys, s)) for s in zip(*datasets)]
dataset.add_group_field("group", default="image0")
samples = []
for sample_dict in sample_dicts:
group = fo.Group()
for name, sample in sample_dict.items():
sample = sample.copy()
sample["group"] = group.element(name)
samples.append(sample)
dataset.add_samples(samples)
videos = dataset.select_group_slices("video")
view1 = …
```

Handling grouped collections when sampling frames

---

docs/source/tutorials/qdrant.ipynb

- Fix the qdrant tutorial. Since it's writing, the qdrant_client api has changed and the args for `recreate_collection` have changed. (See https://github.com/qdrant/qdrant_client/blob/master/tests/test_qdrant_client.py#L78)
- Run the notebook and verify everything runs without error.
-   [ ] Other

Fix qdrant tutorial

---

app/packages/core/src/Dataset.ts
app/packages/core/src/__generated__/DatasetQuery.graphql.ts
app/packages/state/src/recoil/types.ts
app/schema.graphql
fiftyone/server/query.py

Adds info from python lib dataset into the frontend so that metadata about a dataset can be used for plugins
Tested with our custom plugins
-   [X] App: FiftyOne application changes
-   [ ] Other

add info to dataset

---

fiftyone/core/view.py

Resolves https://github.com/voxel51/fiftyone/issues/2113.
@benjaminpkane's diagnosis in https://github.com/voxel51/fiftyone/issues/2113#issuecomment-1255235373 was spot on. There's a `_base_view` property that needs to be used in cases like this.

Fixes mutation of label tags from patches views in the App

---

fiftyone/utils/clip/zoo.py

When running the CLIP zoo model on a cuda device, it would currently fail due to the `text_features` not being properly placed on the cuda device as well causing a device mismatch when running a forward pass.
This PR places the `text_features` tensor on the same device as the model itself to resolve this issue. Tested both on a cuda device and cpu device.

Support cuda devices for CLIP zoo model

---

app/packages/components/src/components/Tooltip/Tooltip.module.css

PR fixes action row item's tooltip text color bug shown in the image below
Tested manually by hovering action row items visually inspecting tooltip text color in both light and dark theme
-   [ ] Other

use theme based color for action row tooltip text

---

app/packages/dataset/src/Dataset.tsx

Fix an issue where bottom row of flashlight images were getting clipped from height overflow
Tested visually by ensuring images are no longer clipped and there is no excess space below last row of images once it's fully scrolled
-   [ ] Other

fix flashlight clipping from height overflow

---

app/packages/core/src/components/Modal/Group.tsx
app/packages/looker-3d/src/Looker3d.tsx
fiftyone/server/samples.py

Fixes [this](https://github.com/voxel51/fiftyone/issues/2164) issue by allowing mediaFields to be null.
Also adds improved error messages when a mediaField is null in Looker3D.

Fix unset media field

---

fiftyone/core/clips.py
fiftyone/core/collections.py
fiftyone/core/patches.py
fiftyone/core/video.py
tests/unittests/video_tests.py

Implements my idea from https://github.com/voxel51/fiftyone/pull/2203: all tagging operations are now done via update operations!
```py
{"$addToSet": {"tags": {"$each": tags}}}  # add tags
{"$pullAll": {"tags": tags}}  # remove tags
```
This is a much better implementation than the current one because:
- The tag edits are no longer applied in-memory; `values()` and `set_values()` are no longer used
- When tagging labels in generated views (patches/frames/clips), the relevant changes are applied to the source collection only on the affected labels by ID, whereas previously the entire field was synced to the source collection via a `$merge` aggregation

More tagging optimization

---

fiftyone/core/patches.py
fiftyone/core/video.py
tests/unittests/video_tests.py

Previously, editing the `filepath` of a frame view would not sync to the source dataset's frame `filepath`, but this should be allowed, since frame views were intended to sync all relevant frame fields of the source dataset. This PR resolves the bug.
```py
dataset = foz.load_zoo_dataset("quickstart-video", max_samples=1)
frames = dataset.to_frames(sample_frames=True)
sample = frames.first()
sample.filepath = sample.filepath.upper()
sample.save()
print(dataset.first().frames.first().filepath)
upper_view = frames.set_field("filepath", F("filepath").upper())
frames.set_values("filepath", upper_view.values("filepath"))
print(dataset.values("frames.filepath", unwind=True)[:5])
frames.set_field("filepath", …
```

Allow frame views to edit source frame filepaths

---

requirements/common.txt
setup.py

I didn't notice this got bumped in the previous PR. The version was too high for FastAPI and VoxelHub to be able to use it. Dropping it back down.

Downgrade starlette

---

docs/source/integrations/cvat.rst
docs/source/user_guide/annotation.rst
fiftyone/core/config.py

CVAT has recently moved from hosting their server from cvat.org to app.cvat.ai. This PR updates the integration to point to app.cvat.ai by default and updates corresponding the references in the docs and tutorials.

Update CVAT integration and docs to point to app.cvat.ai

---

app/packages/core/src/components/Common/RangeSlider.tsx

Fix an issue where multi-line range slider label covers range slider thumb. Also adds an enhancement to show lower range label on hover when two labels are near and the higher range label covers lower range label.
Visually tested to ensure label for various types of range slider renders correctly.
-   [ ] Other

fix range slider value label style

---

app/packages/core/src/components/ViewBar/ViewStage/ViewStage.tsx
app/packages/core/src/components/ViewBar/ViewStage/ViewStageParameter.tsx

Fix view bar colors not updating when toggling between light and dark theme. React spring library resolves css variable to it's corresponding color codes resulting in static colors which are staled when theme mode is switched. Changes in this PR forces re-resolution of color on theme change. 
Visually tested by toggling between theme to ensure colors updates as intended.
- …

update view bar colors on theme change

---

app/packages/components/src/components/Tooltip/Tooltip.module.css
app/packages/dataset/src/Dataset.tsx

Removes redundant font family styles
Visually inspected affected components to ensure font family remains the same
-   [ ] Other

remove redundant font family styles

---

app/packages/components/src/components/ThemeProvider/index.tsx
app/packages/looker/src/elements/common/tags.module.css

Fixes a style issue where label tag text color becomes lighter shade of black. 
Tested by visually inspecting label tag text color in both dark and light theme
-   [ ] Other

fix label tag text color in light theme

---

app/packages/components/src/components/TabOption/TabOption.tsx
app/packages/core/src/components/Actions/Checker.tsx
app/packages/core/src/components/utils.tsx

Improve action row popover items background and text color
Tested visually in both light and dark theme
-   [ ] Other

action row popover content color enhancements

---

app/packages/core/src/components/Sidebar/Entries/Draggable.tsx
app/packages/core/src/components/Sidebar/Entries/RegularEntry.tsx

Fixes an issue where toggle field does not register click sometime if you move cursor right after click a field or checkbox.
Visually inspected to ensure clicking and moving the cursor away is registered as toggle but drag or selection is not.
-   [ ] Other

fix toggling field not capturing click some times

---

app/packages/components/src/components/Icons/Icons.tsx
app/packages/components/src/components/Icons/index.ts
app/packages/components/src/components/JSONPanel/JSONPanel.tsx
app/packages/components/src/components/JSONPanel/json.module.css
app/packages/state/src/hooks/useJSONPanel.ts

Fix JSON panel syntax highlighting colors and copy/close icon colors in light theme.
Tested visually in both light and dark theme.
-   [ ] Other

fix json panel styles in light theme

---

app/packages/app/public/404.html
fiftyone/server/.gitignore

A change in starlette default 404 handling now requires a 404.html to be present in the static directory for the Static file route to resolve on app routes, e.g. `dataset/my-dataset`. Adding a dummy 404.html to the public folder in `@fiftyone/app` accommodates the peculiar behavior.

Build 404 for SPA intex.html handling

---

fiftyone/core/stages.py

In the typical case where the number of selected IDs is small compared to the number of total documents, this implementation of ordered `select()`, `select_by()` and `select_groups()` should be more efficient. `$match` first, then `$set`.

Optimizing ordered select implementation

---

app/packages/dataset/src/index.ts
app/packages/dataset/src/index.tsx
app/packages/state/README.md

Allows for managing state externally.
See [here](https://github.com/voxel51/fiftyone/pull/2214/files#diff-df67c1016008538fab6072e014adc3a196aeb28234134be32382edf99f41c043R41) for example usage.

Export state from dataset module

---

app/packages/core/src/components/Sidebar/Entries/FilterablePathEntry.tsx
app/packages/core/src/components/Sidebar/Entries/FilterableTagEntry.tsx
app/packages/core/src/components/Sidebar/Entries/RegularEntry.tsx

Improve sidebar toggle entry to only toggle when header of entry is clicked and prevent toggle on click and drag to avoid unexpected toggle on selection of entry text.  
Tested visually by interacting with field to ensure entry is toggled only when expected. 
-   [ ] Other

toggle sidebar entry only on clicking header

---

app/packages/core/src/components/Sidebar/Entries/RegularEntry.tsx

PR fixes error in console when click start event is not set on toggling sidebar entry. Not really sure why `onMouseUp` handler would be called without click start event being set in `onMouseDown` handler.
Tested manually to verify console error is no longer logged.
-   [ ] Other

fix toggle error when click start event is unset

---

fiftyone/server/dataloader.py

Replace `==` with `=` so `id` key becomes `_id`
(Details)
-   [ ] Other

Fix typo in get_dataloader 

---

app/packages/core/src/Root/Root.tsx
app/packages/core/src/Root/__generated__/RootConfig_query.graphql.ts
app/packages/core/src/Root/__generated__/RootQuery.graphql.ts
app/packages/core/src/__generated__/DatasetQuery.graphql.ts
app/packages/relay/src/mutations/__generated__/setViewMutation.graphql.ts
app/packages/relay/src/queries/__generated__/histogramValuesQuery.graphql.ts
app/packages/state/src/hooks/useStateUpdate.ts
app/packages/state/src/recoil/types.ts
app/schema.graphql
docs/source/user_guide/config.rst
fiftyone/core/config.py
fiftyone/server/query.py

Adds support for configuring the default App theme via your [App config](https://voxel51.com/docs/fiftyone/user_guide/config.html#configuring-the-app).
```shell
export FIFTYONE_APP_THEME=light
```
```py
print(fo.app_config.theme)  # 'light'
print(session.config.theme)  # 'light'
session.config.theme = "dark"
session.refresh()
```

Add support for configuring the default App theme

---

app/packages/core/src/components/Actions/ActionsRow.tsx
app/packages/core/src/components/Actions/Common.tsx

Fixes #2281
- Hide bookmark icon when no filters are applied
- Render anchor element instead of div in `ItemAction` when there's a href
On a dev build
-   [ ] Other

hide bookmark icon when no filters are applied

---

app/packages/core/src/__generated__/DatasetQuery.graphql.ts
app/packages/relay/src/mutations/__generated__/setViewMutation.graphql.ts
app/schema.graphql
fiftyone/core/odm/dataset.py
fiftyone/server/metadata.py
fiftyone/server/query.py

v0.18 purports to be backwards-compatible with v0.16.6 datasets. However, this is not currently the case because it does not appropriately handle missing `app_config`s.
```shell
fiftyone zoo datasets load quickstart
fiftyone migrate -v 0.16.6 -n quickstart
export FIFTYONE_DATABASE_ADMIN=false
```
```py
dataset = fo.load_dataset("quickstart")
db = foo.get_db_conn()
assert "app_config" not in db.datasets.find_one({"name": "quickstart"})
assert dataset.version == "0.16.6"
assert dataset.app_config is not None  # previously failed; now doesn't
session = fo.launch_app(dataset)  # TODO: fix this
dataset.app_config.grid_media_field = "foo"  # force mongoengine to detect a change
dataset.app_config.grid_media_field = "filepath"
dataset.save() …
```

Patch v0.16.6 compatibility

---

app/packages/core/src/components/Actions/ActionsRow.tsx

Show bookmark icon also when extended selection is on or samples are selected using checkbox. Fixes https://github.com/voxel51/fiftyone/issues/2306
Locally
-   [ ] Other

Fix bookmark icon bug

---

fiftyone/utils/video.py
tests/intensive/video_tests.py

Count exact number of frames in a video.
added a unit-test to the intensive group.
Exact number of frames can be counted with `fiftyone.utils.video.exact_frame_count()`.
This method uses `-count_frames` argument of `ffprobe` which decodes the entire video to count the frames and can be very slow.
-   [ ] Other

count exact number of frames with ffprbe -count_frames

---

fiftyone/core/dataset.py
fiftyone/core/singletons.py
tests/unittests/dataset_tests.py

```py
last_loaded_at1 = dataset.last_loaded_at
dataset = fo.load_dataset("quickstart")
last_loaded_at2 = dataset.last_loaded_at  # previously didn't update; now does
assert last_loaded_at2 > last_loaded_at1
dataset.reload()
last_loaded_at3 = dataset.last_loaded_at  # previously didn't update; now does
assert last_loaded_at3 > last_loaded_at2
```

Updating last_loaded_at whenever Dataset is accessed

---

app/packages/state/src/hooks/useStateUpdate.ts

#2303 
When gridMediaField and modalMediaField are set to a field that’s not in the current view’s schema, the App will override to `filepath` (which must always exist). This makes sure the grid always default render on the right path. 
Locally
s this PR affect?
-   [ ] Other

Override gridMeidaField and ModalMediaField to filepath 

---

app/packages/looker-3d/src/Looker3d.tsx

Adds a new setting to the `3d` plugin.
**useLegacyCoordinates** - defaults to `false` - if you want to get the original style back, just set this to true
`true` - The y position for `Cuboids` will be `location.y + 0.5 * dimensions[1]`.
`false` - The y position for `Cuboids` will be `location.y`.

add flag for switching coordinate style

---

app/packages/dataset/src/Dataset.tsx
app/packages/state/src/hooks/useRouter.ts

Ensure the relay environment is created when the `Dataset` component is used apart for `useRouter()`.

fix sidebar ordering in embed ctx

---

app/packages/core/src/components/Actions/Tagger.tsx

#2278 
Compute Sample and Label tags count seperately in tag UI
locally
-   [ ] Other
https://user-images.githubusercontent.com/17770824/204662476-d12fe69d-3b99-4c82-9577-09338ebdd1b9.mov

Compute sample and label tags counts seperately in tag UI

---

app/packages/core/src/components/Grid/Grid.tsx
app/packages/flashlight/src/index.ts

Fixes situations in which the schema changes when the view changes and flashlight must reset before other effects are run. Also ensures loading pixels are shown during a loading state.

Fix Flashlight resets

---

app/packages/looker/src/index.ts

Ensures the sample is loaded before rendering an unloaded state. Fixes expanding the group modal.
```py
session = fo.Session(dataset) # open the modal
```

Ensure sample is present when rendering an unloaded looker (Fix groups modal)

---

docs/source/integrations/cvat.rst
fiftyone/utils/cvat.py
tests/intensive/cvat_tests.py

Closes #1753 
1. Custom task name can be passed for labelling data in CVAT such as `dataset.annotate("anno_key", backend="cvat", task_name="Custom task name", ...)`
2. Default task name for CVAT to include an annotation key such as `FiftyOne_{dataset_name}_{annotation_key}`
added few lines to existing cvat unit-tests.
A custom task name can be provided with CVAT annotation backend. Default CVAT task name now includes an annotation key.
- …

Provide custom task name for CVAT

---

app/packages/map/src/Map.tsx

fixes #2363 
Handle the map token error when rendering the map
Local
-   [ ] Other

show message for bad token error in map plugin

---

app/packages/core/src/components/Filters/CategoricalFilter.tsx

fixes #2277 
None/Null should not be treated equally as the other value options. There will be a separate ticket tracking how to allow user to select the empty value samples. 
(Details)
-   [ ] Other

Remove `none` as an option from other value options

---

app/packages/core/src/components/Grid/Grid.tsx
app/packages/state/src/hooks/useStateUpdate.ts

Sometimes state updates that are pushed to the App are not handled correctly by the grid. This should fix the issue.

Fix grid sync from event source

---

app/packages/core/src/components/Filters/CategoricalFilter.tsx

fixes #2308 
ID list should always be displayed as a filter search, instead of expanded selection options.
Locally
-   [ ] Other

Never show expanded list for ID fields

---

app/packages/core/src/components/FieldLabelAndInfo/index.tsx

fixes #2409 
Do not re-format label attributes (convert _ to spaces)
-   [ ] Other

Undo reformat of label

---

app/packages/core/src/components/Actions/Tagger.tsx
app/packages/core/src/components/Actions/utils.tsx
app/packages/core/tests/components/Actions/utils.test.ts

Resolves #2433
Previously the `allTags` selector would query for both label and sample tags via a aggregation graphql call. Now they have separate dataflow.

Remove label query from sample tagger data flow

---

app/packages/core/src/components/Actions/Patcher.tsx

Resolves #2275. The current application will display any evaluation key in the Evaluations dropdown in the app's patches menu UI. This is problematic because evaluation types that are not supported will throw an error and cause the app to hang, yet showing them in the dropdown enables the user to pass the evaluation into to_evaluation_patches(). In this PR, rather than showing every key in the active session in the dropdown, I am filtering the keys based on whether or not the type of their corresponding evaluation is supported by the to_evaluation_patches() function. I did so by consulting the dataset schema, as performed in various other places in the Patcher.tsx file to extract the necessary field types.
This patch does not currently include an explicit test suite. I was unable to …

Only show supported eval keys

---

docs/source/user_guide/groups.rst
fiftyone/__public__.py
fiftyone/core/collections.py
fiftyone/core/stages.py
tests/unittests/group_tests.py

`dataset.exclude_groups()`, and the associated `ExcludeGroups()` stage. Syntax is as you'd expect:
```py
group_ids = dataset.take(10).values("group.id")
view = dataset.exclude_groups(group_ids)
view_group_ids = set(view.values("group.id"))
dataset_group_ids = set(dataset.values("group.id"))
assert view_group_ids == set(group_ids)
assert set() = view_group_ids.intersection(dataset_group_ids)
```
-   [ ] Other

added exclude_groups() to mirror select_groups()

---

fiftyone/core/collections.py
fiftyone/utils/data/exporters.py
tests/unittests/import_export_tests.py

Adds more flexibility for specifying frame field exports via `export()`.
Previously only this was allowed:
```py
dataset.export(..., frame_labels_field="XXX")
```
Now any of these are allowed:
```py
dataset.export(..., label_field="frames.XXX")
dataset.export(..., frame_labels_field="XXX")
dataset.export(..., frame_labels_field="frames.XXX")
```
Example usage:
```py
export_dir="/tmp/quickstart-video",
dataset_type=fo.types.CVATVideoDataset,
)
```

Allow frame-level fields to be passed via export(label_field=)

---

fiftyone/core/collections.py
fiftyone/core/stages.py
fiftyone/core/video.py
tests/unittests/video_tests.py

Fixes a bug when calling `to_frames(sample_frames=True)` on a view that filters the frames of the input dataset. The following would previously raise an error but now does not:
```py
view = dataset.match_frames(F("frame_number") == 51)
frames1 = view.to_frames(sample_frames=True, sparse=True)
assert len(frames1) == 10
assert dataset.count("frames.filepath") == 10
frames2 = view.to_frames(sample_frames=True)
assert len(frames2) == 1279
assert dataset.count("frames.filepath") == 1279
```

Using dataset as source of truth for existing frames when sampling frames with to_frames()

---

docs/source/user_guide/model_zoo/index.rst
fiftyone/utils/torch.py

Adds my tip from https://github.com/voxel51/fiftyone/issues/2343#issuecomment-1324524198 formally to the docs.

Documenting how to use custom torch models with builtin FiftyOne methods

---

app/packages/relay/src/mutations/__generated__/setGroupSliceMutation.graphql.ts
app/packages/relay/src/mutations/setGroupSlice.ts
app/schema.graphql
fiftyone/server/aggregate.py
fiftyone/server/aggregations.py
fiftyone/server/mutation.py

- Add a default value when view_name isn't provided
- Addresses https://voxel51.atlassian.net/browse/TEAMS-684
- Run app and verify no error thrown when clicking on Sample tags, Label tags, Labels, and Other fields
- 
- Run app and view `quickstart-groups` dataset. Toggle between left and right group selectors:
- 
- <img width="885" alt="image" src="https://user-images.githubusercontent.com/30936736/209729851-07d09065-1d46-4e63-9883-0743a44b3a0d.png">
-   [ ] Other

[BUG] Fix missing view_name error

---

fiftyone/server/routes/embeddings.py

Updates the existing `post()` method to handle patches plots connected to non-patches views (and vice versa).
Also adds a proposed refactor that splits the above logic into three separate methods:
- `on_plot_load()`: logic needed to load an initial embeddings plot based on the current view
- `on_extended_view_update()`: logic needed to update the selection state of the points in an existing plot when the extended view changes
- `on_selection()`: logic needed to update the current extended view when a selection occurs in the embeddings plot

Proposed refactor to embeddings plot backend

---

fiftyone/core/dataset.py

Refactors clearing of a dataset's run cache into a dedicated `clear_cache()` method. Previously, calling `SampleCollection.reload()` would cause a dataset's cache of run results to be cleared, which is really a separate operation.
`reload()` is required when another process has edited a dataset's field schema, while `clear_cache()` is only required if one is concerned about memory issues due to loading too many large run results into memory in a single session.

Separate method for clearing a dataset's run cache

---

app/packages/core/src/components/Actions/ActionsRow.tsx

Ensure that the tagging icon is not shown when in `readOnly` mode.

fix-teams-163

---

fiftyone/utils/cvat.py
tests/intensive/cvat_tests.py

There was a similar issue when checking if projects exists that we ran into for tasks in https://github.com/voxel51/fiftyone/pull/2070. The issue arises when too many projects exist in once CVAT organizaton.
This is also a similar solution in that it attempts to access the URL for the project and assumes it does not exist on a 404 error. This PR also adds a test for this issue that now passes.

Fix CVAT bug when checking if a project exists

---

fiftyone/utils/csv.py

Closes https://github.com/voxel51/fiftyone/issues/2493
`csv` module quotes the delimiter and double-quotes already with the default `dialect`.
So we do not need to add the literal quotes surrounding the stringified list, as `csv` 
will then quote it again (with 2 double quotes) so we end up with 3 total.
Even though it's the default, I've passed in `quoting=csv.QUOTE_MINIMAL` just to make
sure it's done anyways.
```
view = dataset.limit(2)
view.export(
dataset_type=fo.types.CSVDataset,
export_dir="/tmp/csv_export_test",
fields=[
"filepath",
"tags",
"ground_truth.detections.tags",
"ground_truth.detections.label"
]
)
```
Checked export output which now looks like this:
``` …
```

bugfix: CSVDatasetExporter - Dont pre-quote list values

---

app/packages/core/src/components/Sidebar/ViewSelection/ViewDialog.tsx
app/packages/core/src/components/Sidebar/ViewSelection/index.tsx
app/packages/dataset/src/Dataset.tsx
app/packages/state/src/recoil/atoms.ts

This pr enables passing a canEdit property to ViewSelection. if true, this property would make ViewSelection an editable component. if false, disables the "save new view" and hides edit/delete options.
the changes for teams are in kacey's branch
(Details)
-   [ ] Other

ViewSelection and its subcomponents capable of rendering readonly or editable versions

---

app/packages/state/src/hooks/useSetDataset.ts
app/packages/state/src/routing/matchPath.ts
app/packages/state/src/utils.ts

- Currently, if a dataset name has spaces or other encodable symbols, it is not possible to interact with the dataset in the app because the name will be uri encoded and thus not resolve properly. 
- This change enables using the app for datasets with names like "dataset with name" without requiring a change in the database schema
- This issue will be fully resolved once slugs are merged (https://voxel51.atlassian.net/browse/TEAMS-386)
1. Create a dataset with spaces in the name:
```import fiftyone as fo
dataset = foz.load_zoo_dataset("quickstart", dataset_name="quickstart with  spaces")
```
2. Start the dev server and open the app in the browser.
3. From the `Select dataset` dropdown, select a dataset with spaces in the name
4. Observe …

[BUG FIX] Enable selecting datasets with spaces in the name

---

fiftyone/core/clips.py
fiftyone/core/dataset.py
fiftyone/core/patches.py
fiftyone/core/video.py
tests/unittests/patches_tests.py
tests/unittests/video_tests.py

It should ideally possible to declare a new dynamic label attribute by applying `set_values()` to a generated view (eg patches). Previously the values themselves would be added, but the field wouldn't be added to the underlying dataset's schema. This PR adds the schema piece.
```py
patches = dataset.to_patches("ground_truth")
patches.set_values("ground_truth.foo", ["bar"] * len(patches), dynamic=True)
assert "ground_truth.detections.foo" in dataset.get_field_schema(flat=True)
```

Adding support for declaring dynamic fields on generated views via set_values()

---

app/packages/state/src/recoil/sidebar.ts
app/packages/state/src/recoil/types.ts
app/packages/state/tests/recoil/sidebar.test.ts
app/packages/utilities/src/index.ts
fiftyone/server/query.py

fixes #2284 
- set the groups expansion default to none in the BE 
- in the FE, let `resolveGroup` would expand the defaulted open fields
(Details)
-   [ ] Other

groups expansion should be defaulted to none

---

fiftyone/server/app.py
fiftyone/server/routes/__init__.py
fiftyone/server/routes/embeddings.py

For Teams routing, the OSS routes must be represented as a flat list of tuple definitions for proper construction.

Maintain Starlette route list

---

app/packages/spaces/src/components/Space.tsx
app/packages/spaces/src/hooks.ts
app/packages/spaces/src/state.ts

PR expands spaces panel tabs dropzone area
Interactively within the app as it involves dragging and dropping a tab from one space to another
-   [ ] Other

expand tab drop zone in spaces

---

app/packages/core/src/components/Actions/ActionsRow.tsx
app/packages/core/src/components/Actions/utils.tsx
app/packages/state/src/recoil/atoms.ts

fixes #2541 
As a user, if I did not select any sample and I go into the sample modal view, then when I select labels on the sample, this sample will be added to the selected samples. This way, when I click add sample tag, the tag applies to the current sample, instead of all the samples in the dataset. 
Note: Select labels will not add current sample to selected sample, if the user already selected some samples. It only applies if selectedsample is a empty set. 
https://user-images.githubusercontent.com/17770824/213489763-fd8b088b-c39c-4e7a-bc55-9dd1605d9292.mov
See video.
(Details in 1-2 sentences. You can just refer to another PR with …

update select sample with select label under condition

---

app/packages/state/src/routing/RouterContext.ts

Related #2290 
Fixes handling of GraphQL errors so an informative error is shown.
```py
session.view = dataset.select_group_slices(media_type="image").to_patches("ground_truth")
```

Throw GraphQL errors correctly

---

app/packages/dataset/index.html

- `dataset/index.html` references `./src/index.tsx` which doesn't exist. The existing file is `./src/index.ts`
- without fixing the reference, the dataset package will fail to build 
- 
(Details)
-   [ ] Other

Fix import path

---

app/packages/core/src/components/Filters/NumericFieldFilter.tsx

**Related**
- pull/2466
- TEAMS-763
**Resolves**
"Rendered fewer hooks than expected" when dataset schema changes. Eg. when removing to_patches view stage or select stage.

fix sidebar issue

---

app/packages/dataset/src/Dataset.tsx

This is needed to load the embeddings plugin in the dataset/embed env.

add embeddings plugin to dataset

---

fiftyone/core/collections.py
fiftyone/core/stages.py
fiftyone/server/query.py

Extension of https://github.com/voxel51/fiftyone/pull/2569 that allows for directly passing text prompts to `sort_by_similarity()` when the similarity index was generated by a model that supports prompt embeddings.
```py
fob.compute_similarity(dataset, model="clip-vit-base32-torch", brain_key="clip")
prompt = "kites high in the air"
view = dataset.sort_by_similarity(prompt, k=10, brain_key="clip")
session.view = view
```

Adding native support for text prompts

---

app/packages/state/src/hooks/useSessionSpaces.ts

Update local sessionSpaces atom when space layout or panel state is updated
PR is an enhancement to sessionSpaces atom update and was tested manually to ensure space session continues to work as before
-   [ ] Other

update local sessionSpaces atom on space changes

---

fiftyone/server/query.py

Fix error: 
`ERROR:strawberry.execution:unhashable type: 'StrawberryAnnotation'`
with traceback: 
```Traceback (most recent call last):
File "/Users/kacey/Dev/voxel-hub/fiftyone-teams/teams/lib/python3.9/site-packages/graphql/execution/execute.py", line 528, in await_result
return_type, field_nodes, info, path, await result
File "/Users/kacey/Dev/voxel-hub/fiftyone-teams/teams/lib/python3.9/site-packages/strawberry/schema/schema_converter.py", line 513, in _async_resolver
return await await_maybe(_get_result(_source, strawberry_info, **kwargs))
File "/Users/kacey/Dev/voxel-hub/fiftyone-teams/teams/lib/python3.9/site-packages/strawberry/schema/schema_converter.py", line 499, in _get_result
return field.get_result(
File "/Users/kacey/Dev/voxel-hub/fiftyone-teams/teams/lib/python3.9/site-pack …
```

[Bug Fix] Fix gql saved view field

---

app/packages/state/src/hooks/useStateUpdate.ts
fiftyone/server/routes/sort.py

fixes #2576 
fixed the issue of extended stage not being updated by `useStateUpdate` when sort by similarity on UI
https://user-images.githubusercontent.com/17770824/215925402-791fc25f-2af5-4705-bca4-db3152b558c6.mov
Locally
-   [ ] Other

bugfix: Sort by similarity is broken

---

app/packages/core/src/components/Filters/categoricalFilter/Wrapper.tsx
app/packages/core/src/components/Filters/utils.ts
app/packages/core/src/components/Modal/TooltipInfo.tsx
app/packages/state/src/recoil/pathFilters/index.ts
app/packages/state/src/recoil/pathFilters/string.ts

fix  #2508 
1. filter dropdown should always show as long as totalcount is more than 0. 
2. added filter labels for listfields
3. tooltip will display listfields (except for bounding box) in modal view
locally
-   [ ] Other

bugfix: update filter labels for listfield

---

fiftyone/utils/cvat.py
tests/intensive/cvat_tests.py

Resolves #2572
Resolves #2567
Resolves #2565 
Thanks to @tjaeuth for the recommendation!
The CVAT API response for the jobs query has been modified slightly which broke our integration for v2.4 servers. This PR adds support for v2.4 servers and updates our tests. All tests pass on both v2.3 and v2.4 now.

Add support for CVAT v2.4

---

setup.py

Dacite 1.8.0 breaks Strawberry. Specifically, fields with resolvers like `Dataset.stages` that result in a `StrawberryAnnotation` type in the parent `__annotations__`.
```
[2023-02-01 09:16:42 -0600] [57577] [INFO] Running on http://0.0.0.0:5151 (CTRL + C to quit)
unhashable type: 'StrawberryAnnotation'
GraphQL request:7:3
6 |   ...DatasetSavedViewsFragment
7 |   dataset(name: $name, view: $view, savedViewSlug: $savedViewSlug) {
|   ^
8 |     stages(slug: $savedViewSlug)
File "/Users/benjaminkane/venvs/fo/lib/python3.10/site-packages/graphql/execution/execute.py", line 528, in await_result
return_type, field_nodes, info, path, await result
File "/Users/benjaminkane/venvs/fo/lib/python3.10/site-packages/strawberry/schema/schema_converter.py", line 513, in …
```

Restrict dacite

---

app/packages/core/src/components/Actions/ActionsRow.tsx

bookmark icon always appears when there is an active similarity sort in extended_stages
(Details)
-   [ ] Other

bookmark icon always appears when there is an active similarity sort in extended_stages

---

app/packages/core/src/components/Actions/ActionsRow.tsx
app/packages/core/src/components/Actions/Similar.tsx

https://user-images.githubusercontent.com/17770824/216185385-72c22ea4-5963-4cde-9114-1861cd6a64b6.mov
(Details)
-   [ ] Other

Automatically clear sample selection after sort by similarity is applied

---

app/packages/core/src/components/Common/Checkbox.tsx
app/packages/core/src/components/FieldLabelAndInfo/index.tsx
app/packages/core/src/components/Filters/NumericFieldFilter.tsx
app/packages/core/src/components/Filters/StringFieldFilter.tsx
app/packages/core/src/components/Filters/categoricalFilter/CategoricalFilter.tsx
app/packages/core/src/components/Filters/index.tsx
app/packages/state/src/recoil/aggregations.ts

Fix bug that prevents keypoints filter tray from opening in
https://github.com/voxel51/fiftyone/pull/2582#pullrequestreview-1276544240
1. skeleton filter tray cannot open because keypoints count fails when skeleton is null;
2. addressed type issues
Locally
-   [ ] Other

bugfix: keypoints count fails without skeleton & type issues

---

app/packages/core/src/Dataset.ts

PR enhances consuming of state proxy in the dataset to be extensible. It now supports providing additional app states beyond view and viewName.
Only an enhancement to the current implementation and was tested in app to ensure state sync works as before
-   [ ] Other

extensible state proxy for dataset

---

app/packages/spaces/src/hooks.ts

Fixes React warning when initializing space state
(Details)
-   [ ] Other

fix warning on setting default space state

---

app/packages/state/src/recoil/aggregations.ts

Fix bug where label choices in the filter tray of a Keypoint field incorrectly show the skeleton points labels as keypoints labels
(Details)
-   [ ] Other

Label choices in filter tray of Keypoints field incorrectly show skeleton labels

---

app/packages/core/src/components/Common/CountSubcount.tsx

fix #2443 
In the extended view, if the `subcount` is `0`, it will return`undefined` and render loading dots.
Added the fallback to 0 when subcount is `undefined`. 
(Details)
-   [ ] Other

Sample tag count in extended view is broken

---

app/packages/core/src/components/Grid/Grid.tsx

The fix is to disable the background grid refresh every-time a tagging happens when the sample modal is open which prevents the extra refresh and also prevents the modal closing unexpectedly.
https://user-images.githubusercontent.com/109545780/216155993-9d17db6a-4758-46f2-a03b-32933bd79a08.mov
(Details)
-   [ ] Documentation: …

Do not refresh grid when modal is open

---

docs/source/user_guide/dataset_creation/datasets.rst
docs/source/user_guide/export_datasets.rst
fiftyone/types/dataset_types.py
fiftyone/utils/data/exporters.py
fiftyone/utils/data/importers.py
fiftyone/utils/data/parsers.py
tests/unittests/import_export_tests.py

Adds a `MediaDirectory` type for importing/exporting arbitrary (homogeneous) directories of media (images, videos, point clouds, etc).
```py
export_dir="/tmp/media",
dataset_type=fo.types.MediaDirectory,
)
dataset_dir="/tmp/media",
dataset_type=fo.types.MediaDirectory,
)
```

Adding support for importing/exporting generic media

---

fiftyone/core/aggregations.py
fiftyone/core/collections.py
tests/unittests/aggregation_tests.py

Fixes a bug identified by @allenleetc:
```py
dataset.count_values('frames[].detections.detections[].label')
```

Handling manual unwinds in aggregations

---

app/packages/core/src/components/Actions/Similar.tsx

As a user, if I submitted a similarity, but no samples are currently selected, 
when I open the similarity menu, 
I should see doc_link and reset button only. 
https://user-images.githubusercontent.com/17770824/216999066-fe6e969c-f568-475b-bc1d-20ad0d717c59.mov
(Details)

Tweak Similarity Menu

---

app/packages/core/src/components/Filters/categoricalFilter/Wrapper.tsx
app/packages/core/src/components/Filters/categoricalFilter/filterOption/FilterOption.tsx
app/packages/looker/src/overlays/keypoint.ts
app/packages/state/src/recoil/pathFilters/boolean.ts
app/packages/state/src/recoil/pathFilters/index.ts
app/packages/state/src/recoil/skeletonFilter.ts
fiftyone/server/view.py

We used to filter keypoints by only confidence and points(label). 
Updated the FE and BE to support other properties and fixed some issues. 
https://user-images.githubusercontent.com/17770824/216675550-ddaef8b9-fd40-4e14-af47-b6cf93cb36af.mov
-   [ ] Other

Add support filtering by dynamic properties in keypoints

---

app/packages/app/src/index.tsx
app/packages/core/src/Dataset.ts
app/packages/state/src/hooks/useSetView.ts
app/packages/state/src/routing/RouterContext.ts

Adds the previously missing `variables` state update in `useSetView`. This is required for the dataset query routing variable `view` to be kept in sync and correctly resolve dataset schemas based on the current view. See [here](https://github.com/voxel51/fiftyone/blob/b691096b1537ea1e5e4b6e5ab446967caa7b4a9d/app/packages/state/src/routing/RouterContext.ts#L94).

Correct schema updates with respect to views

---

app/packages/state/src/hooks/useSetView.ts

In a stateless context, `viewCls` must be set in the state proxy in `useSetView` to ensure default behavior like crop to content in patches views work correctly.

Ensure viewCls for state proxy

---

docs/source/user_guide/plots.rst
fiftyone/core/collections.py
fiftyone/core/plots/matplotlib.py
fiftyone/core/plots/plotly.py
fiftyone/core/plots/utils.py
fiftyone/core/runs.py
fiftyone/server/routes/embeddings.py
tests/intensive/plot_tests.py

Updates methods like `scatterplot()` and the in-App embeddings backend to always rely on sample/label IDs when pulling data for plots.
Previously, these implementations assumed that the `view` on which embeddings/etc were computed has not changed in any way. Now, these methods will gracefully handle added/deleted data.
New tests are added to `tests/intensive/plot_tests.py` to verify that the plotting methods function as expected.

Always use IDs in plots and brain results

---

fiftyone/core/aggregations.py
fiftyone/core/collections.py
tests/unittests/aggregation_tests.py

Fixes a couple bugs with the faceted aggregation logic in `aggregate()`:
- Proper handling of multiple aggregations with the same field name and type
- Proper handling of expressions applied to nested list fields
The unit tests added fail on `develop` but pass on this branch.

Faceted aggregation bug fixes

---

app/packages/core/src/Dataset.ts

PR fixes an error when stateProxy is set but the dataset property of state proxy is not set
Tested in the app by setting state proxy to non-null value and not setting the dataset property
-   [ ] Other

use state proxy dataset only if it's set

---

fiftyone/server/view.py

On `develop`, fixes matching via the sidebar in the App for categorical values on single label fields like `ground_truth` in `cifar100`
```py
dataset = foz.load_zoo_dataset("cifar100")
session = fo.Session(dataset)
```
Filter `ground_truth.label`  in sidebar

Fix matching single label fields

---

fiftyone/server/routes/plugins.py

Before this patch, if you added a plugin without a `fiftyone` key in its package.json, all plugin loading would fail.

fix plugins require fiftyone key

---

app/packages/state/src/hooks/useUpdateSample.ts
app/packages/state/src/recoil/groups.ts

I hope this PR will start a larger discussion on "JSON" scalars in FiftyOne, which is essentially schema-less data used largely for sample data and some inputs. Admittedly, this is a shortcoming of the Relay implementation that I did not anticipate.
The issue at hand can be found [here](https://github.com/facebook/relay/issues/91) and it seems unlikely a proper fix will be provided. A practical solution would be to always serialize "JSON" scalars so edge cases don't have to be accounted for.

Relay invariant comment on scalar hydration

---

fiftyone/server/mutation.py

Extended selection should come before patches and other schema converting stages when pinning state.

Add extended selection before converting to patches when pinning state

---

app/packages/state/src/recoil/groups.ts

Fixes sample data state in the sidebar, etc. when the pinned sample is active in group datasets, e.g. `quickstart-groups`

Fix pinned sample sidebar

---

fiftyone/core/aggregations.py
fiftyone/core/collections.py
fiftyone/core/models.py
fiftyone/core/stages.py
tests/intensive/model_tests.py
tests/unittests/similarity_tests.py

Updates the `compute_patch_embeddings()` method to store patch embeddings directly on `Label` objects when the `embeddings_field` argument is provided.
Previously a `num_objects x num_dims` array would be stored as a top-level sample/frame field, which is less desirable because in that case there's no simple way to, for example, use `filter_labels()` + `values()` to extract the patch embeddings for a particular class.

Store patch embeddings directly on label objects

---

docs/source/user_guide/dataset_creation/datasets.rst
docs/source/user_guide/export_datasets.rst
fiftyone/types/dataset_types.py
fiftyone/utils/csv.py
requirements/test.txt
tests/unittests/import_export_tests.py

Adds support for importing datasets stored as CSV files.
```py
dataset = foz.load_zoo_dataset("cifar10")
labels_path="/tmp/cifar10.csv",
dataset_type=fo.types.CSVDataset,
fields={
"filepath": "filepath",
"tags": "tags",
"ground_truth.label": "ground_truth",
},
abs_paths=True,
)
labels_path="/tmp/cifar10.csv",
dataset_type=fo.types.CSVDataset,
fields={
"filepath": None,  # load as strings
"tags": lambda v: v.strip("").split(","),
"ground_truth": lambda v: fo.Classification(label=v) if v else None,
},
)
assert set(dataset.values("filepath")) == set(dataset2.values("filepath"))
assert dataset.count_sample_tags() == dataset2.count_sample_tags()
assert dataset.count_values("ground_truth.label") == …
```

Add support for importing CSV datasets
