voxel51/fiftyone

electron/app/components/CheckboxGrid.tsx
electron/app/components/DisplayOptionsSidebar.tsx
electron/app/components/ImageContainerHeader.tsx
electron/app/components/Sample.tsx
electron/app/components/Tags/SelectionTag.tsx
electron/app/containers/SamplesContainer.tsx
electron/app/utils/hooks.ts

Some design improvements to the sidebar
Locally with some test datasets
(Should probably be combined with other app-side changes)

Sidebar improvements

---

electron/app/utils/tile.ts

Addresses #396. I will double check things in the morning, but this should work. Forgot to test with images with varying aspect ratios.
Visually.

fix tiling in last row, only adjust if threshold hasn't been reached

---

.github/workflows/build-docs.yml
README.md
docs/source/conf.py
docs/source/getting_started/install.rst
docs/source/getting_started/troubleshooting.rst

Documentation for more installation troubleshooting steps, including some common issues that users have encountered.
I split this into a separate page since it's longer than the actual installation guide now (and as a plus, there's no longer just one nav link under "Installation" in the left sidebar)
Built docs locally
(Might be worth mentioning)
-   [ ] `App`: FiftyOne application changes
-   [x] …

Expand troubleshooting docs

---

electron/app/components/Header.tsx
electron/app/icons.tsx

Closes #431
Links
Clicked all the links
section
notes
-   [ ] `bug-fix` - A user-facing bug fix worth mentioning in the release notes
-   [ ] …

Add more links to header

---

electron/app/components/Filter.tsx
electron/app/components/ViewBar/ViewStage/SearchResults.tsx

* Clear labels fixes
* Label results scrolling
* Smaller, consistent fonts

Filtering fixes and tweaks

---

electron/app/Routes.tsx
electron/app/components/DisplayOptionsSidebar.tsx
electron/app/components/Player51.tsx
electron/app/components/Sample.tsx
electron/app/components/SampleModal.stories.tsx
electron/app/components/SampleModal.tsx
electron/app/components/Samples.tsx
electron/app/components/utils.tsx
electron/app/containers/Dataset.tsx
electron/app/containers/SamplesContainer.tsx
electron/app/recoil/atoms.ts
electron/app/recoil/selectors.ts
electron/app/utils/colors.ts

* Improved color selection
* A fixed color palette used for the first ~12 labels (fixes #386)
* A button to choose new colors
Local app instance
App: Improved label colors 
section
notes
-   [ ] `bug-fix` - A user-facing bug fix worth mentioning in the release …

Improve colors

---

electron/app/components/Player51.tsx

Review after #487 is merged. Removes filtering from `loadOverlay`. Before this, the filters inherited by the sample modal would permanently remove overlay data.
Locally.
section
notes
-   [ ] `bug-fix` - A user-facing bug fix worth mentioning in the release …

Overlay fix

---

electron/app/components/Player51.tsx
electron/app/components/SampleModal.tsx
electron/app/utils/labels.ts

A couple minor player51 changes (including #491, #492)
Locally
section
notes
-   [ ] `bug-fix` - A user-facing bug fix worth mentioning in the …

Player51 tweaks

---

electron/app/components/Filter.tsx

Resolves #493 
Built app locally and tested with quickstart
Fixed confidence slider look and feel
-   [ ] Other

Fixes confidence slider look and feel in production build

---

electron/app/components/Player51.tsx
electron/app/components/SampleModal.tsx

Title
Locally (multi-image dataset with detections, confidences, etc)
See above
-   [ ] Other

Save and restore player51 overlay options when navigating

---

.github/workflows/build.yml

CI: fix upgrading pip on Windows

---

electron/app/components/ViewBar/ViewStage/ViewStage.tsx
electron/app/components/ViewBar/ViewStage/viewStageMachine.ts
electron/app/components/ViewBar/viewBarMachine.ts

title
Locally
-   [] Yes. Give a description of this change to be included in the release

ViewBar: Focus on enter for active stages, move right on stage commit

---

README.md
tests/utils/session_helper.py

Title
Positioning inspired by https://github.com/tensorflow/tensorflow
Also hopefully fixed a test failure seen in https://github.com/voxel51/fiftyone/runs/1112658847
https://github.com/voxel51/fiftyone/blob/4657de1fbf93f3806f3ddecb02596b31f465cf70/README.md
-   [ ] Other

Add test badge to readme

---

.github/tools/check-setup-version.py
.github/workflows/build-db.yml
.github/workflows/build-docs.yml
.github/workflows/build-gui.yml
.github/workflows/build.yml
.github/workflows/chromatic.yml
package/db/setup.py
package/gui/setup.py
pytest.ini

Various updates to workflows. Many workflows have cached dependencies now.
Tested several runs - see below. Note that some runs were cancelled, and some intentionally failed, so a lot of commits have a red "x" even if there weren't actually any issues there. For example, https://github.com/voxel51/fiftyone/commit/47caea18860ceffefe18ebdb8674e44d1047065c was also tagged with two deliberately malformed tags, so there are failed checks associated with that commit, but they're not associated with this branch.
-   [ ] App: …

GitHub actions updates/cleanup

---

CONTRIBUTING.md

Storybook is working now thanks to `ExternalLink`s!
N/A

Remove disabled chromatic note in CONTRIBUTING.md

---

electron/package.json
electron/yarn.lock

Recoil upgrade - resolves some issues with state updates after hot reloading, as well as some Batcher-related warnings.
Locally - made some changes to components to trigger a hot reload, and was still able to use the sidebar normally (which previously required a hard reload). Haven't noticed any new issues.
Dev-facing only
-   [ ] Other

Upgrade recoil to 0.0.13

---

setup.py

This needs to get merged into develop (once tests pass) in order to be merged into master

Bump v0.6.0.1

---

docs/source/_static/css/custom.css
fiftyone/core/odm/mixins.py

Various documentation fixes, mostly CSS-related.
Fixes #270 
Fixes #572 
Local build of docs
-   [ ] Other

Docs fixes

---

fiftyone/core/dataset.py

Closes https://github.com/voxel51/fiftyone/issues/402.
```py
sample = fo.Sample(filepath="image.png")
dataset.add_samples([sample, sample])
```
Both of the add commands above now give error messages as follows:
```
ValueError: E11000 duplicate key error collection: fiftyone.samples.2020.10.08.00.55.47 index: filepath_1 dup key: { filepath: "/Users/Brian/dev/fiftyone/image.png" }
```

Raising an informative error when `Dataset.add_samples()` fails

---

docs/source/getting_started/install.rst
docs/source/getting_started/troubleshooting.rst

Docs: clarify that Python 3.9 is not yet supported

---

docs/source/user_guide/dataset_creation/zoo.rst
fiftyone/core/cli.py
fiftyone/utils/lfw.py
fiftyone/zoo/__init__.py
fiftyone/zoo/base.py

Adds the [Labeled Faces in the Wild dataset](http://vis-www.cs.umass.edu/lfw) to the dataset zoo.
```shell
fiftyone app view -z lfw -s test
```

Adding LFW to the zoo

---

electron/app/components/SelectionMenu.tsx

Update selection menu to use new state shape

---

electron/app/recoil/selectors.ts

Omit private fields from App dropdown menus

---

docs/source/environments/index.rst
docs/source/faq/index.rst
docs/source/release-notes.rst
docs/source/user_guide/app.rst
docs/source/user_guide/brain.rst
docs/source/user_guide/dataset_creation/datasets.rst
docs/source/user_guide/export_datasets.rst

These instructions need PR #692 
Add examples for:
* Connecting multiple App instances to the same remote dataset
* Launching multiple local App instances connecting to different datasets
* Collaborating with others that only want to visualize a remote dataset in the App
* Collaborating with others that want to programmatically interface with a remote dataset and use the App

Update FAQ with examples for remote sessions

---

app/src/containers/Setup.tsx
docs/source/cli/index.rst
docs/source/environments/index.rst
docs/source/faq/index.rst
docs/source/getting_started/install.rst
docs/source/release-notes.rst
docs/source/user_guide/app.rst
docs/source/user_guide/config.rst
docs/source/user_guide/using_views.rst
fiftyone/core/cli.py
fiftyone/core/config.py
fiftyone/core/context.py
fiftyone/core/session.py
fiftyone/core/view.py
fiftyone/utils/quickstart.py

Did a pass over the docs to add more exposition where I thought it was useful; updated some old docs sections like remote sessions, and other small consistency tweaks.

Docs updates for colab launch

---

app/src/components/Filter.tsx
app/src/components/Header.tsx
app/src/components/HorizontalNav.tsx
app/src/components/ImageContainerHeader.tsx
app/src/components/Player51.tsx
app/src/components/ViewBar/ViewStage/ViewStage.tsx
app/src/components/ViewBar/ViewStage/ViewStageParameter.tsx
app/src/containers/App.tsx
app/src/containers/SamplesContainer.tsx
app/src/containers/Setup.tsx

Safari fixes

---

fiftyone/server/main.py

Resolves #737
A `None` value must be checked for because of `SampleCollection`s `__bool__` definition.

Fix empty view stats

---

fiftyone/server/main.py

I've been using the v0.7.1 feature that enables `database_dir` to be customized via my FiftyOne config, and noticed that there was one more bit of code that was creating a directory in the old hard-coded location of `~/.fiftyone/var`.
@benjaminpkane This `server.log` seems to be unused; can you confirm that this change is safe?

Removing unused server log directory

---

docs/source/cli/index.rst
fiftyone/core/cli.py

```shell
$ fiftyone datasets stats quickstart -m
key            value
-------------  --------
samples_count  200
samples_bytes  1289086
samples_size   1.2MB
media_bytes    24412374
media_size     23.3MB
total_bytes    25701460
total_size     24.5MB
```

Adding dataset stats to CLI

---

fiftyone/__public__.py
fiftyone/core/expressions.py
tests/unittests/view_tests.py

Resolves https://github.com/voxel51/fiftyone/issues/924.

Fixing ViewField copying

---

docs/source/faq/index.rst
docs/source/user_guide/app.rst

A small update to the FAQ corresponding to changes made in https://github.com/voxel51/fiftyone/pull/930
Also makes small updates to the App User Guide.
I'd be happy to expand on these changes noting the addition of plotting and tagging.

FAQ Refresh

---

app/src/components/ViewBar/ViewStage/viewStageParameterMachine.ts
fiftyone/core/collections.py
fiftyone/core/stages.py

Adds an optional `omit_empty` flag that controls whether samples with no labels are omitted from the view when using `select_labels()` or `exclude_labels()`.
The default behavior remains unchanged: only samples with at least one label are included in the view.
Depending on the workflow, `omit_empty=False` may be the desired behavior, since it ensures that no samples will ever be removed from the view. For example, `dataset.exclude_labels()` won't remove any labels, but it will remove any samples that don't have any labels to begin with, which might not be desirable if you are using `exclude_labels()` in an automated workflow to cleanup a dataset's annotations (but don't want samples to be deleted).
```py
dataset = fo.load_dataset("quickstart")
session = …
```

Adding support for controlling whether label selection/exclusion omits samples with no labels

---

app/src/components/Header.tsx

Adds a "How did you discover FiftyOne?" question to the feedback/t-shirt form. An answer is required.

"How did you discover FiftyOne?" Form question

---

app/src/components/Distributions.tsx
app/src/components/HorizontalNav.tsx
app/src/components/Loading.tsx
app/src/containers/Dataset.tsx
fiftyone/server/main.py

* Resolves #969 
* Resolves #980

Graphs enhancements

---

app/src/components/Actions/ActionsRow.tsx
app/src/components/Actions/Patcher.tsx
app/src/components/Actions/Similar.tsx
fiftyone/server/main.py

Resolves #1012 
@brimoor should marking filters also happen when sorting by similarity?

Mark filters to view before switching to patches

---

docs/source/environments/index.rst
docs/source/faq/index.rst

Update the remote notebook section of the FAQ in the docs to include instructions for port forwarding the App.

Update remote notebook FAQ

---

docs/source/_static/css/custom.css
docs/source/_static/css/voxel51-website.css
docs/source/_templates/layout.html

Links to the open images tutorial

Open Images docs banner

---

docs/source/faq/index.rst
docs/source/user_guide/using_datasets.rst

Adding answers to some common questions:
- What happened to my datasets from previous sessions?
- Why didn't changes to my dataset save?
- Can I use FiftyOne in multiple shells?
- Too many files open on system?

Adding FAQ answers

---

fiftyone/server/json_util.py
fiftyone/server/main.py

* Resolves #1038
* Resolves #1039
```py
sample["classification"] = fo.Classification(label="test", logits=np.random.random(100).tolist())
sample.save()
```
With http://localhost:5151/?fiftyoneColab=true
```py
```

App video issues

---

.github/workflows/build-docs.yml
requirements/docs.txt

Should resolve #1056. Workflow will confirm.

Bump `npsphinx` docs requirement

---

app/package.json
app/src/components/FieldsSidebar.tsx
app/src/components/Header.tsx
app/src/components/Sample.tsx
app/src/recoil/atoms.ts
app/src/recoil/selectors.ts
docs/source/_static/css/custom.css
docs/source/_static/css/voxel51-website.css
docs/source/_templates/layout.html
docs/source/conf.py
docs/source/release-notes.rst
fiftyone/constants.py
fiftyone/migrations/revisions/v0_9_4.py
fiftyone/server/main.py
package/desktop/setup.py
setup.py

Release v0.9.4

---

app/src/components/Sample.tsx

Filter classifications in the sample grid

---

docs/source/user_guide/dataset_creation/datasets.rst
docs/source/user_guide/plots.rst
docs/source/user_guide/using_aggregations.rst
docs/source/user_guide/using_datasets.rst

Fixed some documentation spelling mistakes

---

docs/source/getting_started/install.rst

Taking the first steps to fix the #1178 issue by applying what Ben and Brian said [here](https://github.com/voxel51/fiftyone/issues/1178) into the documentation as a start.
(Details)
-   [ ] Other

Step 1 of fixing the fiftyone desktop / app mismatch 

---

app/packages/app/src/components/Filters/RangeSlider.tsx

Fix range slider blurs

---

app/packages/app/src/components/CheckboxGroup.tsx
app/packages/app/src/components/Flashlight.tsx
app/packages/flashlight/src/index.ts
app/packages/flashlight/src/zooming.ts
app/packages/looker/src/elements/common/tags.ts
app/packages/looker/src/elements/frame.ts
app/packages/looker/src/elements/image.ts
app/packages/looker/src/elements/video.ts
app/packages/looker/src/index.ts

* Resolves #1171
* Resolves #1172 
* Resolves #1173 
* Resolves #1184 
This PR also adjusts rendering thresholds for item (Lookers) in the Flashlight grid.

App issues

---

.github/workflows/build.yml
fiftyone/constants.py
fiftyone/core/service.py

Cleans up some constructed paths. On Windows, the paths were not being normalized

Path cleanup

---

app/packages/looker/src/numpy.ts
app/packages/looker/src/overlays/detection.ts
app/packages/looker/src/overlays/segmentation.ts

Include array type in mask overlay construction

---

fiftyone/core/cli.py
fiftyone/core/service.py
package/desktop/setup.py
requirements/common.txt

Small tweaks to align with teams.
@benjaminpkane is the `fiftyone_desktop` -> `fiftyone-desktop` change safe? I believe so since PyPI translates underscores to hyphens anyway, right?

Setup tweaks

---

fiftyone/core/aggregations.py
fiftyone/core/state.py

Resolves https://github.com/voxel51/fiftyone/issues/1263.

Fixing boolean App filters

---

fiftyone/server/main.py

Remove duplicate page stage

---

fiftyone/utils/annotations.py

Supporting class-specific attributes during annotation import

---

fiftyone/utils/cvat.py

Resolves another issue in the example code from https://github.com/voxel51/fiftyone/issues/1320.
It turns out that CVAT requires booleans to be serialized as exactly `"true"` and `"false"` in order for them to be properly linked with the checkbox tool type.

Fixing serialization of CVAT attribute values

---

docs/source/user_guide/dataset_creation/index.rst

Adds a section on how to add model predictions in general. This section also includes loading YOLO and COCO formatted predictions specifically.

Add model predictions section to docs

---

fiftyone/server/main.py

Fix count values for colab

---

fiftyone/core/video.py

Resolves https://github.com/voxel51/fiftyone/issues/1408.

Fixing to_frames() bug

---

docs/source/faq/index.rst
docs/source/user_guide/app.rst

Adds an FAQ explaining how to launch the App from a script on Windows:

Windows App script FAQ

---

fiftyone/core/dataset.py

Resolves https://github.com/voxel51/fiftyone/issues/1413.

Fixes #1413

---

docs/source/getting_started/install.rst
docs/source/getting_started/troubleshooting.rst

Documenting ffmpeg dependency more prominently

---

docs/source/faq/index.rst
docs/source/user_guide/app.rst

Adding note on supported browsers

---

app/packages/looker/src/index.ts
app/packages/looker/src/worker.ts

Resolves #1400 
The change in for loops brought speeds back to normal. 8-10x faster than `develop`. My mistake.

Optimize worker label processing

---

fiftyone/core/cli.py
fiftyone/core/config.py
fiftyone/utils/cvat.py
fiftyone/utils/voc.py

Implements https://github.com/voxel51/fiftyone/pull/1443#pullrequestreview-813998106.

More robust attribute parsing

---

fiftyone/core/models.py
fiftyone/core/runs.py
fiftyone/utils/annotations.py
fiftyone/utils/eval/classification.py
fiftyone/utils/eval/detection.py
fiftyone/utils/eval/regression.py
fiftyone/utils/eval/segmentation.py
fiftyone/utils/torch.py
tests/misc/torch_tests.py

Resolves https://github.com/voxel51/fiftyone/issues/1442.
Change log
- Resolves https://github.com/voxel51/fiftyone/issues/1442 by ensuring that `TorchImageDataset`, `TorchImageClassificationDataset`, and `TorchImagePatchesDataset` use numpy data structures that can be shared between processes rather than large in-memory Python lists that will be wastefully copied between workers
- Adds `samples.select_fields()` to the `apply_model()`, `compute_embeddings()`, and `compute_patch_embeddings()` routines. This can significantly improve DB I/O performance when applying models to datasets with many existing fields (loading existing fields is not needed to run inference)
- Updates the errors/warnings in `apply_model()`, `compute_embeddings()`, and `compute_patch_embeddings()` to explicitly …

Model inference/embeddings enhancements

---

fiftyone/zoo/datasets/tf.py
fiftyone/zoo/datasets/torch.py

Resolves https://github.com/voxel51/fiftyone/issues/1451.
```py
try:
foz.delete_zoo_dataset("cifar10")
except:
pass
```

Fixing Torch/TF zoo dataset loading bug

---

fiftyone/utils/eval/coco.py

Resolves https://github.com/voxel51/fiftyone/issues/1453.
```py
results = dataset.evaluate_detections(
"predictions",
method="coco",
compute_mAP=True,
)
print(results.mAP())  # same as `develop`
dataset.delete_evaluations()
results = dataset.evaluate_detections(
"predictions",
classes=["bottle"],
method="coco",
compute_mAP=True,
)
print(results.mAP())
```

Fixing #1453

---

fiftyone/core/plots/base.py
fiftyone/core/plots/plotly.py
fiftyone/utils/eval/classification.py
fiftyone/utils/eval/coco.py
fiftyone/utils/eval/openimages.py

Resolves #1195, Resolves #1196 
Adds decision thresholds to the tooltips of PR/ROC curves plotted via the following methods:
- [BinaryClassification.plot_pr_curve()](https://github.com/voxel51/fiftyone/blob/d624f3f1c40399ca6ab65311eb3972cf8a8db70f/fiftyone/utils/eval/classification.py#L990)
- [BinaryClassification.plot_roc_curve()](https://github.com/voxel51/fiftyone/blob/d624f3f1c40399ca6ab65311eb3972cf8a8db70f/fiftyone/utils/eval/classification.py#L1024)
- [COCODetectionResults.plot_pr_curves()](https://github.com/voxel51/fiftyone/blob/d624f3f1c40399ca6ab65311eb3972cf8a8db70f/fiftyone/utils/eval/coco.py#L372)
- [OpenImagesDetectionResults.plot_pr_curves()](https://github.com/voxel51/fiftyone/blob/d624f3f1c40399ca6ab65311eb3972cf8a8db70f/fiftyone/utils/eval/openimages.py#L384)
```py …
```

Adding confidence thresholds to PR/ROC curves

---

fiftyone/core/collections.py

Fixes a bug that prevented `set_values(field_name, values, key_field="id")` from working as expected:
```py
values = {k: v for k, v in zip(*dataset.values(["id", "filepath"]))}
dataset.set_values("filepath2", values, key_field="id")
assert dataset.values("filepath") == dataset.values("filepath2")
```

Proper handling of ID fields in set_values(..., key_field="id")

---

docs/source/recipes/convert_datasets.ipynb
docs/source/recipes/custom_exporter.ipynb
docs/source/recipes/custom_importer.ipynb
docs/source/recipes/custom_parser.ipynb
docs/source/recipes/draw_labels.ipynb
docs/source/recipes/image_deduplication.ipynb
docs/source/recipes/merge_datasets.ipynb
docs/source/tutorials/classification_mistakes.ipynb

Manages #1494 for the time being by adding a note to tutorials and recipes to install OpenCV if the import error is occurring.

Add comment about OpenCV installation to notebooks

---

.github/workflows/build-db.yml
fiftyone/core/odm/database.py
fiftyone/core/utils.py
package/db/setup.py
tests/isolated/service_tests.py
tests/unittests/view_tests.py

Adds `fiftyone-db` wheels for i686 linux systems and win 32 systems.

Add hollow support for 32 bit systems

---

fiftyone/core/metadata.py
fiftyone/utils/aws.py
fiftyone/utils/coco.py
fiftyone/utils/cvat.py
fiftyone/utils/data/base.py
fiftyone/utils/image.py
fiftyone/utils/torch.py

Resolves https://github.com/voxel51/fiftyone/issues/1531.

Defaulting to zero workers on Windows

---

docs/source/_templates/layout.html

- Removes COCO banner
- Updates install count (but @benjaminpkane that code is not being used anymore right? can it just be removed?)

Docs updates

---

docs/source/recipes/convert_datasets.ipynb
docs/source/recipes/custom_exporter.ipynb
docs/source/recipes/custom_importer.ipynb
docs/source/recipes/custom_parser.ipynb
docs/source/recipes/draw_labels.ipynb
docs/source/recipes/image_deduplication.ipynb
docs/source/recipes/merge_datasets.ipynb
docs/source/tutorials/classification_mistakes.ipynb

Update OpenCV install note in notebooks

---

app/packages/app/src/recoil/utils.ts

Encode filepath as URI component

---

app/packages/looker/src/overlays/keypoint.ts

Handle empty Keypoint in App

---

.github/workflows/build.yml
tests/unittests/import_export_tests.py

A test was added that Windows fails on. Punting. Also fixes builds so RC candidates are installed.

Fix builds

---

requirements/common.txt
requirements/docs.txt
setup.py

Update Jinja2 requirement

---

app/package.json
app/packages/app/package.json
app/packages/desktop/package.json
app/packages/looker/src/worker.ts
package/desktop/setup.py
setup.py

Video playback is broken on v0.15.0 due to an incorrect api route

Patch v0.15.0 video playback

---

app/packages/looker/src/numpy.ts
fiftyone/server/json_util.py

Resolves #1657
I fear handling this in the browser would cause performance issues, so they are converted on the server.

Support fortran arrays in the app

---

app/packages/app/src/shared/connection.ts
app/packages/desktop/tsconfig.json

Fix Desktop

---

package/desktop/setup.py

Patch the Desktop App with #1670

Patch Desktop App

---

app/README.md
install.bash

Use a consistent node version in the install script and App README (16.4.2 LTS).

Consistent node version

---

fiftyone/__init__.py
fiftyone/__public__.py
fiftyone/core/odm/database.py

See https://github.com/voxel51/fiftyone/pull/1697.

Non-persistent dataset cleanup tweak

---

fiftyone/utils/cvat.py

Adds:
- Progress bar in CVAT upload.
Resolve #1695 
A simple feature that affects only the terminal visualization.
-   [  ] App: FiftyOne application changes
-   [  ] Build: Build and test infrastructure changes
-   [  ] Core: Core `fiftyone` Python library changes
-   [  ] Documentation: FiftyOne documentation changes
-   [ x ] Other

Adding progress bar to CVAT uploads

---

docs/source/user_guide/dataset_creation/datasets.rst
fiftyone/utils/yolo.py

Resolves #1716.
```python
import fiftyone.utils.yolo as fouy
print(fouy._get_yolo_v5_labels_path("/a/b/images/000001.jpg"))
print(fouy._get_yolo_v5_labels_path("images/000001.jpg"))
```

Fixing #1716

---

CONTRIBUTING.md
STYLE_GUIDE.md
app/README.md
docs/README.md

May 2022 refresh of developer-centric READMEs, including the addition of a `STYLE_GUIDE.md` that documents our style guides.

Updating the dev guide

---

.pre-commit-config.yaml

Upgrading the `prettier` dependency to reflect the latest release which has resolved the dependency tree resolution issue.
Commit a file to the repo and ensure that the pre-commit hook runs without issue.
-   [x] Build: Build and test infrastructure changes
-   [ ] Other

fixing pre-commit hook

---

app/packages/looker/src/elements/common/actions.ts

https://github.com/voxel51/fiftyone/issues/1554
Tested against the quickstart-video dataset.
See feature issue: https://github.com/voxel51/fiftyone/issues/1554
-   [ ] Other

change esc ordering for videos

---

fiftyone/utils/cvat.py

This PR changes the functions that iterate through CVAT tasks and projects by directly building the request url for a specific page rather than using the url provided in the `next` response from the previous page. There can be issues where this url is malformed and does not contain `https` or a port.
This approach is what is used by the [CVAT CLI.](https://github.com/openvinotoolkit/cvat/blob/d7560bbd39fec68f944515c2591dda74f3764b90/utils/cli/core/core.py#L50-L73) 
To test:
```python
dataset = foz.load_zoo_dataset("quickstart", max_samples=10).clone()
"anno_key",
task_size=2,
projects="test_project",
url="https://cvat.org",
username=CVAT_USERNAME,
password=CVAT_PASSWORD,
)
api = results.connect_to_api() …
```

Update how CVAT task and project pages are requested

---

app/packages/looker/src/index.ts

Fix JSON view nested values

---

app/packages/looker/src/elements/common/tags.ts

Remove thumbnail frame classifications 

---

docs/source/_templates/layout.html

Adds big picture analytics to the docs

Big Picture script

---

app/packages/app/src/components/Filters/CategoricalFilter.tsx
app/packages/components/src/components/Results/Results.tsx

On `0.16.5` search result counts in the sidebar are not right aligned.

Fix result alignment in App

---

app/packages/app/src/Root/Datasets/Dataset.tsx

Fixes session views. The bug was introduced in #1931

Fix session views

---

fiftyone/core/plots/base.py
fiftyone/core/plots/matplotlib.py
fiftyone/core/plots/plotly.py

Resolves https://github.com/voxel51/fiftyone/issues/1966
How I tested (in addition to unit test coverage):
- Checking that error in https://github.com/voxel51/fiftyone/issues/1966 no longer occurs
- Checking that [this code](https://voxel51.com/docs/fiftyone/user_guide/evaluation.html#confusion-matrices) still runs

Fixing #1966

---

.github/workflows/build.yml
app/packages/app/src/Root/Datasets/Dataset.tsx
app/packages/app/src/Root/Datasets/__generated__/DatasetQuery.graphql.ts
app/packages/app/src/components/Modal/Bars.tsx
app/packages/app/src/components/Modal/Modal.tsx
app/packages/app/src/components/Sidebar/Entries/PathValueEntry.tsx
app/packages/looker/src/elements/common/panel.module.css
app/packages/looker/src/elements/common/tags.ts
app/packages/map/package.json
app/packages/map/src/Map.tsx
app/packages/relay/src/mutations/__generated__/setViewMutation.graphql.ts
app/packages/relay/src/mutations/setView.ts
app/packages/state/src/recoil/atoms.ts
app/packages/state/src/recoil/groups.ts
app/packages/state/src/recoil/options.ts
app/yarn.lock

Feature release including plugins, geo location maps, group datasets, and point clouds.

v0.17.0rc0

---

app/packages/looker-3d/src/Looker3d.tsx

- adds proper media field support for looker3d
- removes multifield support from looker3d settings

add mediafield support to looker3d

---

.github/workflows/build-docs.yml

Documentation builds are failing, like to changes with `pip` and editable installs.

Fix documentation builds

---

app/packages/components/src/components/Loading/Loading.module.css
app/packages/looker-3d/src/App.tsx
app/packages/looker-3d/src/Looker3d.tsx
app/packages/plugins/src/index.ts

Fixes crashing due to either missing files or misconfiguration. Instead displays error message.

Error handling for Looker3D

---

README.md

Fixes the second of two README slack links. Currently checking other links, as well.

Fix README slack links

---

app/packages/app/src/Root/Datasets/Dataset.tsx
app/packages/state/src/hooks/useStateUpdate.ts

Fixes session updates for empty view and selected sample/label updates from the Python client.

Fix group session updates

---

app/packages/looker-3d/src/Looker3d.tsx
app/packages/looker/src/constants.ts
app/packages/looker/src/elements/common/tags.ts
app/packages/looker/src/index.ts
app/packages/looker/src/overlays/base.ts
app/packages/looker/src/overlays/classifications.ts
app/packages/looker/src/overlays/heatmap.ts
app/packages/looker/src/overlays/keypoint.ts
app/packages/looker/src/overlays/segmentation.ts
app/packages/looker/src/state.ts
app/packages/looker/src/worker.ts
app/packages/state/src/recoil/color.ts
app/packages/utilities/src/color.ts
app/packages/utilities/src/index.ts

Looker3d: add color by instance and label support

---

app/packages/utilities/src/index.ts

Fixes an issue where settings were lost after a state update.

Looker3D Settings Issue

---

app/packages/looker-3d/src/Looker3d.tsx

Fixes issues with the escape hotkey in Looker3D.

Fix Looker3D escape sequence

---

app/packages/app/src/components/Actions/Tagger.tsx
app/packages/app/src/components/Actions/utils.tsx
app/packages/app/src/components/Modal/Looker.tsx
app/packages/looker/src/elements/common/actions.ts
fiftyone/server/routes/tag.py
fiftyone/server/routes/tagging.py
fiftyone/server/tags.py
tests/unittests/server_tests.py

Adds to server tests and improves the tagging implementation by sharing parameter generation between the tagging statistics that create the checkbox list and subsequent tagging calls.

Tagging simplification and server tests

---

fiftyone/core/dataset.py

Resolves https://github.com/voxel51/fiftyone/issues/2096.
Dataset creation was not previously multiprocess-safe due to potential name clashes in the sample collection names. Now UUIDs are used.

Use UUIDs in dataset collection names

---

.github/workflows/build.yml
app/packages/app/src/Root/Datasets/Dataset.tsx
app/packages/state/src/recoil/groups.ts
docs/source/release-notes.rst
fiftyone/server/tags.py
package/desktop/setup.py
setup.py

Removes `TypedDict` usage to fix Python 3.7 in `0.17.0`

[HOTFIX] Release v0.17.1 (patch Python 3.7)

---

app/packages/plugins/README.md

Added more info around manually installing plugins.

improve plugin install docs

---

README.md
docs/source/cli/index.rst
fiftyone/core/cli.py

Typo fixes

---

app/packages/plugins/README.md

Adds a clarification to plugin docs about relative paths.

add note to plugin docs

---

app/packages/looker/src/elements/common/looker.module.css

Changes the looker background to be transparent so background color is configured by the parent element. Fixes tile coloring in the grid.

Transparent looker background

---

README.md

Modified Python version starting number as per Python package project description.
Updated broken link
-   [ ] Other

Minor fixes to fiftyone/README.md

---

app/packages/core/src/components/Sidebar/Sidebar.tsx

Reduce left margin of sidebar to achieve straight vertical edge on the left
Change was tested visually and by interacting with drag functionality of sidebar to ensure there is no overflow
-   [ ] Other

reduce sidebar margin to fix left vertical edge

---

app/packages/components/src/components/ThemeProvider/index.tsx
app/packages/looker/src/elements/common/controls.module.css

PR removes border in dark theme to be consistent with light and enhances shadow
Changes were tested visually in both themes
-   [ ] Other

looker arrow styles enhancements

---

app/packages/core/src/Dataset.ts
app/packages/state/src/hooks/useSetView.ts

Resolves #2229. This is a syncing issue with recoil/relay and the url state. @kaixi-wang per you offline comment, Recoil Sync could be a great fit for keeping state in sync. The current implementation isn't ideal.

Sync router state

---

app/packages/app/src/index.tsx
app/packages/core/src/Dataset.ts
app/packages/state/src/hooks/useStateUpdate.ts

PR fixes an issue where color scheme is not updated on theme change from session
Manually tested by toggling theme from session
-   [ ] Other

update color scheme on theme update

---

app/packages/state/src/hooks/useStateUpdate.ts
app/packages/state/src/recoil/sidebar.ts

Resets the current sidebar configuration in the App on dataset change

Sidebar resets

---

app/packages/core/src/components/Filters/CategoricalFilter.tsx

Removed extra title

---

fiftyone/utils/data/parsers.py
tests/unittests/dataset_tests.py

Resolves https://github.com/voxel51/fiftyone/issues/2302.

Fixing #2302

---

app/packages/components/relay.config.json

- Fix path to `schema.graphql` file
(Details)
-   [x] Build: Build and test infrastructure changes
-   [ ] Other

Fix relay config

---

fiftyone/core/collections.py

Resolves https://github.com/voxel51/fiftyone/issues/2292.

Fixing #2292

---

app/packages/core/src/components/ViewBar/ViewStage/ViewStage.tsx

Resolved App React Spring error

---

app/packages/components/src/components/Icons/Icons.tsx

Fixes `yarn build` error:
```
[vite]: Rollup failed to resolve import "@material-ui/icons" from "../components/src/components/Icons/Icons.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "@material-ui/icons" from "../components/src/components/Icons/Icons.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
at onRollupWarning (file:///Users/kacey/Dev/voxel51/fiftyone/app/node_modules/vite/dist/node/chunks/dep-561c5231.js:43522:19)
at onwarn …
```

Fix build error

---

app/packages/components/src/components/index.ts

Export External Link

---

app/packages/utilities/src/fetch.ts

Changes the default number of retries for all network requests to 2

Default App retries

---

app/packages/core/src/components/Filters/CategoricalFilter.tsx

Reverts voxel51/fiftyone#2403
This can introduce bugs and issues, so i am reverting the pr.

Revert "Remove `none` as an option from other value options"

---

fiftyone/core/odm/database.py
tests/unittests/utils_tests.py

FiftyOne requires a single doc in the `config` collection, which is where it stores its config information. Although this *should not* happen, every now and then a user reports that they have multiple docs in their `config` collection, which currently causes `import fiftyone` to fail.
This PR gracefully detects and handles the multiple config docs scenario by automatically deleting all docs except the one with the latest `version` (seemed like a reasonable choice to me).
Add a duplicate config document:
```py
db = foo.get_db_conn()
config = foo.get_db_config()
d = dict(config.to_dict())
d.pop("_id")
db.config.insert_one(d)
```
Verify that extra doc is automatically cleaned up:
```py
```
No warning this time:
```py …
```

Graceful cleanup of multiple config docs

---

app/packages/core/src/components/Filters/NumericFieldFilter.tsx
app/packages/state/src/recoil/pathFilters/numeric.ts

fixes #2399 
https://user-images.githubusercontent.com/17770824/206592972-a68968a7-990d-480a-8fca-b97dc1a1b14d.mov
(Details)
-   [ ] Other

Fix none filter for numeric field

---

docs/source/user_guide/export_datasets.rst
fiftyone/types/dataset_types.py
fiftyone/utils/csv.py
tests/unittests/import_export_tests.py

Example usage:
```py
dataset.untag_samples("validation")
for tag in ("train", "test", "validation"):
dataset.take(100).tag_samples(tag)
dataset_type=fo.types.CSVDataset,
labels_path="/tmp/labels.csv",
fields=["filepath", "tags", "metadata.size_bytes", "uniqueness"],
abs_paths=True,
)
```

CSV exporter

---

app/packages/core/src/plugins/histograms.tsx
app/packages/spaces/src/AppModules.tsx
app/packages/spaces/src/components/Panel.tsx
app/packages/spaces/src/hooks.ts
app/packages/spaces/src/state.ts
app/packages/spaces/src/types.ts

improve spaces hooks and fix panel re-render issue

---

docs/source/user_guide/app.rst
docs/source/user_guide/using_views.rst
fiftyone/core/dataset.py
fiftyone/core/odm/dataset.py
fiftyone/core/odm/document.py
fiftyone/core/odm/views.py
fiftyone/server/aggregate.py
fiftyone/server/aggregations.py
fiftyone/server/mutation.py
fiftyone/server/query.py
fiftyone/server/routes/aggregate.py
fiftyone/server/routes/frames.py
fiftyone/server/routes/sort.py
fiftyone/server/routes/values.py
fiftyone/server/samples.py
fiftyone/server/tags.py
fiftyone/server/view.py
fiftyone/utils/data/exporters.py
fiftyone/utils/data/importers.py
tests/unittests/dataset_tests.py
tests/unittests/server_tests.py

Change log
- Adds saved view documentation (awaiting bugfixes and look & feel updates before actually adding the GIF though)
- Refactors the `no_dereference` work to avoid a leaky abstraction (comments inline)

Saved view tweaks

---

app/packages/components/src/components/IconButton/index.tsx
app/packages/core/src/components/SamplesContainer.tsx
app/packages/core/src/plugins/samples.tsx
app/packages/spaces/src/App.css
app/packages/spaces/src/App.tsx
app/packages/spaces/src/AppModules.tsx
app/packages/spaces/src/SpaceNode.tsx
app/packages/spaces/src/SpaceTree.ts
app/packages/spaces/src/components/AddPanelButton.tsx
app/packages/spaces/src/components/AddPanelItem.tsx
app/packages/spaces/src/components/Panel.tsx
app/packages/spaces/src/components/PanelIcon.tsx
app/packages/spaces/src/components/PanelTab.tsx
app/packages/spaces/src/components/Space.tsx
app/packages/spaces/src/components/StyledElements.tsx
app/packages/spaces/src/hooks.ts
app/packages/spaces/src/types.ts
app/packages/spaces/src/utils.ts

more fixes and enhancements for spaces

---

app/packages/relay/src/queries/__generated__/countValuesQuery.graphql.ts
app/packages/relay/src/queries/__generated__/histogramValuesQuery.graphql.ts
app/packages/relay/src/queries/countValues.ts
app/packages/relay/src/queries/histogramValues.ts
app/packages/state/src/recoil/distributions.ts
app/schema.graphql
fiftyone/server/aggregate.py
fiftyone/server/view.py

extended view form for aggregate

---

.github/workflows/test.yml

Should resolve rate limiting issues, noting the following:
* rate limiting can be resolved by supplying a token: https://github.com/FedericoCarboni/setup-ffmpeg/issues/4
* [v1 had no default value for token](https://github.com/FedericoCarboni/setup-ffmpeg/blob/v1/action.yml)
* [v2 correctly uses the github token for a default](https://github.com/FedericoCarboni/setup-ffmpeg/blob/v2/action.yml)

Upgrading the ffmpeg action 

---

docs/source/integrations/cvat.rst
docs/source/release-notes.rst
fiftyone/utils/cvat.py

It updates only links in documentation.
N/A (documentation only)
(Details)
-   [ ] Other

Fix several links on CVAT GitHub repository and its documentation.

---

app/packages/state/src/hooks/useStateUpdate.ts

PR fixes an issue where app crashes on refreshing session from Python
Manually
-   [ ] Other

add missing theme atom import

---

app/packages/app/src/index.tsx
app/packages/components/src/components/Selection/SearchBox.tsx
app/packages/components/src/components/Selection/Selection.tsx
app/packages/core/src/components/Actions/ActionsRow.tsx
app/packages/core/src/components/Grid/Grid.tsx
app/packages/core/src/components/Sidebar/Sidebar.tsx
app/packages/core/src/components/Sidebar/ViewSelection/ViewDialog.tsx
app/packages/core/src/components/Sidebar/ViewSelection/index.tsx
app/packages/core/src/components/Sidebar/ViewSelection/styledComponents.tsx
app/packages/core/src/components/ViewBar/ViewBar.tsx
app/packages/core/src/components/ViewBar/ViewStage/ViewStageParameter.tsx
app/packages/core/src/components/ViewBar/ViewStage/viewStageMachine.ts
app/packages/core/src/components/ViewBar/viewBarMachine.ts
app/packages/relay/src/mutations/__generated__/createSavedViewMutation.graphql.ts
app/packages/relay/src/mutations/createSavedView.ts
app/packages/state/src/hooks/useSavedViews.ts
app/packages/state/src/hooks/useSetView.ts
app/packages/state/src/recoil/aggregations.ts
app/packages/state/src/recoil/selectors.ts
app/schema.graphql
fiftyone/server/events.py
fiftyone/server/mutation.py
fiftyone/server/query.py

Save extended view + additional bug fixes

---

app/packages/looker/src/worker.ts

fix tooltip bug in segmentation overlay

---

app/packages/state/src/recoil/sidebar.ts

https://user-images.githubusercontent.com/17770824/212395563-74f2a04a-0ea1-4045-924a-7d4f2bc4e69d.mov
-   [ ] Other

Fix bug that dragging side bar and dropping does not work

---

app/packages/spaces/src/SpaceTree.ts
app/packages/spaces/src/SpacesRoot.tsx
app/packages/spaces/src/components/Space.tsx

vertical split and nested layout support for space

---

app/packages/utilities/src/fetch.ts

This was a small bug introduced by #2397 that caused fetch to not work in web workers.
Locally, on multiple datasets.

fix bug in fetch 

---

fiftyone/server/events.py

Removing a stray print statement from #2494

Remove stray print

---

.github/workflows/test.yml

Ensures both Python and App reports are uploaded and coverage deltas are accurate

Always run and upload reports

---

app/packages/core/src/components/ViewBar/ViewStage/ErrorMessage.tsx
app/packages/embeddings/src/Embeddings.tsx
app/packages/looker/src/lookers/abstract.ts
app/packages/state/src/recoil/view.ts

Cleaning some code for builds to work in all environments

Cleaning for builds

---

app/packages/core/src/components/ViewBar/ViewStage/ErrorMessage.tsx

revert import removal

---

fiftyone/core/dataset.py
fiftyone/server/mutation.py

- clean up the set_view mutation
(Details)
-   [ ] Other

[Saved views] clean up set_view mutation

---

app/packages/spaces/src/components/Panel.tsx

Fixes #2536 
Tested manually by following re-creation steps in #2536 to ensure app no longer crasher
-   [ ] Other

fix spaces exception on active panel removal

---

docs/source/plugins/index.rst

Adds information about panels and deprecation of `PluginComponentType.Plot`.

0.19 plugin doc updates

---

app/packages/core/src/components/MainSpace/MainSpace.tsx

Fixes #2531 
Tested manually by attempting to re-create #2531 and confirming it is no longer re-creatable
-   [ ] Other

fix switching to patches view resetting space bug

---

app/packages/state/src/recoil/selectors.ts

Support all label container types when resolving label ids.

find label ids for all types

---

app/packages/core/src/components/Filters/categoricalFilter/Wrapper.tsx
app/packages/core/src/components/Sidebar/Entries/PathValueEntry.tsx
app/packages/core/src/components/Sidebar/Entries/RegularEntry.tsx

fix #2575 
fix #2554 
Locally, with the code Eric provided in Jira ticket
-   [ ] Other

Bug fixes: bool in modal + single value in filter

---

app/packages/components/src/components/ThemeProvider/index.tsx
app/packages/embeddings/src/Embeddings.tsx
app/packages/embeddings/src/useBrainResult.tsx
app/packages/embeddings/tests/hooks/useBrainResultsSelector.test.tsx

Fixes #2573
Makes the wording / style of the embeddings visualization verbiage better and more consistent.

Improve no brain results message

---

app/packages/core/src/Dataset.ts
app/packages/core/src/Root/Datasets/Dataset.tsx
app/packages/core/src/Root/Root.tsx
app/packages/core/src/__generated__/DatasetQuery.graphql.ts
app/packages/core/src/components/Actions/Patcher.tsx
app/packages/core/src/components/Sidebar/ViewSelection/index.tsx
app/packages/core/src/makeRoutes.ts
app/packages/dataset/src/Dataset.tsx
app/packages/looker/src/index.ts
app/packages/state/src/hooks/useRouter.ts
app/packages/state/src/hooks/useSessionSpaces.ts
app/packages/state/src/hooks/useSetView.ts
app/packages/state/src/routing/RouteDefinition.ts
app/packages/state/src/routing/RouterContext.ts
app/packages/state/src/routing/matchPath.ts
app/packages/state/src/utils.ts
app/schema.graphql
fiftyone/core/dataset.py
fiftyone/server/events.py
fiftyone/server/mutation.py
fiftyone/server/query.py

[Bug fix] Fix saved views and state

---

app/packages/state/src/recoil/groups.ts

fix modal crash when trying to tag a point cloud sample

---

app/packages/core/src/Dataset.ts
app/packages/core/src/__generated__/DatasetQuery.graphql.ts

- consolidate appConfig fields and remove duplicate field on query
(Details)
-   [ ] Other

[bug fix] rm duplicate appConfig

---

app/packages/core/src/components/Sidebar/ViewSelection/index.tsx
app/packages/dataset/src/Dataset.tsx
app/packages/state/src/hooks/useSessionSpaces.ts
app/packages/state/src/recoil/view.ts

Changes in this PR fixes a state conflict between spaces and view. 
Tested in the app and using the session to ensure state changes do not override other non-modified state
-   [ ] Other

fix spaces and view state update conflicts

---

docs/source/faq/index.rst
fiftyone/zoo/models/manifest-torch.json

Minor doc/tutorial updates after testing in fresh environments
Manual testing of notebooks on Linux, reading html
-   [ ] Other

Minor doc updates

---

app/packages/app/vite.config.ts
app/packages/state/src/hooks/useScreenshot.ts
app/packages/state/src/hooks/useTo.ts

Fixes screenshotting by using the `notebook` URL search flag to check for context

Ensure notebook context and screenshots

---

app/packages/core/src/components/Sidebar/Sidebar.tsx

Fixes sidebar sizing when it is not full height in the modal. Also fixes inexact sizing in the grid

Sidebar sizing

---

app/packages/state/src/hooks/index.ts

Exports the sometimes required `getCurrentEnvironment` from `@fiftyone/state`

Export getCurrentEnvironment from state package

---

app/packages/components/src/components/Selection/Selection.tsx
app/packages/core/src/components/Sidebar/ViewSelection/index.tsx

Proposal: Easier and more intuitive way to clear saved view by user. share your thoughts!
https://user-images.githubusercontent.com/109545780/218877666-cc463e2c-549b-43f1-a1d7-32b80b753489.mov
(Details)
-   [ ] Other

clear saved view proposal

---

.github/workflows/publish.yml
app/packages/app/vite.config.ts
docs/source/release-notes.rst
fiftyone/core/session/notebooks.py
fiftyone/server/query.py
setup.py

* Resolves https://github.com/voxel51/fiftyone/issues/2650
* Resolves https://github.com/voxel51/fiftyone/issues/2648
* Resolves https://github.com/voxel51/eta/issues/579

Release v0.19.1

---

app/packages/core/src/plugins/histograms.tsx
app/packages/core/src/plugins/samples.tsx
app/packages/embeddings/src/styled-components.tsx
app/packages/map/src/Map.module.css
app/packages/spaces/src/components/StyledElements.tsx

PR adds default panel background consistent with core panel plugins
(Details)
-   [ ] Other

add default panel background

---

fiftyone/migrations/runner.py

Suppose an SDK client with version `X` and `FIFTYONE_DATABASE_ADMIN=true` encounters a dataset created by a different client with version `Y` such that `Y > X` but `Y` is in the compatibility range of `X`.
Previously, when `FIFTYONE_DATABASE_ADMIN=true`, an error would be raised when trying to load the dataset using client `X`, because the migration runner would complain that `Y > X` and therefore it had no way to know whether any migrations exist for the `Y --> X` downgrade path.
Now, as long as `Y` is in the compatibility range of `X`, the dataset will be loaded without migration.
This also applies to databases themselves. So, for example, since the compatibility range of `0.19.1` is `>=0.19,<0.20`, it will now be possible for a client running `0.19.1` with …

Skipping downward migrations for future-but-compatible versions

---

app/packages/app/package.json
app/packages/components/src/components/JSONPanel/JSONPanel.tsx
app/packages/components/src/components/JSONPanel/panel.module.css
app/packages/core/src/components/Modal/Modal.tsx
app/packages/looker/package.json
app/packages/state/src/hooks/useJSONPanel.ts
app/yarn.lock

- New improved JSON viewer.
- fields (including nested fields) can be collapsed!
- User can search **to highlight** text. note that search is clearable using x icon.
- User can copy any and all part of the json into clipboard and paste/use it elsewhere
- If content is long horizontally, we enabled scroll so the entire content is viewable.
- works well in both dark/light mode
https://user-images.githubusercontent.com/109545780/220481550-cc0daa33-b06a-47e6-9cd1-cde6253c7332.mov
(Details)
-   [ ] App: FiftyOne application …

JSON viewer V2

---

docs/source/recipes/custom_exporter.ipynb

[Typo] Custom Export Docs

---

app/packages/looker/src/elements/common/tags.ts
docs/source/recipes/custom_exporter.ipynb
fiftyone/server/routes/frames.py
fiftyone/server/samples.py

- Add support arg for empty views 
(Details)
-   [ ] Other

Temp fix for enabling loading large videos

---

app/packages/state/src/hooks/useCreateLooker.ts

fix hardcoded orthographic_projection_metadata bug in app

---

app/packages/components/src/components/ErrorBoundary/ErrorBoundary.tsx
app/packages/plugins/src/components.tsx
app/packages/plugins/src/index.ts

Improve plugin loading and error handling. Prevent plugin scripts from re-loading multiple times. Isolate plugin errors to the component they are rendered within eg. `<Panel />`.

plugin error handling

---

app/packages/embeddings/src/EmbeddingsPlot.tsx
app/packages/embeddings/src/fetch.tsx
app/packages/embeddings/src/useViewChangeEffect.tsx
fiftyone/server/routes/embeddings.py

Show error when visualization run has not associated data

---

app/packages/map/src/Map.tsx

When lassoing patch emeddings, instead of crashing, we show an existing "No Data" message (the same if no samples match).

Fix Map Panel Crash when Extended Selection is Patch ids

---

app/packages/embeddings/src/useExtendedStageEffect.tsx

skip fetched extended stage if dataset is changed

---

fiftyone/server/query.py

bugfix: fix the nonetype bug from adding type

---

app/packages/app/src/Network.tsx
app/packages/app/src/index.tsx
app/packages/components/src/components/ErrorBoundary/ErrorBoundary.tsx

Show error boundary for `/events` request errors
(Details)
-   [ ] Other

move error boundary up the components tree

---

docs/source/recipes/custom_exporter.ipynb
docs/source/recipes/custom_importer.ipynb
docs/source/recipes/custom_parser.ipynb
docs/source/recipes/draw_labels.ipynb
docs/source/user_guide/dataset_zoo/api.rst
docs/source/user_guide/dataset_zoo/index.rst

Fixed broken torchvision dataset link

---

app/packages/operators/src/constants.ts
app/packages/operators/src/operators.ts
app/packages/operators/src/state.ts
app/packages/spaces/src/SpaceTree.ts

fix operator browser search & keyboard navigation

---

app/packages/core/src/components/Actions/Selected.tsx
app/packages/core/src/components/Group/Group.tsx
app/packages/state/src/recoil/schema.ts
app/packages/state/src/routing/RouterContext.ts

See #2257 for bug details.
https://user-images.githubusercontent.com/462228/224837371-ab31c720-d5b5-4827-85bb-e094f1d5015f.mov

Fix group selection target

---

fiftyone/server/view.py

Follow up to #2774. Small PR to ensure unexpected keypoint list filters are made known

Raise on unexpected keypoint list filter

---

fiftyone/server/metadata.py

use deep get to get opm image path

---

app/packages/embeddings/src/useViewChangeEffect.tsx
fiftyone/server/routes/embeddings.py

Handle both then load_brain_result() returns None or throws.

Additional error handling for plot loading

---

app/packages/utilities/src/fetch.ts

PR improves error parsing for fetch requests to display server stack trace when available
Preview:
Manually
-   [ ] Other

fetch error parsing enhancements

---

fiftyone/utils/data/exporters.py
fiftyone/utils/data/importers.py

Adding control over importing/exporting runs and saved views

---

app/packages/core/src/components/Group/Group.tsx
app/packages/core/src/components/Modal/Group.tsx
app/packages/core/src/components/Modal/Looker.tsx
app/packages/looker-3d/src/Environment.tsx
app/packages/looker-3d/src/action-bar/PointSize.tsx
app/packages/looker-3d/src/action-bar/style.module.css
app/packages/state/src/hooks/useCreateLooker.ts
app/packages/state/src/recoil/groups.ts
app/packages/state/src/recoil/modal.ts

1. Fix point size button crashing issue because of material
2. Pass urls to looker and not use filepath
3. Fix issue where app was crashing when default slice was pointcloud
4. Use more than one grid lines for small pcds
Locally.
-   [ ] Other

group / modal / looker bug fixes

---

fiftyone/server/decorators.py

Log route exception to stdout
Manually
-   [ ] Other

log route error to terminal

---

fiftyone/server/metadata.py

fix regression introduced in #2809

fix regression

---

app/packages/core/src/components/Actions/Selected.tsx
app/packages/state/src/hooks/useToPatches.ts

PR fixes syncing issue with clearing selected samples
Manually
-   [ ] Other

fix issue with clearing sample selection

---

app/packages/looker/src/lookers/abstract.ts
app/packages/looker/src/state.ts
app/packages/looker/src/worker/index.ts
app/packages/state/src/hooks/useCreateLooker.ts
fiftyone/server/metadata.py

Metadata/filepath tweaks for segmentation/heatmap/opm fields

Metadata tweaks

---

app/packages/core/src/components/Filters/categoricalFilter/CategoricalFilter.tsx
fiftyone/core/aggregations.py
fiftyone/server/routes/values.py

Fixes values search for group datasets and a pipeline issue in `CountValues` when both `_selected` and `_search` are provided

Fix values search

---

app/packages/looker/src/worker/threed-label-processor.ts

Fix issue with orthographic projection bounds
Locally

fix bounds issue

---

app/packages/core/src/components/Actions/similar/utils.ts
app/packages/looker/src/worker/index.ts
app/packages/state/src/hooks/hooks-utils.ts
app/packages/state/src/recoil/groups.ts
fiftyone/server/query.py
fiftyone/server/routes/sort.py

* sort by similarity embedded context issues
* tagging in modal response mapping when updating samples
* streaming mask/map data on frames for video samples

Release fixes

---

app/packages/core/src/components/Actions/similar/utils.ts
app/packages/state/src/hooks/hooks-utils.ts
app/packages/state/src/hooks/useStateUpdate.ts

Prevents spaces from resetting when sorting by similarity

Ignore spaces when sorting by similarity

---

docs/source/user_guide/dataset_zoo/datasets.rst
fiftyone/zoo/datasets/base.py

Updated the source urls for Caltech 101 and 256 datasets

---

fiftyone/utils/coco.py
fiftyone/utils/data/importers.py

Resolves https://github.com/voxel51/fiftyone/issues/2845

Fixing #2845

---

app/packages/components/src/components/ThemeProvider/index.tsx
app/packages/core/src/components/MainSpace/MainSpace.tsx
app/packages/operators/package.json
app/packages/operators/src/OperatorBrowser.tsx
app/packages/operators/src/OperatorInput.tsx
app/packages/operators/src/OperatorPrompt.tsx
app/packages/operators/src/RJSFOverrides.tsx
app/packages/operators/src/operators.ts
app/packages/operators/src/state.ts
app/packages/operators/src/types.ts
app/packages/operators/src/utils.ts
app/packages/state/src/constants.ts
app/packages/state/src/index.ts
app/yarn.lock
fiftyone/operators/types.py

initial generated input for operators

---

fiftyone/core/odm/utils.py
tests/unittests/dataset_tests.py

The unit test added in this PR fails on `develop`, but now passes as expected.

Fixing a bug in dynamic schema expansion

---

app/packages/operators/src/OperatorPrompt.tsx
app/packages/operators/src/RJSFOverrides.tsx
app/packages/operators/src/utils.ts
app/packages/operators/tsconfig.json
fiftyone/operators/operator.py
fiftyone/operators/types.py

generated form and types fixes

---

fiftyone/utils/complex_yolo/__init__.py
fiftyone/utils/complex_yolo/model.py
fiftyone/utils/complex_yolo/zoo.py
fiftyone/utils/torch.py
fiftyone/zoo/models/manifest-torch.json

This PR should be logically equivalent to https://github.com/voxel51/fiftyone/pull/2333. I'm just updating the implementation to be more idiomatic.
TODO: test with actual feature maps, etc.
```py
import fiftyone.utils.complex_yolo as fouy
model = foz.load_zoo_model("complex-yolo-v3-torch")
fouy.apply_model(dataset, model, ...)
```

Complex YOLO tweaks

---

fiftyone/utils/eval/segmentation.py
tests/intensive/evaluation_tests.py

Finishes https://github.com/voxel51/fiftyone/pull/2777.

Finishing Dice score

---

app/packages/core/src/plugins/SchemaIO/utils/operator.ts

fix crash when there are no validation errors

---

fiftyone/plugins/__init__.py
fiftyone/zoo/utils/github.py

plugins api refactor

---

fiftyone/plugins/__init__.py
tests/unittests/plugins/core_tests.py

Add unittests for plugins

---

fiftyone/utils/scale.py

Resolves https://github.com/voxel51/fiftyone/issues/2915.

Fixing Scale docs links + unlabeled annotation tasks

---

app/packages/core/src/components/Actions/ActionsRow.tsx
app/packages/core/src/plugins/OperatorIO/examples/Panel.tsx
app/packages/core/src/plugins/histograms.tsx
app/packages/embeddings/src/Embeddings.tsx
app/packages/map/src/Options.tsx
app/packages/operators/src/OperatorPlacement.tsx
app/packages/operators/src/OperatorPlacements.tsx
app/packages/operators/src/index.ts
app/packages/operators/src/types.ts
fiftyone/operators/types.py

add operator icon placement support

---

fiftyone/plugins/definitions.py

- cleanup impl and add validation

Cleanup plugins/definitions.py

---

fiftyone/plugins/core.py

- create app config file when necessary/if possible
- rm noisy logging.error messages

Fix noisy app config file error messages

---

app/packages/core/src/components/Actions/ActionsRow.tsx
app/packages/core/src/components/Schema/SchemaSearchHelp.tsx
app/packages/core/src/components/Schema/SchemaSettings.tsx

small ui tweaks
manually
-   [ ] Other

ui tweaks, close modal on click outside

---

fiftyone/plugins/core.py

fix type annotation

---

app/packages/core/src/components/Actions/ActionsRow.tsx
app/packages/core/src/components/ColorModal/ColorFooter.tsx
app/packages/core/src/components/ColorModal/ColorModal.tsx
app/packages/core/src/components/ColorModal/FieldSetting.tsx
app/packages/core/src/components/ColorModal/JSONViewer.tsx
app/packages/core/src/components/ColorModal/ShareStyledDiv.ts
app/packages/core/src/components/ColorModal/SidebarList.tsx
app/packages/core/src/components/ColorModal/colorPalette/AttributeColorSetting.tsx
app/packages/core/src/components/ColorModal/colorPalette/ColorPalette.tsx
app/packages/core/src/components/ColorModal/controls/ColorAttribute.tsx
app/packages/core/src/components/ColorModal/controls/ModeControl.tsx
app/packages/core/src/components/ColorModal/controls/OpacityAttribute.tsx
app/packages/core/src/components/ColorModal/utils.ts
app/packages/core/src/components/Dataset.tsx
app/packages/core/src/components/FieldLabelAndInfo/index.tsx
app/packages/looker/src/elements/common/tags.ts
app/packages/looker/src/elements/common/util.ts
app/packages/state/src/recoil/atoms.ts
app/packages/state/src/recoil/color.ts
app/packages/utilities/src/index.ts
fiftyone/core/colorscheme.py
fiftyone/core/session/session.py

ColorScheme: use menu list selection

---

app/packages/operators/src/OperatorPlacements.tsx
app/packages/state/src/hooks/index.ts
app/packages/state/src/hooks/withSuspense.tsx
app/packages/state/tsconfig.json

wrap operator placements with suspense

---

fiftyone/utils/labelstudio.py

Finishes https://github.com/voxel51/fiftyone/pull/2706.
Example usage:
```py
"coco-2017",
label_types=["segmentations"],
classes=["person", "cat", "dog"],
label_field="instances",
max_samples=25,
)
"test_instances",
label_field="instances",
label_type="instances",
backend="labelstudio",
)
```

Finishing Label Studio instances support

---

fiftyone/utils/cvat.py

Made a few additional updates to the CVAT v2.4 compatibility branch. A few code cleaning changes and a new issue logging into app.cvat.ai were the main things added in this PR.
This was tested both with a local CVAT v2.3 server and v2.4.3 on app.cvat.ai

CVAT v2.4 updates

---

app/packages/core/src/components/Modal/Modal.tsx

Fixes modal expansion regression from #2948

Fix modal expansion

---

app/packages/operators/src/OperatorPrompt.tsx
fiftyone/operators/server.py

- fixes a regression in generator based operators
- adds in a close button for dynamic operator prompts

fix generator operators

---

fiftyone/plugins/core.py

Minor improvements to plugins/core.py

---

app/packages/core/src/plugins/OperatorIO/examples/input.json
app/packages/core/src/plugins/SchemaIO/components/AlertView.tsx
app/packages/core/src/plugins/SchemaIO/components/AutocompleteView.tsx
app/packages/core/src/plugins/SchemaIO/components/DynamicIO.tsx
app/packages/core/src/plugins/SchemaIO/components/MapView.tsx
app/packages/core/src/plugins/SchemaIO/components/TupleView.tsx
app/packages/core/src/plugins/SchemaIO/components/index.ts
app/packages/core/src/plugins/SchemaIO/examples/input.json
app/packages/operators/src/built-in-operators.ts
app/packages/operators/src/operators.ts
app/packages/operators/src/types.ts
fiftyone/operators/types.py

more operator types fixes

---

app/packages/core/src/components/Sidebar/Entries/FilterEntry.tsx
app/packages/state/src/hooks/useSchemaSettings.ts
app/packages/state/src/hooks/useSetView.ts
app/packages/state/src/routing/RouterContext.ts

Adds support for field visibility selection in the embedded context and fixes `useSetView` in the embedded context

Embedded field visibility support and useSetView fix

---

app/packages/components/src/components/ErrorBoundary/ErrorBoundary.tsx
app/packages/operators/src/OperatorPlacements.tsx
app/packages/plugins/src/index.ts
fiftyone/plugins/definitions.py

This is needed to support placement icons in all form factors

allow plugins to resolve paths

---

fiftyone/plugins/definitions.py

Prior to this change, JS plugins would not load.

fix plugin loading

---

app/packages/core/src/components/Actions/ActionsRow.tsx

show bookmark icon when fields are filtered

---

app/packages/operators/src/index.ts

Missing export for executeOperator in TS

Operator hot fixes

---

docs/source/plugins/index.rst
fiftyone/core/cli.py
fiftyone/plugins/core.py

- add CLI commands
(Details)
-   [ ] Other

Plugins CLI

---

app/packages/embeddings/src/Embeddings.tsx

fix long brain keys

---

app/packages/operators/src/OperatorPrompt.tsx
app/packages/operators/src/built-in-operators.ts
app/packages/operators/src/types.ts

Fixes operator testing util and show_output modal (missing done button).

Fix op testing

---

app/packages/operators/src/OperatorBrowser.tsx
app/packages/operators/src/OperatorIO.tsx
app/packages/operators/src/OperatorPalette.tsx
app/packages/operators/src/OperatorPrompt.tsx
app/packages/operators/src/built-in-operators.ts
app/packages/operators/src/styled-components.tsx
app/packages/operators/src/types.ts

operator palette enhancements

---

app/packages/operators/src/OperatorPrompt.tsx
app/packages/operators/src/state.ts

improve operator input resolve throttle

---

app/packages/plugins/src/index.ts

mui external support for plugins

---

app/packages/operators/src/OperatorPalette.tsx
app/packages/operators/src/OperatorPrompt.tsx
app/packages/operators/src/state.ts

operator fixes and enhancements

---

app/packages/components/src/components/Selector/Selector.tsx
app/packages/core/src/components/Actions/DynamicGroupAction.tsx
app/packages/core/src/components/Actions/DynamicGroupAction/useDynamicGroupChoices.ts
app/packages/core/src/components/Modal/Group/DynamicGroup/carousel/DynamicGroupCarousel.tsx
app/packages/core/src/components/Modal/Group/DynamicGroup/carousel/DynamicGroupsFlashlightWrapper.tsx
app/packages/core/src/components/Modal/Looker.tsx
app/packages/embeddings/src/index.ts
app/packages/looker-3d/src/Looker3d.tsx
app/packages/state/src/hooks/hooks-utils.ts
app/packages/state/src/hooks/useCreateLooker.ts
app/packages/state/src/recoil/groups.ts
fiftyone/server/routes/__init__.py
fiftyone/server/routes/dynamic_groups.py

- Add route to get dynamic group candidate fields from backend
- Fix outside click for dynamic group pop-up and looker3d
- Add validation so that orderBy and groupBy keys cannot be the same
- Misc bug fixes
Locally.
-   [ ] Other

Dynamic groups bug fix / refactor

---

fiftyone/operators/executor.py
fiftyone/operators/server.py

Minor fix: execution errors would only print to console, this shows the errors to the user.

fix execution error messages

---

app/packages/core/src/components/Schema/SchemaSearch.tsx
app/packages/core/src/components/Schema/SchemaSelectControls.tsx
app/packages/core/src/components/Schema/SchemaSelection.tsx
app/packages/relay/src/mutations/__generated__/searchSelectFieldsMutation.graphql.ts
app/packages/relay/src/mutations/searchSelectFields.ts
app/packages/state/src/hooks/useSchemaSettings.ts
app/schema.graphql
fiftyone/server/mutation.py

https://github.com/voxel51/fiftyone/assets/109545780/8942bbf7-f291-4f55-8ce6-4b162e412e69
(Details)
-   [ ] Other

Ability to include nested fields in searches

---

app/packages/operators/src/utils.ts

fix placement icon when prefix is set

---

package/desktop/setup.py

bump desktop version to 0.27.0

---

fiftyone/plugins/core.py
tests/unittests/plugins/core_tests.py

Fix plugins unittests

---

docs/source/plugins/index.rst

Update docs for installing plugins

---

app/packages/operators/src/OperatorPlacements.tsx
app/packages/operators/src/operators.ts
app/packages/operators/src/state.ts

operator placement enhancement

---

app/typedoc.js
docs/source/plugins/ts-api.rst

include spaces in typedoc

---

app/packages/components/src/components/ThemeProvider/index.tsx

change link color to white in theme
(Details)
-   [ ] Other

change link color to white in theme

---

docs/source/plugins/index.rst

improve operators placement docs

---

app/packages/core/src/plugins/SchemaIO/components/DynamicIO.tsx
app/packages/core/src/plugins/SchemaIO/components/FieldWrapper.tsx
app/packages/operators/src/state.ts
app/packages/operators/src/validation.ts
fiftyone/operators/types.py

fix validation issue for nested property

---

app/packages/operators/src/OperatorPalette.tsx
app/packages/operators/src/built-in-operators.ts
app/packages/spaces/src/SpaceTree.ts

add split panel operator

---

app/packages/core/src/components/Actions/ActionsRow.tsx
app/packages/core/src/components/ColorModal/FieldSetting.tsx
app/packages/core/src/components/ColorModal/JSONViewer.tsx
app/packages/core/src/components/ColorModal/ShareStyledDiv.ts
app/packages/core/src/components/ColorModal/SidebarList.tsx
app/packages/core/src/components/ColorModal/colorPalette/AttributeColorSetting.tsx
app/packages/core/src/components/ColorModal/colorPalette/ColorPalette.tsx
app/packages/core/src/components/ColorModal/utils.ts
app/packages/core/src/components/Filters/BooleanFieldFilter.tsx
app/packages/core/src/components/Filters/LabelFieldFilter.tsx
app/packages/core/src/components/Filters/NumericFieldFilter.tsx
app/packages/core/src/components/Filters/StringFieldFilter.tsx
app/packages/core/src/components/Filters/categoricalFilter/CategoricalFilter.tsx
app/packages/core/src/components/Grid/Grid.tsx
app/packages/core/src/components/Sidebar/Entries/FilterablePathEntry.tsx
app/packages/looker/src/elements/common/util.ts
app/packages/looker/src/lookers/shared.ts
app/packages/looker/src/util.ts
app/packages/state/src/hooks/useStateUpdate.ts
app/packages/state/src/recoil/atoms.ts
app/packages/utilities/src/index.ts
fiftyone/core/odm/dataset.py
fiftyone/core/session/session.py
fiftyone/core/state.py
fiftyone/server/mutation.py

This bugfix fixes the following bugs: 
Instance Mask:
https://github.com/voxel51/fiftyone/assets/17770824/0b3bdad1-802b-40a2-8fc5-7a03b2a9e494
Changing dataset on UI updates session.color_scheme:
https://github.com/voxel51/fiftyone/assets/17770824/852fbfc1-f623-4e25-8454-93307bad9e0e
Chrome color picker:
https://github.com/voxel51/fiftyone/assets/17770824/abe6437d-07f3-437d-ab6c-05199c70bcc0
(Details) …

bugfix: color scheme instance mask, refresh with dataset, color picker UI and etc

---

README.md
app/packages/components/src/components/Icons/Icons.tsx
app/packages/desktop/src/menu.ts
docs/source/conf.py
docs/source/getting_started/troubleshooting.rst
docs/source/index.rst
docs/source/release-notes.rst
fiftyone/constants.py
fiftyone/core/session/session.py
fiftyone/core/uid.py

Logs a welcome message the first time the App is launched on a machine with a new FiftyOne version

Welcome message!

---

docs/source/teams/index.rst

[Docs] Teams Docs Typo

---

app/packages/state/src/hooks/useCreateLooker.ts

This fixes cloud orthographic projections not rendering correctly. 
Locally, and on staging.
-   [ ] Other

account for url filepaths with query params

---

app/packages/looker/src/elements/common/tags.ts
app/packages/looker/src/elements/common/util.ts
fiftyone/server/routes/tagging.py
fiftyone/server/utils.py
fiftyone/server/view.py

Bugfix: Tagger should count embeddedDocField labels for selected samples

---

fiftyone/utils/scale.py

Resolves https://github.com/voxel51/fiftyone/issues/3119.

Assume line annotations are not closed

---

docs/source/teams/index.rst

Minor docs typo

---

fiftyone/core/utils.py

Remove asyncio typing

---

fiftyone/operators/executor.py
fiftyone/operators/server.py

non-blocking operator execution

---

docs/source/cheat_sheets/fiftyone_terminology.rst
docs/source/plugins/index.rst
docs/source/release-notes.rst
docs/source/user_guide/app.rst
docs/source/user_guide/config.rst
fiftyone/core/config.py
fiftyone/operators/decorators.py
fiftyone/operators/loader.py
fiftyone/operators/permissions.py
fiftyone/operators/registry.py
fiftyone/operators/server.py
fiftyone/plugins/core.py

Change log
- Removes `KNOWN_PLUGIN_CONTEXTS`, which was not actually being used
- Backports `@plugins_cache` decorator from Teams

cache expensive plugin/operator listings

---

fiftyone/core/collections.py
fiftyone/core/stages.py
fiftyone/server/utils.py
fiftyone/server/view.py

Fixes label tag matching in the sidebar

Fix label tag matching in sidebar

---

app/packages/operators/src/OperatorPalette.tsx
app/packages/operators/src/OperatorPrompt.tsx
app/packages/operators/src/operators.ts
app/packages/operators/src/state.ts
app/packages/operators/src/validation.ts
fiftyone/operators/executor.py
fiftyone/operators/operator.py

allow disabling schema validation for operator

---

app/packages/operators/src/built-in-operators.ts

fix open panel operator to skip non-existent panel

---

fiftyone/core/config.py
fiftyone/core/utils.py

allow configuring max thread pool workers

---

fiftyone/core/dataset.py
tests/unittests/video_tests.py

Fixing merge_samples() for video datasets

---

fiftyone/core/clips.py
fiftyone/core/collections.py
fiftyone/core/dataset.py
fiftyone/core/document.py
fiftyone/core/fields.py
fiftyone/core/labels.py
fiftyone/core/models.py
fiftyone/core/odm/document.py
fiftyone/core/odm/mixins.py
fiftyone/core/odm/utils.py
fiftyone/core/patches.py
fiftyone/core/stages.py
fiftyone/server/utils.py
fiftyone/server/view.py
fiftyone/utils/annotations.py
tests/unittests/dataset_tests.py
tests/unittests/import_export_tests.py
tests/unittests/label_tests.py
tests/unittests/sample_tests.py

Merging https://github.com/voxel51/fiftyone/pull/3152 into release branch.

Merging #3152 into release branch

---

app/packages/core/src/plugins/SchemaIO/components/DropdownView.tsx

add support for multi-select with string type

---

README.md

Adds a Docker Hub Pulls badge to the README header

adds a Docker Hub Pulls badge

---

app/packages/state/src/recoil/selectors.ts

fixes embedding modal - thanks to Ben for help!
(Details)
-   [ ] Other

embeddings modal atom fix

---

app/packages/core/src/components/Actions/Patcher.tsx
app/packages/core/src/components/FieldLabelAndInfo/index.tsx
app/packages/looker/src/elements/common/tags.ts
app/packages/looker/src/overlays/index.ts
app/packages/looker/src/worker/index.ts
app/packages/state/src/hooks/useSchemaSettings.ts
app/packages/state/src/hooks/useStateUpdate.ts
app/packages/state/src/recoil/aggregations.ts
app/packages/state/src/recoil/schema.ts
app/packages/state/src/recoil/sidebar.ts
app/packages/state/src/recoil/types.ts
app/packages/state/src/recoil/utils.ts
app/packages/state/tests/recoil/sidebar.test.ts
app/packages/utilities/src/index.ts
fiftyone/core/patches.py
fiftyone/core/stages.py

Follow up to https://github.com/voxel51/fiftyone/pull/3141
* Only one level of nesting, e.g. `dynamic.labels` or `frames.dynamic.labels`
* Dynamic document lists do not support labels e.g. `dynamic_list.label`
* Raw lists of labels are not supported
```py
dataset = foz.load_zoo_dataset("quickstart", max_samples=10)
sample["dynamic"] = fo.DynamicEmbeddedDocument(
classification=fo.Classification(label="single"),
classifications=fo.Classifications(
classifications=[fo.Classification(label="list")]
),
detection=fo.Detection(
bounding_box=[0.25, 0.25, 0.5, 0.5], label="single"
),
detections=fo.Detections(
detections=[
fo.Detection(bounding_box=[0.25, 0.25, 0.5, 0.5], label="list")
]
),
)
sample.save() …
```

Restricted supported App labels to match SDK

---

docs/source/faq/index.rst

Minor typo fixes

---

fiftyone/core/collections.py
fiftyone/core/stages.py
tests/unittests/view_tests.py

Resolves https://github.com/voxel51/fiftyone/issues/3277

Fixing #3277

---

docs/source/integrations/labelbox.rst

Fix a typo

---

.github/workflows/e2e.yml
e2e-pw/playwright.config.ts

fix playwright reporter

---

docs/source/release-notes.rst
fiftyone/core/session/client.py
setup.py

Merging https://github.com/voxel51/fiftyone/pull/3303 into `develop`.

Merging v0.21.4 into develop

---

fiftyone/utils/coco.py

fix https://github.com/voxel51/fiftyone/issues/3309
code in https://github.com/voxel51/fiftyone/issues/3309 passes
-   [ ] Other

fix bug on coco keypoints export with nan coordinates 

---

app/packages/core/src/components/Schema/SchemaSearch.tsx
app/packages/core/src/components/Schema/SchemaSelectControls.tsx
app/packages/core/src/components/Schema/SchemaSettings.tsx
app/packages/core/src/components/Sidebar/Entries/FilterEntry.tsx
app/packages/state/src/hooks/index.ts
app/packages/state/src/hooks/schema/useSearchSchemaFields.test.tsx
app/packages/state/src/hooks/schema/useSearchSchemaFields.ts
app/packages/state/src/hooks/schema/useSetSelectedFieldsStage.test.tsx
app/packages/state/src/hooks/schema/useSetSelectedFieldsStage.ts
app/packages/state/src/hooks/schema/useSetShowNestedFields.test.tsx
app/packages/state/src/hooks/useSchemaSettings.ts

schemaSearch and selectedFieldsStage custom hooks / tests 

---

app/packages/core/src/components/Actions/ActionsRow.tsx
app/packages/core/src/components/Actions/DynamicGroupAction.tsx
app/packages/core/src/components/ImageContainerHeader.tsx
app/packages/core/src/components/Sidebar/Entries/EntryCounts.tsx
e2e-pw/src/oss/poms/action-row/display-options.ts
e2e-pw/src/oss/poms/action-row/grid-actions-row.ts
e2e-pw/src/oss/poms/grid/index.ts
e2e-pw/src/oss/specs/smoke-tests/quickstart-groups.spec.ts

- Fix bug where group count wasn't showing in `group` statistics aggregation mode
- Add E2E test
- Add other useful POMs
E2E test
-   [ ] Other

Bug fix: group count

---

app/packages/plugins/src/externalize.ts
app/packages/plugins/src/index.ts

externalize styled-components

---

fiftyone/utils/torch.py

#2843 added MPS support. Unfortunately MPS does not yet support certain ops, so some zoo models like `clip-vit-base32-torch` don't support it.
This PR reverts to the previous behavior of using CUDA if available, else falling back to CPU.
MPS can still be requested by manually passing `device="mps"`:
```py
model = foz.load_zoo_model("...")
model = foz.load_zoo_model("...", device="mps")
```

Only use MPS when manually specified

---

docs/source/cli/index.rst
fiftyone/core/cli.py
fiftyone/factory/__init__.py
fiftyone/factory/repos/delegated_operation.py
fiftyone/operators/__init__.py
fiftyone/operators/delegated.py
fiftyone/operators/executor.py
tests/unittests/delegated_operators_tests.py

Delegated ops cli merge

---

docs/source/integrations/qdrant.rst

Add gRPC configuration variables to Qdrant integration documentation
-   [] Yes. Give a description of this change to be included in the release
This PR documents connecting to Qdrant servers via gRPC for Similarity Search workflows. 
(The code changes are in the FiftyOne Brain.)
-   [] Core: Core `fiftyone` Python library changes
-   [ ] Other

[Doc] Qdrant gRPC connection

---

app/packages/components/src/index.ts
app/packages/components/src/scrollable.module.css
app/packages/core/src/components/Actions/ActionsRow.tsx
app/packages/core/src/components/Actions/DynamicGroup.tsx
app/packages/core/src/components/Actions/DynamicGroupAction.tsx
app/packages/core/src/components/Actions/Options.tsx
app/packages/core/src/components/Actions/Patcher.tsx
app/packages/core/src/components/Actions/Popout.tsx
app/packages/core/src/components/Actions/Selected.tsx
app/packages/core/src/components/Actions/Tagger.tsx
app/packages/core/src/components/Actions/similar/Similar.tsx
app/packages/core/src/components/ImageContainerHeader.tsx

improve actions row overflow ux

---

app/packages/looker/src/elements/common/tags.ts
app/packages/state/src/recoil/pathFilters/index.ts
app/packages/state/src/recoil/pathFilters/string.ts

fix the sample tag and label tag bubble visibility setting was not applied correctly.
(Details)
-   [ ] Other

bugfix: sample tag and label tag visibility and filter issue

---

.github/workflows/build-docs.yml
docs/source/user_guide/using_datasets.rst
fiftyone/core/labels.py

Resolves https://github.com/voxel51/fiftyone/issues/1821

Use frame size when constructing rotated boxes

---

app/packages/core/src/components/Modal/Looker.tsx
app/packages/core/src/components/Modal/Sample.tsx
app/packages/core/src/components/Modal/Sample3d.tsx

add sample bar in sample3d

---

e2e-pw/src/oss/specs/groups/large-groups.spec.ts
e2e-pw/src/oss/specs/groups/sparse-groups.spec.ts

- execute python code only once in group tests
- skip pcd for now because slice selection behavior is different from other modalities

group tests refactor

---

app/packages/core/src/components/Grid/recoil.ts
app/packages/core/src/components/Modal/Group/DynamicGroup/carousel/DynamicGroupsFlashlightWrapper.tsx
app/packages/core/src/components/Modal/Group/GroupCarousel.tsx
e2e-pw/src/oss/poms/modal/index.ts
e2e-pw/src/oss/specs/groups/large-groups.spec.ts
e2e-pw/src/oss/specs/groups/sparse-groups-scenes.spec.ts
e2e-pw/src/oss/specs/groups/sparse-groups.spec.ts
e2e-pw/src/oss/specs/regression-tests/grid-page.spec.ts

Resolves a page offset by 1 bug in flashlight paging

Page offset bug

---

README.md

Fix broken Downloads link

---

app/packages/flashlight/src/index.ts
e2e-pw/src/oss/poms/action-row/tagger.ts
e2e-pw/src/oss/poms/grid/index.ts
e2e-pw/src/oss/poms/sidebar.ts
e2e-pw/src/oss/specs/3d/pcd-only-dataset.spec.ts
e2e-pw/src/oss/specs/dynamic-groups-cifar.spec.ts
e2e-pw/src/oss/specs/dynamic-groups.spec.ts
e2e-pw/src/oss/specs/groups/large-groups.spec.ts
e2e-pw/src/oss/specs/groups/sparse-groups-scenes.spec.ts
e2e-pw/src/oss/specs/groups/sparse-groups.spec.ts
e2e-pw/src/oss/specs/regression-tests/grid-page.spec.ts
e2e-pw/src/oss/specs/regression-tests/group-video/default-video-slice-group.spec.ts
e2e-pw/src/oss/specs/regression-tests/group-video/group-video-label.spec.ts
e2e-pw/src/oss/specs/regression-tests/sidebar/sidebar-datetime.spec.ts
e2e-pw/src/oss/specs/selection.spec.ts
e2e-pw/src/oss/specs/sidebar/sidebar-cifar.spec.ts
e2e-pw/src/oss/specs/sidebar/sidebar.spec.ts
e2e-pw/src/oss/specs/smoke-tests/quickstart-groups.spec.ts
e2e-pw/src/oss/specs/smoke-tests/quickstart.spec.ts
e2e-pw/src/oss/specs/smoke-tests/tagger.spec.ts
e2e-pw/src/shared/event-utils/index.ts

- Add `getWaitForGridRefreshPromise()` method to the grid POM
- Minor linting
- Local E2E green

Minor e2e refactoring

---

app/packages/app/package.json
app/packages/app/src/index.tsx
app/packages/operators/src/state.ts
app/packages/state/src/hooks/index.ts
app/packages/state/src/hooks/useNotification.tsx
app/yarn.lock

Show a notification when a delegated operator is scheduled successfully
Preview: 
(Details)
-   [ ] Other

show notification on scheduling an operator

---

fiftyone/operators/delegated.py

raise exception on validation failure, rather than just marking as failed.

---

docs/source/tutorials/qdrant.ipynb

Updated Qdrant tutorial to use native integration.
Ran cells in jupyter notebook. Ran docs generation script to ensure that the formatting is correct.
Updated Qdrant Tutorial to utilize the native Qdrant integration.
-   [ ] Other

Updated Qdrant Tutorial

---

docs/source/tutorials/qdrant.ipynb

Merging qdrant tutorial changes from develop into release
tested in develop
Notes in original commit.
-   [ ] Other

Qdrant tutorial changes

---

docs/source/teams/installation.rst

FiftyOne Teams installation doc: include doc for configuring CORS for cloud buckets (needed for cloud-backed PCDs, segmentations)
-   [ ] Other

Document CORS configuration for FiftyOne Teams Installation

---

docs/source/cli/index.rst
fiftyone/core/cli.py
fiftyone/core/dataset.py

```py
dataset = fo.Dataset("tmp-auto")
dataset.tags = ["tmp", "automotive"]
fo.list_datasets(tags="automotive")
fo.list_datasets(tags=["automotive", "healthcare"])
```
```shell
fiftyone datasets list --tags automotive
fiftyone datasets list --tags automotive healthcare
fiftyone datasets info --tags automotive
fiftyone datasets info --tags automotive healthcare
fiftyone datasets delete tmp-auto
```

Adding support for listing datasets with tags

---

app/packages/core/src/plugins/SchemaIO/components/FileExplorerView/ExplorerActions.tsx
app/packages/core/src/plugins/SchemaIO/components/FileExplorerView/FileExplorer.tsx
app/packages/core/src/plugins/SchemaIO/components/FileExplorerView/FileExplorerView.tsx
app/packages/core/src/plugins/SchemaIO/components/FileExplorerView/FileTable.tsx
app/packages/core/src/plugins/SchemaIO/components/FileExplorerView/VolumeSelector.tsx
app/packages/core/src/plugins/SchemaIO/components/FileExplorerView/state.ts

style enhancements for FileExplorerView

---

app/packages/state/src/hooks/useNotification.tsx

remove stray closeSnackbar

---

.github/workflows/e2e.yml
app/packages/components/src/components/FilterAndSelectionIndicator/FilterAndSelectionIndicator.tsx
app/packages/components/src/components/Link/Link.tsx
app/packages/embeddings/src/Embeddings.tsx
app/packages/embeddings/src/EmbeddingsPlot.tsx
app/packages/embeddings/src/styled-components.tsx
app/packages/embeddings/src/useExtendedStageEffect.tsx
app/packages/embeddings/src/useSelectionEffect.tsx
e2e-pw/src/oss/poms/panels/embeddings-panel.ts
e2e-pw/src/oss/poms/panels/histogram-panel.ts
e2e-pw/src/oss/poms/panels/panel.ts
e2e-pw/src/oss/specs/display-options/display-options.spec.ts
e2e-pw/src/oss/specs/groups/empty-groups.spec.ts
e2e-pw/src/oss/specs/plugins/histograms.spec.ts
e2e-pw/src/oss/specs/smoke-tests/embeddings.spec.ts
requirements/e2e.txt

https://github.com/voxel51/fiftyone/assets/109545780/8d9d5da6-511e-4f71-bd1c-b7b8de4266bc
```
fob.compute_visualization(dataset, brain_key="img_viz")
fob.compute_visualization(dataset, patches_field="ground_truth", brain_key="gt_viz")
```
Lasso should work for any brain key including gt_viz
https://github.com/voxel51/fiftyone/assets/109545780/54b16667-8b25-44d5-8511-855bbe6baf04
(Details)
if this PR is part …

Embeddings panel fix

---

app/packages/core/src/plugins/SchemaIO/components/FileExplorerView/FileExplorerView.tsx
app/packages/core/src/plugins/SchemaIO/components/FileExplorerView/VolumeSelector.tsx
app/packages/core/src/plugins/SchemaIO/components/FileExplorerView/state.ts

Error preview:
(Details)
-   [ ] Other

file system label and error enhancements

---

fiftyone/operators/delegated.py
tests/unittests/delegated_operators_tests.py

fix for operators that execute as generators

---

fiftyone/operators/delegated.py

exhaust the generator before returning

---

docs/source/plugins/index.rst
docs/source/teams/installation.rst

Delegated Operations docs

---

app/packages/operators/src/state.ts

prevent resolve input after execute

---

app/packages/core/src/plugins/SchemaIO/components/FileExplorerView/FileExplorer.tsx
app/packages/core/src/plugins/SchemaIO/components/FileExplorerView/FileExplorerView.tsx
app/packages/core/src/plugins/SchemaIO/components/FileExplorerView/state.ts
app/packages/core/src/plugins/SchemaIO/components/FileExplorerView/types.ts
app/packages/core/src/plugins/SchemaIO/components/FileExplorerView/utils.ts

Preview:
https://github.com/voxel51/fiftyone/assets/25350704/eea5c9e5-1d22-4faf-a89a-84946c178a88
(Details)
-   [ ] Other

support providing custom path in FileExplorerView

---

app/packages/core/src/components/ViewBar/ViewStage/ViewStageParameter.tsx
app/packages/desktop/src/main.ts
app/packages/plugins/src/index.ts
app/packages/spaces/src/AppModules.tsx
app/packages/state/src/hooks/useSavedViews.ts

Remove `console.log` or change to `console.debug` or `console.error`
(Details)
-   [ ] Other

console logging cleanup in app

---

app/packages/core/src/plugins/SchemaIO/components/ErrorView.tsx

Make ErrorView scrollable if it overflows
(Details)
-   [ ] Other

fix ErrorView overflow

---

docs/source/teams/index.rst

forgot to update the toctree entry for dataset versioning after copy-pasta. thanks @kaixi-wang for finding

update index entry for versioning

---

app/gen-docs.js
docs/source/plugins/index.rst
docs/source/plugins/ts-api.rst
fiftyone/operators/operator.py

small tweaks for plugins docs

---

e2e-pw/src/oss/poms/sidebar.ts
e2e-pw/src/oss/specs/regression-tests/sidebar/sidebar-datetime.spec.ts

This is one of the some flaky tests we found in develop - here is a refactor and passing tests. simplifies the slider drag and hopefully less flaky 🤞 
Thanks to @lanzhenw for the help! 🚀 
(Details)
-   [ ] Other

sidebar slider test refactor

---

docs/source/teams/secrets.rst

Fix typo in secrets doc, minor doc update (working)
-   [ ] Other

fix doc typo, minor doc edit

---

README.md

Add Contributors Image

---

fiftyone/operators/types.py

Update types.py typo

---

codecov.yml

Adding codecov settings to disable some of the unwanted checks that show up in PRs. Codecov will still comment with a report

Codecov cleanup

---

app/packages/operators/src/state.ts

Resolves https://github.com/voxel51/fiftyone/issues/3557
This is tested with this [new example operator](https://github.com/voxel51/fiftyone-plugins/pull/58/files).

fix issue 3557

---

.github/workflows/pr.yml
.github/workflows/publish.yml

e2e tests are stable now, so I propose we include them as required checks (open to discussion, they are slower than other checks)

[Proposal] Require e2e in PR and Publish workflows

---

docs/source/teams/teams_plugins.rst

Fix docs typo

---

app/packages/operators/src/OperatorBrowser.tsx

update help icon link in operator browser

---

fiftyone/migrations/revisions/v0_19_0.py

Fixes a bug where datasets that contains runs (evaluation, brain, annotation) exported in `FiftyOneDataset` format using `fiftyone<0.19` would not be importable using `fiftyone>=0.19`.
The issue was that the `fiftyone==0.19` migration script was not smart enough to handle cases where datasets need to be migrated upwards but already have runs stored in the `runs` collection.
In a venv with `fiftyone==0.22` installed:
```shell
fiftyone migrate -v 0.18
```
A fresh venv:
```
pip install ipython fiftyone==0.18
```
```py
dataset.evaluate_detections(
"predictions",
)
export_dir="/tmp/quickstart",
dataset_type=fo.types.FiftyOneDataset,
)
```
``` …
```

Gracefully handle runs that are already migrated when importing data in FiftyOneDataset format

---

app/packages/components/src/scrollable.module.css
app/packages/utilities/src/styles.ts

transparent background for scrollbar corner

---

app/packages/core/src/plugins/SchemaIO/components/Header.tsx
app/packages/operators/src/state.ts

handle null value for componentsProps in Header

---

app/packages/map/src/Map.tsx
app/packages/map/src/index.ts

switch Map plugin to Panel type

---

app/packages/components/src/scrollable.module.css
app/packages/utilities/src/styles.ts

cherry-pick of fix in PR https://github.com/voxel51/fiftyone/pull/3584
(Details)
-   [ ] Other

[v0.22.1]: transparent background for scrollbar corner

---

fiftyone/core/view.py
fiftyone/utils/coco.py

Pulling https://github.com/voxel51/fiftyone/pull/3599 and this missing commit https://github.com/voxel51/fiftyone/commit/4658b6ecfd7747a40f30751e2936bc9b2984fe98 from `develop` into `release/v0.22.1`.
Now I'm confident all desired changes from `develop` will be in 0.22.1.

Release patch

---

app/packages/core/src/components/Actions/ActionsRow.tsx
app/packages/core/src/components/ColorModal/ColorFooter.tsx
fiftyone/server/events.py

Fixes a bug resulting from #3603. e2e will confirm the fix

Fix actions row component

---

.github/workflows/e2e.yml
app/packages/core/src/plugins/SchemaIO/components/FileExplorerView/FileExplorerView.tsx
app/packages/looker-3d/src/Looker3d.tsx
app/packages/looker/src/overlays/base.ts
app/packages/looker/src/worker/painter.ts

Daily merge of `release/v0.22.1` into `develop`

---

fiftyone/core/cli.py

Conflicts:
```
app/packages/looker-3d/src/Looker3d.tsx
app/packages/looker/src/overlays/base.ts
app/packages/looker/src/worker/painter.ts
```

Daily merge of `release/v0.22.1` to `develop`

---

app/packages/core/src/components/Actions/ActionsRow.tsx
app/packages/relay/src/graphQLSyncFragmentAtom.ts
e2e-pw/src/oss/poms/action-row/grid-actions-row.ts
e2e-pw/src/oss/specs/smoke-tests/quickstart.spec.ts

Fixes bookmark action filters and adds corresponding e2e

Fix bookmark filters action

---

docs/source/cheat_sheets/filtering_cheat_sheet.rst

Fixed a couple syntax typos in documentation code
-   [ ] Other

docs: fix a couple code typos in filtering_cheat_sheet.rst

---

app/.eslintrc.js
app/packages/core/src/plugins/SchemaIO/components/AutocompleteView.tsx
app/packages/core/src/plugins/SchemaIO/components/ChoiceMenuItemBody.tsx
app/packages/core/src/plugins/SchemaIO/components/DropdownView.tsx

add description and caption in autocomplete option

---

app/packages/state/src/recoil/color.ts
fiftyone/core/state.py

hotfix for a type error
(Details)
-   [ ] Other

fix type errors

---

.github/workflows/pr.yml
app/packages/core/src/components/Modal/Sample.tsx

Fixes duplicate import (Next.JS complains)

Fix duplicate import

---

e2e-pw/src/oss/specs/smoke-tests/dynamic-embedded-documents-segmentation.spec.ts

normalize path in DED test
(Details)
-   [ ] Other

normalize segmentation mask path in test

---

fiftyone/operators/decorators.py
tests/unittests/operators/decorators_tests.py

[Operators] unit tests for coroutine timeout

---

package/desktop/setup.py
setup.py

Bumping desktop to 0.31 to ensure compatibility

bump desktop

---

app/packages/core/src/plugins/SchemaIO/components/FileDrop.tsx
app/packages/core/src/plugins/SchemaIO/components/FileExplorerView/FileTable.tsx
app/packages/core/src/plugins/SchemaIO/components/FileView.tsx
app/packages/utilities/src/index.ts
fiftyone/operators/types.py

Improvements for fileview.
Usage example here: https://github.com/voxel51/fiftyone-plugins/pull/68

File obj support rel

---

fiftyone/core/odm/database.py
fiftyone/operators/decorators.py
tests/unittests/operators/decorators_tests.py

- check top level plugins dir for last modified at rather than individual plugins to account for deleted plugins
- add and update tests

Fix plugin cache check

---

app/packages/core/src/plugins/OperatorIO/utils/index.ts
app/packages/core/src/plugins/SchemaIO/components/SliderView.tsx
app/packages/core/src/plugins/SchemaIO/components/TextFieldView.tsx
app/packages/operators/src/validation.ts
fiftyone/operators/executor.py
fiftyone/operators/types.py

Use specified min and max property in Number type for Views and Validation
-   [ ] Other

operator number type enhancements

---

docs/source/integrations/pytorch_hub.rst
docs/source/release-notes.rst

Release notes/v0.22.2

---

docs/source/cheat_sheets/filtering_cheat_sheet.rst

Doc typo pointed out by @timmermansjoy 
Ran code locally, works now.
-   [ ] Other

Doc typos in filtering cheat sheet #bounding-boxes

---

app/packages/core/src/utils/generic.tsx

fix the issue that boolean values are not displayed in the sample modal view. 
(Details)
-   [ ] Other

bugfix: boolean value cannot display correctly in the sample modal view

---

app/packages/core/src/components/Modal/Looker.tsx
docs/source/plugins/developing_plugins.rst
docs/source/plugins/using_plugins.rst
docs/source/teams/teams_plugins.rst
setup.py

Daily Merge release0.22.3 to develop

---

.github/ISSUE_TEMPLATE/bug_report_template.md

I'm proposing some updates to make the bug report template easier and clearer for both writer and reader.
I will comment on the specific reasons for each change inline

[DOCS] Proposal to update github bug report template

---

fiftyone/operators/delegated.py

Async generator delegated operations fails with an error to follow.
We need to use `async for ...` if the result is an async generator.
While we're at it, we should use the standard `inspect` module.
```
File "/Users/stuart/dev/fiftyone/fiftyone/operators/delegated.py", line 252, in execute_queued_operations
execution_result = asyncio.run(self._execute_operator(op))
File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
return future.result()
File "/Users/stuart/dev/fiftyone/fiftyone/operators/delegated.py", line 307, in _execute_operator …
```

[BUGFIX] fix async gen del ops

---

app/packages/core/src/components/ColorModal/ShareStyledDiv.ts
app/packages/core/src/components/Modal/Modal.tsx

bugfix: Show operator modal in front of sample modal

---

.github/workflows/build-docs.yml
docs/source/release-notes.rst

Fixed a `remove_from_index()` reference and removes stray bullet point

Lint v0.22.3 Release Notes

---

app/packages/operators/src/operators.ts
app/packages/operators/src/state.ts
app/packages/state/src/recoil/modal.ts
docs/source/plugins/developing_plugins.rst
fiftyone/operators/executor.py

See [an example](https://github.com/voxel51/fiftyone-plugins/pull/83/files) operator that shows the usage of this new field.

Add ctx.current_sample

---

fiftyone/operators/executor.py
fiftyone/plugins/secrets.py
tests/unittests/plugins/secrets_tests.py

Re-enable iterating through secrets like a dict (TEAMS-1980)

Allow iterating ctx.secrets.items()

---

docs/source/release-notes.rst

Release notes for Teams v1.4.5

teams v1.4.5 Release Notes

---

app/packages/core/src/components/ColorModal/ColorFooter.tsx
app/packages/core/src/components/ColorModal/ShareStyledDiv.ts
app/packages/core/src/components/ColorModal/colorPalette/Colorscale.tsx
app/packages/core/src/components/ColorModal/colorPalette/GlobalColorscale.tsx
app/packages/core/src/components/ColorModal/controls/ColorAttribute.tsx
app/packages/core/src/components/ColorModal/controls/ManualColorScaleList.tsx
app/packages/core/src/utils/links.ts
app/packages/relay/src/graphQLSyncFragmentAtom.ts
app/packages/relay/src/graphQLSyncFragmentAtomFamily.ts
app/packages/relay/src/mutations/__generated__/setDatasetColorSchemeMutation.graphql.ts
app/packages/relay/src/mutations/setDatasetColorScheme.ts
app/schema.graphql
fiftyone/server/color.py

- implemented design changes: add an info icon to named colorscale that links to guidelines
- fixed the following bugs:
tested locally
-   [ ] Other

colorscheme bugfix

---

app/packages/components/src/components/TabOption/TabOption.tsx
app/packages/core/src/components/Actions/Options.tsx
app/packages/state/src/recoil/view.ts

Fixes a bug introduced by #3863 that was causing dynamic groups tests to fail.
All E2E now green.

Bugfix dynamic groups

---

docs/source/release-notes.rst

Add a missing bugfix to snapshots in the FiftyOneTeams 1.4.4 release notes
-   [ ] Other

[DOCS] missing bugfix release note FOT v1.4.4

---

fiftyone/utils/data/importers.py
tests/unittests/group_tests.py

Resolves https://github.com/voxel51/fiftyone/issues/3891

Ensure group indexes exist when importing FiftyOneDataset format

---

fiftyone/utils/data/importers.py
tests/unittests/group_tests.py

0.23.1 Ensure group indexes exist when importing FiftyOneDataset format

---

fiftyone/server/query.py
tests/unittests/server_tests.py

Fix App server on Python 3.8

---

docs/source/integrations/v7.rst

Update v7 integration docs per current state

V7 doc updates

---

docs/source/environments/index.rst
docs/source/faq/index.rst
docs/source/user_guide/config.rst

Fixes notebook and proxy URL documentation references

Fix documentation references

---

docs/source/plugins/using_plugins.rst
fiftyone/core/cli.py
fiftyone/operators/executor.py
fiftyone/utils/data/exporters.py
fiftyone/utils/data/importers.py
fiftyone/zoo/datasets/__init__.py
setup.py

Change log
- Documents the `@voxel51/utils/delegate` operator introduced in https://github.com/voxel51/fiftyone-plugins/pull/98
- Misc tweaks to support some edge cases of SDK operator execution that the above PR revealed

SDK operator execution tweaks + docs

---

fiftyone/utils/iou.py

Cherry-picking https://github.com/voxel51/fiftyone/pull/3930 for 0.23.2 release.
Test code:
```py
import fiftyone.utils.iou as foui
def to_keypoint(xc, yc, w, h, theta, **kwargs):
R = np.array([[np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)]])
x = 0.5 * w * np.array([1, -1, -1, 1])
y = 0.5 * h * np.array([1, 1, -1, -1])
points = R.dot(np.stack((x, y))).T + np.array((xc, yc))
return fo.Keypoint(points=points.tolist(), **kwargs)
def to_polyline(xc, yc, w, h, theta, **kwargs):
R = np.array([[np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)]])
x = 0.5 * w * np.array([1, -1, -1, 1])
y = 0.5 * h * np.array([1, 1, -1, -1])
points = R.dot(np.stack((x, y))).T + np.array((xc, yc))
return fo.Polyline(points=[points.tolist()], …
```

Update iou.py (cherry-pick)

---

fiftyone/utils/labelstudio.py
tests/intensive/labelstudio_tests.py

Closes #3888 
~~The only thing i can't figure out is where to convert Segmentation -> Detection (instances) in this approach~~
Fixed
all previous tests pass + added few to cover new use-cases
Added support for more complex LabelStudio workflows, with multiple label fields
-   [ ] Other

support multiple fields in Label-Studio

---

app/packages/state/src/recoil/selectors.ts

Remove unused savedViewsSelector

Remove unused savedViewsSelector

---

docs/source/integrations/mongodb.rst

Doc updates for MongoDB integration. 
Remove manual index creation for Mongo Atlas 6.0. Add note re similarity search on views.

[Doc] MongoDB Integration Doc Updates

---

fiftyone/server/routes/sort.py

Cherry picking #3958 for release

#3958 for release/v0.23.3

---

app/packages/operators/src/operators.ts

Remove extra properties in selected_labels sent for operator context
Using an example operator
Remove extra properties in selected_labels to match SDK
-   [ ] Other

remove extra properties in selected_labels

---

fiftyone/core/document.py
fiftyone/core/odm/document.py
fiftyone/core/validation.py
tests/unittests/evaluation_tests.py
tests/unittests/operators/decorators_tests.py

Fix schema bugs with embedded document fields

---

app/packages/core/src/components/Actions/similar/Similar.tsx

Fixes `k` requirement logic in the App similarity logic

Fix similarity action k requirement

---

docs/source/integrations/huggingface.rst
docs/source/release-notes.rst

Release notes for v0.23.3 and Teams v1.5.4

---

tests/unittests/operators/decorators_tests.py

fix dir state rename test

---

docs/source/release-notes.rst
package/db/setup.py
tests/unittests/operators/decorators_tests.py

Merge main to develop after releasing v0.23.3

Merge main to develop

---

docs/source/_includes/substitutions.rst
docs/source/user_guide/brain.rst

Documentation for https://github.com/voxel51/fiftyone-brain/pull/175.

Documenting visualization method customization

---

docs/source/_includes/substitutions.rst
docs/source/release-notes.rst
docs/source/user_guide/brain.rst
fiftyone/core/collections.py
fiftyone/core/runs.py
setup.py
tests/unittests/run_tests.py

Cherry-picks:
- https://github.com/voxel51/fiftyone/pull/4038
- https://github.com/voxel51/fiftyone/pull/4039

Cherry-picking ML work for release

---

package/desktop/setup.py

Omit desktop release from 0.23.4

Downgrade desktop

---

fiftyone/core/odm/dataset.py
tests/unittests/odm_tests.py

Resolves #4059. Will undraft after adding tests

Fix id serialization in color scheme

---

fiftyone/utils/labelbox.py

Resolves https://github.com/voxel51/fiftyone/issues/1654
Reintroduces support for video datasets and adds support for video slices of grouped datasets. Tested classification and detection annotation runs with flat video, grouped video with a selected slice, flat image, and grouped image with a selected slice datasets.
Additionally fixes a bug when annotating checkbox list attributes of the form:
```python
label_schema = {
"field": {
"type": "detections",
"classes": ["TEST"],
"attributes": {
"type": "checkbox",
"values": ["testval"],
}
}
}
```

Fix video, and video slice support for Labelbox

---

docs/source/release-notes.rst

0.23.5 release notes

---

docs/source/integrations/huggingface.rst
docs/source/release-notes.rst
fiftyone/utils/transformers.py
fiftyone/zoo/models/manifest-torch.json

Bring final changes from `release/v0.23.5` into `develop`

Merge main to develop after releasing v0.23.5

---

docs/source/faq/index.rst

Updating FAQ answer about using cloud data with fiftyone.
Built docs and verified formatting and text look accurate and links work as expected.
-   [ ] Other

updating cloud data faq to reflect new best practice

---

docs/source/integrations/milvus.rst
setup.py

This PR only changes the integration docs, but it relies on a pending change to the brain which enables cosine metric for Milvus backend.
-   [x] Other

Adds cosine metric to Milvus

---

docs/source/user_guide/dataset_creation/datasets.rst
docs/source/user_guide/export_datasets.rst
fiftyone/utils/yolo.py

Finishes the work started in https://github.com/voxel51/fiftyone/pull/4070 to add formal support for YOLO contour labels

Adding support for YOLO contours

---

docs/source/integrations/labelstudio.rst

Documents https://github.com/voxel51/fiftyone/pull/3969. To be merged alongside that PR.

Update Label Studio documentation for local storage feature

---

docs/source/integrations/labelstudio.rst
fiftyone/utils/labelstudio.py

Cherry-picks https://github.com/voxel51/fiftyone/pull/3969 and https://github.com/voxel51/fiftyone/pull/4100 for release.

Cherry-picking Label Studio local storage for release

---

docs/source/release-notes.rst

0.23.6 release notes

---

docs/source/release-notes.rst
docs/source/teams/installation.rst

Adding more release notes

---

docs/source/plugins/developing_plugins.rst
docs/source/plugins/using_plugins.rst

Minor fixes

---

app/packages/core/src/components/Sidebar/Entries/PathValueEntry.tsx

Problem
The setting of non-valued fields inside the useEffect in a Lazily-loadable component is getting called N^N times given N is the number of none-valued fields in a sample. 
Solution
In general setting state inside a useEffect hook is not recommended. Mostly due to possibility of infinite loops like this. This PR removes the calculation of sample's `None-valued fields` from `useEffect` into the hook that fetches the sample field's value. 
Before (with > 35 none valued fields in sample 2 and 4 none valued fields for sample 1)
- sample 1 loads fine (only 4 none fields)
- sample 2 crashes the app (at least 35 * 35 iterations - based on console.log)
https://github.com/voxel51/fiftyone/assets/109545780/7489ee10-981d-4abb-870e-85ec82d4097f
After
- sample 1 loads fine (only 4 none fields)
- …

Fixes app crash when many None-valued fields exist in the sample modal

---

fiftyone/utils/super_gradients.py

This pull request updates our prediction handling to align with the latest changes in the super-gradients repository, adapting to their revised predict method structure. 
Please take a look at the modification in this link: 
https://github.com/Deci-AI/super-gradients/issues/958#issuecomment-1546886715
Thanks,
Ado

Adapting to Super-Gradient Repo Updates: Prediction Method Change

---

fiftyone/utils/iou.py
fiftyone/utils/labels.py
tests/unittests/label_tests.py

Merges https://github.com/voxel51/fiftyone/pull/4160 into `develop` with a bit of cleanup and a unit test.

Merging NMS utility into develop

---

docs/source/plugins/developing_plugins.rst
docs/source/plugins/using_plugins.rst

Minor fixes cherry pick #4145

---

fiftyone/core/labels.py

Cherry pick #4175

---

docs/source/release-notes.rst

v0.23.7 release notes

---

docs/source/release-notes.rst

Release notes updates

---

docs/source/teams/pluggable_auth.md

Pluggable Authentication is a major addition to FiftyOne Teams.  Having not been involved in the project, I figured I would contribute to the docs (in the spirit of improvement)
n/a docs only changes.

docs: refactor pluggable auth docs for clarity and editing.

---

fiftyone/utils/huggingface.py

- single progress bar when downloading parquet files datasets
- pass `token` to all relevant methods in `push_to_hub()`

HF hub integration tweaks

---

fiftyone/utils/huggingface.py

Creates a `_no_progress_bars()` context that prevents the printing of a progress bar for each file uploaded or downloaded during `push_to_hub()` and `load_from_hub()` operations.
(Details)
-   [x] Other

[HF Hub Integration] Upload and Download without Progress Bars

---

docs/source/release-notes.rst

release note for #4242
(Details)
-   [ ] Other

add release note for #4242

---

fiftyone/utils/annotations.py

Pulls in a universal fix ID'd by @ehofesmann in https://github.com/voxel51/fiftyone/pull/4249

Fix API key env var hint

---

app/packages/components/src/components/CenteredStack/index.tsx
app/packages/components/src/components/index.ts
app/packages/core/src/plugins/SchemaIO/components/MarkdownView.tsx
app/packages/operators/package.json
app/packages/operators/src/CustomPanel.tsx
app/packages/operators/src/constants.ts
app/packages/plugins/src/index.ts
app/packages/spaces/package.json
app/packages/spaces/src/components/Panel.tsx
app/packages/spaces/src/components/PanelSkeleton.tsx
app/packages/spaces/src/components/PanelTab.tsx
app/packages/spaces/src/constants.ts
app/packages/spaces/src/hooks.ts
app/packages/spaces/src/index.ts
app/packages/state/src/hooks/index.ts
app/packages/state/src/hooks/useTimeout.ts
app/yarn.lock

- Fix Python panel layout bounds
- add loading state
- Persist dynamically registered panel across session refresh
- Fix MarkdownView not rendering default value
Using a python panel operator
-   [ ] Other

python panel fixes and enhancements

---

docs/source/release-notes.rst

Release notes for Teams v1.6.1

add release notes for Teams v1.6.1

---

app/packages/operators/src/CustomPanel.tsx
app/packages/operators/src/operators.ts
app/packages/operators/src/state.ts
app/packages/operators/src/useCustomPanelHooks.ts
fiftyone/operators/executor.py
fiftyone/operators/operations.py
fiftyone/operators/panel.py

Adds `ctx.extended_selection` and `panel.on_change_extended_selection`.

Ctx extended selection

---

app/packages/core/src/plugins/SchemaIO/components/PlotlyView.tsx
fiftyone/operators/operations.py
fiftyone/operators/panel.py

Fixes for embeddings python panel extended selectioin.

py panels embeddings extended selection

---

fiftyone/operators/executor.py

Resolves https://github.com/voxel51/fiftyone/issues/4387

Fixing log syntax in set_progress()

---

.github/workflows/push-release.yml

This update should allow existing Merge PRs to be seamlessly amended as new changes are pushed
-   [x] Other

Improve push release

---

app/packages/analytics/src/usingAnalytics.ts
app/packages/app/src/components/Nav.tsx
app/packages/app/src/pages/datasets/DatasetPage.tsx
app/packages/core/src/components/Dataset.tsx
app/packages/core/src/components/Sidebar/ViewSelection/index.tsx
app/packages/core/src/components/ViewBar/ViewStage/ViewStage.tsx
app/packages/operators/src/OperatorBrowser.tsx

Additional tracking and analytics fixes.

Analytics follow ups

---

fiftyone/operators/types.py

Fix grid based views duplicate orientation error
-   [ ] Other

fix grid based views

---

.github/workflows/pr.yml

Disables Teams PRs during while automation process is improved
-   [x] Other

Temporarily disable teams PRs

---

app/packages/core/package.json
app/packages/core/src/plugins/SchemaIO/components/DashboardView.tsx
app/yarn.lock

fix resize handles for dashboard items

---

tests/intensive/cvat_tests.py

Adds a test to the CVAT intensive tests for annotation of frame views implemented in https://github.com/voxel51/fiftyone/pull/4477

Add test for frame view annotation

---

tests/intensive/cvat_tests.py

Adds CVAT tests for the new ability to annotate clip views.

Add test for clip view annotation

---

docs/source/plugins/developing_plugins.rst

update python panel docs

---

fiftyone/operators/panel.py
fiftyone/operators/server.py

Fix operators listing and panel registering
(Details)
-   [ ] Other

fix listing operator and panel registration

---

app/packages/core/src/components/Actions/ActionsRow.tsx
app/packages/utilities/src/order.ts

Fixes an issue where operator placements are not being loaded due to race condition.
Using static and dynamic operator placements
-   [ ] Other

fix operator placements not loading issue

---

app/packages/core/src/components/Modal/ImaVidLooker.tsx
app/packages/looker/src/elements/imavid/index.ts
app/packages/playback/src/lib/state.ts
app/packages/playback/src/lib/use-create-timeline.ts
app/packages/playback/src/views/svgs/buffering.svg

Pause animation if buffering

---

app/packages/core/src/plugins/SchemaIO/components/index.ts
app/packages/operators/src/types.ts
fiftyone/operators/types.py

This seems to have been dropped during a cherry-pick or merge
(Details)
-   [ ] Other

Bring back the missing types

---

fiftyone/zoo/models/manifest-tf.json
fiftyone/zoo/models/manifest-torch.json

Ensures all models in torch and tf zoo manifests are tagged with the (generic) model architectures, and backbones where relevant.
(Details)
-   [x] Other

Add Model Architecture Tags to Zoo Manifest

---

app/package.json
app/packages/components/src/components/DatePicker/DatePicker.tsx
app/packages/components/src/components/DatePicker/index.tsx
app/packages/components/src/components/index.ts
app/yarn.lock

Added a datepicker so that we can use in sidebar
* Manual testing 
-   [] App: FiftyOne application changes
-   [x] Other

Adding Basic Datepicker

---

docs/source/release-notes.rst

Updates the release notes for the v1.0.2 patch release

Add to v1.0.2 release notes 

---

app/packages/core/src/plugins/SchemaIO/components/OperatorExecutionButtonView.tsx
app/packages/operators/src/components/OperatorExecutionButton/index.tsx
app/packages/operators/src/state.ts
app/packages/operators/src/types-internal.ts
fiftyone/operators/types.py

- Add onClick methodology
Locally
-   [ ] Other

Add additional functionality to OperatorButtonView

---

app/packages/core/src/plugins/SchemaIO/components/ActionsMenu.tsx

Fix icon alignment
dev server
-   [x] Other

Fix icon alignment

---

app/packages/components/src/components/PanelCTA/index.tsx
app/packages/core/src/components/Starter/content.ts
app/packages/core/src/plugins/SchemaIO/components/NativeModelEvaluationView/Evaluation.tsx
app/packages/core/src/plugins/SchemaIO/components/NativeModelEvaluationView/EvaluationPlot.tsx
app/packages/core/src/plugins/SchemaIO/components/NativeModelEvaluationView/Overview.tsx
app/packages/core/src/plugins/SchemaIO/components/NativeModelEvaluationView/index.tsx
app/packages/embeddings/README.md
app/packages/embeddings/src/EmbeddingsCTA.tsx
app/packages/map/README.md
app/packages/operators/README.md
docs/source/tutorials/pointe.ipynb
e2e-pw/scripts/generate-screenshots-docker-image/build-docker-image.sh
fiftyone/core/threed/__init__.py
fiftyone/core/threed/object_3d.py
fiftyone/internal/secrets/secret.py
fiftyone/operators/builtins/panels/model_evaluation/__init__.py

Fixes for model evaluation and embeddings panel
(Details)
-   [ ] Other

Fixes for model evaluation and embeddings panel

---

docs/source/release-notes.rst

(already deployed to https://docs.voxel51.com/release-notes.html)

Fix release date in docs

---

docs/source/_templates/layout.html

@ben took the time to update the footer, we should include it in this patch release

add 2025 to docs footer

---

app/packages/components/package.json
app/yarn.lock

adds dependency on jotai in components library

add jotai in components subpkg

---

app/packages/embeddings/package.json
app/yarn.lock

Upgrades plotly.js and react-plotly.js to latest versions.
Embeddings panel in the local app.

upgrade plotly to 3.0.1

---

README.md

Discord is now the main community forum

Remove community slack links

---

app/packages/embeddings/src/useBrainResult.tsx
app/packages/embeddings/src/useExtendedStageEffect.tsx
app/packages/embeddings/src/useViewChangeEffect.tsx
fiftyone/core/stages.py
fiftyone/server/routes/embeddings.py

See https://github.com/voxel51/fiftyone-brain/pull/239 for usage.

Lasso with point field (updates)

---

fiftyone/core/utils.py

Enable multiprocessing for Windows by default
* Testing on Windows shows that multiprocessing does work.
-   [ ] Other

Enable Multiprocessing for Windows

---

app/packages/core/src/plugins/SchemaIO/components/NativeModelEvaluationView/index.tsx

fix rename evaluation in model eval panel
Using the model evaluation panel
-   [ ] Other

fix rename evaluation in model eval panel

---

docs/source/user_guide/using_datasets.rst

* Added documentation for `map_samples` and `update_samples` 
NA
-   [ ] Other

Adding documentation for map_samples and update_samples

---

fiftyone/core/collections.py
fiftyone/utils/eval/segmentation.py
tests/unittests/evaluation_tests.py

Implement eval_segmentation with map_samples
* Added unit tests (✅ )
* Tested locally (✅ )
-   [ ] Other

Added eval_segmentation with map_samples

---

docs/source/_includes/substitutions.rst
docs/source/deprecation.rst
docs/source/plugins/developing_plugins.rst
docs/source/release-notes.rst
docs/source/user_guide/app.rst
docs/source/user_guide/config.rst
docs/source/user_guide/groups.rst
docs/source/user_guide/using_datasets.rst

Editing pass over 1.5/2.8 docs

---

docs/source/_includes/substitutions.rst
docs/source/deprecation.rst
docs/source/plugins/developing_plugins.rst
docs/source/release-notes.rst
docs/source/user_guide/app.rst
docs/source/user_guide/config.rst
docs/source/user_guide/groups.rst
docs/source/user_guide/using_datasets.rst

Cherry-picking https://github.com/voxel51/fiftyone/pull/5863 for the patch release.

Cherry-pick editing pass over 1.5/2.8 docs

---

fiftyone/utils/ultralytics.py

- Enable users to set confidence threshold via `model.config.confidence_thresh` when loading a model 
- Update Ultralytics confidence based on `confidence_thresh` set during `apply_model` (this will override the confidence threshold set at model initialization)
```py
dataset = foz.load_zoo_dataset("coco-2017", split="validation")
batch_size = 32
model_name_fo = "yolo11l-coco-torch"
#
#
model = foz.load_zoo_model(model_name_fo)
dataset.apply_model(model, label_field="predictions_yolo_25")
assert(len(dataset.filter_labels("predictions_yolo_25", F("confidence") < 0.25))==0)
count_025 = dataset.count("predictions_yolo_25.detections")
#
#
model = foz.load_zoo_model(model_name_fo, confidence_thresh=0.15) …
```

Manage ultralytics confidence thresholding

---

.github/workflows/build-docs.yml
docs/README.md
docs/source/_static/js/custom.js
docs/source/conf.py
docs/theme/pytorch_sphinx_theme/__init__.py
docs/theme/pytorch_sphinx_theme/layout.html
docs/theme/pytorch_sphinx_theme/static/css/theme.css
docs/theme/scss/_sphinx_base.scss
install.bash
install.bat
requirements/dev.txt
requirements/docs.txt

1. **Upgraded Sphinx and documentation dependencies**  
- **Sphinx:** Pinned Sphinx to version 8.1.3 to work around an incompatibility with `nbsphinx`, which does not yet support Sphinx versions above 8.2 ([related issue](https://github.com/spatialaudio/nbsphinx/issues/832)). This enables using a recent Sphinx release while preserving notebook rendering functionality.  
- **Python:** Upgraded Python from 3.9 to 3.11 for documentation builds, aligning with Sphinx 8.x requirements.
- **Theme:** Applied fixes to the theme and configuration for compatibility with updated dependencies.
- **Workflows:** Updated GitHub workflows for documentation builds.  
2. **Separate documentation and development dependencies**  
- **Rationale:** Isolated documentation-specific dependencies from general …

Upgrade Sphinx to 8.x

---

app/packages/state/src/recoil/groups.ts
docs/source/integrations/cvat.rst
docs/source/user_guide/annotation.rst
fiftyone/core/collections.py

Merging more typo fixes.
